### ISSUE TITLE
Help Styling the generated docs

### ISSUE THREAD

**Issue by patrick-rodgers** [SharePoint/PnP-JS-Core#147]
#### Category

[X] Enhancement

[ ] Bug

[ ] Question
#### Expected / Desired Behavior / Question

Looking for someone (or someones) interested in helping out with styling the generated documentation. This is done through the customization of the handlebars templates that are part of the typedoc package. The existing templates are located in the folder in the [dev tree](https://github.com/OfficeDev/PnP-JS-Core/tree/dev/typedoctheme). We will merge to master during the next release.

Would like to base the styling around the office UI fabric, but the actual design would be up to you. This is a great opportunity to have a very visible impact on the project and help us enhance our API docs to make it easier for folks to use the library.

Let us know here if you are interested in helping out so we can get you assigned, or any questions as well.

Thanks!

**Comment by tobiaswest83** [comment]
Yo, I'm interested @patrick-rodgers Fabric have just released a load of Handlebars templates as part of Fabric 3.0 so they should work pretty well together. I'll give it some thought and throw together a few plunks. 

Can't make calls at the moment as I'm on site a lot - will catch up with Gitter/calls but let me know if any discussions have started

**Comment by patrick-rodgers** [comment]
Sounds good - talked about it in the call today for the first time. Would love to see what you can some up with!

**Comment by tobiaswest83** [comment]
@StfBauer @mikewheaton lets hijack this issue to talk ideas 

Obvious candidates to me are -

-using fabric table to show list items, with a commandbar 
-Facepile to show members of a group and allow them to add/remove people to the group 
-getting quick launch and top nav times 


Sure there's loads more, let's add ideas and then settle on a few and break it down

**Comment by mikewheaton** [comment]
I'm focusing on getting Fabric 3.0 ready for release now, but once that's done I can take a look at the documentation and make some quick cleanup suggestions.

**Comment by patrick-rodgers** [comment]
@tobiaswest83, working examples are great too! Mike might have ideas on where they can live, I am not sure in this repo - but we will figure it out. But yes, for this issue I was focused on our documentation getting a nice look/feel to help folks find the info they need.

@mikewheaton, thanks! Can't wait for OF3!

**Comment by tobiaswest83** [comment]
@patrick-rodgers, will focus on the TypeDoc for now-was getting ahead of myself!
