### ISSUE TITLE
Error "TS2300: Duplicate identifier 'Promise'" after installing in a SPFx project

### ISSUE THREAD

**Issue by pranavmmodi** [SharePoint/PnP-JS-Core#221]
#### Category

[ ] Enhancement

[+ ] Bug

[ ] Question

Getting some typings while running application.

![error](https://cloud.githubusercontent.com/assets/16353403/19328397/afbcb296-9090-11e6-8888-9274ffc7deb7.png)

Looks like postscript is not running while installing sp-pnp-js module. it use to work fine till yesterday and today something goes wrong.

**Comment by patrick-rodgers** [comment]
What version of the library? If you have updated to 1.0.5 it is targeted to TypeScript 2.0. Did you get a chance to review the [release notes post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/10/11/pnp-js-core-1-0-5/) or the [updated app setup post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/10/11/node-console-app-debugging-typescript-2-0-in-vs-code/)?

**Comment by pranavmmodi** [comment]
I am using typescript 2.0 and Tried both version  1.0.5 and 1.0.4 , same issue

**Comment by pranavmmodi** [comment]
![image](https://cloud.githubusercontent.com/assets/16353403/19358809/9734b134-9134-11e6-9e53-e95190a060d5.png)
Here I was anticipating some post install script which use to install some typescript or something.. Lets see if that help

**Comment by patrick-rodgers** [comment]
There is no longer a post install step, it was removed. We now depend on some of the @types libraries to do the typings where we used to use typings. In what context are you trying to use the library? You haven't given us much to go on in terms of helping you - so the more info you can share the more we can try and help.

**Comment by pranavmmodi** [comment]
I understand. I am trying to run this library with share point client side framework (SPFX) http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/build-a-hello-world-web-part  

This project is with React, Typescript and Gulp all provided in initial setup by Microsoft.

Everything use to work fine until yesterday untill I take latest of sp-pnp-js.  Task Typescript start throwing error. Just tried to import pnp library , nothing else.
![image](https://cloud.githubusercontent.com/assets/16353403/19365423/eced12b8-914f-11e6-8315-ed029c1c74ea.png)

**Comment by pranavmmodi** [comment]
Ok so Its look like reference syntax create problem in my project.    

Error on line /// <reference types="core-js" />   and issue is getting fixed after I remove one / from reference.     // <reference types="core-js" />  just work fine

![image](https://cloud.githubusercontent.com/assets/16353403/19366050/cd32e06c-9152-11e6-8e97-f59bb141b3e2.png)

**Comment by patrick-rodgers** [comment]
Hmmm...ok, very strange. The change yesterday was definitely the release of 1.0.5 which did change the definition files. Let me grab the very latest of SPFx and see if I can duplicate and I'll get back to you on this. Sorry for the difficulties but thanks for reporting it. We'll see if we can get you sorted out.

**Comment by patrick-rodgers** [comment]
Interesting - so when I pulled latest SPFx it turns out it is still using TypeScript 1.8.* and I was able to duplicate this. Let me see if I can get some clarity on when they will drop the version which uses TS2. I thought we timed this well but seems like not the case.

**Comment by patrick-rodgers** [comment]
Quick update - drop 5 of SPFx has been released and includes TypeScript 2.0, which resolves the above issues. However I am keeping this open as there are now errors related to duplicate definitions. Working with SP Engineering on best approach to make it all work together and will report back when I have something. So still working on it.

**Comment by patrick-rodgers** [comment]
Had a look at this first thing this morning and don't have a perfect fix yet, but if you edit the tsd.d.ts file under "typings" folder in your project and remove/comment out these two lines things start working again as expected:

```
/// <reference path="whatwg-fetch/whatwg-fetch.d.ts" />
/// <reference path="es6-promise/es6-promise.d.ts" />
```

Will keep this open until we can firm up the entire experience but still working with PG on that. Thanks!

**Comment by patrick-rodgers** [comment]
Tracking: https://github.com/SharePoint/sp-dev-docs/issues/265

**Comment by biste5** [comment]
Hi Patrick,

I'm encountering the same error, when trying to include PnP-JS in an existing TS project (it's NOT an SPFx project) where I was previously already using ES6-Promise package, but not PnP-JS.

In the screenshot below you can see as soon as I install PnP-JS, I get that error during build.
Further, in my case, I can't apply the workaround above as I'm not using typings, but trying to use only @types package

Let me know in case you need more details, or is better if I create a separate issue for this

![tspnperror](https://cloud.githubusercontent.com/assets/8156032/20559199/be65f5a6-b173-11e6-9c28-c9eca8321206.png)

**Comment by patrick-rodgers** [comment]
@biste5 - I am currently working on dropping the reference to core-js in @types but am blocked as discussed in [this thread](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11290). I am honestly considering just removing all type information from the npm package and forcing folks to install the typings using whatever system they want. I think that is less than ideal experience but this is turning into a circular problem that fixing one part breaks something for someone else. Had hoped @types was the solution but does not seem to be.

**Comment by celerity12** [comment]
I am having similar issue, please see https://github.com/SharePoint/PnP-JS-Core/issues/287 

i am using tsc v 2.1.4

**Comment by joelfmrodrigues** [comment]
Hi @patrick-rodgers, 
same problem here using the latest version of package with latest version of SharePoint Framework (RC0). This package is amazing :) is there something I can help with to get this resolved?

Joel

**Comment by patrick-rodgers** [comment]
@joelfmrodrigues - thanks for the kind words. I haven't had a chance to work with our latest with RC0 yet - been working on work + refactoring the provisioning library and getting it up in the new repo. So busy days. If you want to test out removing all the @types from sp-pnp-js and see if that builds with RC0 give it a go. My feeling currently is to not package any typing info with the library and document that folks may need to add some depending on their project. There are too many variables it seems to make it all work, so doing nothing might be best.

**Comment by joelfmrodrigues** [comment]
Hi @patrick-rodgers I will do my best to give it a try an let you know in case it worked 👍 I'm also super busy at work, but I'm trying to promote SPFx adoption within the team and this package is definitely a must have 🥇

**Comment by patrick-rodgers** [comment]
Things should now be working fully with RC0 release of SPFx. You will need to pull latest dev branch and ensure you have RC0 installed. If someone could verify it works somewhere other than my machine that would be great. Thanks!

**Comment by joelfmrodrigues** [comment]
@patrick-rodgers  that was a quick fix! It's working for me 👍

**Comment by patrick-rodgers** [comment]
Awesome - thanks @joelfmrodrigues for confirming. Will close this as the last issue before 2.0.0!

**Comment by joelfmrodrigues** [comment]
I'm getting this error when trying to run the SPFx project locally. Not sure if it's related
node_modules\@microsoft\sp-build-core-tasks\node_modules\source-map-loader-web-loader doesn't exist
