### ISSUE TITLE
Cross Domain multiple web application

### ISSUE THREAD

**Issue by Djemel** [SharePoint/PnP-JS-Core#230]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Expected / Desired Behavior / Question
I am using sp-pnp-js (on premise SP2013) in a Script Editor WebPart located in a web in https://webapp1.mycompany.com web application but I would need to gather data from a web in another web application https://webapp2.mycompany.com

I tried using the SP.RequestExecutory and/or CrossDomainRequest but without success.

Is the only way to achieve this to have an SharePoint Hosted Addin with "tenant level" permission or is there a way to do such a cross domain call outside an Addin ?

Thanks!

**Comment by patrick-rodgers** [comment]
If you are running in the browser you would execute with the permissions of the user - and provided they have permissions to the other web you want to access should be ok (let's just assume all the auth piping is working for SSO etc). - From an AUTH perspective.

But I think what you are running into is CORS limitations - yes? The cross domain libraries require an add-in web in the target, so you'd have to deploy something there.

My recommendation here would be a microservice you call from your client script that is registered as a tenant level provider hosted add-in (with read permissions or whatever is appropriate) which can gather the data you need and send it down.

**Comment by patrick-rodgers** [comment]
Closing this as answered since I haven't heard back, please reopen if you still have questions. Thanks!
