### ISSUE TITLE
results is undefined while getPaged

### ISSUE THREAD

**Issue by mauricionr** [SharePoint/PnP-JS-Core#231]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Observed Behavior
sp-pnp-js v1.0.5 

This list have 4500 itens.
![image](https://cloud.githubusercontent.com/assets/2263551/19574360/a9095612-96e8-11e6-94ec-a09ec6cba50c.png)

#### Steps to Reproduce
List with more than one item

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @mauricionr,

I've tried to duplicate this and cannot. What I did was create a new list and added ~150 items. I then executed a query exactly as you have above and I get back the paged items collection as expected. Is there another error like the list not existing in that web or having a different title? If you can provide a little more info I can try and repro the issue and fix it. Thanks!

```
list.items.orderBy("ID").top(1).getPaged().then(items => {
  Logger.log({ data: items, level: LogLevel.Verbose, message: "debugging" });
});
```

**Comment by mauricionr** [comment]
Hi @patrick-rodgers 

I've tried the same thing you did, create a new list and get the top

in the network tab i can see the response

![image](https://cloud.githubusercontent.com/assets/2263551/19652414/6cb9ebae-99ef-11e6-8f27-4bf6296a9575.png)

but in the then response is not the same as in network tab

![image](https://cloud.githubusercontent.com/assets/2263551/19652578/01c1abec-99f0-11e6-877f-f7bbe86b4018.png)

**Comment by patrick-rodgers** [comment]
Hmm, very strange - I just noticed you are using odata=verbose which I was not, let me play with that and see if I can reproduce, might be a parsing issue. Thanks!

**Comment by patrick-rodgers** [comment]
Just merged a fix into dev branch, if you get a chance please pull dev and ensure it is fixed for you as well. Thanks again for reporting this.

**Comment by patrick-rodgers** [comment]
Please pull dev again maybe - I did a bad merge and killed my changes but now is all set.

**Comment by patrick-rodgers** [comment]
Closing this as resolved, please let us know if you have further questions and thanks for reporting this issue!
