### ISSUE TITLE
Get web and add subsitex

### ISSUE THREAD

**Issue by okaufmann** [SharePoint/PnP-JS-Core#233]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Expected / Desired Behavior / Question
I'd like to know how to retrive a Web by its url or Title and how to add a subsite to this after fetched.
I can't found any docs describing this simple task and don't know how to use it the correct way.

The following code worked for just add a subweb to a existing web. But then I don't have all the latest information about the given Web, so I should reload it (I don't know how to do this either).

```typescript 
let web = new Web("https://a.sharepoint2013.host/shinywebs/
let create = web.webs.add("Shiny new Web!", "shine", "Oh its so shiny!");
```

Thanks!

**Comment by patrick-rodgers** [comment]
The important thing to remember is that everything is async when performing an action so returns a promise. That value in your above "create" is actually a promise. So you can do this:

```
web.webs.add(...).then(webAddResult => {

let j =   webAddResult.data;

  webAddResult.web.select("Title").get().then(...);
});
```

Then use the WebAddResult object which gives you the web that was just created as well as a "data" property which is the raw return from the creation operation in case you need that. @sksnips has a [good blog post on the basic web operations](http://www.ktskumar.com/2016/06/basic-web-operations-using-pnp-js-core-sharepoint/) and you can also see it in use in the [test setup method](http://www.ktskumar.com/2016/06/basic-web-operations-using-pnp-js-core-sharepoint/).

**Comment by okaufmann** [comment]
Thank you. Just found this blog too.
Is this blog linked anywhere in this Repo or Wiki? Would be useful for people new to PnP-JS-Core.

**Comment by okaufmann** [comment]
And how can I get a web from a specific url?

When I do it like this, I got a unknown type and can't get webs anymore.

```typescript
public getWebByUrl(url:string): Promise<any>{
   return new Web(webUrl).get();
}

let web = getWebByUrl("https://a.sharepoint2013.host/shinywebs/").then(console.log);
```

I noticed get() optionally want a ODataParser, should I use that? how?

**Comment by patrick-rodgers** [comment]
Just as you have above by using the Web object. Remember CORS limitations still apply. You should very likely never need to deal with the ODataParser stuff directly. Calling get() executes a REST query and gets an object with properties of that web. It returns a promise. If you are trying to use a web and do multiple things to it you can create a variable but remember the distinction of idea of building a query and executing the query. Setting things in the manner you are trying doesn't really work in async programming. Everything will flow through the promises and .then(). You can have a look at the [samples add-in](https://github.com/OfficeDev/PnP/tree/master/Samples/SharePoint.pnp-js-core) as well.

```
let web = new Web("the url you want")
web.lists.get().then((lists) => {
//   Do stuff with the lists which will be an array of plain objects with list data
});
```

**Comment by okaufmann** [comment]
Cool. Thanks for your detailed explanation. I close this issue now 👍 

Everything works fine :)

**Comment by gauravgoyal5** [comment]
How to open web by url i.e.
var MyWeb = $pnp.sp.crossDomainWeb('https://mysharepoint.sharepoint.com');

I am not able to open it up. It is showing error
Error: $pnp.sp.Web is not a function

I am using AngularJS 1.X. I am not using Angular 2 and Type Script.
How can I use web object for other web in current site collection?
i.e. I am on the root site collection but want to show data from a sub site.

Thanks,
Gaurav
