### ISSUE TITLE
Batch API

### ISSUE THREAD

**Issue by Tran-Kien** [SharePoint/PnP-JS-Core#237]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

I'm trying to use the batching API and I'm getting errors _Uncaught (in promise): Error: Bad Request_ when I do the following call:

`var batch = pnp.sp.createBatch();`
`pnp.sp.site.rootWeb.lists.getByTitle('MyList').items.inBatch(batch).get().then(function(data) {
  console.log(data);
}`
`batch.execute().then(function() {
  console.log("All is done!");
});`

But when I just do the following simple call, it works fine... 
`var batch = pnp.sp.createBatch();`
`pnp.sp.site.rootWeb.inBatch(batch).get().then(function(web) {
  console.log(web.Title);
}`
`batch.execute().then(function() {
  console.log("All is done!");
});`

Am I using inBatch() wrong when querying a list for its items?

Thanks!

**Comment by patrick-rodgers** [comment]
It looks like you are using inBatch correctly, my first guess is that the title of the list is not "MyList" but rather something else.

I did just try to repo this error and could not, so please double check the list title (not url).

**Comment by Tran-Kien** [comment]
Thanks for your prompt reply.

I forgot to mention that doing the call without the batch API actually works and I get the items.

I wanted to use the batch API as I have multiple calls to do and need to wait for all the calls to go on complete to perform further actions.

I have also successfully used inBatch with the current web pnp.sp.web.lists.getByTitle("MyList").items.get()

Could it be something with the fact that I'm querying a list on the rootweb?

**Comment by patrick-rodgers** [comment]
Just tried again and used the following code and it works as expected. I also tried originating the query from a sub web. Are you certain the list exists in the site's root web? Can you provide the full URL that is returning the bad request? you can scrub out your main domain but need to see what the _api part is.

below works as expected:
```
let batch = pnp.sp.createBatch();

pnp.sp.site.rootWeb.lists.getByTitle("LotsOfItems").items.inBatch(batch).get().then(i => {

    Logger.log({ data: i, level: LogLevel.Error, message: "debug" });

}).catch(r => {

    Logger.log({ data: r, level: LogLevel.Error, message: "error" });

});

batch.execute().then(_ => Logger.write("done"));
```

**Comment by Tran-Kien** [comment]
Thanks for looking into this. It turns out I was on version 1.0.4 and as soon as I changed the version to 1.0.5 it started working.

**Comment by patrick-rodgers** [comment]
Ah, ok thanks for letting me know. So the real issue is special characters in the list name causing problems with batching. I'll have a look and see if that is something we can address. Thanks.

**Comment by Tran-Kien** [comment]
Just another question about the batching API: Is it possible to use pnp.sp.search with the batching API? I can't seem to find any documentation about this.

**Comment by patrick-rodgers** [comment]
Been looking at this and not going to make any changes to the library to try and auto encode special chars. Going to leave that responsibility to the developers with these special chars. There are just too many possibilities for us to try and manage them automatically and once we open that door it will be an ongoing issue to support.

Search is not supported with batching.

Thanks for reporting the issue but going to close for now.

**Comment by sw-ms-harshbhavsar** [comment]
can we use "getItemsByCAMLQuery" with batching?

**Comment by phawrylak** [comment]
Yes, just write `list.inBatch(batch).getItemsByCAMLQuery()`.

**Comment by sw-ms-harshbhavsar** [comment]
I have a little different requirement.

var web = new $pnp.Web(_spPageContextInfo.siteAbsoluteUrl + '/facilities');
var batch = web.createBatch();
console.log(batch);

web.getList(_spPageContextInfo.webServerRelativeUrl + '/facilities' + '/Lists/Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
web.getList(_spPageContextInfo.webServerRelativeUrl + '/facilities' + '/Lists/Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
batch.execute().then(function () {
    alert('done')
});

**Comment by koltyakov** [comment]
I have a feeling you're mismatching web URLs, in one place it's `_spPageContextInfo.siteAbsoluteUrl + '/facilities'`, then `_spPageContextInfo.webServerRelativeUrl + '/facilities'`.

**Comment by sw-ms-harshbhavsar** [comment]
1st is for getting web object.
while the 2nd one is for getting a list from the web.

This is also not working


var web = new $pnp.Web(_spPageContextInfo.siteAbsoluteUrl + '/facilities');
var batch = web.createBatch();
console.log(batch);

web.lists.getByTitle('Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
web.lists.getByTitle('Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
batch.execute().then(function () {
    alert('done')
});
var web = new $pnp.Web(_spPageContextInfo.siteAbsoluteUrl + '/facilities');
var batch = web.createBatch();
console.log(batch);

web.lists.getByTitle('Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
web.lists.getByTitle('Events').inBatch(batch).getItemsByCAMLQuery({ ViewXml: "<View><Query><Where><And><Geq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-02-25</Value></Geq><Leq><FieldRef Name='EventDate' /><Value Type='DateTime' IncludeTimeValue='FALSE'>2018-04-08</Value></Leq></And></Where><ViewFields>  <FieldRef Name='Title' /> <FieldRef Name='Location' /><FieldRef Name='Description' /> <FieldRef Name='EndDate' /> <FieldRef Name='EventDate' /> <FieldRef Name='Attachments' /></ViewFields><OrderBy><FieldRef Name='EventDate' /></OrderBy></Query></View>" }).then(function (data) {
    console.log(data);
});
batch.execute().then(function () {
    alert('done')
});
