### ISSUE TITLE
Query search suggestions

### ISSUE THREAD

**Issue by kchiragowni** [SharePoint/PnP-JS-Core#238]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X ] Enhancement

#### Question
Can we use this library to query search suggestions (..._api/search/suggest?queryText='policies') if not then I think it would be very useful to include this in the core

Thanks!

**Comment by patrick-rodgers** [comment]
This is a good idea - but need to look at the best way to integrate the functionality. As in where on the API to hang it. Thanks!

**Comment by patrick-rodgers** [comment]
Have actually just merged this into the dev branch, you can now do something like below:

```
pnp.sp.searchSuggest({ 
    querytext: "item",
    includePeople: true,
 }).then(r => Logger.write(JSON.stringify(r)));
```
or

`pnp.sp.searchSuggest("item").then(r => Logger.write(JSON.stringify(r)));`

There are other options as well as defined [here](https://github.com/SharePoint/PnP-JS-Core/blob/dev/src/sharepoint/rest/searchsuggest.ts#L6).

**Comment by kchiragowni** [comment]
That's really cool. Thanks for swift response.

I guess I have to update my local pnp js core file or reference to cdnjs right?
