### ISSUE TITLE
Api documentation is not accessible

### ISSUE THREAD

**Issue by kchiragowni** [SharePoint/PnP-JS-Core#239]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X ] Question

#### Question
API documentation is not accessible http://officedev.github.io/PnP-JS-Core/ getting 404 error. 

Thanks!

**Comment by patrick-rodgers** [comment]
Thanks, updated the link on readme.md. The correct link is now https://sharepoint.github.io/PnP-JS-Core/. We moved the repo from officedev -> sharepoint org and are still finding all the little things that broke :) Appreciate you reporting this. Thanks!

**Comment by kchiragowni** [comment]
Thanks @patrick-rodgers
