### ISSUE TITLE
pnp.sp.search should also support GraphQuery and GraphRankingModel properties

### ISSUE THREAD

**Issue by arheom** [SharePoint/PnP-JS-Core#240]
#### Category

[X] Enhancement

[ ] Bug

[ ] Question
#### Desired Behavior

I try to use pnp.sp.search to find documents trending for me from the graph. I am able to use the GraphQuery and GraphRankingModel in the search rest api, but not using the pnp.sp.search. I think the graph will be used more and more these days, so makes sense to have an easy integration with it also in the pnp.

Thanks!
Bogdan

**Comment by arheom** [comment]
I already fixed it on my local branch (added basic Properties element to the search, so one can add more properties to the query and some properties are also the GraphQuery and GraphRankingModel). Can I get access to publish the branch and create a pull request for you to check?

**Comment by patrick-rodgers** [comment]
You don't need any special permissions - you would create a PR from your branch to the dev branch in this repo. I can then review and merge / provide comments as appropriate. Thanks!
