### ISSUE TITLE
pnp.sp.search does not work with Refiners set

### ISSUE THREAD

**Issue by arheom** [SharePoint/PnP-JS-Core#241]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Problem
I am trying to use pnp.sp.search to get some elements from SP Online. I am passing a list of Refiners, but I am getting the following error from search:
`{"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}`

The code I am using is:
`pnp.sp.search({
			Querytext: queryText,
			SelectProperties: selectProperties,
			EnableSorting: true,
			Refiners: ["DisplayAuthor"],
			SortList:sorts
		});`
Everything works well if I remove the Refiners property.
I see on the internet that property might be a string and not a string[]:
https://blogs.msdn.microsoft.com/nadeemis/2012/10/20/how-to-postquery-in-sharepoint-2013-search-rest-api/
but in the actual request we have the string[].

Thanks!
Bogdan

**Comment by patrick-rodgers** [comment]
Interesting, we based this off of [this resource](https://msdn.microsoft.com/en-us/library/office/jj163876.aspx) which appears to be wrong. I changed the Refiners property to a string and things seem to be working now. This is tied to PR #243 and is now in dev branch so you can try it out.

**Comment by SushanthYethonda** [comment]
Iam using "pnp search" for getting "all site urls" in my sitecollection. In url i am passing my root site url.
**i.e.,**
pnp.sp.search({"Querytext":"Path:myurl",
                              "RefinementFilters":"contentclass:sts_web",
				"TrimDuplicates":false,
				"EnableSorting":true,
				"RowLimit":3000,
				"SelectProperties":["Title","Author","Path","Description","Write","ParentLink","SiteLogo","ParentSiteTitle","Created"]});

but it is not returning results under PrimaryQueryResult.RelevantResults.Table.Rows.
