### ISSUE TITLE
File.prototype.moveTo

### ISSUE THREAD

**Issue by SaavanHirani** [SharePoint/PnP-JS-Core#244]
#### Category
[ ] Enhancement

[ X? ] Bug

[ X ] Question

#### Expected / Desired Behavior / Question
I am trying to make use of `File.prototype.moveTo()`. 

I have successfully been able to get my file by using `getFileByServerRelativeUrl()`.  I then try to use the result from that inside a `.then()` to invoke the `moveTo()`.  

```
$pnp.sp.crossDomainWeb($scope.appweburl, $scope.hostweburl).getFileByServerRelativeUrl(serverRelativeUrl).get().then(function (result) {
                                result.moveTo(finalPath, "Overwrite");
                            });
```
I have even tried using a `.then()` and anonymous function after the `.moveTo()` method without any luck.

#### Observed Behavior
I get an error back stating that:

`App.js:123 Uncaught (in promise) TypeError: result.moveTo is not a function`

I am just using this method incorrectly or is it actually a bug?

Regards.

**Comment by patrick-rodgers** [comment]
I think you want to leave off the ".get()". Calling .get() actually invokes the request and you are getting back the file properties in the result object. Would instead suggest trying:

`$pnp.sp.crossDomainWeb($scope.appweburl, $scope.hostweburl).getFileByServerRelativeUrl(serverRelativeUrl).moveTo(finalPath, 1).then(...);`

**Comment by SaavanHirani** [comment]
Hi Patrick,

Thanks for the advice, that work like a dream.  

Kind regards,
Saav.
