### ISSUE TITLE
Custom expiration date on  $pnp.storage.local.getOrPut method doesn't work.

### ISSUE THREAD

**Issue by sanjeev006** [SharePoint/PnP-JS-Core#245]
[x ] Bug

Hello - tried to use 

 $pnp.storage.local.getOrPut(storageKeyName, xxx, expiration).then(
            function (data) {
                xxx
            }
        );

where expiration is custom data value.  Unfortunately custom expiration date is never passed on to PnPClientStorageWrapper.prototype.put method so local storage entry is always sets with **expire = util_1.Util.dateAdd(new Date(), "minute", this.defaultTimeoutMinutes);** value.

PnPClientStorageWrapper.prototype.getOrPut = function (key, getter, expire) {
        var _this = this;
        if (!this.enabled) {
            return getter();
        }
        if (!util_1.Util.isFunction(getter)) {
            throw "Function expected for parameter 'getter'.";
        }
        return new Promise(function (resolve, reject) {
            var o = _this.get(key);
            if (o == null) {
                getter().then(function (d) {
                    _this.put(key, d, _expire_);
                    resolve(d);
                });
            }
            else {
                resolve(o);
            }
        });
    };

I was able to resolve this by updating **_this.put(key, d);** to **_this.put(key, d, _expire_);** as shown above. 

Can pnp,js and pnp-min.js be updated so we can either use "defaultTimeoutMinutes" or pass custom expiration date to getOrPut method?

Thanks

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, will have a look.

**Comment by patrick-rodgers** [comment]
Fixed in #246, will be part of the next release but you can pull dev branch and try it out. Thanks again for reporting this.

**Comment by sanjeev006** [comment]
Thanks Patrick for quick resolution.
