### ISSUE TITLE
batch and subwebs bug

### ISSUE THREAD

**Issue by johnnliu** [SharePoint/PnP-JS-Core#249]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question

```
// assume current web is at root /sites/root/

var subweb = new pnp.Web("/sites/root/subweb");
subweb.lists.getByTitle("Documents").get(); //great.

var batch = new $pnp.sp.createBatch();
subweb.lists.getByTitle("Documents").inBatch(batch).get(); //not great.

```
Http Response: bad request

#### Observed Behavior

The batch seems to execute against the current web 

https://github.com/SharePoint/PnP-JS-Core/blob/1f4c8ee30091aebf2d5cd72a6ba3c79a90f4ac38/src/sharepoint/rest/odata.ts#L269

calls 

https://github.com/SharePoint/PnP-JS-Core/blob/1f4c8ee30091aebf2d5cd72a6ba3c79a90f4ac38/src/utils/util.ts#L245

So we either need a constructor on the Batch object to specify the web, or use the subweb pnp.Web to create a new batch object.

**Comment by johnnliu** [comment]
I'm thinking a subweb.createBatch() method may make more sense, since batches has to execute against the right context web?

so I think this code looks better

var subweb = new pnp.Web("/sites/root/subweb");
var batch = subweb.createBatch();
subweb.lists.getByTitle("Documents").inBatch(batch).get(); 

and this code looks less great, but serviceable

var subweb = new pnp.Web("/sites/root/subweb");
var batch = new $pnp.sp.createBatch("/sites/root/subweb");
subweb.lists.getByTitle("Documents").inBatch(batch).get(); //not great.

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, let me think on it a bit. Definitely don't want to make someone pass a path twice as in your second example but also considering something like:

`pnp.sp.createBatch(subweb);`

End of the day certainly a bug to fix.

**Comment by patrick-rodgers** [comment]
Working on the web.createBatch syntax but change is actually affecting the plumbing more than I thought so will take a bit.

**Comment by patrick-rodgers** [comment]
Just merged #251 which contains this update. Added createBatch to both Web and Site objects as well as left pnp.sp.createBatch as is for proper compatibility. Pull dev and give it a try.

**Comment by patrick-rodgers** [comment]
@johnnliu - were you able to pull dev and have a look? Will be looking to close this shortly as I believe it to be resolved. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this as resolved, please reopen if you find issues. Thanks!
