### ISSUE TITLE
Get AllProperties from Web

### ISSUE THREAD

**Issue by Hennadiy** [SharePoint/PnP-JS-Core#253]
#### Category
[ + ] Enhancement

[ - ] Bug

[ + ] Question

I want to get AllProperties from web:
`pnp.sp.web.select('AllProperties').get()`
but this returns to me only url which i can query and i need to make additional service call
```
   pnp.sp.web.select('AllProperties').get().then((value): void => {

      ajax(value.AllProperties.__deferred.uri, {
        method: 'get',
        headers: {
          'Accept': 'application/json; odata=verbose'
        }
      }
```

Is there any better way to get it?

**Comment by mauricionr** [comment]
@Hennadiy try `pnp.sp.web.select('AllProperties').expand('AllProperties').get()`

**Comment by Hennadiy** [comment]
Great! Thank you.
