### ISSUE TITLE
Request body not added when using SPRequestExecutorClient

### ISSUE THREAD

**Issue by Abrissirba** [SharePoint/PnP-JS-Core#255]
#### Category
[ ] Enhancement

[ *] Bug

[ ] Question

#### Expected / Desired Behavior / Question
The following code, pnp.sp.crossDomainWeb(this.sharePointConfigService.addInWebUrl, this.sharePointConfigService.hostWebUrl).getFileByServerRelativeUrl(serverRelativeUrl).setContent(content), should update the content of the specified file.

#### Observed Behavior
The request body is null and there the content of the file will be empty

The error comes from this change, https://github.com/SharePoint/PnP-JS-Core/commit/fe7299dd8fb57f37e2a450b91d2cbd955acef4d9. 

Util.extend does not update the target object. Created a PR that fices the issue, https://github.com/SharePoint/PnP-JS-Core/pull/254

**Comment by patrick-rodgers** [comment]
Great catch, thanks for finding and fixing. Just merged the PR into dev. Thanks!
