### ISSUE TITLE
Response 204 with "" instead of null

### ISSUE THREAD

**Issue by Abrissirba** [SharePoint/PnP-JS-Core#256]
#### Category
[ ] Enhancement

[ *] Bug

[ ] Question

#### Expected / Desired Behavior / Question
pnp.sp.crossDomainWeb(this.sharePointConfigService.addInWebUrl, this.sharePointConfigService.hostWebUrl).getFileByServerRelativeUrl(serverRelativeUrl).setContent(content); should update the content of the file without throwing an exception.

#### Observed Behavior
ConvertToResponse in this file, https://github.com/SharePoint/PnP-JS-Core/blob/master/src/net/sprequestexecutorclient.ts, throws an exception in chrome because the body is "" when it should be null when the status is 204. Not sure if this should be considered as a bug in pnp-js-core or SP.RequestExecutor.js. 

I solved it temporarily with this code:
`var body = spResponse.statusCode === 204 && spResponse.body === "" ? null : spResponse.body;`

**Comment by patrick-rodgers** [comment]
Wouldn't we want here to just anytime the body === "" to pass null instead? Does the status code matter, or is this really specific to a Response object with a status code 204?

**Comment by Abrissirba** [comment]
From my understanding of things. A 204 response is a "No Content" response and therefore it should always be empty. Other status codes can return values in the body and an empty string is a value and should therefore not be converted to null.

**Comment by patrick-rodgers** [comment]
So looking at fixing this, should the logic be if 204 then null? we really don't care to check if the body is "" or not, right?

**Comment by patrick-rodgers** [comment]
Just merged this fix into dev - any chance you can pull dev and test in your scenario to ensure things are working for you @Abrissirba? Thanks!

**Comment by Abrissirba** [comment]
It seems to be working fine now :)

**Comment by patrick-rodgers** [comment]
Great, thanks for verifying!
