### ISSUE TITLE
Get file content as JSON

### ISSUE THREAD

**Issue by Abrissirba** [SharePoint/PnP-JS-Core#257]
#### Category
[ ] Enhancement

[ ] Bug

[* ] Question

In previous version it was possible to get the file content as a json object by getFileByServerRelativeUrl(serverRelativeUrl).value.get(). Is this possible in 1.0.6 or do I need to JSON.parse() on the response?

**Comment by patrick-rodgers** [comment]
You should be able to use the getText() method on File which was added with 1.0.6. That replaces the value along with getBlob() and getBuffer(). Took away value in favor of the more explicit methods. Let me know if that works for you.

**Comment by Abrissirba** [comment]
Yes, getText gets the content as text but when I used the value.get() the result was an object and not a string. This is not a big issue since a can do the parsing myself but it would be nice if there was a getJson aswell :)

**Comment by patrick-rodgers** [comment]
Makes sense, will add a getJSON() on File.

**Comment by patrick-rodgers** [comment]
Merged in #259 to dev

**Comment by Abrissirba** [comment]
Thanks Patrick! :)
