### ISSUE TITLE
Question about attachments

### ISSUE THREAD

**Issue by laimonas** [SharePoint/PnP-JS-Core#263]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Expected / Desired Behavior / Question

Any example how to add attachment to existing item or new item (base64 image)?

Thanks!

**Comment by patrick-rodgers** [comment]
Great question - we don't currently support attachments (image or other) but we had already been discussing that it was a good thing to take a look at adding. This helps jump it up the priorities so expect it in the next release. Thanks for your suggestion!

**Comment by koltyakov** [comment]
Hi there,

As was mentioned above, `attachmentFiles` is implemented as a QueryableCollection in read-only mode.
I was managed to extend current implementation with the class which allows basic add and delete operations for item's attachment.

@patrick-rodgers, as a superior master of the library, please take a glance at [this pull request](https://github.com/SharePoint/PnP-JS-Core/pull/264). :)

On my environment these options work now:

##### Add an attachment to the item

```javascript
var content = "binary/base64 content - bla bla bla";
var listRelativeUrl = "/sites/dev01/lists/custom01";
var itemId = 1;
var attachmentFileName = "MyFileName.txt";

$pnp.sp.web.getList(listRelativeUrl).items.getById(itemId).attachmentFiles.add(attachmentFileName, content).then(function() {
    console.log("Attachment has been added");
});
```

##### Delete an attachment to the item

```javascript
var listRelativeUrl = "/sites/dev01/lists/custom01";
var itemId = 1;
var attachmentFileName = "MyFileName.txt";

$pnp.sp.web.getList(listRelativeUrl).items.getById(itemId).attachmentFiles.getByName(attachmentFileName).delete().then(function() {
    console.log("Attachment has been deleted");
});
```

**Comment by laimonas** [comment]
Thank you both. Will be waiting next release :)

**Comment by patrick-rodgers** [comment]
Just added support via #264, if you pull dev you can check out the changes now. You'll find a attachmentfiles property on item. Going to close this issue. Thanks again for your interest!
