### ISSUE TITLE
Issues with Batching

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#266]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

I hava a typescript method deined as 
 public loadData(forceReload: boolean): Promise<SPSecurityInfo> {
    let securityInfo: SPSecurityInfo = new SPSecurityInfo();
    let batch: any = pnp.sp.createBatch();
    pnp.sp.web.inBatch(batch).siteUsers.get().then((response) => {
      securityInfo.siteUsers = response.map((u) => {
        let user: SPSiteUser = new SPSiteUser();
        user.id = u.Id;
        user.name = u.Title;
        if (u.UserId) {
          user.userId = new SPExternalUser();
          user.userId.nameId = u.UserId.NameId;
          user.userId.nameIdIssuer = u.UserId.NameIdIssuer;
        }
        return user;
      });
    });
    pnp.sp.web.inBatch(batch).siteGroups.expand("Users").select("Id", "IsHiddenInUI", "IsShareByEmailGuestUse", "IsSiteAdmin", "IsSiteAdmin").get().then((response) => {
      securityInfo.siteGroups = response.map((grp) => {
        let siteGroup: SPSiteGroup = new SPSiteGroup();
        siteGroup.id = grp.Id;
        siteGroup.title = grp.Title;
        siteGroup.userIds = grp.Users.map((user) => {
          return user.Id;
        });
        return siteGroup;
      });
    });
    return batch.execute().then(() => {
      return securityInfo;
    });
  }

the batch is resolving immediately (i e. the line  return securityInfo; is runn) before any of the 'child promises are resolved.  I ran fiddler and stepped through the process and saw that the individual calls were bing sent out immediately. I.e. after I setpped over the line ' pnp.sp.web.inBatch(batch).siteUsers.get().then((response) => '
I immediately saw fiddler send the request to sharepoint..

This was working previously. I just upgraded to SPFX Drop 5, I'm not sure if its related somehow.

**Comment by patrick-rodgers** [comment]
Thanks for reporting this @russgove, we'll try and have a look early next week and let you know what we find. Thanks!

**Comment by patrick-rodgers** [comment]
Hi @russgove - can you try moving the ".inBatch(batch)" to be the last thing before the .get() calls? Based on the code I think the batch is actually empty.

**Comment by russgove** [comment]
Thanks Patrick,. Moving inBatch() to the end fixed the issue.

**Comment by patrick-rodgers** [comment]
Glad to hear it, I'll close the issue now. Cheers!
