### ISSUE TITLE
New etag is not returned after calling update on a list item

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#273]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ x] Enhancement

[ ] Bug

[x ] Question

#### Expected / Desired Behavior / Question
using this code:
const promise = web.lists.getById(listid).items.getById(listItem.ID).update(typedHash, listItem["odata.etag"])
        .then((response) => {

the response object does not have the new etag that was assigned by sharepoint. The new etag is returned in the HTTP headers, but I don't see how I can access them from my code,

**Comment by russgove** [comment]
Here is  tthe raw hson from the update request:
HTTP/1.1 204 No Content
Cache-Control: private, max-age=0
Expires: Sun, 04 Dec 2016 20:02:59 GMT
Last-Modified: Mon, 19 Dec 2016 20:02:59 GMT
ETag: "4"
Server: Microsoft-IIS/8.5
....

I need to use that etag on my net update.

**Comment by patrick-rodgers** [comment]
Hi @russgove -

You do not have to use the etag for updates, it is optional and the default "*" will update regardless of the last etag. But, I see your point. I'll try and have a look over the holidays. Thanks,

Patrick

**Comment by patrick-rodgers** [comment]
@russgove - took a look at this and ended up rewriting the odata pipeline to fully move the responsibility for parsing responses to the parser and removed all logic from the Queryable class. This gives full control to the parser but should be transparent to consumers. Offshoot of this is that I added a parser to synthesize an object with an "odata.etag" property from the headers when you call item.update. Now the .data property of the item updated return value will have this property. This is now part of dev so give it a try, I'll close this but you can reopen if you find issues.
