### ISSUE TITLE
Uncaught (in promise) TypeError: this.getLogEntry is not a function

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/PnP-JS-Core#281]
#### Category
[ ] Enhancement

[x ] Bug

[x] Question

#### Observed Behavior / Steps to Reproduce

When running the following code, it should create error (cause the List does not exist). It does, but seems there is something wrong in the Error logging handling. Or is there somethign wrong with my code? I'm using the latest dev branch. 

```
Logger.subscribe(new ConsoleListener())

pnp.sp.web.lists.getByTitle("ImNotHere").get().then(function(result) {
    console.log(result);
});
```

will output to console the following error:
**Uncaught (in promise) TypeError: this.getLogEntry is not a function**

**Comment by patrick-rodgers** [comment]
Your code looks fine, taking a look now. I don't get that error so trying to find where it is happening. I might just be missing it in my testing. Thanks for reporting this.

**Comment by tavikukko** [comment]
It might also be something to do with inheriting from Error.
I created sample in [typescript playground](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20uncomment%20these%20to%20test%20when%20inheriting%20from%20Error%0D%0A%2F%2Fabstract%20class%20Exception%20extends%20Error%20%7B%0D%0Aabstract%20class%20Exception%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20*%20%40param%20name%20The%20Name%20given%20to%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%40param%20message%20The%20message%20contained%20by%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%0D%0A%20%20%20%20%20*%2F%0D%0A%20%20%20%20constructor(name%3A%20string%2C%20message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20uncomment%20these%20to%20test%20when%20inheriting%20from%20Error%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20super(message)%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20this.name%20%3D%20name%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'cat'%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Log()%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.getLogEntry())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Represents%20an%20exception%20with%20an%20HttpClient%20request%0D%0A%20*%20%0D%0A%20*%2F%0D%0Aclass%20ProcessHttpClientResponseException%20extends%20Exception%20%7B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(%22ProcessHttpClientResponseException%22%2C%20%60Error%20making%20HttpClient%20request%20in%20queryable%60)%3B%0D%0A%20%20%20%20%20%20%20%20super.Log()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'dog'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20test%20%3D%20new%20ProcessHttpClientResponseException()%3B). This works, when not inheriting from Error. If you remove the commented lines from sample and switch it inheriting from Error, you will get the same error as in pnp-js-core.

**Comment by tavikukko** [comment]
@patrick-rodgers [here's a working sample](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20uncomment%20these%20to%20test%20when%20inheriting%20from%20Error%0D%0A%2F%2Fabstract%20class%20Exception%20extends%20Error%20%7B%0D%0Aabstract%20class%20Exception%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20*%20%40param%20name%20The%20Name%20given%20to%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%40param%20message%20The%20message%20contained%20by%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%0D%0A%20%20%20%20%20*%2F%0D%0A%20%20%20%20constructor(name%3A%20string%2C%20message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20uncomment%20these%20to%20test%20when%20inheriting%20from%20Error%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20super(message)%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20this.name%20%3D%20name%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'cat'%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Log()%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.getLogEntry())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Represents%20an%20exception%20with%20an%20HttpClient%20request%0D%0A%20*%20%0D%0A%20*%2F%0D%0Aclass%20ProcessHttpClientResponseException%20extends%20Exception%20%7B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(%22ProcessHttpClientResponseException%22%2C%20%60Error%20making%20HttpClient%20request%20in%20queryable%60)%3B%0D%0A%20%20%20%20%20%20%20%20super.Log()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'dog'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20test%20%3D%20new%20ProcessHttpClientResponseException()%3B#src=interface%20IError%20extends%20Error%20%7B%0D%0A%20%20%20%20getLogEntry()%3A%20string%3B%0D%0A%20%20%20%20Log()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Exception%20implements%20IError%20%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20*%20%40param%20name%20The%20Name%20given%20to%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%40param%20message%20The%20message%20contained%20by%20the%20Error%20instance%0D%0A%20%20%20%20%20*%20%0D%0A%20%20%20%20%20*%2F%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20message%3A%20string%3B%0D%0A%20%20%20%20constructor(name%3A%20string%2C%20message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20name%3B%0D%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'cat'%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20Log()%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(this.getLogEntry())%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Represents%20an%20exception%20with%20an%20HttpClient%20request%0D%0A%20*%20%0D%0A%20*%2F%0D%0Aclass%20ProcessHttpClientResponseException%20extends%20Exception%20%7B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(%22ProcessHttpClientResponseException%22%2C%20%60Error%20making%20HttpClient%20request%20in%20queryable%60)%3B%0D%0A%20%20%20%20%20%20%20%20super.Log()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20getLogEntry()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'dog'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20test%20%3D%20new%20ProcessHttpClientResponseException()%3B), we just need to create interface from the Error and implement it.

**Comment by patrick-rodgers** [comment]
Fixed and merged in #282 - give that a try please.

**Comment by tavikukko** [comment]
yes it works, thanks.
