### ISSUE TITLE
How to open web by url i.e.

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/PnP-JS-Core#284]
How to open web by url i.e. 
var MyWeb = $pnp.sp.crossDomainWeb('https://mysharepoint.sharepoint.com');

I am not able to open it up. It is showing error 
Error: $pnp.sp.Web is not a function

**Comment by russgove** [comment]
you can try 
import {Web} from pnp
var MyWeb = new Web('https://mysharepoint.sharepoint.com');

**Comment by patrick-rodgers** [comment]
You can also review the discussion in [this thread](https://github.com/SharePoint/PnP-JS-Core/issues/233).

**Comment by russgove** [comment]
you can try
import {Web} from pnp
var MyWeb = new Web('https://mysharepoint.sharepoint.com/some/other/web')

**Comment by gauravgoyal5** [comment]
This will work with TypeScript. I am not using TypeScript. I am using simple JavaScript.

**Comment by patrick-rodgers** [comment]
I think then you need something like this:

```
var w = new $pnp.Web("url");
w.lists...
```

The objects are exported at the top level. You should be able to see them all in a debugger as well to give you an idea what is available.

**Comment by karthik15981** [comment]
I am using the following code

```
var web = new pnp.Web("http://xxx/sites/xxx");
            web.select("Title").get()
            .then(function (data) {
                console.log(data.Title);
            })
            .catch(function (data) {
                alert(data);
            });
```

With this code I got a 406 NOT ACCEPTABLE error

_fetchclient.js:6 GET http://xxx/sites/xxx/_api/web?$select=Title 406 (Not Acceptable)
Uncaught (in promise) Error making HttpClient request in queryable: Not Acceptable_

To fix this I had to edit the pnp.js file and change the following code:

```
var headers = {
                "Accept": "application/json;",
            };
```

to

```
var headers = {
                "Accept": "application/json;odata=verbose",
            };
```

After I made this change, it works fine.

Is there a better solution?

**Comment by patrick-rodgers** [comment]
Yes, you can just set the global headers if you are working in an environment that does not support the minimal metadata as outlined in [this blog post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/06/13/pnp-jscore-1-0-1/). Editing the pnp.js file directly isn't recommended.

**Comment by karthik15981** [comment]
> Yes, you can just set the global headers if you are working in an environment that does not support the minimal metadata as outlined in this blog post. Editing the pnp.js file directly isn't recommended.

Thank you!!

Did as mentioned in the blog post and it works like a charm. 

Would be nice to have this _setup_ option mentioned in the [wiki getting started](https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Install-&-Use) page.  Would definitely help newbies like me out there :)

**Comment by patrick-rodgers** [comment]
Going to close this as I believe it is resolved.

**Comment by sinr0202** [comment]
I landed here trying to find any documentations/examples on crossDomainWeb mentioned in #135 i believe the original question was trying to figure out how to work around cors like i am
