### ISSUE TITLE
GroupWritableProperties : "Title", not "title"

### ISSUE THREAD

**Issue by aurelienprevotMVP** [SharePoint/PnP-JS-Core#288]
Hi guys,

In TypeScript, when you want to create a site group, the property "title" should be "Title".
I'm speaking about the line 31 of this file : https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/rest/sitegroups.ts

According to [the documentation](https://msdn.microsoft.com/en-us/library/office/dn531432.aspx), I've made the test on my tenant and it is working with "Title" and not with "title".

Thank you for your awesome work !

**Comment by aurelienprevotMVP** [comment]
After other test, I've just figured out that it's also true for "description" which should be "Description". Do you want me to test for all of those attributes ?

**Comment by patrick-rodgers** [comment]
Instead I think the correct thing is to just remove those interfaces and have it work like all of the other classes where you can just pass a plain object. Likely if those two are wrong most of the others are as well - which is ultimately my fault for not fully testing this when it was submitted.

**Comment by aurelienprevotMVP** [comment]
Don't care about the fault, only about the solution !
Thank you very much !

**Comment by patrick-rodgers** [comment]
This fix is in dev branch now if you want to give it a try.

**Comment by patrick-rodgers** [comment]
Closing as fixed in dev branch - fix was to remove those interface and align the code to the rest of the library.
