### ISSUE TITLE
How to add/associate a site column to a content type?

### ISSUE THREAD

**Issue by karthik15981** [SharePoint/PnP-JS-Core#290]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Expected / Desired Behavior / Question
How to add/associate a site column to a content type?

#### Observed Behavior
My requirement is to create a new site column, a new content type and add the site column to that content type.

I am able to add a new content type using code like this:

```
web.contentTypes.add("id_xxx", "name", "desc", "group", {"Sealed": "False"})
                .then(function (result) {
                    console.log("Created Content Type: " + result.data.Name);
                })
                .catch(function (err) {
                    console.log(err);
                });
```
I am able to add a site column using this:

```
var fieldXML = "<Field ID='{afbac031-ead6-4274-b6e1-9140bcadfaea}' Name='FldName' DisplayName='DspName' Type='Text' Required='TRUE' Group='Custom Site Columns'></Field>";
            web.fields.createFieldAsXml(fieldXML)
                .then(function (result) {
                    console.log("Created Field ID: " + result.data.Id);
                })
                .catch(function (err) {
                    console.log(err);
                });
```

I am not able to figure out how to add this site column to the content type.

Can you please help?

Thanks!

**Comment by patrick-rodgers** [comment]
We don't currently have a method for that as part of the library. Will need to look at what it will take to implement. Thanks for the suggestion.

**Comment by patrick-rodgers** [comment]
After having a look I remember that it isn't really possible. The exposed REST end point looks at the parent content type (which makes it basically not work). You can [read the details](https://msdn.microsoft.com/EN-US/library/office/jj245869.aspx#postsyntax). On a happier note based on working on this I have added a FieldLinks class that should support _some_ additional functionality, though unfortunately not add. Going to close this as unfixable based on current API. You can always vote on uservoice it this is important functionality. Easy to add once the API is updated behind the scenes.
