### ISSUE TITLE
Allow to get the SP.File from SP.ListItem if the SP.ListItem has a File property.

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-JS-Core#292]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Be abilty to call something like this
pnp.sp.web.lists.getByTitle("<title of document Library ").items.getById(<List Item ID>).file.get()
 to get the SP.File from List Item that stores the metadata.

#### Observed Behavior
When getting list item from Document Library to update or change metadata fields, then you want to get retrieve the SP.File object, even thou the rest api has File property what contains the url to get the SP.File object.

Thanks!

**Comment by patrick-rodgers** [comment]
Good suggestion, added a file property to the item class.
