### ISSUE TITLE
Managed Metadata - How to update a list item?

### ISSUE THREAD

**Issue by yngrdyn** [SharePoint/PnP-JS-Core#295]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

How to update a Managed metadata item field using PnP-JS-Core?

I realized, If PnP-JS-Core is based in API REST so, let's use the API REST format. I'm trying to pass an object like:

var myObject = {
        __metadata: {"type" : "SP.Taxonomy.TaxonomyFieldValue"},
        Label: term.get_name(),
        TermGuid: term.get_id().toString(),
        WssId: -1
};
Now I don't get an error now but the field is not updated.

Could you help me?

Thanks!

**Comment by patrick-rodgers** [comment]
The below works for me. I think the lable is the ID of the label to use, generally 1 unless you are using localizations. The guid id is the value that appears on the term editing page as the unique identifier. If you do a get you can see those are the values that come back.

```TypeScript
    let list = pnp.sp.web.lists.getByTitle("termlist");

    list.items.getById(1).update({
        MetaData: {
            __metadata: { "type": "SP.Taxonomy.TaxonomyFieldValue" },
            Label: "1",
            TermGuid: "6eccf028-399c-486d-9260-72c81f2d5344",
            WssId: -1
        }
    }).then(i => {

        console.log(i);

    });
```

HTH

**Comment by patrick-rodgers** [comment]
Closing this as resolved, please reopen if you still have questions.

**Comment by olemp** [comment]
@patrick-rodgers I get success on the update, but the item is not updated.

**Comment by patrick-rodgers** [comment]
Hmm..not sure. The above worked for me in SPO. I also had a very simple terms setup for for testing. What environment?

**Comment by yngrdyn** [comment]
@olemp it didn't work for me either.
I'm using SPO.

**Comment by webtechy** [comment]
Did you get this resolved @yngrdyn @olemp?

**Comment by yngrdyn** [comment]
No @webtechy 
I had to update the managed metadata fields using JSOM.

**Comment by webtechy** [comment]
(Worked for me with a single item taxonomy picker field)

**Comment by oyvindam** [comment]
Quick followup on this: [Here is a quick description of how we solved the multi-value issue](http://www.pointtaken.no/blogg/updating-single-and-multi-value-taxonomy-fields-using-pnp-js-core/)

**Comment by matthewrobb** [comment]
@oyvindam How would one add a new term to an item without first adding it to the termset? Can I just throw new stuff into the termString?

**Comment by oyvindam** [comment]
@matthewrobb I'm assuming you mean "fill-in"-choices on an open termset. Gut feeling is probably not, but worth a try I guess. So far I've done this with existing terms, e.g. retrieving values from a taxonomy field in one list and writing them to a tax field in a second list.

**Comment by Rajesh-Pradhan** [comment]
not bale to get any link for adding the MMS term to list column

**Comment by nareshkapa** [comment]
Hi, I am trying to create a new item( using sp.web.lists.getByTitle('Title').items.add({}) ), how can i set the value for Multi value enabled Managed metadata column? could you provide any help or suggestions on this?
