### ISSUE TITLE
ver 2.0.* available through NPM

### ISSUE THREAD

**Issue by jarzimichal** [SharePoint/PnP-JS-Core#296]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Expected / Desired Behavior / Question
I would like to be able to download 2.0.* ver from NPM to play with NodeFetchClient and localhost authentication when using Angular2. 

#### Observed Behavior
When I use `import { setup, Web, NodeFetchClient } from "sp-pnp-js";` in ver 1.0.6 I got error that NodeFetchClient is not accessible. 

#### Submission Guidelines
There is article about using ver 2.0, however I can't install it through npm:  https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-1.0.*-to-2.0.* 

Thanks!
Michal

**Comment by patrick-rodgers** [comment]
Indeed and we are very close. I'm excited about getting it out, and the articles will be part of that release. Just trying to get things staged and ready. The menu of the wiki will be updated along with the release to pull those articles front and center. I'm looking forward to it as much as anyone :)

Sent from my iPhone

On Jan 12, 2017, at 8:50 PM, jarzimichal <notifications@github.com<mailto:notifications@github.com>> wrote:

Category

[ ] Enhancement

[ ] Bug

[x] Question

Expected / Desired Behavior / Question

I would like to be able to download 2.0.* ver from NPM to play with NodeFetchClient and localhost authentication when using Angular2.

Observed Behavior

When I use import { setup, Web, NodeFetchClient } from "sp-pnp-js"; in ver 1.0.6 I got error that NodeFetchClient is not accessible.

Submission Guidelines

There is article about using ver 2.0, however I can't install it through npm: https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-1.0.*-to-2.0.*

Thanks!
Michal

-
