### ISSUE TITLE
GetUserEffectivePermissions error

### ISSUE THREAD

**Issue by somartin90** [SharePoint/PnP-JS-Core#300]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question

When I call method "getUserEffectivePermissions(loginName: string): Queryable", it returns bad request.
I think the url is not being built correctly.

#### Observed Behavior

I have been able to solve this problem by replacing the following code in queryablesecurable.ts:

public getUserEffectivePermissions(loginName: string): Queryable {
        this.append("getUserEffectivePermissions(**@user**)");
        this._query.add("**@user**", "'" + encodeURIComponent(loginName) + "'");
        return new Queryable(this);
    }

By this:

public getUserEffectivePermissions(loginName: string): Queryable {
        this.append("getUserEffectivePermissions(**@target**)");
        this._query.add("**@target**", "'" + encodeURIComponent(loginName) + "'");
        return new Queryable(this);
    }

I hope to receive your feedback
Thanks!

**Comment by patrick-rodgers** [comment]
Thanks @somartin90 - good catch, not sure how that slipped through for so long. Fixed as part of #299. Will close this, appreciate you reporting it.
