### ISSUE TITLE
Usable outside SharePoint?

### ISSUE THREAD

**Issue by Tim86** [SharePoint/PnP-JS-Core#303]
[x] Question

Is there a way to use the library without running on a SharePoint page? If so, how would authentication work?

Thank you!

**Comment by patrick-rodgers** [comment]
@Tim86 - can you tell us a little more about your scenario? You can use the library in nodejs, [details here](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#fetch-client-factory). Note these instructions are for 2.0.0 which is about to be released (likely Monday).

**Comment by mauricionr** [comment]
@Tim86 check out my nodejs demo tracking hashtag's on twitter and saving in sharepoint list

**Comment by Tim86** [comment]
@patrick-rodgers - I was thinking about experimenting with it on a page which does not load the sp.js and the other SharePoint scripts. Either on the SharePoint domain or maybe even in a completely different, like in a cordova app.

**Comment by mauricionr** [comment]
@Tim86 looks like a provider hosted app?

**Comment by patrick-rodgers** [comment]
@Tim86 - as @mauricionr said that sounds a lot like a provider hosted add-in. The library will work in the sense that you are just making REST calls to SharePoint but you have to look at the authentication. You could look at using something like node-sp-auth [blog post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/10/17/using-pnp-js-core-and-node-sp-auth/). You should avoid embedding the credentials into the application in some way - and especially avoid including a client id and secret in the application. You can write your own HttpClientImpl to handle custom security scenarios as outlined [here](https://github.com/SharePoint/PnP-JS-Core/wiki/Custom-HttpClientImpl), but this isn't something we can provide support for.

You can just load the script on a page from the style library using a script editor web parts and do things as well inside SharePoint.

**Comment by patrick-rodgers** [comment]
Hi @Tim86 - haven't heard back from you in a bit so hopefully we've answered your question. If not please re-open this issue and let us know what else we can help with - going to close as resolved. Thanks!

**Comment by Tim86** [comment]
Hi @patrick-rogers - sorry for not replying. I think that the provider hosted add in is the solution that answers my question yes. Thank you for your support!

**Comment by pridemusvaire** [comment]
Is there a way to authenticate client-side with sp-pnp-js, I would like to test my apps on my local machine without deploying to a SharePoint env.

**Comment by koltyakov** [comment]
Hey @pridemusvaire,

We use [this](https://www.linkedin.com/pulse/local-spfx-workbench-against-real-sharepoint-api-andrew-koltyakov/) approach. The article shows an example of usage with SPFx, extra section is dedicated to how to configure PnPjs to work with proxy, there are also examples of CEWP/ Assets' style development in project's readme. 

We use such dev workflow for a large MPA React apps. Some folks do the same with Angular as well.
