### ISSUE TITLE
source-maps-loader issue

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/PnP-JS-Core#304]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Expected / Desired Behavior / Question
Hi guys, is the dev branch now fully working with the SharePoint framework?

#### Observed Behavior
I'm getting a very long list of errors just by trying to use sp-pnp-js on a new project. I suspect it may be related to my machine or user error...
Updated all my global packages today and using npm link to the latest dev branch version of sp-pnp-js.

Errors happen when running gulp serve on the webpart project, when executing 'webpack' task and seems to be related to source-maps-loader module as all the errors relate to it. 

Small extract of the error:

[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-webpack-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-webpack-loader.web-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader.webpack-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader.web-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader.loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-web-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader.web-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader.webpack-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader.loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader.webpack-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader.loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader.js]
[C:\Users\rodriguesj\Documents\GitHub\PnP-JS-Core\node_modules\source-map-loader.web-loader.js]
 @ ../PnP-JS-Core/lib/pnp.js 41:9-33

#### Steps to Reproduce
Create a new SP webpart using yeoman
Create an npm link reference to PnP-JS-Core (dev branch)
import sp-pnp-js on the webpart project
add some code using the imported module and run gulp serve

Thanks!

**Comment by patrick-rodgers** [comment]
Did you run `gulp package` in the sp-pnp-js project? That creates all the files that would be in the npm package.

**Comment by joelfmrodrigues** [comment]
Yes I did. Just done again, "just in case", but the problem remains

**Comment by patrick-rodgers** [comment]
I am not sure how you've set up your environment but I can't duplicate this. I pulled latest from dev branch, did a gulp package, then did an npm install c:\{path to sp-pnp-js repo on my machine}, then ran gulp serve. Everything worked as expected.

**Comment by russgove** [comment]
Hi,
I think Joel was  npm installing from the npm repo. So he is getting the
v1.x build and running it with spfx, which would give him those errors.

Joel,
Once patrcick pushes v2.0 out you should be fine.

Patrick,
I had no Idea you could npm install c:{path to sp-pnp-js repo on my
machine},! i have been manually copying the folders from my pnp to my other
project. We should document that somewhere in the contributors notes
Russell

**Comment by joelfmrodrigues** [comment]
Hi @patrick-rodgers  I will try to install using the path to the folder instead of using npm link. sorry if this is user error...first time I'm actually trying to run it from my machine 

@russgove I'm not installing from npm. I'm using npm link, which basically creates a shortcut to the folder when the project is located. I've used this approach before with private modules and never had issues.

**Comment by joelfmrodrigues** [comment]
@patrick-rodgers  you are a star 👍 
I've removed the package previously installed using npm link and installed it using the path on my machine. It just worked! 
I'm happy with the solution, but do you have any idea why it didn't work with npm link? I'm curious :)
