### ISSUE TITLE
OfficePnPClientSideJavaScriptSIG.ics cannot be imported to Google Calendar

### ISSUE THREAD

**Issue by VelinGeorgiev** [SharePoint/PnP-JS-Core#306]
OfficePnPClientSideJavaScriptSIG.ics located on https://dev.office.com/patterns-and-practices cannot be imported to Google Calendar.

#### Category
[x ] Enhancement

#### Expected / Desired Behavior / Question
Successful import

#### Observed Behavior
Could not import the iCal error

#### Steps to Reproduce
Go to Google Calendar => Settings => Import calendar => select the OfficePnPClientSideJavaScriptSIG.ics

Thanks!

**Comment by patrick-rodgers** [comment]
The ics file is just a standard ics file, unfortunately there isn't anything to "fix" here as it was just exported from outlook. If you continue to encounter errors it might be easiest for you to directly create a reoccurring meeting every two weeks (starting Feb 2 as the next meeting). The direct link to join the meeting is below.

https://join.microsoft.com/meet/patrodg/56VW2859

Hope to see you on the calls!

**Comment by akhileshnirapure** [comment]
@patrick-rodgers  would be great if you can somehow update this, i could get the other PnP call invite imported in Google Calendar but not this one, i don't get reminded and always miss :-(
