### ISSUE TITLE
Duplicated information in documentation

### ISSUE THREAD

**Issue by mauricionr** [SharePoint/PnP-JS-Core#312]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Expected / Desired Behavior / Question
Appears only once and not twice

#### Observed Behavior
![image](https://cloud.githubusercontent.com/assets/2263551/22468191/984cdba2-e7ae-11e6-8416-20f8d5942219.png)

#### Steps to Reproduce
go to these links for example

https://sharepoint.github.io/PnP-JS-Core/FetchClient.html

https://sharepoint.github.io/PnP-JS-Core/File.html

https://sharepoint.github.io/PnP-JS-Core/Field.html

...

I guess all classes in documentation is duplicated in a same page

Thanks!

**Comment by patrick-rodgers** [comment]
Hmm, interesting. I am just using JSDoc as standard so nothing custom is happening.

**Comment by mauricionr** [comment]
@patrick-rodgers i found an issue here https://github.com/jsdoc3/jsdoc/issues/1002

**Comment by patrick-rodgers** [comment]
Good find - seems to be related. I changed the recurse flag in the jsdoc.json to false and that seems to have fixed it. I'll leave this open since I need to actually update the docs branch but will close it when I do. Thanks!

**Comment by patrick-rodgers** [comment]
Resolved in 2.0.1 release and docs site updated.
