### ISSUE TITLE
SyntaxError: Unexpected token: name (Def) when "gulp bundle --ship" with sp-pnp-js

### ISSUE THREAD

**Issue by webtechy** [SharePoint/PnP-JS-Core#314]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Expected / Desired Behavior / Question
Solution should build for both "gulp build" and "gulp build --ship".

#### Observed Behavior
It builds correctly if I use "gulp build", but if I do "gulp build --ship" I get:

`[23:39:54] Starting subtask 'webpack'...
[23:40:36] Error - [webpack] 'dist':
requirements-form.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (Def) [./~/source-map-loader!./~/sp-pnp-js/l
ib/pnp.js:43,0]
`
#### Steps to Reproduce
In my TS I have:

`import * as sp from "sp-pnp-js";`

And:

`new sp.Web(AppSettings.SHAREPOINT_SITE_URL).lists.getByTitle("Requirements").items.add({
            Title: this.Requirement.Title,
            Requirement_x0020_Details: this.Requirement.Details,
            Requirement_x0020_Rating: this.Requirement.Rating,
        }).then((result) => {
            this.newRequirement = this.Requirement.Title;
            this.itemAdded = true;
            setTimeout(function () {
                this.itemAdded = false;
            }.bind(this), 3000);
            this.reset();
            this.loading = "done";
            console.log('BGW: Completed');
        }).catch((e) => { this.loading = "error"; });`

My tsconfig.json is as follows:

`{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    //"types": [
    //  "webpack-env"
    //]

    // KENDOUI CHANGES:
    //"moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    //"lib": ["es6", "dom"],
    "mapRoot": "./",
    //"module": "es6",
    "moduleResolution": "node",
    "typeRoots": [
      "./node_modules/@types" // This is a directory higher than in the Kendo project
    ]
    /*,
    "types": [
      "jasmine",
      "webpack-env",
      "node"
    ]*/
  }
}`

In my package.json I have:

`{
  "name": "sharepoint-app",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@angular/common": "^2.4.5",
    "@angular/compiler": "^2.4.5",
    "@angular/core": "^2.4.5",
    "@angular/forms": "^2.4.5",
    "@angular/http": "^2.4.5",
    "@angular/platform-browser": "^2.4.5",
    "@angular/platform-browser-dynamic": "^2.4.5",
    "@angular/router": "^3.4.5",
    "@microsoft/sp-client-base": "~0.7.0",
    "@microsoft/sp-client-preview": "~0.9.0",
    "@microsoft/sp-core-library": "~0.1.2",
    "@microsoft/sp-webpart-base": "~0.4.0",
    "@progress/kendo-angular-buttons": "^0.16.0",
    "@progress/kendo-angular-dropdowns": "^0.26.9",
    "@progress/kendo-angular-grid": "^0.14.0",
    "@progress/kendo-angular-intl": "^0.9.0",
    "@progress/kendo-angular-layout": "^0.20.1",
    "@progress/kendo-angular-upload": "^0.13.1",
    "@progress/kendo-data-query": "^0.3.5",
    "@progress/kendo-theme-default": "^2.11.8",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "json-stringify": "^1.0.0",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.0.3",
    "sp-pnp-js": "^2.0.0",
    "ts-helper": "0.0.1",
    "tslint": "^4.4.2",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~0.9.0",
    "@microsoft/sp-module-interfaces": "~0.7.0",
    "@microsoft/sp-webpart-workbench": "~0.8.0",
    "@types/chai": "^3.4.34",
    "@types/jasmine": "^2.5.41",
    "@types/mocha": "^2.2.38",
    "@types/node": "^7.0.4",
    "bootstrap-loader": "^2.0.0-beta.20",
    "bootstrap-sass": "^3.3.7",
    "codelyzer": "^2.0.0-beta.4",
    "css-loader": "^0.26.1",
    "gulp": "^3.9.1",
    "gulp-spsave": "^3.0.0",
    "html-loader": "^0.4.4",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^3.2.0",
    "jquery": "^3.1.1",
    "karma": "^1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "node-sass": "^4.3.0",
    "resolve-url-loader": "^1.6.1",
    "sass-loader": "^4.1.1",
    "sp-pnp-js": "^1.0.6",
    "spsave": "^3.0.2",
    "style-loader": "^0.13.1",
    "ts-node": "^2.0.0",
    "tslint": "^3.15.1",
    "typescript": "^2.1.5",
    "url-loader": "^0.5.7"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  }
}`

Thanks!

**Comment by patrick-rodgers** [comment]
Issue here is likely a lack of support for es6 in uglify, which is what is deployed in the npm package lib folder for sp-pnp-js now. You can [register this library as an external](https://github.com/SharePoint/PnP-JS-Core/wiki/Deployment#cdn-and-spfx) which should allow you to continue in ship mode.

When we build the library's dist files we use babel to get around this limitation.

**Comment by webtechy** [comment]
Thank you very much. That solved the problem. I would have been stuck on that for a while.

**Comment by webtechy** [comment]
(Although it does not seem to get stuck on:

[01:03:33] Starting subtask 'copyAssets'...

**Comment by webtechy** [comment]
**EDIT: Issue resolution to comment above**

Resolution was to change prepare-deploy.json from:

{ "deployCdnPath": "https://[somecompany].sharepoint.com/sites/Development/SiteAssets/[SomeFolder]/" }

Back to:

{ "deployCdnPath": "temp/deploy" }

**Comment by patrick-rodgers** [comment]
@webtechy - glad to hear you are unblocked. A little unclear - are you saying we need to update the wiki article? Want to make sure we have the right info out there for folks.

**Comment by webtechy** [comment]
Perhaps the "deployCdnPath" should be renamed so you don't assume it should be changed to the same value as cdnBasePath in write-manifests.json - but assume that relates to @microsoft/sp-dev-docs more than SharePoint/PnP-JS-Core. Other than that, I guess we just need to wait for ES6 support n Uglify, or use a different tool other than Ugilify. Seeing as PnP-JS-Core is going to be wrapped up in SPFx it makes sense to resolve this (or get external reference added by default to the SharePoint Yeoman project).

**Comment by patrick-rodgers** [comment]
Have also mentioned this issue in [an article](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-in-SPFx) I'm staging for 2.0.1 release. Should also hopefully help.

**Comment by patrick-rodgers** [comment]
Closing this issue as it appears to be mitigated with a successful workaround.

**Comment by russgove** [comment]
PnP-JS-Core is going to be wrapped up in SPFx?

**Comment by patrick-rodgers** [comment]
Update on this, we are going to roll back to es5 in lib folder. That should resolve a lot of these compat issues and not require any special steps. [Ref](https://github.com/SharePoint/PnP-JS-Core/issues/327#issuecomment-284273796)

**Comment by patrick-rodgers** [comment]
@russgove - I haven't heard anything like that.
