### ISSUE TITLE
Framework is return undefine for a file's ServerRelativeUrl when you get the file from listitem

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-JS-Core#315]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
The file's ServerRelativeUrl  property should have the relative url to the file in sharepoint 
#### Observed Behavior
The file's ServerRelativeUrl  property is undifine

#### Steps to Reproduce
1. Have a document lib called "Document Attactments"
2. pnp.sp.web.lists.getByTitle("Document Attactments").items.getById("<id of a file listitemid>").file.get()
3. The result of above request pull back an object that has the ServerRelativeUrl equal to undifine

Code that we are using:

```
this.GetItemsFromList("Document Attactments").getById(id).file.get().then((file) => {
                    test.AddFile(value.Document_x0020_TypeId, file.Title, file.ServerRelativeUrl);
                    count--;
                    if (!(count > 0)) {
                        this.UpdateDispaly();
                        resolve(true);
                    }
                });
```

**Comment by patrick-rodgers** [comment]
Does it come back if you add a .select("ServerRelativeUrl") before the get? Not all properties are returned by default so sometimes you need to explicitly request it.

**Comment by ravenboilinux** [comment]
When I add .select("ServerRelativeUrl") i get this error
GET http://ssc.guardian.com/_api/web/lists/getByTitle('Document%20Attactments')/items(112)?$select=ServerRelativeUrl 400 (Bad Request)

{"error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'ServerRelativeUrl' does not exist."}}}

**Comment by ravenboilinux** [comment]
I found the issue. My copy of the pnp framework had this 


 Object.defineProperty(Item.prototype, "file", {
        get:function(){
            return new files_1.File(this);
        }
    });


not this(Which in the master branch)
 Object.defineProperty(Item.prototype, "file", {
        get:function(){
            return new files_1.File(this,"file");
        }
    });
