### ISSUE TITLE
Problem with file-upload and setting metadata due to cached File.listItemAllFields

### ISSUE THREAD

**Issue by lqdchrm** [SharePoint/PnP-JS-Core#320]
#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Expected / Desired Behavior / Question
I'm trying to upload a file to a document library and set its metadata. As far as I understood there are currently three calls involved:

1) upload via
> pnp.sp.site.rootWeb.lists.getByTitle(listTitle)
> .select('RootFolder/ServerRelativeUrl')
> .expand('RootFolder').get().then(function(list) {
>            return pnp.sp.site.rootWeb.getFolderByServerRelativeUrl(list.RootFolder.ServerRelativeUrl)
> .files.add(filename, blob, true).then(function(fileAddResult) {...

2) getting the ID for the newly created item from the `fileAddResult` via `fileAddResult.file.listItemAllFields.get().then(function(item) { ... } `

3) update the item by getting it from the list via: `pnp.sp.site.rootWeb.lists.getByTitle(listTitle).items.getById(item.Id).update(metadata).then(function() {...}`, as the listItemAllFields in readonly
 
#### Observed Behavior
This works as expected for normal cases. A problem occurs, if a file is uploaded like above, then the item/file is deleted from SharePoint, and then you try to upload the same file again.

In this case Step 2 returns the old/wrong item.Id due to caching (returns a 304 not modified). Am I doing something wrong here, or would you consider this a bug?

I'm using sp-pnp-js@2.0.0

#### Steps to Reproduce
please see above

Thanks for this awesome lib, keep up the good work!

**Comment by mauricionr** [comment]
Could you test with 2.0.1 version? 

Thanks 😃

**Comment by patrick-rodgers** [comment]
Interesting, I'll have to have a look. Do you notice if time is a factor? Say I upload the file (works), delete file (works), re-upload file (fails) - does that behavior hold if you say wait a few minutes? What I am getting at is how are you testing this, with an immediate upload/delete/upload?

**Comment by lqdchrm** [comment]
I switched to version 2.0.1, behavior is still the same. These are my test scenarios:

1) with browser caching disabled and immediate deletion
* completely clear the document lib via SP-UI
* disable the browser cache in Chrome Developer Tools
* upload the file with the code below
* immediately delete the file via SP-UI
* immediately re-upload the file via code
--> everything works as expected

2) with browser caching enabled and immediate deletion
* completely clear the document lib via SP-UI
* enable the browser cache in Chrome Developer Tools
* upload the file with the code below
* immediately delete the file via SP-UI
* immediately re-upload the file via code
--> file is uploaded correctly, but metadata is not set: Promise rejection due to 404, item not found caused by wrong item.Id from cached listItemAllFields.get (304)

3) with browser caching enabled and waiting for 5 minutes between deletion and re-upload
* completely clear the document lib via SP-UI
* enable the browser cache in Chrome Developer Tools
* upload the file with the code below
* immediately delete the file via SP-UI
* wait for 5 minutes
* re-upload the file via code
--> same as 2) , so I suspect timing plays no role in here

``` js
function uploadToDocumentLibraryTest($pnp, listTitle, blob, filename, metadata) {
    // upload -> fileAddResult
    return $pnp.sp.site.rootWeb.lists.getByTitle(listTitle).select('RootFolder/ServerRelativeUrl').expand('RootFolder').get().then(function(list) {
        return $pnp.sp.site.rootWeb.getFolderByServerRelativeUrl(list.RootFolder.ServerRelativeUrl).files.add(filename, blob, true)
    }).then(function(fileAddResult) {
        // fileAddResult -> item.Id
        return fileAddResult.file.listItemAllFields.get().then(function(item) {
            return item.Id;
        });
    }).then(function(itemId) {
        // set metadata
        if (metadata) {
            return $pnp.sp.site.rootWeb.lists.getByTitle(listTitle).items.getById(itemId).update(metadata);
        } else {
            return Promise.resolve();
        }
    });
}
```

Thanks for you efforts, is there anything else I can provide?

Currently my workaround is to query the id by filename instead directly from the fileAddResult:

``` js
function uploadToDocumentLibraryTest($pnp, listTitle, blob, filename, metadata) {
    // upload -> fileAddResult
    return $pnp.sp.site.rootWeb.lists.getByTitle(listTitle).select('RootFolder/ServerRelativeUrl').expand('RootFolder').get().then(function(list) {
        return $pnp.sp.site.rootWeb.getFolderByServerRelativeUrl(list.RootFolder.ServerRelativeUrl).files.add(filename, blob, true)
    }).then(function(fileAddResult) {
        // fileAddResult -> item.Id
.then(function(fileAddResult) {
        // get itemId
        return $pnp.sp.site.rootWeb.lists.getByTitle(listTitle).items
            .filter(encodeURIComponent('FileLeafRef eq \''+ filename + '\''))
            .select('Id, Title, FileLeafRef')
            .get().then(function(items) {
                if (_.size(items) > 0) {
                    var first = items[0];
                    return first.Id;
                }
                throw new Error('no matching FileLeafRef found: ' + filename);
            });
    }).then(function(itemId) {
        // set metadata
        if (metadata) {
            return $pnp.sp.site.rootWeb.lists.getByTitle(listTitle).items.getById(itemId).update(metadata);
        } else {
            return Promise.resolve();
        }
    });
}
```

**Comment by ravenboilinux** [comment]
This seem alot like my issue #305

**Comment by patrick-rodgers** [comment]
Ok, got the Travis integration done - will look at this next, so should have some time early next week.

**Comment by patrick-rodgers** [comment]
Reviewing this it is a pretty edge case, but I see what you mean. Can you try either:

```TypeScript
 return fileAddResult.file.listItemAllFields.get(new ODataDefaultParser(), {
                headers: {
                    "Cache-Control": "no-cache",
                }
            }).then(function (item) {
```

OR

```TypeScript
let d = new Date();
            let q = fileAddResult.file.listItemAllFields;
            q.query.add("t", d.getTime().toString());
            return q.get().then(function (item) {
                return item.Id;
            });
```

One of those should let you bypass the cached value (which is cached in your browser, not the server or our framework). Let me know if either (or both) of those work for you.

**Comment by lqdchrm** [comment]
Thanks for your feedback. Both of your solutions work for me.

**Comment by patrick-rodgers** [comment]
Great! So I am going to close this with a work around. I don't see it as an update for the library as there techniques as above which work. Glad you're unblocked!
