### ISSUE TITLE
Migrate to Webpack 2

### ISSUE THREAD

**Issue by patrick-rodgers** [SharePoint/PnP-JS-Core#324]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question

Update project to use webpack 2 and update associated packages (server, loaders) as needed

**Comment by patrick-rodgers** [comment]
https://webpack.js.org/guides/migrating/

**Comment by jquintozamora** [comment]
Hi @patrick-rodgers ,

I did some work to migrate to webpack 2: https://github.com/jquintozamora/PnP-JS-Core/commit/4d1c3962eadc560c280d375cd62cc7ce31a527e1

The problem I found was I had to edit gulp tasks as well and I wasn´t 100% sure if some of my changes will produce some side effects. 

Anyways, I'd like to share with you just in case it could helps.

Regards!

**Comment by patrick-rodgers** [comment]
Thanks @jquintozamora - appreciate the info. I haven't started looking into this at all yet but will be great to look at the work you've done as a guide, thanks for sharing.
