### ISSUE TITLE
Update listItem Does not handle Validation rules

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#328]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[x ] Enhancement

[x ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
I have set up a validation rule on a task library that  requires the Due Date to be 2017(=YEAR([Due Date])=2017

When I try to update the dueDate with a 2016 date with this code:
` const promise = web.lists.getById(listid).items.getById(listItem.ID).update(typedHash, listItem["odata.etag"])
                .then((response) => {
                 ...
                })
                .catch((error) => {
                   ...
                });`

neither the then, nor the catch block is executed. The server returned a http 500:
HTTP/1.1 500 Internal Server Error
Cache-Control: private, max-age=0
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
Expires: Sat, 04 Feb 2017 19:03:05 GMT
Last-Modified: Sun, 19 Feb 2017 19:03:05 GMT
Server: Microsoft-IIS/8.5
Set-Cookie: r...
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 53
SPRequestDuration: 74
X-AspNet-Version: 4.0.30319
SPRequestGuid: e69ed69d-a015-3000-e33a-089e8a9f43c8
request-id: e69ed69d-a015-3000-e33a-089e8a9f43c8
X-RequestDigest: 0xAFF4D2F2E124DD65677EB343E2103DEAD1F2DD7AA1ABFEF3BFFBD1F73B515CA2AD16B6EEE7125C3FDAB28E9ADED3B9C6BCB554F607E9925771AFBB6F495683A7,19 Feb 2017 19:03:05 -0000
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6209
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Sun, 19 Feb 2017 19:03:04 GMT
Content-Length: 156

{"odata.error":{"code":"-2130575162, Microsoft.SharePoint.SPListDataValidationException","message":{"lang":"en-US","value":"List data validation failed."}}}

I would expect the catch block to be executed with the odata error.

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by russgove** [comment]
I am using spfx  rc0 with pnp-js-core 2.0

**Comment by patrick-rodgers** [comment]
Hmmm... will test this - perhaps we are eating the error somewhere (bad) but I don't see it right away just glancing at the code. Will have a look.

**Comment by patrick-rodgers** [comment]
Yep, sure enough we are eating the error on the inner post. That's a bug. Getting it fixed and writing a test to ensure we are actually producing an error for the future.

**Comment by patrick-rodgers** [comment]
Update merged in dev.
