### ISSUE TITLE
DocumentSets

### ISSUE THREAD

**Issue by PCASME** [SharePoint/PnP-JS-Core#332]
#### Category
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Expected / Desired Behavior / Question
Is there a way to create and manipulate DocumentSets?

Thanks!

**Comment by patrick-rodgers** [comment]
Nothing currently, but will have a look at how to accomplish this. I know there is a way through the old listdata svc:

```JavaScript
URL: /_vti_bin/listdata.svc/Documents 

const options: ISPHttpClientOptions = {
	method: "POST",
	body: JSON.stringify({
		'Title' : foldername,
		'Path' : listUrl
	}),
	headers: {
		"content-type": "application/json;odata=verbose",
		"accept": "application/json;odata=verbose",
		"slug": `${listUrl}/${foldername}|${contentTypeId}`
	}
};
```

Will have to see if we can come up with something in the library to help out here.

**Comment by PCASME** [comment]
Thanks @patrick-rodgers for your help.
For the moment I have accomplish it using JSOM code:

```
SP.DocumentSet.DocumentSet.create(<ctx>, <Library_root_folder>, <DocumentSet_name>, <DocumentSet_ContentTypeId>);
```

Maybe you folks could use something like this.
Hope this helps.

Thanks and greetings.

**Comment by patrick-rodgers** [comment]
Hi @PCASME - I've been working on this but there currently isn't a reliable way create a document set via rest that I can find. The code I pasted above works in some environments but not in my SPO tenant so I didn't add that to the library. I am going to close this as not supported by the underlying API and there is a workaround to use the JSOM. Once API support is available we can look at adding in doc set capabilities to sp-pnp-js. Thanks for your feedback and interest in sp-pnp-js!

**Comment by PCASME** [comment]
Thanks @patrick-rodgers for your reply.

While the API REST does not give support to the DocumentSets, maybe you could include the JSOM version in the library. I know it can be complicated to include this in the library chaining structure, but you could create an additional class that wraps the required JSON calls in a more user-friendly way.
It's an idea.
