### ISSUE TITLE
View properties and caching

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#343]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Data about views should be cache in session/local storage for better performances.

#### Observed Behavior
Consider the code bellow. I'd expect the http call behind the scenes to only happen once and to find data in my local storage after the first call. However this doesn't cache anything.
If the library cannot cache this data for any reason, usingCaching method should not be available and fail either during compilation or at runtime.

#### Steps to Reproduce
```
pnp.sp.web.lists.getByTitle("Pages")
            .views.getByTitle("MyView")
            .usingCaching({ storeName: "local", expiration: pnp.util.dateAdd(new Date(), "minute", 1440), key: "mycustomkey" })
            .get().then((view) => {
                //DO something
            })
```

**Comment by patrick-rodgers** [comment]
Are you running in nodejs?

**Comment by baywet** [comment]
No it's client side development. Same thing for #345 and #344

**Comment by patrick-rodgers** [comment]
Currently can't duplicate. I've just tried out the code you supplied above and the return value is successfully cached in local storage - verified in the chrome F12 tool. I then did subsequent requests and the XHR request was not sent for this data, it was retrieved from the cached value.

Anything else you can share to help recreate? Thanks!

**Comment by baywet** [comment]
You're right, I re-ran my tests and this was a keyboard-chair issue. Sorry for wasting your time and thank you for checking. Closing now

**Comment by JackHu88** [comment]
Hi @patrick-rodgers ,

I'm debug the coding blow with F12 Chrome debugger, it show me an error below:
**Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: RangeError: Unsupported time zone specified undefined at new DateTimeFormat (native) at Date…}**

Code:
```
$pnp.sp.web.lists.getByTitle("Test").items.usingCaching().get().then(function(r){
    console.log(r)
});
```
