### ISSUE TITLE
Lots of calls being made to context info 

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#345]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
I'd expect the library to get the request digest once, cache it as long as it is valid either using shared memory, local or session storage and reuse it for any request.

#### Observed Behavior
There's one contextinfo request per pnp request.

#### Steps to Reproduce
Implement multiple queries not using batching (in case of a components based approach) using sp-pnp-js.
Look at the xhr requests in the browser.
![contextinfo](https://cloud.githubusercontent.com/assets/7905502/23569816/5479c5f4-002f-11e7-8483-22935beb3ec3.PNG)

**Comment by patrick-rodgers** [comment]
Looks like this is due to each httpclient getting its own digest cache. Seems like something we should address. Will target resolution for the next release, 2.0.2.

**Comment by patrick-rodgers** [comment]
Addressed in #349, fixed in dev, will be part of 2.0.2 release on March 10.
