### ISSUE TITLE
What about SP 2016 on-premise? 

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/PnP-JS-Core#346]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior / Question
In the step "Grant Your Add-In Permissions"  I should be able to "Trust the app"
#### Observed Behavior
In the step "Grant Your Add-In Permissions" I get error:
"sorry only tenant administrators can add or give access to this app"
How ca I be tenant administrator on-premise?  I am farm admin and SC admin

#### Steps to Reproduce
Changed AppPermissionProvider.content.XML to use "SiteCollectionAdmin" instead of Tenantadmin
Thanks!

**Comment by KEMiCZA** [comment]
I've had this problem before. You CAN'T active any app using the Adminstrator account or farm account. Try activating the app with a site collection admin user. I remember it being something like this.

**Comment by mauricionr** [comment]
@Ofer-Gal in a sharepoint online you can grant permissions in `tenant-admin.sharepoint.com` and i believe the same functionality is in central admin for on-primise enviroment //just a guess, i've not tested

Thanks!

**Comment by Ofer-Gal** [comment]
central admin  on-primise enviroment have no concept of "tenant" In the UI.
Maybe it buried in some powershell I am not aware of
