### ISSUE TITLE
Import sp-pnp-js in a typescript project causes duplicate identifiers errors

### ISSUE THREAD

**Issue by Land3r** [SharePoint/PnP-JS-Core#347]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

I am trying to use the sp-pnp-js node module in Visual Studio 2015 with Task Runner Explorer extension for a SharePoint Online Hosted Addin using react, typescript 2.2.1 and webpack 2.2.1

In a node.js console, i typed :
`npm install --save sp-pnp-js`
Result :
weir.spo.gestiondocumentaire.addin@1.0.0 C:\Dev\WeirDocu\Weir.SPO.GestionDocumentaire.Addin
-- sp-pnp-js@2.0.1
  +-- @types/sharepoint@2013.1.2
  | -- @types/microsoft-ajax@0.0.31
  -- @types/whatwg-fetch@0.0.33
    -- @types/whatwg-streams@0.0.2

And then linked the typescript definitions:
`npm link typescript`
Result :
C:\Dev\WeirDocu\Weir.SPO.GestionDocumentaire.Addin>npm link typescript
C:\Dev\WeirDocu\Weir.SPO.GestionDocumentaire.Addin\node_modules\typescript -> _C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript`

In a .tsx file I imported it like this :
`import * as sppnp from "sp-pnp-js";`
And i didn't called it yet from my application code

#### Expected Behavior / Question
The build should work.

#### Observed Behavior
The build doesn't work anymore with the sp-pnp-js package included in the project.
A bunch of duplicate identifiers are found while trying to build.

build action result :

> C:\Dev\WeirDocu\Weir.SPO.GestionDocumentaire.Addin> cmd /c SET NODE_ENV=production&& webpack -p --color
ts-loader: Using typescript@2.2.1 and C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\tsconfig.json
Hash: d194ede0651257547ba9
Process terminated with code 2.
Version: webpack 2.2.1
Time: 22487ms
                         Asset       Size  Chunks             Chunk Names
          ./dist/app.bundle.js     196 kB       0  [emitted]  app
      ./dist/vendors.bundle.js  561 bytes       1  [emitted]  vendors
    ./dist/polyfills.bundle.js  563 bytes       2  [emitted]  polyfills
      ./dist/app.bundle.js.map    2.01 MB       0  [emitted]  app
  ./dist/vendors.bundle.js.map    6.15 kB       1  [emitted]  vendors
./dist/polyfills.bundle.js.map    6.16 kB       2  [emitted]  polyfills
  [15] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react/lib/React.js 2.69 kB {0} [built]
  [47] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react/react.js 56 bytes {0} [built]
  [52] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/intl-messageformat/index.js 553 bytes {0} [built]
  [79] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react-dom/index.js 59 bytes {0} [built]
  [80] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react-intl/lib/index.es.js 55 kB {0} [built]
  [81] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react-intl/locale-data/en.js 7.15 kB {0} [built]
  [82] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react-intl/locale-data/fr.js 4.28 kB {0} [built]
  [95] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/intl-format-cache/index.js 110 bytes {0} [built]
 [105] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/intl-relativeformat/index.js 557 bytes {0} [built]
 [111] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/invariant/browser.js 1.52 kB {0} [built]
 [125] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react-dom/lib/ReactDOM.js 5.14 kB {0} [built]
 [185] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/~/react/lib/onlyChild.js 1.34 kB {0} [built]
 [190] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/src/_app.tsx 628 bytes {0} [built]
 [191] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/src/_polyfills.js 1 bytes {2} [built]
 [192] C:/Users/ngordat/Documents/visual studio 2015/Projects/Weir.SPO.GestionDocumentaire/Weir.SPO.GestionDocumentaire.Addin/src/_vendors.js 1 bytes {1} [built]
    + 178 hidden modules
**ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(11168,11): error TS2300: Duplicate identifier 'Headers'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(11177,13): error TS2300: Duplicate identifier 'Headers'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13544,11): error TS2300: Duplicate identifier 'ReadableStream'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13550,13): error TS2300: Duplicate identifier 'ReadableStream'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13566,11): error TS2300: Duplicate identifier 'Request'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13583,13): error TS2300: Duplicate identifier 'Request'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13588,11): error TS2300: Duplicate identifier 'Response'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(13599,13): error TS2300: Duplicate identifier 'Response'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(19116,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(19121,6): error TS2300: Duplicate identifier 'BodyInit'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(19142,6): error TS2300: Duplicate identifier 'HeadersInit'.
ERROR in C:\Users\ngordat\AppData\Roaming\npm\node_modules\typescript\lib\lib.d.ts
(19152,6): error TS2300: Duplicate identifier 'RequestInfo'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-streams\index.d.ts
(32,15): error TS2300: Duplicate identifier 'ReadableStream'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-streams\index.d.ts
(52,21): error TS2304: Cannot find name 'IteratorResult'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-streams\index.d.ts
(62,42): error TS2304: Cannot find name 'IteratorResult'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(13,14): error TS2300: Duplicate identifier 'HeadersInit'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(14,15): error TS2300: Duplicate identifier 'Headers'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(24,16): error TS2304: Cannot find name 'IterableIterator'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(26,13): error TS2304: Cannot find name 'IterableIterator'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(27,15): error TS2304: Cannot find name 'IterableIterator'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(28,6): error TS2304: Cannot find name 'Symbol'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(28,26): error TS2304: Cannot find name 'IterableIterator'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(31,14): error TS2300: Duplicate identifier 'BodyInit'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(43,14): error TS2300: Duplicate identifier 'RequestInfo'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(44,15): error TS2300: Duplicate identifier 'Request'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(64,11): error TS2300: Duplicate identifier 'Request'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(70,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'referrerPolicy' must be of type 'string', but here has type 'ReferrerPolicy'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(71,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'string', but here has type 'RequestMode'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(72,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'string', but here has type 'RequestCredentials'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(73,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'string', but here has type 'RequestCache'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(74,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'redirect' must be of type 'string', but here has type 'RequestRedirect'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(76,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'window' must be of type 'any', but here has type 'null'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(88,15): error TS2300: Duplicate identifier 'Response'.
ERROR in C:\Users\ngordat\Documents\visual studio 2015\Projects\Weir.SPO.GestionDocumentaire\Weir.SPO.GestionDocumentaire.Addin\node_modules\@types\whatwg-fetch\index.d.ts
(107,11): error TS2300: Duplicate identifier 'Response'.**

package.json file :
> {
  "version": "1.0.0",
  "name": "weir.spo.gestiondocumentaire.addin",
  "private": true,
  "devDependencies": {
    "source-map-loader": "^0.1.6",
    "ts-loader": "^2.0.1"
  },
  "dependencies": {
    "@types/react": "^15.0.14",
    "@types/react-dom": "^0.14.23",
    "@types/react-router": "^3.0.6",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-intl": "^2.2.3",
    "react-router": "^3.0.2",
    "react-router-dom": "^4.0.0-beta.6",
    "sp-pnp-js": "^2.0.1"
  }
}

tsconfig.json file :
> {
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "allowJs": true,
    "typeRoots": ["node_modules/@types"]
  },
  "exclude": [
    "node_modules",
    "typings",
    "wwwroot"
  ]
}

webpack.config.js file :
> "use strict";
module.exports = {
    entry: {
        app: "./src/_app",
        vendors: "./src/_vendors.js",
        polyfills: "./src/_polyfills.js"
    },
    output: {
        filename: "./dist/[name].bundle.js"
    },
    devtool: "source-map",
    resolve: {
        modules: ["node_modules"],
        extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
    },
    module: {
        loaders: [
            // General
            {
                test: /\.tsx?$/,
                loader: "ts-loader"
            }
        ],
    }
};

**Comment by patrick-rodgers** [comment]
This is actually a duplicate to #331. This is fixed and will be included in the 2.0.2 release of sp-pnp-js. Until then please continue using TS 2.2.0 or manually remove the @types installed for whatwg-fetch. Thanks for reporting it!
