### ISSUE TITLE
Publish recent version to the Bower registry

### ISSUE THREAD

**Issue by koltyakov** [SharePoint/PnP-JS-Core#348]
Hi,

It looks like the lib was not published to the Bower registry since v1.0.6?
It would be great to have the latest version both in NPM and Bower as there are scenarios then Bower package should be used in a project.

#### Category
[x] Enhancement

[ ] Bug

[x] Question

Thanks!

**Comment by patrick-rodgers** [comment]
Just published 2.0.1 (current master). This is 100% an oversight on my part - so my bad. Will update my release guide to ensure this step is called out. Thanks for pointing this out, let me know if you see any issues with the latest release.

**Comment by koltyakov** [comment]
Thanks!
