### ISSUE TITLE
ng build --prod fails when using PnP-JS-Core

### ISSUE THREAD

**Issue by malexandrum** [SharePoint/PnP-JS-Core#352]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior
Using PnP-JS-Core in an Angular2 project.

#### Observed Behavior
Once pnp is imported in a service and trying to use any method of pnp, Uglify step fails during build for production with:
`ERROR in vendor.bundle.js from UglifyJs
Unexpected token: name (CachedDigest) [vendor.bundle.js:264,6]`

#### Steps to Reproduce
* Create new Angular project with @angular/cli@1.0.0-rc.1
* npm install sp-pnp-js --save
* import pnp in a service and use pnp.sp.web
* ng build --prod

**Comment by patrick-rodgers** [comment]
This is resolved in the dev branch as we will be rolling the lib folder back to es5. Will be included in 2.0.2 release of sp-pnp-js scheduled for March 10. Thanks for letting us know!

**Comment by ezhile** [comment]
ERROR in vendor.0b999fee024d91a07b2f.bundle.js from UglifyJs
Unexpected token: name (IonRangeSliderModule) [vendor.0b999fee024d91a07b2f.bundle.js:57013,4]
