### ISSUE TITLE
Failed to load resource: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by webtechy** [SharePoint/PnP-JS-Core#355]
#### Category
[x] Enhancement
[x] Bug
[ ] Question

#### Expected / Desired Behavior / Question
I would expect if I run:

> npm install sp-pnp-js –save

Then if I run a Typescript project, all resources should be available locally (and subsequently uploaded to my CDN). If I'm working on my local workbench, and I'm request npm packages, I would expect everything to be downloaded locally. Additionally, if I'm uploading assets to a CDN, I expect all dependencies to be uploaded to here, and not reliant on other CDNs (especially relevant considering the recent CloudFlare issue).

#### Observed Behavior
When not connected to the internet, you get the following errors:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED

and

SPComponentLoader.loadComponent: ERROR: ***Failed to load path dependency "sp-pnp-js" from component "ffaa6a0e-9eba-40a0-bec5-226d1db53caf" (RequirementsFormWebPart).

and

SPComponentLoader.loadComponent: ERROR: ***Failed to load entry point from component "ffaa6a0e-9eba-40a0-bec5-226d1db53caf" (RequirementsFormWebPart).

and

[1488354840668][Shell.ClientSideWebPartManager] [SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.RequirementsFormWebPart.abe85d82-5d05-412b-b02d-b4cd3bea304d,Error: ***Failed to component "ffaa6a0e-9eba-40a0-bec5-226d1db53caf" (RequirementsFormWebPart). Original error: 
	Error loading https://component-id.invalid/ffaa6a0e-9eba-40a0-bec5-226d1db53caf_0.0.1/sp-pnp-js as "sp-pnp-js" from https://component-id.invalid/ffaa6a0e-9eba-40a0-bec5-226d1db53caf_0.0.1 script resources due to: undefined. CALLSTACK:: Error

Items it can't find are:

https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabricmdl2icons.woff
https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.0/pnp.min.js
https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabricmdl2icons.ttf
https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.0/pnp.min.js

Thanks!

**Comment by patrick-rodgers** [comment]
This appears to be related to SPFx?

Sorry - I don't follow. If you are referencing libraries on the internet and the internet is not available that will fail. Nothing we can resolve there.

If you want to work strictly locally you can remove the externals reference in the config/config.js file for sp-pnp-js and it will build the library into your package and work in your local workbench without the internet.

Regarding your mentioning of uploading to a CDN, and if that is related to SPFx, that issue is better reported [here](https://github.com/SharePoint/sp-dev-docs/issues) as this library doesn't control anything related to your CDN.

**Comment by webtechy** [comment]
But this file is part of PNP?

https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.0/pnp.min.js

But you are right, I hadn't realised this entry was in the config:

```
  "externals": {
    "sp-pnp-js": "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.0/pnp.min.js"
  },
```

This was an old Yeoman project, and a new one didn't have this sp presumed removed from the scaffolding.

**Comment by patrick-rodgers** [comment]
Ok, does that mean you are sorted out - or did you still have questions? Want to check before closing this in case. Thanks!

**Comment by JackHu88** [comment]
Thanks, This resolved my problem, can close now.

**Comment by patrick-rodgers** [comment]
Going to close this as it appears you are unblocked, please reopen if you still have questions. Thanks for your interest in sp-pnp-js!
