### ISSUE TITLE
gulp compilation errors with *.d.ts files when referencing PnP

### ISSUE THREAD

**Issue by Tran-Kien** [SharePoint/PnP-JS-Core#358]
#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Expected / Desired Behavior / Question
As soon as I reference PnP in my project, there are compilation errors: (around 200 errors) 
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(43,14): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(43,21): error TS1005: ';' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(43,40): error TS1005: '(' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(44,14): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(44,33): error TS1005: ';' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(44,45): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(45,14): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(45,42): error TS1005: ';' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(46,14): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(46,32): error TS1005: ';' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(47,14): error TS1005: '=' expected.
Error - typescript - node_modules\sp-pnp-js\lib\configuration\pnplibconfig.d.ts(47,32): error TS1005: ';' expected.

#### Steps to Reproduce
Clone https://github.com/SharePoint/sp-dev-samples/tree/master/Samples/react-generic-app
npm install
npm install sp-pnp-js --save
import * as pnp from 'sp-pnp-js'; in ./src/components/HelloWorld/HelloWorld.tsx
gulp

This is the package.json
{
  "name": "react-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@microsoft/web-library-build": "^0.5.0",
    "es6-promise": "^4.1.0",
    "office-ui-fabric-react": "^0.36.3",
    "sp-pnp-js": "^2.0.1",
    "typescript": "^2.2.1"
  },
  "devDependencies": {
    "react": "^15.3.2",
    "react-dom": "^15.3.2"
  }
}

Thanks!

**Comment by patrick-rodgers** [comment]
Please try with the latest release (just released today) 2.0.2. Curious if this is an es6 issue.

**Comment by Tran-Kien** [comment]
Hi, it is still doing the same errors with 2.0.2
I think I have narrowed it down to Microsoft's build library @microsoft/web-library-build

**Comment by patrick-rodgers** [comment]
That sample may be not updated to GA yet. Unsure. You OK if I close this as it seems to not be an issue with sp-pnp-js. I think the GA release is all 1.0.0 for the @microsoft pieces.

**Comment by Tran-Kien** [comment]
Yea. I'll find another way/figure it out. Thanks for your time.

**Comment by patrick-rodgers** [comment]
YW, if you do find an issue with sp-pnp-js please let us know so we can get it resolved :)
