### ISSUE TITLE
UglifyJs Error while building Angular 2(Angular-cli) project in Production mode using sp-pnp-js package

### ISSUE THREAD

**Issue by sraddhan** [SharePoint/PnP-JS-Core#359]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
"ng build --prod" should bundle the project successfully and should generate "dist" folder.

#### Observed Behavior
Works great in development mode i.e. "ng build" works great. 
But when Angular 2 project is built using the command "ng build --prod", it errors out.

**Error Message**  
"ERROR in vendor.c71699387434c14250a9.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (CachedDigest) [vendor.c71699387434c14250a9.bundle.js:265,6]"

#### Steps to Reproduce
1. Download and npm install "angular-cli" ([link](https://www.npmjs.com/package/angular-cli))
2. Follow the steps on README.md file on angular-cli to generate an angular 2 application.
3. npm install sp-pnp-js 
4. Use sp-pnp-js in the service -> import * as sp from 'sp-pnp-js'; 
5. Build the project with command "ng build" as suggested in angular-cli -> this should be successful
6. Now, build the project using command "ng build --prod". This is where error should appear. 

OR 

1. clone [this](https://github.com/sraddhan/ng2Forms.git) repository.
2. checkout to tag v0.1
3. run "npm install"
4. run "ng build --prod"

Notice, removing the import * as sp from 'sp-pnp-js' and commenting related code will let build successfully. 

#### Submission Guidelines
NA

Thanks!

**Comment by patrick-rodgers** [comment]
Yep, thanks for reporting this. Have already heard this a few times and we are rolling back to es5 in the lib folder which will fix this. New version 2.0.2 will be released tomorrow, March 10, 2017. Closing as duplicate.

**Comment by olemp** [comment]
Lovely @patrick-rodgers!

**Comment by sraddhan** [comment]
@patrick-rodgers Thanks for the answer and awesome work you are doing ! Truly inspiring !
