### ISSUE TITLE
Can not update an item after filter

### ISSUE THREAD

**Issue by JackHu88** [SharePoint/PnP-JS-Core#360]
Category
[ ] Enhancement

[ ] Bug

[ ] Question

Expected / Desired Behavior / Question
I want to filter an item by title then update it, but it show me an error below:
**Uncaught TypeError: $pnp.sp.web.lists.getByTitle(...).items.top(...).filter(...).update is not a function**

Observed Behavior
Code below:
$pnp.sp.web.lists.getByTitle('Test').items.top(1).filter("Title eq 'test1'")
.update({"Status":"Closed"}).then(function(){console.log("done")}).catch(function(err) {console.log(err)});

**Comment by patrick-rodgers** [comment]
The code you have written will return a collection of zero or more matching items. You want something more like the below. A collection does not have an update method, which is the error you are seeing. I will also add the below example to the [working with list items wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items) in the [developer guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide).

```TypeScript
// you are getting back a collection here
$pnp.sp.web.lists.getByTitle("").items.top(3).filter("").get().then((items: any[]) => {

    // see if we got something
    if (items.length > 0) {

        // update the first one in the array
        items[0].update({
            Title: "Updated Title",
        }).then(result => {

            // here you will have updated the item
            console.log(JSON.stringify(result));
        });
    }
});
```

Thanks for your question, let me know if that helps you out.

**Comment by JackHu88** [comment]
Hi @patrick-rodgers ,
Your code seems can't work, it show me an error "Uncaught SyntaxError: Unexpected token :", i'm referring the pnp.min.js on a sharepoint online page.
i change the code to below, but it show me another error "items[0].update is not a function".

$pnp.sp.web.lists.getByTitle("Market Sweeps").items.top(1).filter("Title eq 'P-20170303'").get().then(function(items){
    // see if we got something in that collection
    if (items.length > 0) {
        // update the first one in the array
        items[0].update({
            Title: "P-20170303",
        }).then(result => {
            // here you have updated the item
            console.log(JSON.stringify(result));
        });
    }
});

**Comment by patrick-rodgers** [comment]
Yes you would need to get the item, did this off the top of my head without testing it:

```TypeScript
// you are getting back a collection here
pnp.sp.web.lists.getByTitle("").items.top(3).filter("").get().then((items: any[]) => {

    // see if we got something
    if (items.length > 0) {

        pnp.sp.web.lists.getByTitle("").items.getById(items[0].Id).update({
            Title: "Updated Title",
        }).then(result => {

            // here you will have updated the item
            console.log(JSON.stringify(result));
        });
    }
});
```

**Comment by JackHu88** [comment]
Thanks @patrick-rodgers,
Hope you can add the function items[0].update in later release, closing now.

**Comment by patrick-rodgers** [comment]
You actually already can, here is a slightly improved version of the above where we are telling the library what type we are getting back. You can see more on [ODataParsers in the wiki](https://github.com/SharePoint/PnP-JS-Core/wiki/Response-Parsers).

```TypeScript
// you are getting back a collection here, and we are using the ODataEntityArray to type the items in that
// array an 'Item' you could create your own item types as described in an upcoming article
pnp.sp.web.lists.getByTitle("Test345-2").items.top(3).get(ODataEntityArray(Item)).then((items: Item[]) => {

    // see if we got something
    if (items.length > 0) {

        // the items in the array will be of type Item
        items[0].update({
            Title: "A new title!",
        }).then(_ => {

            console.log("Update Complete of item index 0.")

        });
    }
});
```

**Comment by JackHu88** [comment]
Hi @patrick-rodgers,
I'm referring pnp.js directly on a sharepoint online page, how can i use the ODataEntityArray ?
It show me an error **"ODataEntityArray is not defined"**

```
$pnp.sp.web.lists.getByTitle("Test").items.top(1).filter("Title eq '123'").get(ODataEntityArray(Item)).then(function(items){
    // see if we got something
    if (items.length > 0) {
        // the items in the array will be of type Item
        items[0].update({
            Title: "222",
        }).then(_ => {
            console.log("Update Complete of item index 0.")
        });
    }
});
```

**Comment by patrick-rodgers** [comment]
You would need to reference it from the root namespace: $pnp.ODataEntityArray($pnp.Item)

**Comment by JackHu88** [comment]
Thanks @patrick-rodgers , can works now.

One more question for the caching function, I'm debug the coding blow with F12 Chrome debugger, it show me an error below, please help check what's the problem?
**Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: RangeError: Unsupported time zone specified undefined at new DateTimeFormat (native) at Date…}**

Code:
```
$pnp.sp.web.lists.getByTitle("Test").items.usingCaching().get().then(function(r){
    console.log(r)
});
```

**Comment by patrick-rodgers** [comment]
Hi @JackHu88 - I am unable to reproduce this using your code in SPO. Can you provide some more detail into what you are doing as well as browser version(s) and SharePoint environment (SPO, 2013, etc). Also, what timezone are you in? Any chance you can get a line number for that error in pnp.js?

**Comment by JackHu88** [comment]
Hi @patrick-rodgers , I'm debug with chrome on SPO environment just for testing the caching function.
My timezone is (UTC+08:00).

```
Uncaught (in promise) RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleString (native)
    at Function.value (https://xx.sharepoint.com/SiteAssets/pnp.min.js:1:2677)
    at new e (https://xx.sharepoint.com/SiteAssets/pnp.min.js:2:17528)
    at https://xx.sharepoint.com/SiteAssets/pnp.min.js:2:15051
    at Function.value (https://xx.sharepoint.com/SiteAssets/pnp.min.js:2:14861)
    at r.value (https://xx.sharepoint.com/SiteAssets/pnp.min.js:2:13620)
    at https://xx.sharepoint.com/SiteAssets/pnp.min.js:2:12851
```

**Comment by patrick-rodgers** [comment]
What is your timezone name you have set on your machine? This is an issue with the Date object, not really anything in the library so unsure what fix we can offer here. If you change your timezone to a different one does it then work?

**Comment by JackHu88** [comment]
Thanks @patrick-rodgers , Maybe some problem caused by my site, when i test it today it can works now.
