### ISSUE TITLE
Latest release not available via bower

### ISSUE THREAD

**Issue by da-maxl** [SharePoint/PnP-JS-Core#361]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Successful installation of latest release 2.0.1 via bower.

#### Observed Behavior
The latest release 2.0.1 doesn't seem to be available via bower.
A quick test with command `bower info sp-pnp-js` shows that 1.0.6 is currently the latest available release

**Comment by patrick-rodgers** [comment]
Just did a release based on [this ticket](#348) earlier this week. Will do a release as well for today's release.
