### ISSUE TITLE
ColumnDefaults for lists

### ISSUE THREAD

**Issue by olemp** [SharePoint/PnP-JS-Core#363]
#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Question
Would be awesome to support column defaults for libraries

**Comment by patrick-rodgers** [comment]
How are they not supported now? When you add a field you can specify a plain object of properties, does default value not work?

**Comment by olemp** [comment]
Oh, sorry. I didn't explain myself very well here @patrick-rodgers.

I mean setting Forms/client_LocationBasedDefaults.html together with adding receiver Microsoft.Office.DocumentManagement.LocationBasedMetadataDefaultsReceiver ItemAdded for libraries.

This can be set for both the root folder and the subfolders of a library, but it's a bit of a hassle doing it "manually". Could we make this a part of the library? I could attempt to make a PR.

**Comment by patrick-rodgers** [comment]
Sorry - still not following exactly what you are meaning here. If you want to add some pseudo code here that might help. If it makes sense as part of the library (i.e. we can make it completely generic and REST based) then I don't have any reason to not look at adding it.

**Comment by olemp** [comment]
It's what these lines of code are doing:

`const SetMetadataDefaults = (phaseName: string, lib: string): Promise<any> => {
    return new Promise<any>((resolve, reject) => {
        GetCurrentProjectPhase().then(({ Id, WssId }) => {
            pnp.sp.web.lists.getByTitle(lib).expand("RootFolder").get().then(({ RootFolder: { ServerRelativeUrl } }) => {
                const blob = new Blob([`<MetadataDefaults><a href="${ServerRelativeUrl.replace(/ /g, "%20")}"><DefaultValue FieldName="${PROJECTPHASE_FIELD}">${WssId};#${phaseName}|${Id}</DefaultValue></a></MetadataDefaults>`], {
                    type: "text/plain",
                });
                pnp.sp.web.getFolderByServerRelativeUrl(`${ServerRelativeUrl}/Forms`).files.add("client_LocationBasedDefaults.html", blob, true).then(resolve, reject);
            });
        }, reject);
    });
};

const EnsureMetaDataDefaultsEventReceiver = (lib, recName = "LocationBasedMetadataDefaultsReceiver ItemAdded"): Promise<any> => {
    return new Promise<any>((resolve, reject) => {
        let ctx = SP.ClientContext.get_current(),
            eventReceivers = ctx.get_web().get_lists().getByTitle(lib).get_eventReceivers();
        ctx.load(eventReceivers);
        ctx.executeQueryAsync(() => {
            let eventReceiverExists = eventReceivers.get_data().filter(er => er.get_receiverName() === recName).length > 0;
            if (!eventReceiverExists) {
                let eventRecCreationInfo = new SP.EventReceiverDefinitionCreationInformation();
                eventRecCreationInfo.set_receiverName(recName);
                eventRecCreationInfo.set_synchronization(1);
                eventRecCreationInfo.set_sequenceNumber(1000);
                eventRecCreationInfo.set_receiverAssembly("Microsoft.Office.DocumentManagement, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c");
                eventRecCreationInfo.set_receiverClass("Microsoft.Office.DocumentManagement.LocationBasedMetadataDefaultsReceiver");
                eventRecCreationInfo.set_eventType(SP.EventReceiverType.itemAdded);
                eventReceivers.add(eventRecCreationInfo);
            }
            if (ctx.get_hasPendingRequest()) {
                ctx.executeQueryAsync(resolve, reject);
            } else {
                resolve();
            }
        }, reject);
    });
};`

**Comment by patrick-rodgers** [comment]
If the only way to do it is with the SP library I'll have to say no, want to avoid that dependency. What is the scenario where you need this? Would it make more sense in the provisioning library?

**Comment by olemp** [comment]
Yeah, good point!
