### ISSUE TITLE
Add user to a group didn't return the user object

### ISSUE THREAD

**Issue by JackHu88** [SharePoint/PnP-JS-Core#371]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
Add user to a group didn't return the user object

#### Observed Behavior
I want add a user to a group then get the id of the user. but the method below didn't return the user object back but returned the t object below:
`t {_query: e, _batch: null, _parentUrl: "_api/web/sitegroups/getByName('Dev Members')/users", _url: "_api/web/sitegroups/getByName('Dev Members')/users(@v)"}`

#### Steps to Reproduce
```
$pnp.sp.web.siteGroups.getByName("Dev Members").users
.add("i:0#.f|membership|jhu1@xxx.com").then(function(d){
	console.log(d)
});
```
also tested add user to site, have the same issue.
```
$pnp.sp.web.siteUsers.add("i:0#.f|membership|jh1@xxx.com").then(function(d){
	console.log(d)
});
```

**Comment by patrick-rodgers** [comment]
In the library we don't generally make queries for you - so you would need to do something like the below. What you are getting back is the SiteUser queryable instance and you can make your own queries from that.

```TypeScript
    pnp.sp.web.siteGroups.getByName("Dev Members").users.add("{ login info }").then(function (d) {
       
        d.select("Id").get().then(userData => {
            console.log(userData);
        });
    });
```

In _this particular case_ while I was testing it I found a bug in the getByLoginName method where it was not adding the single quotes around the query string value so the above code won't work right now. I have fixed that bug and checked it into the dev branch.

**Comment by JackHu88** [comment]
Hi @patrick-rodgers , how can i get the pnp.js from the dev branch?

**Comment by patrick-rodgers** [comment]
@JackHu88 - you would need to fork/clone the repo to your machine and build it, we don't have a distributed copy. But this gave me an idea to use travisCI to produce a beta release on npm each time we merge to dev. Will have a look into setting that up but can't commit to a timeline. Going to close this one for now. Thanks!

**Comment by JackHu88** [comment]
Hi @patrick-rodgers , i tested your code above with the pnp.js in dev branch, the SiteUser object was returned. but it throw an error below when query the user.
_**The query string "loginName" is missing or invalid.**_

**Comment by simkessy** [comment]
@patrick-rodgers I was wondering if you ever got to setting up a way to get a beta version from NPM?
