### ISSUE TITLE
Updating a choice field

### ISSUE THREAD

**Issue by webtechy** [SharePoint/PnP-JS-Core#374]
#### Category
[ ] Enhancement
[ ] Bug
[x] Question

#### Expected / Desired Behavior / Question
What is the method to update/save a single choice field?

#### Observed Behavior

> /_api/web/lists/getByTitle('Requirements')/items(65) 400 (Bad Request)

#### Steps to Reproduce
Here is the code (Requirement_x0020_Rating is a choice field):

```
pnp.sp.web.lists.getByTitle("Requirements").items.getById(this.Requirement.Id).update({
                Title: self.Requirement.Title,
                Requirement_x0020_Details: self.Requirement.Details,
                //R2_x0020_Category: this.Requirement.Category,
                //Requirement_x0020_Rating: self.Requirement.Rating.RatingText,
                Requirement_x0020_RatingValue: self.Requirement.Rating.RatingText,
                Final_x0020_Version: self.Requirement.FinalVersion,
                Regulatory_x0020_ProvisionId: self.Requirement.RegulatoryProvision.Id
            })
```

(will raise a similiar issue as to why the error is not being caught).

**Comment by patrick-rodgers** [comment]
This worked for me. Just setting the field to the text value I wanted. Not sure if there were any additional details with the Bad Request, but guessing you might have a field name wrong?

```TypeScript
    pnp.sp.web.lists.getByTitle("ChoiceFieldList").items.getById(1).update({
        ChoiceField: "Choice 3",
    });
```

**Comment by patrick-rodgers** [comment]
Closing this as answered, please reopen if you continue to see a problem here. Thanks!

**Comment by koltyakov** [comment]
Hey @Shyammi,

```typescript
pnp.sp.web.getList(`${_spPageContextInfo.webServerRelativeUrl}/Lists/MyList`)
	.items.getById(1)
	.update({
		ChoiceField: {
			results: [
				'Choice #2',
				'Choice #3'
			]
		}
	})
	.then(console.log)
```

**Comment by Shyammi** [comment]
Thanks, It worked!!!
