### ISSUE TITLE
Add new list item doesn't validate required columns

### ISSUE THREAD

**Issue by johnfabian** [SharePoint/PnP-JS-Core#376]
When I insert a list item using list.items.add(newItem) why does it allow a null object to pass through successfully and the required columns contain null data? I understand I should validate clientside but say I miss a column this doesn't respond with an error?

**Comment by koltyakov** [comment]
Hi John, it's a standard CSOM/JSOM/REST behavior and has been never taken into account. Client object model always allowed to ignore required fields.

**Comment by johnfabian** [comment]
Ok thanks,, I was just checking, I wrote a wrapper around the rest api similar to pnp but switched to using pnp but I was always validating and never noticed so I'll do the same via pnp. Really nice library btw, wish I would have stumbled on this before writing my own which wasn't fluent so really nice!

**Comment by koltyakov** [comment]
Yep, the lib is really cool, love it too, we start using it as a default on our projects.

Btw, it's possible to get fields model with pnp-js-core:

```javascript
$pnp.sp.web
  .getList('/d/gexpo/Lists/BMCats')
  .contentTypes.expand('fields')
  .get().then(r => console.log(r));
```

Check to required fields and then wrap these settings to the add operation logic.

**Comment by johnfabian** [comment]
Thanks, that is exactly what I was looking for.

**Comment by patrick-rodgers** [comment]
@johnfabian - thanks for the kind words! Glad you are enjoying the library!
