### ISSUE TITLE
Unexpected Error when try to test if a web exists.

### ISSUE THREAD

**Issue by oka-garaio** [SharePoint/PnP-JS-Core#377]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
If I want to load a web to determine if it exists, I should be able to do this:

```javascript
$pnp.web.get().then(()=> {
    console.log("It exists");
}, (error) => {
    console.log("It doesn't");
})

// or

$pnp.web.get().then(()=> {
    console.log("It exists");
}).catch((error) => {
    console.log("It doesn't");
})
```

#### Observed Behavior
Despite which version I used, I always got this:

```
GET http://my-lovely-sharepoint-site.com/test/_api/web 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
```

#### Steps to Reproduce
Run the code above on a page where where pnp 2.0.1 is present.

Am I missing some configuration or do I use it the wrong way?

Thanks!

**Comment by patrick-rodgers** [comment]
Interesting find - this varies with how the json method was implemented in fetch. If the body is empty some implementations error out. So easy enough to fix and that fix is just merged to dev.

**Comment by oka-garaio** [comment]
Thanks for the fast fix. I was not sure if this is a bug ir a wrong usage.

**Comment by oka-garaio** [comment]
@patrick-rodgers is there any date, a stable release will be published containing this fix?

**Comment by patrick-rodgers** [comment]
Target is April 8th. I added this to the milestone related to that release so you can see the date.
