### ISSUE TITLE
Multiple attachments using batch calls in SharePoint 2013 on-premise

### ISSUE THREAD

**Issue by CoderGeet** [SharePoint/PnP-JS-Core#381]
[X ] Enhancement

[ ] Bug

[X ] Question

I have a requirement to attach multiple files to a list item in SharePoint. I know we have the batch api available with PnP.  But since REST batch calls is available only for SharePoint Online and SharePoint 2016 On-Premise, I cannot use this api for doing batch operations in SharePoint 2013 On-premise.
Multiple upload is a very common requirement by customers. I can play around with recursive function calls and promises and try to work around with this. But my question is if I have to use pnp-js-core to achieve this, is there any recommended way of doing it. 

Thanks!

**Comment by koltyakov** [comment]
Hi,

You are absolutely right that unfortunately there is no batch API in SP 2013.
Yet your tasks looks to be achievable with the use of standard Promise.all functionality. Yep, there will be numerous physical requests, yet the script can be pretty straightforward like:

```javascript
var itemPnp = $pnp.sp.web.getList('/sites/dev01/Lists/Custom02').items.getById(101);

var promises = [
  itemPnp.attachmentFiles.add('Attachment 01.txt', 'Content123'),
  itemPnp.attachmentFiles.add('Attachment 02.txt', 'Content234'),
  itemPnp.attachmentFiles.add('Attachment 03.txt', 'Content567'),
  itemPnp.attachmentFiles.add('Attachment 04.txt', 'Content789')
];

Promise.all(promises).then(function(results) {
  console.log(results);
});
```

**Comment by CoderGeet** [comment]
Hi Koltyakov,

Thank you so much for your reply. Unfortunately this will not work always as I am trying to update a single list item with all the attachments. Since the calls are async so there might be scenarios where I will get 409 Save Conflict error as all the updates are happening to the same list.  I tried this approach and if I try to upload a bunch of files together then I do encounter this issue intermittently with 409 error code. :(

Thanks!

**Comment by patrick-rodgers** [comment]
@CoderGeet - @koltyakov is correct, you can use the promise.app - but based on something in gitter that might cause conflicts with adding the files to the list item as the promises will be firing simultaneously. So you can chain them using .then() as I [discuss in a blog post](https://blogs.msdn.microsoft.com/patrickrodgers/2017/02/06/using-mapreduce-with-asynchronous-operations-in-typescript/). Let me think about adding support for this and see how it might fit.

**Comment by CoderGeet** [comment]
Thanks Patrick. I will follow the blog post and do required changes to my code.

**Comment by CoderGeet** [comment]
@koltyakov @patrick-rodgers : I am able to upload multiple items to a list by making recursive calls to add attachment using .then(). 
@patrick-rodgers : It will be awesome if we can have a wrapper method where pnp-js component takes care of the chaining and we simply pass a collection object as an input. 
Thanks a lot :)

**Comment by patrick-rodgers** [comment]
So for this to work you'd have a method signature something like.

```
attachments.addMultiple(fileInfo: { name: string, content: string | Blob | ArrayBuffer}[]): Promise<void>
```
and a usage like:

```
let files = [
{ name: "File1.txt", content: "blah" },
{ name: "File2.txt", content: "blah" },
{ name: "File3.txt", content: "blah" }
];

attachments.addMultiple(files).then(_ => console.log("all done"));
```

Is that what you had in mind?

**Comment by patrick-rodgers** [comment]
Well, went ahead and added it. Have a look and let me know if that is indeed what you had in mind. #383

**Comment by patrick-rodgers** [comment]
Usage: 

```Typescript
let files = [{
    name: "File5.txt",
    content: "balh"
}, {
    name: "File6.txt",
    content: "balh"
}, {
    name: "File7.txt",
    content: "balh"
}, {
    name: "File8.txt",
    content: "balh"
}]

pnp.sp.web.lists.getByTitle("ChoiceFieldList").items.getById(1).attachmentFiles.addMultiple(files).then(_ => {

    pnp.sp.web.lists.getByTitle("ChoiceFieldList").items.getById(1).attachmentFiles.get().then(files => {
        console.warn(files);
    })

});
```

**Comment by CoderGeet** [comment]
@patrick-rodgers Awesome. That was exactly what I was looking for. Right now I am not having access to my SharePoint environment but will test it the first thing tomorrow. I am quite sure it will work like a charm. I will update after doing a testing tomorrow morning. Thanks for adding a wrapper method.

**Comment by CoderGeet** [comment]
@patrick-rodgers My apologies for asking this dumb question but how do I get the updated package? When I try to install/update the sp-pnp-js package using npm it does not bring the updated files for me. I have the version 2.0.2 installed for sp-pnp-js.

**Comment by patrick-rodgers** [comment]
There isn't a way currently to get a new version until we do a monthly release. You can fork the library and build/package the dev branch yourself to test changes. I am also looking at how hard it would be to produce a beta release (unstable) off the dev branch. But just starting that work so likely not ready for a bit.

Going to close this as resolved as the change is merged to dev - will be part of the April release.

**Comment by CoderGeet** [comment]
@patrick-rodgers That makes sense. Thanks a lot for working on this and providing a method to upload multiple files. Really appreciate that.

**Comment by PCASME** [comment]
What about a **deleteMultiple** method?
