### ISSUE TITLE
Expand fields in folder didn't return result as list item

### ISSUE THREAD

**Issue by JackHu88** [SharePoint/PnP-JS-Core#386]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
i want to filter a file by custom field in a folder, so i try to use the expand, i expand all the fields but my custom field didn't return, i checked the result,  property odata.type:"SP.File", didn't return as list item, it seems the expand didn't work, coding below.

#### Steps to Reproduce
```
$pnp.sp.web
.getFolderByServerRelativeUrl(_spPageContextInfo.webServerRelativeUrl + '/Pages')
.files
.expand('Files/ListItemAllFields')
.get()
.then(function(item) {
	console.log(item)
});
```

**Comment by patrick-rodgers** [comment]
The below works for me, note the expand value is changed. Going to close this as resolved.

```TypeScript
pnp.sp.web
    .getFolderByServerRelativeUrl('/sites/dev/SitePages')
    .files
    .expand('ListItemAllFields')
    .get()
    .then(function (files: any[]) {
        
        let results = files.filter(file => {
            return file.ListItemAllFields.SomeColumn === "SomeValue";
        });

        console.log(results);
    });
```

**Comment by JackHu88** [comment]
I'm using pnp.js, **files: any[]** didn't work.

**Comment by patrick-rodgers** [comment]
Please reopen issues where you are still having trouble. If you are using JavaScript and not TypeScript you need to remove the typing ": any[]".

**Comment by JackHu88** [comment]
Got it now, thx
