### ISSUE TITLE
Error while creating folder hierarchy in a batch

### ISSUE THREAD

**Issue by samgoodey** [SharePoint/PnP-JS-Core#387]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Expected / Desired Behavior / Question
Create a parent folder, create sub folders, and then apply metadata to the parent folder, this is the code I'm using:

```
function testingWithFolders() {
  let batch = pnp.sp.createBatch();

  pnp.sp.web.folders.getByName("Bids").folders.inBatch(batch).add("parentFolder").then(function (data) {
    console.log("Created folder parentFolder " + data);
  });

  pnp.sp.web.folders.inBatch(batch).add("Bids/parentFolder/SubFolder1").then(function (data) {
    console.log("Created sub-folder 1 " + data);
  });

  pnp.sp.web.folders.inBatch(batch).add("Bids/parentFolder/SubFolder2").then(function (data) {
    console.log("Created sub-folder 2 " + data);
  });
   pnp.sp.web.folders.getByName("Bids").folders.getByName("parentFolder").listItemAllFields.inBatch(batch).get().then(function (item) {
    pnp.sp.web.lists.getByTitle("Bids").items.getById(item.Id).inBatch(batch).update({
      Organisation: "TesingTest",
    }).then(result => {
      console.log("Done");
    });
  });

  batch.execute().then(() => console.log("We're done"));
}
```
#### Observed Behavior
Running into a few errors, the batch does not seem to be executing the code in the intended order and sometimes run into errors such as the one below

POST https://mod881845.sharepoint.com/sites/Dev/_api/web/folders/add('Bids/parentFolder/SubFolder1') 500 (Internal Server Error)
Uncaught (in promise) Error: Error making HttpClient request in queryable: [500] Internal Server Error

Assuming this is because when the sub folder creation is being executed, the parent folder has yet to be created.

The function to retrieve all fields from the parent folder also fails to execute, I'm assuming for the same issue as the sub folder not being created.

#### Steps to Reproduce
I'm executing this function on a standard HTML button click within the SharePoint Framework that has been deployed to a CDN.

Thank you!

**Comment by patrick-rodgers** [comment]
For things that are order dependent you would likely be better off by chaining things in order using then. This will create a repeatable process. Batches are better for independent actions.

**Comment by samgoodey** [comment]
Thanks @patrick-rodgers, I've started chaining some of the functions together but running into a few other issues.

```
function createSubFolder1() {
  pnp.sp.web.folders.add("Bids/parentFolder/SubFolder1").then(function (data) {
    console.log("Sub folder 1 created");
  }).catch(function (data) {
    console.log('Error: ' + data);
  });
}

function createSubFolder2() {
  pnp.sp.web.folders.add("Bids/parentFolder/SubFolder2").then(function (data) {
    console.log("Sub folder 2 created");
  }).catch(function (data) {
    console.log('Error: ' + data);
  });
}

function updateFolderWithMetaData() {
 pnp.sp.web.folders.getByName("Bids").folders.getByName("parentFolder").listItemAllFields.get().then(function (item) {
    pnp.sp.web.lists.getByTitle("Bids").items.getById(item.Id).update({
      Organisation: "parent"
    }).then(result => {
      console.log(result);
    });
  }).catch(function (data) {
    console.log("Did not find folder " + data);
  });
}

function testingWithFolders() {
  pnp.sp.web.folders.getByName("Bids").folders.add("parentFolder").then(function (data) {
    return createSubFolder1();
  }).then(function (data) {
    return createSubFolder2();
  }).then(function (data) {
    return updateFolderWithMetaData();
  }).then(function (data) {
    console.log("Folder structure created");
  });
}
```

Running the testingWithFolders function, I'm getting some issues when updating the folder with meta data. Sometimes it will bypass this function entirely, I'm assuming this is because it cannot find the folder that has just been created but it does not seem to even trigger the catch function.

**Comment by patrick-rodgers** [comment]
I think you need to return the .update in that function or put a catch on that level. [Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) is a good article to understand how catch works within the promise chain. Going to close this as it doesn't appear to be an issue with the library. Please re-open if you feel otherwise. Thanks!
