### ISSUE TITLE
[400] Bad Request - No specific information

### ISSUE THREAD

**Issue by webtechy** [SharePoint/PnP-JS-Core#388]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

#### Expected / Desired Behavior / Question
Rather than just giving a 400 bad request message back, would speed development up if you could tell us the offending column (for instance, when trying to update an item). In addition (apparently this may be fixed), the bad request doesn't get caught in a catch statement.

#### Observed Behavior
Generic 400 bad request that doesn't tell us what is wrong.

**Comment by patrick-rodgers** [comment]
If you enable the console logger you will see the full error message - but the message comes from the server, so if what we get back doesn't have the column that isn't information we can produce. I just put up an [article on working](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Logging) with the logging to explain that process.
