### ISSUE TITLE
How to avoid URL length errors?

### ISSUE THREAD

**Issue by Greg-Hitchon** [SharePoint/PnP-JS-Core#395]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [6.9.1]

#### Question
Hello,

I am trying to simply add a file to a folder in the "Shared Documents" library as in:
`web.getFolderByServerRelativeUrl(relativeUrl).files.add(files[i].name, files[i])`

Which is working fine, however it is creating a POST like: 
`POST /sites/mysite/_api/web/getFolderByServerRelativeUrl('/sites/mysite/Shared%20Documents/myfolder')/files/add(overwrite=true,url='some file name') HTTP/1.1`

As the relative url is somewhat long, and the file names can also be long this can max out the url size. Thus I would like to create a POST like:

`/sites/mysite/_api/web/getFolderByServerRelativeUrl(@a1')/files/add(overwrite=true,url=@a2)?@a1='my url'&@a2='my file name' HTTP/1.1``

I know I can just make the request "manually" but was wondering if there was a "pnp-js-core" way of doing it? Any help would be appreciated!
Thanks!

**Comment by patrick-rodgers** [comment]
Well, with a get request there would be a trick, but in your case there isn't. So, let me think about a way to solve this generally. I think what you really want is a way to alias any parameters to the query string. OR  we could update those methods to always put their value on the querystring. Thanks for the idea!

**Comment by Greg-Hitchon** [comment]
OK thanks for the reply!

**Comment by patrick-rodgers** [comment]
Added the capability to alias any parameter [as described in this wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Aliased-Parameters). Will be part of 2.0.3. Going to close this issues as completed.
