### ISSUE TITLE
How to add SP.FieldLookupValue to list item?

### ISSUE THREAD

**Issue by duythanhvo** [SharePoint/PnP-JS-Core#398]
Hello everyone,

#### Category

[ ] Question

#### Version

Please specify what version of the library you are using: [    v.2.0.2     ]

#### Expected / Desired Behavior / Question

I try to insert value for lookup field as I have familiar with JSOM like this:
```
var myFieldLookupValue = new SP.FieldLookupValue();
myFieldLookupValue.set_lookupId(ID);
```

I cannot do it with pnp-js-core:

```
$pnp.sp.web.lists.getById(myListID).items.add({
            Title: quotationNo,
            LookupFieldName: myFieldLookupValue,
            TO: to,
            LOT: lot,
            PIC: pic,
            Email: email,
            Mobile: mobile,
            Service: service
        }).then(item => {
            // Do something
        });
```
There is no error in console. 
Thanks!

**Comment by koltyakov** [comment]
Hi there,

You can't apply JSOM approaches to REST API. There is no need in any `new SP.FieldLookupValue`.

Please use:

```javascript
$pnp.sp.web.lists.getById(myListID).items
  .add({
    LookupFieldNameId: 12,
    MultyValueLookupFieldNameId: {
     results: [1, 3]
    },
  })
  .then(console.log)
  .catch(console.log);
```

There should be an `Id` suffix after a lookup field name.

**Comment by duythanhvo** [comment]
Thanks. I can do it now.

**Comment by koltyakov** [comment]
You're welcome!

**Comment by duythanhvo** [comment]
Hi koltyakov,
Is there any reference for this?

**Comment by koltyakov** [comment]
As the library is mostly a REST based API fluent wrapper (with some exceptions), SP REST API references are relevant, then Issues KB, tech community, blog posts, and sources investigation.
SharePoint REST API reference is on the first place for the new comers, IMO, you can find a lot of parallels, yet one should know that the lib can cover not each and every aspect of the REST API in a specific moment of time, but it, actually, provides helpers for most use cases.
