### ISSUE TITLE
What SharePoint version supported by this library

### ISSUE THREAD

**Issue by jckh1234** [SharePoint/PnP-JS-Core#399]
#### Category
[ ] Enhancement

[ ] Bug

[ #] Question

#### Expected / Desired Behavior / Question
What SharePoint version supported by this library?

**Comment by KEMiCZA** [comment]
2013, 2016 and SharePoint Online should all work if they support the API calls being made. OnPremise I would assume it depends on what version you have installed CU's/updated. Most of the API calls should work on premise and I think should be 100% compatible with SPO. For exampe, if I'm not mistaken batch functionality doesn't work onpremise 2013, not sure about 2016.

**Comment by patrick-rodgers** [comment]
@KEMiCZA is correct. Everything works with SPO, but other things are limited by on-premises versions. Where we know a method does not work we try to note that in the comments but that may not be perfect. Also note [this post](https://blogs.msdn.microsoft.com/patrickrodgers/2016/06/13/pnp-jscore-1-0-1/) on using the setup method when you need to switch the json format when minimal is not available.

Going to close this as answered, please reopen if you have further questions. Thanks!
