### ISSUE TITLE
Is it possible to use pnp-js-core inside a gulp task?

### ISSUE THREAD

**Issue by rrocham** [SharePoint/PnP-JS-Core#402]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version
Lastest version

#### Question
I'm using pnp-js-core in my SPFX project and I'd like to create a simple gulp task to upload some files to SharePoint as part of my build process. In the documentation I noticed that I could setup pnp with a fetch client, more specifically NodeFetchClient that can take a client id and secret. This looks exactly what I need. I registered an app using appregnew.aspx and then granted access using appinv.aspx but I'm getting 403 forbidden in my gulp task. Is there anything else I'd need to do? Is this even possible at all? I'm testing it in a SharePoint online site.

Thanks!

**Comment by rrocham** [comment]
Thanks a lot @koltyakov! I'll give it a shot

**Comment by patrick-rodgers** [comment]
Thanks @koltyakov for the help!

@rrocham - I am going to close this as answered, please reopen if you have further questions. Thanks!
