### ISSUE TITLE
support calling sharepoint rest apis from a mobile app

### ISSUE THREAD

**Issue by petersgiles** [SharePoint/PnP-JS-Core#409]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 2.0.3 ]

Please support using rest queries from a client app not hosted in Sharepoint. i.e. how would I use this in an Ionic App

Thanks!

**Comment by koltyakov** [comment]
Hi Peter,

PnP-JS-Core can execute in two kinds of environments: the first and general, as you mentioned, is a browser's page with SharePoint context, the second one is a Node JS (server side) with [patched Fetch and Headers](https://github.com/SharePoint/PnP-JS-Core/issues/402) (to emulate browser's globals).

I could describe our approach for 3rd (to SharePoint) party client applications. The app should have a backend with API. The backend can be boundary with SharePoint, proxying particular operations to SharePoint in a context of a service account, AddIn only auth, or user auth (in the case when app authenticate its user in SharePoint).

PnP-JS-Core can be used in such a scheme in app's web service implemented as Node JS (Express, Loopback, Hapi, name your favorite API, custom one).
In web-based apps (not sure about Ionic (have no experience with the one), but I tried it with custom web based apps outside SharePoint and Electron-based apps) you can patch your environment to behave like SharePoint REST emulation and `_api/` endpoint (like in [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy)), then you'll be able to use PnP-JS-Core in a context of the app. Yet, it can be a complex and needs deep knowledge of SharePoint REST API.

I would recommend wrapping only a specific operations into your custom backend methods to consume SharePoint data and integrate the app with it.

--
Cheers,
Andrew

**Comment by tavikukko** [comment]
I have been using Ionic + cordova-plugin-ms-adal combo to succesfully read data from SharePoint _api from mobile application. Just add the library to your Ionic project and use is like you would use it any web/ionic project. Add [interceptor](https://github.com/tavikukko/devtalksdemo/blob/master/www/js/services.js#L11) that will add the accesstoken to your calls after you have authenticated with ADAL.

[Here](https://github.com/tavikukko/devtalksdemo) is one older project of mine where Im using graph api, but it could be easily changed to use SharePoint _api with sp-pnp-js.

**Comment by petersgiles** [comment]
Thanks Tomi I will investigate, if I can make sense of it, I'll write up an
article for the wiki here

**Comment by petersgiles** [comment]
@tavikukko thanks, I see that I should authenticate against AD and get a token before doing any sharepoint stuff and it looks like the key to my problem is creating and maintaining a context

`var context = new Microsoft.ADAL.AuthenticationContext(authority);` 

that library looks to come from cordova. which is fine for ionic apps (one of the many things I wish to use) but I'm wondering can I use it in a regular angular2+ app. The documentation seems to suggest you can only use it with Azure...maybe I'm reading it wrong.

In a nutshell I'm trying to develop a web/mobile app that could be run on multiple devices that gets most of its data from regular web services but It sometimes needs to check a sharepoint document library to see if a document has moved to the next workflow step. so for the most part the app really doesn't do much with sharepoint. 

everything happens inside a company VPN and there is no cloud hosting...its all on prem.

as @koltyakov suggested I was thinking that my only way forward was to wrap sharepoint rest api in my own web services and use csom to query sharepoint but I would need to pass through user creds there anyway because of the security trimming on records.

It's just all very lumpy :(

**Comment by patrick-rodgers** [comment]
@tavikukko & @koltyakov - great suggestions, thanks guys!

@petersgiles - I think you have some great guidance above. You say "It's just all very lumpy" - help me turn that into an actionable thing. How can we make it less lumpy? In a generic way what thing(s) could be added to help here?

**Comment by petersgiles** [comment]
@patrick-rodgers fair-call :) and yes @tavikukko & @koltyakov - have made great suggestions, thanks again guys!

You guys have written a good api for taking the sting out of interacting with SharePoint REST. I guess as someone who isn't much of a SharePoint dev it seems odd that in order to use a REST api your app has to be hosted on the same infrastructure as the REST api. So yeah, to me its lumpy. I also acknowledge that you are not in any position change the architecture of SharePoint.

The actionable item(s)

1) I note that there is a SP.RequestExecutor.js which by my read of the documentation can used to perform REST queries in apps not hosted on SharePoint. (btw, i haven't gotten it to work so its likely I'm reading it wrong)
* Bake whatever SP.RequestExecutor.js does into your api for non hosted apps.

---

All that aside, I'm going to give the stuff mentioned here  [patched Fetch and Headers](https://github.com/SharePoint/PnP-JS-Core/issues/402) and [here](https://github.com/koltyakov/sp-rest-proxy) a go.

**Comment by koltyakov** [comment]
Hi Peter,

> odd that in order to use a REST api your app has to be hosted on the same infrastructure as the REST api

With auth cookie injected to the headers, it can be any REST client in absolutely any environment, particular any programming language.
With NodeJS, in most cases, I can recommend taking a look at [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) which abstracts numerous authentication scenarios in SharePoint to straightforward clean universal usage. Which is what is used in Fetch client patching reference above. The library is mentioned via the link and sources, but I decided to emphasize the attention on its role in the NodeJS apps for SP architecture.
After you have this cookie in your app, it has authorized, user security trimmed access to the tenant.
Authentication in the app also can be joined with SharePoint authentication.

**Comment by patrick-rodgers** [comment]
I would also point you to a [post I did on using node-sp-auth with the library](https://blogs.msdn.microsoft.com/patrickrodgers/2016/10/17/using-pnp-js-core-and-node-sp-auth/) as well as the article on [writing your own client](https://github.com/SharePoint/PnP-JS-Core/wiki/Custom-HttpClientImpl) should you need to inject some auth stuff.

I think using the node-sp-auth library, would be a good first step to try out.

I'm going to close this as I think you have some great info to get started. If you get stuck please re-open so we can continue the discussion.

And thanks @koltyakov and @tavikukko for sharing your ideas!
