### ISSUE TITLE
How can i specify the search scope for specified Web Site ? i don't found the correct property

### ISSUE THREAD

**Issue by LMahfoud** [SharePoint/PnP-JS-Core#416]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

How can i specify the search scope for specified Web Site ? i don't found the correct property

**Comment by KEMiCZA** [comment]
Hi LMahfoud

If you would like to search the current web and only the current web, you have to specify the WebId. I've tested the following script on my test environment.

```typescript
pnp.sp.web.select("Id").get().then(w => {
	pnp.sp.search('Test WebId:"' + w.Id + '"').then(results => {
		console.log(results);
	});
})
```

Alternatively you can use 'Path:...' to specify the path to search, for example:

 ```typescript
pnp.sp.search('Test path:"https://mod12345.sharepoint.com/sites/test"').then(results => {
	console.log(results);
});
```
I'm not sure yet if there are built in methods in the library to provide these types of parameters.

**Comment by LMahfoud** [comment]
Hi KEMiCZA,

I will try it right now.

**Comment by LMahfoud** [comment]
This is my expression, so where can i make this scope 
  $pnp.sp.search({

                    Querytext: expression,
                    EnableSorting: true,
                    SelectProperties: ["Title", "Author", "Description", "SiteDescription", "AverageRating", "LastModifiedTime", "Write", "Path"],
                    RowLimit: 500
                }).then(controllerToViewResult);

**Comment by KEMiCZA** [comment]
I think it should go inside **Querytext**: _expression_

So it would be something like:
```typescript
$pnp.sp.search({
                Querytext: 'Test path:"https://mod12345.sharepoint.com/sites/test"',
                EnableSorting: true,
                SelectProperties: ["Title", "Author", "Description", "SiteDescription", "AverageRating", "LastModifiedTime", "Write", "Path"],
                RowLimit: 500
            }).then(controllerToViewResult);
```

**Comment by LMahfoud** [comment]
Its not working
I will get the result from all sites and when i show the data i filter fo the site scope

**Comment by KEMiCZA** [comment]
@LMahfoud try specifying the Id of the web to only search within that web like this:
```typescript
pnp.sp.web.select("Id").get().then(w => {
	pnp.sp.search({
		Querytext: 'Test WebId:"' + w.Id + '"',
		EnableSorting: true,
		SelectProperties: ["Title", "Author", "Description", "SiteDescription", "AverageRating", "LastModifiedTime", "Write", "Path"],
		RowLimit: 100
	}).then(x => { console.log(x); });
});
```

I think it's a matter of configuring it correctly.

**Comment by LMahfoud** [comment]
So where can i make my search expression ?

**Comment by KEMiCZA** [comment]
@LMahfoud if you mean the text you want to search for you can type at the beginning of your Querytext parameter. For example if you're searching for "Expenses" you would specificy it like this:
```typescript
Querytext: 'Expenses WebId:"' + w.Id + '"',
```

Appologies if I'm misunderstanding you. Is this what you mean?

**Comment by LMahfoud** [comment]
Ok thank's

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks @LMahfoud & @KEMiCZA for the great discussion. If you have further questions please _reopen_ this thread or start a new one. Thanks!
