### ISSUE TITLE
How to use /_api/site/openWebById using PnP

### ISSUE THREAD

**Issue by hitendraapatel** [SharePoint/PnP-JS-Core#422]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by patrick-rodgers** [comment]
You haven't provided any details?

**Comment by hitendraapatel** [comment]
I am using REST call to get list items based on web and list guid as per below.
REST URL:  _spPageContextInfo.siteAbsoluteUrl+"/_api/site/openWebById(webId)/lists(guid)/items

When I look for PnP code for the same REST call, unable to find any details.

**Comment by patrick-rodgers** [comment]
So you are asking for support to get a web by id? Seems easy enough.

**Comment by patrick-rodgers** [comment]
I spoke to soon. That method only accepts POST requests - so you are doing a POST to get items? Seems like a lot of extra overhead. Have you tried other approaches? Or help me understand what you are trying to do and we can suggest alternatives. It is easy enough to implement and will look like this - but that seems harder than just getting the web using a filter on id and then creating a new web instance using the id.

```TypeScript
pnp.sp.site.openWebById("guid").then(w: Web => {
   // where w will be a Web instance.
});
```

**Comment by hitendraapatel** [comment]
Thanks for response. 

I was using OpenWebById method in REST call to get document library files as having long web url(having multiple subwebs) as well as having long folder hierarchy in document library in which i was getting files. At the time of using REST url, there is limitation of REST url length while doing get or post call. It gave me REST Url length exceeds error. So I decided to make short REST URL. Due to this reason, I have used OpenWebById in REST and it was working fine. 

Now I am using PnP code and replacing existing REST. I raised query to have support of such method in PnP as it is not available.

As per your comment, I will try to create web object and then do call for items.

**Comment by patrick-rodgers** [comment]
So the answer to your question is no the library does not currently support that method. We can add it, no problem. You could also look at the [parameter aliasing](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Aliased-Parameters) feature added in 2.0.3 to help with url length.

**Comment by patrick-rodgers** [comment]
Added this in #431. Going to close this it will be part of 2.0.5.
