### ISSUE TITLE
Multi-tenancy support with FetchClientFactory

### ISSUE THREAD

**Issue by tylerjwatson** [SharePoint/PnP-JS-Core#423]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [2.0.4]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Hi guys,

We have a rather unusual use case in that we run a node.js server which is responsible for proxying calls to multiple sharepoint online tenants for the purposes of backend storage in list items.  The server is, for our intents and purposes, multi-tenant.

The server already retrieves application bearer tokens per tenant per request, for use with plain restful calls to SharePoint `_api` endpoints, all of which we would love to replace with pnp-js-core.  I find myself tripping over the global library configuration as it doesn't really support a multi-tenant scenario in a way that's obvious to me: Calling `setup(...)` allows for a custom `HttpClientImpl` factory function, but the factory isn't able to be made aware of context-specific site URLs or bearer tokens, which are constructed on a per-request basis.  I can call `setup(...)` once each request, but it seems like that would be doing unnecessary work yet still yield incorrect results.  If the global HTTP client factory function closes over `url` and `token` from one request, there may be a possibility to leak information from one tenant to another.

Calling `new Web(httpClient)` and setting that on our request environment could work.

Am I missing something?  Is there a way we can get js-core to support multi-tenant setup?  If not, are you able to point me in the general direction in which I can go about contributing this myself?

Have a wonderful day!

Cheers,
T.

**Comment by patrick-rodgers** [comment]
Hi @tylerjwatson - so short answer is no, we don't have support for this currently.

Longer answer...this is an interesting scenario but not one we considered when designing the library. As you noted it is very much single tenant focused. I don't off the top of my head have a quick answer for how to make it work with multi-tenant, but can start to think about it. There are a few things ahead of this in the feature queue but always welcome a PR if you come up with something. For now let's leave this issue open and do some investigation. IF we can find a way to support it I want to be very careful, we can't break the entire API to enable it. It might be helpful if you can share some code showing the type of request you are currently making.

Actually, now that I have thought about it a little more, have you tried just giving Web the urls of the sites you want? I can't think of anything that should disallow that...

**Comment by tylerjwatson** [comment]
Thanks Patrick, might give this a bit more thought on this end as well.  I'm tied up, but will update this issue with more coherent stuff as the idea matures.

**Comment by patrick-rodgers** [comment]
Ok, cool - will close this for now then. Please reopen once you have a better idea of what changes you would need to help enable this scenario. Thanks!
