### ISSUE TITLE
example to write a user field with multiple entries

### ISSUE THREAD

**Issue by cOwOsen** [SharePoint/PnP-JS-Core#424]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [2.0.4]

#### Expected / Desired Behavior / Question
Hi,

i need an example to write a user field with multiple entries.

Thanks!

**Comment by koltyakov** [comment]
Hi,

Multiple users can be populated like this:

```javascript
pnp.sp.web.lists.getByTitle('List_Name').items
  .add({
    UsersPickerId: {
     results: [9, 19] // User Ids from UIL as an array of numbers
    },
  })
  .then(console.log)
  .catch(console.log);
```

`UsersPickerId` is a people picker internal name concatenated with 'Id'.

**Comment by cOwOsen** [comment]
Hi,

thanks for your support.
