### ISSUE TITLE
Exposing utilities functions 

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-JS-Core#425]
#### Category
[X ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [    2.0.4     ]

#### Expected / Desired Behavior / Question
Should  pnp expose the sp.utilities.utility.sendemail and other methods(like searchPrincipals, and 
resolvePrincipal etc) 
https://msdn.microsoft.com/en-us/library/office/jj838435.aspx

**Comment by patrick-rodgers** [comment]
Sure, no reason not to.

**Comment by patrick-rodgers** [comment]
Added support for this in #427. Also just pushed a beta release 2.0.5-beta.0 so you can try it out and let us know how it works.

**Comment by ravenboilinux** [comment]
Just ran through the new utility api from the beta. It works great. One thing I notice is the interface EmailProperties as the property From as required fields, but if the field is not present, the Rest API uses the server outbound email address or if none is present, throws an error

**Comment by patrick-rodgers** [comment]
Thanks for the feedback, I'll reopen this to remind myself to mark that property as optional in the interface.

**Comment by ravenboilinux** [comment]
you welcome.

**Comment by patrick-rodgers** [comment]
And done.
