### ISSUE TITLE
Is it possible to use pnp-js-core in provider-hosted web?

### ISSUE THREAD

**Issue by jckh1234** [SharePoint/PnP-JS-Core#426]
#### Category
[ ] Enhancement

[ ] Bug

[ #] Question

#### Expected / Desired Behavior / Question
Is it possible to use pnp-js-core in provider-hosted web?

Thanks!

**Comment by patrick-rodgers** [comment]
Yes, please see [the samples add-in](https://github.com/SharePoint/PnP/tree/master/Samples/SharePoint.pnp-js-core) for examples of this.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please reopen if you still have questions. Thanks!
