### ISSUE TITLE
Check out/in functions? 

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#429]
Does this library have any functions to check-out/in files? 

I need to update list items with a Ribbon button on a library where checkout is forced. It seems like I need to do 3 REST calls for this so I'm hoping pnp-core-js would have something I could use to make this simpler. 

I can't find anything about check in/out in the wiki however

**Comment by patrick-rodgers** [comment]
Yes, it does. I just added [a section in the wiki to explain check in, check out, and approve](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Files#check-in-check-out-and-approve). HTH

**Comment by simkessy** [comment]
Perfect. Question, this and batching make sense in this senario: I need to update 1 value for all selected documents in a view but the library has forceCheckOut enabled. So I need to loop over each item, checkout, update value, checkin. Could this be all one batch operation with pnp-js?

**Comment by simkessy** [comment]
Never mind I was able to figure it out. I put [this function ](https://gist.github.com/simkessy/1aaea535e8c73876553371f9f2ab3e8a)together that uses batching to checkout/update/checking all selected files. 

This library is awesome.
