### ISSUE TITLE
Submitting more than one people field update in a single request fails

### ISSUE THREAD

**Issue by hankanman** [SharePoint/PnP-JS-Core#430]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.4]

#### Expected Behavior
Issuing an items.add to a list will allow more than one people field to be updated in a single request.

#### Observed Behavior
Adding more than one people field to be updated to a request causes the request to fail.

Works:
`web.lists.getByTitle(this.props.listName).items.add({ PeopleField1Id: { "results": [204] } });`

Fails:
`web.lists.getByTitle(this.props.listName).items.add({ PeopleField1Id: { "results": [204] }, PeopleField2Id: { "results": [53] } });`

**Comment by patrick-rodgers** [comment]
What is the error you are receiving? There isn't anything the library does that should be impacting this, but if so want to get it fixed.

**Comment by patrick-rodgers** [comment]
I just added [this section to the wiki explaining how to update user fields](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#user-fields). Perhaps that will help you out as well.

**Comment by hankanman** [comment]
@patrick-rodgers your documentation clears it up, the issue was that I was formatting both fields as if they were multiple. Where actually in my list, one was multiple, one was single. I have tested with several variations of field settings and it appears to be working fine now. Just the lack of documentation that caused the issue, i might suggest adding documentation for each of the field types for clarity.
