### ISSUE TITLE
How get items which I am following & Search for Documents

### ISSUE THREAD

**Issue by gauravgoyal5** [SharePoint/PnP-JS-Core#435]
Hi ,
1. I wanted to get items which I am following. These items can be People, Documents & Sites.
Can you please let me know how can I get these?

2. I want to search for Documents for within Site Collection and within specific web & its child web. How can I get this?

Thanks & Regards
Gaurav Goyal

**Comment by patrick-rodgers** [comment]
We don't currently have support for the following API, though something we can look at adding. For search you can [use the search API](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Search). Out search API support is improved in the upcoming 2.0.5 release planned for May 10th.

**Comment by schurlinga** [comment]
Is it planned to support the "Following people and content REST API"?

If not, is there a possibility to use the pnp library to make a "custom" sharepoint rest api call? to be able to use currently unsupported rest api?
