### ISSUE TITLE
shareWith always successful

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/PnP-JS-Core#441]
#### Category
- [ ] Enhancement
- [x] Bug
- [x] Question

#### Version
2.0.3

#### Expected / Desired Behavior / Question

When using the shareWith() method I always get "CompletedSuccessfully" as StatusCode.
I don't think this is really PnP-JS-Core related, since this server returns this data:
```json
{
  "ErrorMessage":null,
  "InvitedUsers":
    [{
      "Email":"someone@123",
      "InvitationLink":"...",
      "Succeeded":true
    }],
  "Name":"Kindsite",
  "PermissionsPageRelativeUrl":null,
  "StatusCode":0,
  "UniquelyPermissionedUsers": [],
  "Url":"...",
  "UsersAddedToGroup":null
}
```
I've stripped some information for privacy and readability.

#### Steps to Reproduce
Do a request like this:
```typescript
pnp.sp.web.shareWith('someone@123').then((inviteResult)=>{
  console.log('invite StatusCode:', inviteResult.StatusCode); // Will return 0
});
```
I would expect this tot return some other StatusCode, since this is an invalid address.

**Comment by patrick-rodgers** [comment]
I don't think this is an issue with the library as you say. One thing that might be in play here is that the list of emails we pass back to the service is passed as resolved people picker entities (we do that mapping for you to make things easier). So the back end might not check them at all as it expects they are already resolved. Just a guess though on my part. You can check/resolve users by using the newly added in 2.0.5 [resolvePrincipal utility method](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-SP.Utilities.Utility#resolveprincipal).

**Comment by patrick-rodgers** [comment]
As also a reference to where we do that [mapping from email to resolved users](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/queryableshareable.ts#L130)

**Comment by RoelVB** [comment]
Thanks you for your reply.

I thought the resolvePrincipal method would solve my issue, but it won't return the user information until the user has accepted the invitation. I don't really care about the invite. If I could add a user directly without an invite it would be fine, but I don't think this would be possible.

**Comment by patrick-rodgers** [comment]
Ah, so for external folks you are correct the resolve principal will not work. The sharing API is still in "beta" so perhaps this behavior will change in the future. Will close this thread, please reopen to continue the discussion if needed. Thanks!
