### ISSUE TITLE
Promote list column to site column

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#442]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[x ] Enhancement

[ ] Bug

[x ] Question

I created a program a long time ago that converted list columns to site columns. It seems that this would be a god candidate for a powershell command. It uses CSO< . Any interest in incorporating this into PNP-Cpre/PNP-Powershell? Is there another way to do this? 
https://code.msdn.microsoft.com/Convert-Sharepoint-28e28d4d
https://yetanothersharepointblog.wordpress.com/2013/07/12/listcolumn_to_sitecolumn/

**Comment by patrick-rodgers** [comment]
Hey @russgove, Maybe, but that is a question better asked in the [PowerShell repo](https://github.com/SharePoint/PnP-PowerShell/issues). I can certainly see the value of such a command. Will close this but encourage you to submit it in PowerShell repo. Thanks!
