### ISSUE TITLE
Any good reason why Util.makeAbsoluteUrl is now missing and Util.toAbsoluteUrl is returning a promise?

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP-JS-Core#449]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version
2.0.5

Is there any good reason why Util.makeAbsoluteUrl is gone from this version? And I noticed the alternative (Util.toAbsoluteUrl) is returning a promise instead of normal string, is this the expected result?

Thanks

**Comment by patrick-rodgers** [comment]
Yes, the makeAbsoluteUrl was deprecated a few versions ago and removed in this latest release. The toAbsoluteUrl returns a promise as that works better within the request pipeline and it didn't make sense to maintain both methods. The value you get back is the same as you would have for makeAbsoluteUrl. Sorry if this tripped you up.

**Comment by jonathanhotono** [comment]
Thanks for the clarification @patrick-rodgers ..
Another thing,
Can we also make the `Web` to receive ServerRelativeUrl? (E.g: `new Web("/sites/sample/test")` )
The current situation that I got is some of configuration strings that I got is in form of ServerRelativeUrl, e.g:
ListUrl = "/sites/sample/test"
My spfx webpart is deployed and embedded into "/sites/sample" (which is the parent absolute url of the site collection).
To access the "/sites/sample/test" web from "/sites/sample", it simply cannot be done by using `toAbsoluteUrl("/sites/sample/test")` function as it will basically spit out the wrong url: `https://contoso.sharepoint.com/sites/sample/sites/sample/test`.

So what I did to fix is to do pre-flight check by using `isUrlAbsolute` against the string and prepend the FQDN url into the string if it isn't absolute url and pass the prepended url into the Web parameter.

**Comment by patrick-rodgers** [comment]
@jonathanhotono - I would have to look at what the impact of that change would be, but my initial feeling is that would be hard. We need to convert the request to an absolute url when we execute the get so as it stands I think we'd end up doing exactly what you called out and you'd end up with the wrong path. IF all you want is to hit a sub web I think (haven't tested this) you can use this:

```TypeScript
let w = new Web("", "test");
```

That should use the main web url as calculated by toAbsoluteUrl and append "test" giving you what you expect. Can you give that a try?

**Comment by patrick-rodgers** [comment]
Going to close this for now, please reopen if you need to continue the conversation. Thanks!
