### ISSUE TITLE
if statement wrong for emailSubject

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/PnP-JS-Core#450]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
2.0.5

#### Expected / Desired Behavior / Question
The emailSubject is not set when sending a share invite

#### Observed Behavior
Default subject is set

This if statement here is the wrong way around:
https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/queryableshareable.ts#L142

Same here:
https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/queryableshareable.ts#L90

**Comment by patrick-rodgers** [comment]
Yep, that sure looks like a bug. Thanks for letting us know will get this fixed and out in a beta.

**Comment by patrick-rodgers** [comment]
Fixed in #451 and available in sp-pnp-js@2.0.6-beta.1 for validation.
