### ISSUE TITLE
Uncaught (in promise) Error: Error making HttpClient request in queryable: [400] Bad Request

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#456]
Hi Team,
I'm using PnP JS version 2.0.5 and I got the error mentioned in the subject line while I update the item into SharePoint list. Please find the code below and provide the solution for this issue. Here I'm using Angular JS to do the promise.

1. Set the updated value as below
var fieldValue = {
                WorkDescription: "Work Description - Philip",
                Title: "New Title Updated"
            };

2. Pass the value into the method
function updateListItem(itemId, listName, fieldValue) {
            var d = $q.defer();            $pnp.sp.web.lists.getByTitle(listName).items.getById(itemId).update(fieldValue).then(function(data) {
                d.resolve(data);
            });
            return d.promise;
        };

Kindly provide the solution for the same. 
Thanks
Philip

**Comment by koltyakov** [comment]
Hi @spvjebaraj ,

My guess, that you have placed wrong field name into update object or mismatched list name.
`getByTitle` users display names. Update and add objects should include only correct internal names with some exceptions for OData namings.

The errors in a console don't give all the information. `[400] Bad Reques` can mean anything. Please check real response message in Chrome Dev Tools in Network tab or by a message within a catch.

OData error message will say more, e.g.:

```json
{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The property 'Error' does not exist on type 'SP.Data.[ListName]ListItem'. Make sure to only use property names that are defined by the type."}}}
```
is a wrong set of field names

```json
{"error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List '[Wrong lists' display name]' does not exist at site with URL 'http://....com/sites/site'."}}}
```
is a wrong lists' display name

Also, there is no any need to wrap promise into another promise.
`$pnp.sp.web.lists.getByTitle(listName).items.getById(itemId).update(fieldValue)` is already return a promise. Your function can be:

```javascript
var updateListItem = function(itemId, listName, fieldValue) {
  return $pnp.sp.web.lists
    .getByTitle(listName)
    .items.getById(itemId)
    .update(fieldValue);
};
```

To troubleshoot I would suggest:

1) Check if the list name provided is correct:

```javascript
var listName = '[your_list]';
$pnp.sp.web.lists.getByTitle(listName).then(console.log); 
// Should return list metadata, if not, then your're trying wrong name
```

2) Chech field internal names and that you provide corresponding data type format:

```javascript
var listName = '[your_list]';
var itemId = [item_id];
$pnp.sp.web.lists.getByTitle(listName).items.getById(itemId ).get().then(console.log); 
// Check the list of possible basic fields 
// `WorkDescription` can be names something else there, like `WorkDescription0`
```

**Comment by spvjebaraj** [comment]
Hi Andrew,
I've given the correct list name and fields. I got the error in "fetchclient.js" file. Please find the fetchclient code below and I've attached the screenshot of error.

var FetchClient = (function () {
    function FetchClient() {
    }
    FetchClient.prototype.fetch = function (url, options) {
      **return global.fetch(url, options);** **// error came here**
![pnp error](https://cloud.githubusercontent.com/assets/25079793/26024595/13e68b94-37f2-11e7-9147-ea76366ba088.png)

    };
    return FetchClient;
}());
exports.FetchClient = FetchClient;

Thanks
Philip

**Comment by koltyakov** [comment]
@spvjebaraj, how about troubleshooting suggestions? 
Can you get list's metadata (by **display name**) and is there a `WorkDescription` (**internal name**) field in the list?

I can assure, that nothing wrong with fetch client here. Server response with 400 because something wrong in the REST request you've constructed.
To get a clue what's wrong in your code I recommend to check network tab in your browser's tools find request with the issue and investigate response object.

**Comment by spvjebaraj** [comment]
Hi Andrew,
Thanks for your help. I've given the field name as correct but the value of field is wrong. In my code, I used the currency datatype and I passed the value as string, that's why it throws error. Now it is resolved with currency value.

Thanks
Philip

**Comment by koltyakov** [comment]
Glad to hear you figured it out! Have a good coding day!
