### ISSUE TITLE
Adding options to existing choice fields? 

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#457]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Latest

#### Expected / Desired Behavior / Question
Is it possible to add more options to existing Choice fields using PNP?

All options I've seen have been through JSOM. 

Thanks!

**Comment by koltyakov** [comment]
Hi @simkessy,

Yes, this is possible with pnp-js-core.

Here is an example which adds choices values to a field instance in a list.
For site columns, it works in the same way.

```javascript
var addChoicesToListsChoiceField = (listName, choiceFieldName, newChoices) => {

    // Field promise
    let field = $pnp.sp.web.lists.getByTitle(listName)
        .fields.getByInternalNameOrTitle(choiceFieldName);

    // Getting current choice values
    field.select('Choices')
        .get().then((fieldData) => {
            // Append only unique choices
            let choices = fieldData.Choices.results || fieldData.Choices; // For verbose & minimalmetadata
            let newUniqueChoices = newChoices.reduce((res, val) => {
                if (choices.indexOf(choices) === -1) {
                    res.push(val);
                }
                return res;
            }, []);

            // Update choice field with new array of choices
            field
                .update({ 
                    Choices: {
                        results: choices.concat(newUniqueChoices)
                    }
                }, 'SP.FieldChoice')
                .then(console.log)
        });

};

addChoicesToListsChoiceField('List Name', 'ChoiceFieldName', [ 'New choice value 1', 'New choice value 2' ]);
```

**Comment by patrick-rodgers** [comment]
@simkessy - let us know, that works for me as well so I think you should be sorted.

Great example @koltyakov, thanks as always!!

**Comment by patrick-rodgers** [comment]
Going to close this issue as the question is answered. Please reopen the issue to continue the conversation if needed. Thanks!

**Comment by simkessy** [comment]
Hey, 

@koltyakov thank you for the response, works perfectly.

**Comment by jchilde** [comment]
The above does work for Site Columns and List Fields.  What I can't seem to find is an option to push changes to lists when updating a site column.  Am I missing something or is there a path to trigger this option?
