### ISSUE TITLE
Search using SourceId

### ISSUE THREAD

**Issue by MarkStokes-outlook** [SharePoint/PnP-JS-Core#460]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
Please specify what version of the library you are using: [ 2.0.4 ]

#### Expected / Desired Behavior / Question
I am trying to perform a search against a Site Collection Result Source, but my attempts are failing.

#### Observed Behavior
I am receiving a '500 (Internal Server Error)' error when I try to submit my search

#### Steps to Reproduce
```
pnp.sp.search({
    Querytext: "*",
    SourceId: "b2935547-bc92-46cf-815a-fd2ef0e8bb61",
    RowLimit: 50
})
```

Thanks!

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, we'll have a look.

**Comment by patrick-rodgers** [comment]
Hi @MarkStokes-outlook - I am not able to duplicate this, at least in my testing. I tried it with both a custom result source and an OOTB provided one. You can double check you have the right id. Do you have any other details you can share?

**Comment by patrick-rodgers** [comment]
Going to close this as we haven't heard back. Please _reopen_ if you are still having issues or need assistance. Thanks!

**Comment by ttalies** [comment]
Hi, 
I ran into the same problem. When I try to set the SourceId within the search, it is ignored.

We defined a custom result source and set it as default. Now I want to get the results of the OOTB resulte source "Local SharePoint results" ID 8413cd39-2156-4e00-b54d-11efd9abdb89.

But all results I get are within the custum result source.

Here is my code:
pnp.sp.search({
          Querytext: "test",
          RowLimit: "10",
          SourceId: "8413cd39-2156-4e00-b54d-11efd9abdb89",
          EnableInterleaving: true,
      }).then((results) => {
      let _resultset = [];
      for (var i=0; i < results.PrimarySearchResults.length; i++)
          {
              _resultset.push(results.PrimarySearchResults[i]);
          };
      this.setState({resultset1: _resultset});
      }
    );
