### ISSUE TITLE
 search paging + filters 

### ISSUE THREAD

**Issue by biogenez** [SharePoint/PnP-JS-Core#462]
[x ] Bug
There is an error occurred, when using search paging (method: getPage) 
if the SearchQuery contains some additional params (for example RefinementFilters).
The method getPage calls 'search.execute(query);' 
In the method 'execute' some params (like RefinementFilters) will be encapsulated (in 'results') every time:
```
if (formattedBody.RefinementFilters) {
formattedBody.RefinementFilters = { results: query.RefinementFilters };
}
```
As result the RefinementFilters will be equal:
`{ results : 'filter value' }`
And after calling the getPage method (search.execute):
`{ results : { results : 'filter value' } }`

The variable 'query' s should not be changed in the method 'execute' :
```
let formattedBody: any;
formattedBody = query; // <- it's wrong. (because original query object will be modified)
```

**Comment by patrick-rodgers** [comment]
Fixed this in #472, thanks for reporting it!
