### ISSUE TITLE
ViewXML with pnp.js

### ISSUE THREAD

**Issue by jaiswati** [SharePoint/PnP-JS-Core#463]
Hi ,

Below code snippet , did not work as expected , it did not filter the list data based on the query object 
Please correct if anything is missing below (already added the reference of required  pnp/fetch/promise.js)

ES6Promise.polyfill();

// Insert PnP example script
$pnp.setup({  
    headers: {  
        "Accept": "application/json; odata=verbose",  
    },  
});

``var` queryText =''"<Where><And><Gt><FieldRef Name='DueDate'/><Value Type='DateTime'>2017-05-03T00:00:00Z</Value></Gt><Lt><FieldRef Name='DueDate'/><Value Type='DateTime'>2017-06-02T00:00:00Z</Value></Lt></And></Where>";
    queryText = queryText+"<GroupBy Collapse='TRUE' GroupLimit='30'><FieldRef Name='GroupName' /></GroupBy>><OrderBy><FieldRef Name='DueDate' `/></OrderBy>""";``
var query = {
        "ViewXml": queryText 
    };
[this query works fine with REST api]
$pnp.sp.web.lists.getByTitle("TaskList").getItemsByCAMLQuery(query).then(function(result) {

alert('Test');
for (var i = 0; i < result.length; i++) {
        console.log(result[i].Title);
}

    //Add your code to display the collection results
});

**Comment by patrick-rodgers** [comment]
What is the error or response you are getting?

**Comment by patrick-rodgers** [comment]
After looking at your XML it appears there is an extra ">" character:

```
/GroupBy>><OrderBy>
```
Not sure if that is the issue or not. Please let us know what error you are seeing with this. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this as we haven't heard back. Please _reopen_ if you are still having issues or need assistance. Thanks!
