### ISSUE TITLE
GetWopiFrameUrl returns undefined

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#466]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ c] Bug

[ ] Question

#### Version

Latest Version

#### Expected / Desired Behavior / Question
GetWopiFrameUrl should return the WopiFrameUrl

#### Observed Behavior
GetWopiFrameUrl returns undefined
#### Steps to Reproduce
callgetwopiframeurl

Hi, in GetWopiFrameUrl the methoid is returning 'data.GgetWopiFrameUrl'  data is just  a string that contains the url. it has no member GetWopiFrameUrl,

It should return dat, not data.getWopiFrameUrl.

I can submit a quick patch, but I wanted to make sure i wasnt missing something here.

**Comment by patrick-rodgers** [comment]
Out of curiosity are you running with vebose odata?

**Comment by russgove** [comment]
i have not set up anything to override the oob behavior. i'm running against sharepoint online

**Comment by russgove** [comment]
my setup looks like this.
      pnp.setup({
        spfxContext: this.context,
      });

**Comment by patrick-rodgers** [comment]
ok, thanks @russgove

**Comment by patrick-rodgers** [comment]
Fixed in #473. The issue here is that the old code worked for verbose mode BUT NOT not verbose mode. Whenever this was written/tested it happened apparently in verbose mode. Anyway, thanks for reporting it and will be included in a rollup beta release once I get caught up. Thanks @russgove!

**Comment by russgove** [comment]
is this fix in the llatest release?
