### ISSUE TITLE
How do I return security trimmed sub webs? (new pnp.Web(this.url).webs) either returns all or returns a System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by kittycatbytes** [SharePoint/PnP-JS-Core#468]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.5  ]

#### Expected / Desired Behavior / Question
Return all webs that the user has access to.

#### Observed Behavior
Mostly a System.UnauthorizedAccessException response, since most users do not have Browse Directories permissions

#### Steps to Reproduce
The following line : return new pnp.Web(this.url).webs;

**Comment by patrick-rodgers** [comment]
You could try using search with a query similar to:

```
path:"https://tenant.sharepoint.com/sites/mysite" contentclass:STS_Web
```

You can adjust the path and as well you can add additional filters as needed.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ the issue if you are still having trouble so we can help out. Thanks!
