### ISSUE TITLE
Request Digest call is not required when passing Access Token in Authorization header

### ISSUE THREAD

**Issue by garrytrinder** [SharePoint/PnP-JS-Core#469]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   2.0.5   ]

#### Expected / Desired Behavior / Question
When making a POST request, passing an access token in the Authorization header of the request is sufficient to use a SharePoint REST endpoint.

#### Observed Behavior
PnP Core JS does not respect that an Authorization header has been setup in the custom headers and therefore makes a request to get the request digest instead rather than calling the SharePoint REST resource directly passing the token. There is another issue in that when making these POSTs the headers are not passed, so a 401 thrown as no access token is passed, this has been raised as a separate issue [#464](https://github.com/SharePoint/PnP-JS-Core/issues/464)

#### Steps to Reproduce
Get a valid access token from Azure AD
Ref - [Create JavaScript web apps using CORS to access Office 365 APIs](https://msdn.microsoft.com/en-us/office/office365/howto/create-web-apps-using-CORS-to-access-files-in-Office-365#get-an-access-token-from-azure)
Setup custom headers in PnP.Setup to pass Authorization header
Make any POST call using PnP Core
First request is to "_api/contextinfo" endpoint

**Comment by patrick-rodgers** [comment]
This was completed and merged in #475. Will be part of an upcoming beta release so it can be tested and tried out. Thanks!
