### ISSUE TITLE
Issues with PnP Core JS because of requireJS in SharePoint Online

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-JS-Core#470]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [  2.0.3   ]

#### Observed Behavior

PnP JS Core dist is bundled as umd module with webpack

(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["$pnp"] = factory();
	else
		root["$pnp"] = factory();
})

The problem within sharepoint online is now (since they are using requireJS) when loading the library async when needed e.g. using jQuery.getScript() pnp registers itself as anonymous module "define([], factory);" therefore $pnp is not available in global namespace.

The question is now, how should we deal with this within a sharepoint online classic page without adding a script tag (which breaks MDS) for the library directly into the page?

I would like to load the library async whenever we need it and I don't want to hijack the requireJS loader that is now beeing loaded by Microsoft (via Core.js)

**Comment by patrick-rodgers** [comment]
I think I get the question, but please let me know if I miss the mark. If you aren't using a script tag you do get an anonymous module via a script loader such as system or require and you will get a var back that === the global $pnp part. This pseudo code shows that:

```
require(["pnp"], function (pnp) {

  //  pnp here is === the global $pnp

});
```

There is a sample [here](https://github.com/OfficeDev/PnP-JS-Core/wiki/files/TypeScriptHTMLApp1.zip) which is a little old but shows the pattern as well. The same thing should work with jquery's load script. Does that give you the info you need?

**Comment by OliverZeiser** [comment]
Thank you for your answer. I know how I would deal with it, if it was my own requirejs loader. But in SharePoint Online MS has added requirejs to every teamsite now. I could hijack this one to load my scripts, but MS advices not to rely on this one: https://dev.office.com/blogs/RequireJS-On-First-Release-Tenants
So now with requireJS from Microsoft loading, if we load pnp async and not in a script tag, we dont have $pnp in global namespace so we can't use it anmyore.

Here is a simple example. Go to any ootb SharePoint Online Teamsite (classic) and paste this in your browser console:

var script = document.createElement('script');
script.src = 'https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.5/pnp.js';
script.onload = function () {    
};
document.head.appendChild(script);

In theory I should have a global $pnp now, right? But since the requirejs that MS is loading now, I don't have a global $pnp. Is it more clear this time what I mean?

**Comment by patrick-rodgers** [comment]
I just pasted the below code into a script editor web part and it worked as expected. So unsure what issue you are seeing. Perhaps you need to have a trigger function in the script's onload method and are trying to execute code against $pnp before it is loaded?

```
<p>Script Editor is on page.</p>
<div id="testingdiv"></div>
<script>

function stuffisloaded() {

    console.log(0);

    var script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.5/pnp.js';
    script.onload = function () {
        console.log(1);
        $pnp.sp.web.get().then(w => {
            console.log(2);
            console.log(w);
        });
    };
    document.head.appendChild(script);

}
</script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?callback=stuffisloaded&features=es6|always|gated,fetch|always|gated"></script>
```

**Comment by OliverZeiser** [comment]
Sorry for the trouble, but if you paste it into a script editor, it could well happen that your code executes faster than the code where Microsoft loads the requirejs. They are also loading requirejs async (via Core.js). Thats why I suggested to load it via console after all MS stuff has loaded. This is the biggest problem, it is a timing issue. If we load pnp after ms loaded requirejs it does not work. If we load it before, everything works as expected.

**Comment by patrick-rodgers** [comment]
Not quite following, the code I pasted should be independent of requirejs and not affected by it. Can you give me the full repro steps you are using? I'd like to help but I seem to be missing the actual issue. Thanks!

**Comment by OliverZeiser** [comment]
Hi Patrick, Thanks again and sorry I think I know now why you could not reproduce it. The issue does not occure on all sites in SPO, but only on classic WEB PART PAGES that are added in SitePages library. This was my mistake. See a network trace here, on those Web Part Pages, requirejs is beeing loaded.
![requirejs](https://cloud.githubusercontent.com/assets/8672900/26498355/1487c3f0-422f-11e7-931f-7de444af5d29.PNG)

**So the repro steps are:**
Go to a sharepoint online site and go into sitepages library.
Now click New (Arrow icon) and choose Web Part Page.
Create a new page (pick any layout) and make sure it is added to the sitepages library (not siteassets).
Paste the snippet above into developer console and after that type $pnp into console, once the pnp.min.js is added.

Here is a screenshot of my console output using IE:
![requirejs2](https://cloud.githubusercontent.com/assets/8672900/26498652/0b06c302-4230-11e7-9a36-d5343e825bc6.PNG)

The way I understand it, this happens because the script now registers itself via requirejs instead of globally.

**Comment by OliverZeiser** [comment]
Just to complete this, here is the screenshot of your code (adjusted from typescript to javascript):
![requirejs3](https://cloud.githubusercontent.com/assets/8672900/26499292/52b2dcc0-4232-11e7-95d9-056f2e0febea.PNG)

**Comment by patrick-rodgers** [comment]
So you aren't adding the code to the page, you are trying to use it via the console only? What is the use case for this? I am not sure the console works that way or that require being loaded is interfering.

It works for me as expected in a publishing page (using blank web part page layout) when I paste the script exactly as I provided above. At this point it doesn't seem to be an issue with the library but rather how browsers use the console.

If you are trying to do some quick testing/editing I recommend this [chrome extension](https://chrome.google.com/webstore/detail/sp-editor/ecblfcmjnbbgaojblcpmjoamegpbodhd?hl=en) by Tomi Tavela. it allows you to have a console like experience using this library and provides intellisense as well. A great way to quickly test out some code without having to deploy anything.

**Comment by OliverZeiser** [comment]
Okay, here is a full sample. Just paste this in a script editor web part on a normal teamsite in a classic web part page, just as I described earlier. Wait until the page is loaded and then click on the link.
It should work, right? But for me it does not work....

<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6|always|gated,fetch|always|gated"></script>
<script>
function runPnPStuff() {
    console.log(0);
    var script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.5/pnp.js';
    script.onload = function () {
        console.log(1);
        $pnp.sp.web.get().then(function(w) {
            console.log(2);
            console.log(w);
        });
    };
    document.head.appendChild(script);

}
</script>
<a href="#" onclick="runPnPStuff();">KLICK ME</a>

**Comment by KEMiCZA** [comment]
@OliverZeiser try adding type="text/javascript" to the script tags. I've had a similar issue before and setting the type worked.

**Comment by OliverZeiser** [comment]
This does not change anything apperantly :(
![pnpcapture](https://cloud.githubusercontent.com/assets/8672900/26821091/8ae9d244-4aa5-11e7-9dce-2783813fc2ba.PNG)

**Comment by KEMiCZA** [comment]
Why not include the pnp.js library directly in a script tag. This works fine for me in a script editor webpart:
``` javascript
<script type="text/javascript" src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6|always|gated,fetch|always|gated"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.5/pnp.js"></script>
<script type="text/javascript">
function runPnPStuff() {
        console.log(1);
        $pnp.sp.web.get().then(function(w) {
            console.log(2);
            console.log(w);
        });
}
</script>
<a href="#" onclick="runPnPStuff();">KLICK ME</a>

**Comment by OliverZeiser** [comment]
Well because we are loading the scripts only when needed async. If you add script tags within the site, the minimal download feature will break. So we add a usercustomaction to the site and load the scripts on demand dynamically and very generic depending on what is on the page.

**Comment by KEMiCZA** [comment]
@OliverZeiser This works for me
``` javascript
<script type="text/javascript" src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6|always|gated,fetch|always|gated"></script>

<script type="text/javascript">
    function runPnPStuff() {
        var defineOriginalValue= define;
        if(typeof define === 'function' && define.amd){define = null;}
        var tt= document.createElement('script');
        tt.setAttribute("type", "text/javascript");
        tt.setAttribute("src", "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.5/pnp.js");
        tt.onload = function () {
            define = defineOriginalValue;
    }
        document.getElementsByTagName("head")[0].appendChild(tt);
    }
</script>
<a href="#" onclick="runPnPStuff();">KLICK ME</a>
```

Or you can download the pnp.js file and remove the following line:
``` javascript
	else if(typeof define === 'function' && define.amd)
		define([], factory);
``` 
and upload the pnp.js file to a document library. I'm not familiar with the requireJS library or if changing this code would break any other elements.

**Comment by OliverZeiser** [comment]
Thanks @KEMiCZA I know that it would work if I'd remove the line from pnp.js. And setting define=null is probably not a good idea, because it might break things from SharePoint/Microsoft.
This is what my original question is all about. How should we deal with this and what is the intention of bundling the pnp.js as webpack UMD module?

**Comment by KEMiCZA** [comment]
@OliverZeiser My knowledge is very limited when it comes to modules. But I know that the PnP library can be used in combination with nodejs to create server side applications (authentication with clientId/secret). Maybe this is the reason why that module exists?

**Comment by patrick-rodgers** [comment]
@OliverZeiser - We seem to be going in loops where for each response you then present a new scenario. What are you actually aiming to do? If it is loading scripts dynamically **I'd recommend systemjs, requirejs, or similar to handle that as they will properly scope the variables.** It doesn't seem like you actually need the script to be global. If you do need the script to be global then I'd recommend just using a script tag in the page - i.e. if everything depends on this script being present and global there is no benefit to loading it later as you'll need it almost immediately regardless.

To answer your question the library is bundled as UMD to provide the greatest amount of flexibility to either use it in a script tag or through a module loader. Most folks use it via a module loader or built into their solutions using webpack (or similar).

**Comment by OliverZeiser** [comment]
Thank you @patrick-rodgers . I was not trying to go in loops, just trying to provide a very simple example to reproduce the issue as fast as possible. Sorry for the confusion there. But the problem remains the same: Loading the library async will be a in SharePoint Online

In fact I am using an async loader from this PnP example here:
https://github.com/SharePoint/PnP/tree/master/Samples/Core.JavaScript
This one to be exactly. 
https://github.com/SharePoint/PnP/blob/master/Samples/Core.JavaScript/Core.JavaScript.CDN/js/pnp-loaderMDS.js

Now depending on the amount of scripts you load in this example and when you load the pnp.js, the issue can occur but will not always occur because it is a little bit of a timing issue. (MS is loading requirejs async as well....) That is why I tried to make an example that demonstrates the issue itself without you having to build a full app.

Many people out there are using scriptloaders like that within SharePoint Online and are not using additional libraries like requirejs because you are forced to load your scripts async unless you customize the masterpage within SharePoint Online. This is what the PnP Core Team recommends doing...
If I would use requirejs now, this would be a problem because I would overwrite the global require variable from Microsoft...

**Comment by patrick-rodgers** [comment]
We've had a good conversation around this but there isn't a fix we can implement that will solve this problem as such. You can make use of requirejs, systemjs, or other module loaders to handle this. One option would be to first check that require is on the page or not, then load it if needed. I am aware of the pnp sample you linked (I wrote it), but it was made before SPFx. You can also look to use SharePoint Framework that will handle loading your dependencies and ensuring proper scoping, which is the recommended client side customization technique moving forward.

If you would like to continue this conversation you can _reopen_ the issue. Thanks!
