### ISSUE TITLE
Get Web Properties of specific site

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#477]
Hi Team,
I'm using pnp js core in my project along with typescript. I want to get the information from specific web and not the current context site. I've used the below code to achieve the same but the "webServerRelativeUrl" is appended to the main url while retrieve. Please consider the code below and provide the solution.

import { Web } from "sp-pnp-js";

var siteUrl = "/sites/dev-sp1/en";
var filePath = "pages/test.aspx";

public getPageInfo(siteUrl: string, filePath: string) {
       let web = new Web(siteUrl);
       return web.getFileByServerRelativeUrl(siteUrl + filePath).get();
}

I got the error as "Error: Error making HttpClient request in queryable: [404] Not Found".

The url is appended as below. 
http://hostname/sites/dev-sp1/en/sites/dev-sp1/en/_api/web/getFileByServerRelativeUrl('/sites/dev-sp1/en/pages/test.aspx')

Kindly provide the solution for the same to get it from specific site.

Thanks
Philip

**Comment by koltyakov** [comment]
Hi,

For new Web creation, an absolute URL is used. While getFileByServerRelativeUrl method receives a relative URL. So, in your case you could try:

```javascript
import { Web } from "sp-pnp-js";

var webAbsoluteUrl = "https://contoso.sharepoint.com/sites/dev-sp1/en";
var webRelativeUrl = "/sites/dev-sp1/en"; // or calc from an absolute one
var filePath = "pages/test.aspx";

...
let web = new Web(webAbsoluteUrl);
web.getFileByServerRelativeUrl(`${webRelativeUrl}${filePath}`).get();
...
```

Well, hope you got the idea.

**Comment by spvjebaraj** [comment]
Hi Andrew,
Thanks for provided the solution. It works like a charm.
Could you please help me, how to get the page information from the above code.
I've used the code as "web.getFileByServerRelativeUrl(`${webRelativeUrl}${filePath}`).getText()".

But I got the ouput as below.
<%@ Page language="C#"   Inherits="Microsoft.SharePoint.Publishing.PublishingLayoutPage,Microsoft.SharePoint.Publishing,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %>
<%@ Register Tagprefix="SharePointWebControls" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="WebPartPages" Namespace="Microsoft.SharePoint.WebPartPages" Assembly="Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="PublishingWebControls" Namespace="Microsoft.SharePoint.Publishing.WebControls" Assembly="Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %> <%@ Register Tagprefix="PublishingNavigation" Namespace="Microsoft.SharePoint.Publishing.Navigation" Assembly="Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<asp:Content ContentPlaceholderID="PlaceHolderAdditionalPageHead" runat="server">
	<SharePointWebControls:CssRegistration name="<% $SPUrl:~sitecollection/Style Library/~language/Themable/Core Styles/pagelayouts15.css %>" runat="server"/>
	<PublishingWebControls:EditModePanel runat="server">
		
		<SharePointWebControls:CssRegistration name="<% $SPUrl:~sitecollection/Style Library/~language/Themable/Core Styles/editmode15.css %>"
			After="<% $SPUrl:~sitecollection/Style Library/~language/Themable/Core Styles/pagelayouts15.css %>" runat="server"/>
	</PublishingWebControls:EditModePanel>
</asp:Content>

But I want to get the body content of the page. Any idea and suggestion please..

**Comment by koltyakov** [comment]
Hey,

Looks like you are trying to get layout page data.

In some cases publishing page content can be extracted like this:

```javascript
$pnp.sp.web
  .getFileByServerRelativeUrl('/[webUrl]/Pages/Test.aspx')
  .listItemAllFields.select('PublishingPageContent').get()
  .then(res => {
    console.log(res.PublishingPageContent);
  });
```

With getText file content is retrieved.

**Comment by spvjebaraj** [comment]
Hi Andrew,
In my case, I want to fetch the item from list based on target audience in Office 365. There is no API to fetch item with target audience using JSOM, REST (client object model). So I have created new page called service page and in that page I have added CQWP and apply the filter properties including target audience.

From that page I extracted the html DOM elements using jquery. But now I want to achieve the same using pnp.

Thanks
Philip

**Comment by koltyakov** [comment]
PnP JS Core, in some way, is equal to REST API and if anything is impossible with current REST API implementation it's automatically can't be achieved with PnP JS Core. Please hold this in mind.

**Comment by spvjebaraj** [comment]
Thanks. Is it possible to get the page content as HTML DOM using pnp?

**Comment by koltyakov** [comment]
I do not know about such capability in REST API, because it has no sense. Maybe someone will correct me, but plain GET request to the page is already there to do the thing.

Maybe you do not want to reference 3rd party Ajax libraries or struggle with XMLHttpRequest.
PnP uses native Fetch client, with fetch you can do the following:

```javascript
fetch('/[webUrl]/Pages/Test.aspx', {
   method: 'GET',
   credentials: 'same-origin' 
})
    .then(response => response.text())
    .then(console.log); // Page DOM
```

**Comment by spvjebaraj** [comment]
Hi Andrew,
Thanks. It is working fine. Both (ajax request & fetch api) fetching times are same.
Thanks
Philip

**Comment by patrick-rodgers** [comment]
Thanks @koltyakov for the great answers. @spvjebaraj - it looks like you got your questions answered so I am going to close this issue. If you have further questions, please _reopen_ the issue so we can assist. Thanks!
