### ISSUE TITLE
When you add multiple list items, the promise is not resolved

### ISSUE THREAD

**Issue by somartin90** [SharePoint/PnP-JS-Core#478]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

sp-pnp-js v2.0.5

#### Expected / Desired Behavior / Question
When I add multiple items, the items are added correctly to the list, but the promises are not resolved.

My code is the following:

`private addMultipleListItems(): Promise<any> {
        var self = this;

        return new Promise<any>((resolve, reject) => {

            var promises = new Array<Promise<any>>();

            for (var i = 0; i < 5; i++) {
                var list = pnp.sp.web.lists.getByTitle("Test List");
                var promise = list.items.add({ Title: "Item " + i });
                promises.push(promise);
            }

            Promise.all(promises).then(result => {
                resolve();
            });
        });
    }`
 
I am using the chrome browser and the error that returns me after a couple of minutes is the following:

![image](https://cloud.githubusercontent.com/assets/21335587/26520376/7dbeeef0-42d1-11e7-9619-a2d40514a528.png)

Thanks!

**Comment by koltyakov** [comment]
Hi,

Are you sure that it's not an error in your code rather that in the library?
Please apply some attention on how you create a promise.

Please try:

```javascript
...
    return new Promise((resolve, reject) => {
        let promises: Promise<any>[] = [];
        let list = $pnp.sp.web.lists.getByTitle('Test List');
        for (var i = 0; i < 5; i += 1) {
            let promise = list.items.add({ Title: `Item ${i}1` });
            promises.push(promise);
        }
        Promise.all(promises).then(result => {
            resolve();
        });
    });
...
```

or

```javascript
...
  let promises: Promise<any>[] = [];
  let list = $pnp.sp.web.lists.getByTitle('Test List');
  for (var i = 0; i < 5; i += 1) {
    let promise = list.items.add({ Title: `Item ${i}1` });
    promises.push(promise);
  }
  return Promise.all(promises);
...
```

Have no env with 2.0.5 by hand but from what I can see in your code, it's this line `return new Promise<any>((resolve, reject) => {` it should be at least `return new Promise((resolve, reject) => {`.

**Comment by patrick-rodgers** [comment]
@somartin90 - did the above answer help resolve your issue or are you still having problems with multiple promises?

**Comment by patrick-rodgers** [comment]
Going to close this as it appears to have been answered and we haven't heard back. Please _reopen_ the issue if you have further questions or need additional help. Thanks!
