### ISSUE TITLE
Get Body Content of Page using PnP

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#479]
Hi,
How to read the body of the page content using pnp js core.
I've used the below code to get the body of page content without using pnp.
return jQuery.ajax(
                {
                    url: "sites/dev-sp1/en/mylibrary/test.aspx",
                    dataType: "html",
                    context: document.body,
                    cache: false,
                    success: (data: any, status: string, jqXHR: JQueryXHR) => {
                    }
                }
            );

I've used the below code to get the same by using pnp but the page content is not displayed.
return web.getFileByServerRelativeUrl(`${webRelativeUrl}${filePath}`).getItem();
or 
return web.getFileByServerRelativeUrl(`${webRelativeUrl}${filePath}`).get();
or
return web.getFileByServerRelativeUrl(`${webRelativeUrl}${filePath}`).getText();

Thanks
Philip

**Comment by patrick-rodgers** [comment]
I believe this is a duplicate and was answered in #477. Going to close this but if you have further questions please _reopen_ the issue so we can assist. Thanks!
