### ISSUE TITLE
attachmentfiles.add from another list attachment

### ISSUE THREAD

**Issue by floodycarlow** [SharePoint/PnP-JS-Core#481]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ v2.0.5 ]

#### Question

Dear Community,

A JS novice here but I am looking into using JS core to be able to "copy" a list attachment to another list item.

While I am able to get the item attachment details e.g.ServerRelativeUrl I am struggling to be able to use the received data and pass it through to the attachmentfiles.add method correctly.

Any guidance would be of great help.

```
var file ="";

let item = $pnp.sp.web.lists.getByTitle("List A").items.getById(1);

item.attachmentFiles.getByName("External Users.docx").getBlob().then(v => {

    console.log(v);
    
    
});


item.attachmentFiles.getByName("External Users.docx").get().then(v => {
    
    console.log(v.ServerRelativeUrl);
    
    file = (v.ServerRelativeUrl);

});
    
    
     $("#btnClick").click(function CopyItem() {
     
     let item = $pnp.sp.web.lists.getByTitle("List A").items.getById(2);

    item.attachmentFiles.add("External Users.docx", file ).then(v => {

    alert("File copied");


    });

    });


```

**Comment by patrick-rodgers** [comment]
The below worked for me, so I think you can do something similar. There are other gets available such as getBlob if the file is not text. HTH

```TypeScript
    const list = $pnp.sp.web.lists.getByTitle("ListTitle");

    list.items.getById(1).attachmentFiles.getByName("file.txt").getText().then(file => {

        list.items.getById(2).attachmentFiles.add("newname.txt", file).then(_ => {

            console.log("done");

        });
    });
```

**Comment by floodycarlow** [comment]
@patrick-rodgers thanks Patrick. Was able to get it to work using "getBlob". Cheers

**Comment by patrick-rodgers** [comment]
Awesome! I'll close this then, but please reopen if you need to continue the conversation - or open a new issue if you run into something else. Thanks!

**Comment by floodycarlow** [comment]
@patrick-rodgers Back again :) The above worked great for adding a single attachment. But now I am struggling with multiple attachments. I have looked at the [thread ](https://github.com/SharePoint/PnP-JS-Core/issues/381 )on supporting multiple attachments but cant seem to get my head around the correct method with the data I get back i.e. multiple blobs...again appreciate any guidance.

```
// get current item attachments
    sourceitem.attachmentFiles.get().then(v => {

      for (var k in v) {
        console.log(v[k].FileName);

        let filename = v[k].FileName;

        // get currect item attachments blobs
        sourceitem.attachmentFiles.getByName(filename).getBlob().then(blobs => {

          console.log(blobs);
        });
      }
    });

    $("#btnClick").click(function AddItem() {

      destlist.items.getById(id).attachmentFiles.addMultiple(filename, file).then(_ => {

        console.log("done");

      });
    });
```

**Comment by patrick-rodgers** [comment]
I just added [guidance for the addMultiple method](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Attachments#add-multiple), please have a look at the usage. You'll also need to ensure your variables are properly scoped such that the data is available when you need it.

**Comment by floodycarlow** [comment]
@patrick-rodgers thanks so much for this. I am testing the guideline and usage but getting an "Uncaught SyntaxError: Unexpected token :" for the following. Maybe its me not implementing correctly?

`var fileInfos: AttachmentFileInfo[] = [];`

**Comment by patrick-rodgers** [comment]
If you are just doing JavaScript and not TypeScript that line would be:

```
var fileInfos = [];
```

**Comment by floodycarlow** [comment]
@patrick-rodgers thanks so much again for the guidelines and support. Really helpful :)

**Comment by patrick-rodgers** [comment]
YW!
