### ISSUE TITLE
error TS2304: Cannot find  name 'Response'.

### ISSUE THREAD

**Issue by ADPangburn** [SharePoint/PnP-JS-Core#482]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  2.0.5       ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Expecting build process of tsc to succeed.

#### Observed Behavior
When using npm start using quick start seed from angular.io getting the following errors
node_modules/sp-pnp-js/lib/net/fetchclient.d.ts(6,47): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(15,57): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(16,60): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(17,55): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(18,56): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(19,57): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(20,58): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/httpclient.d.ts(24,56): error TS2304: Cannot find
 name 'Response'.
node_modules/sp-pnp-js/lib/net/nodefetchclient.d.ts(21,47): error TS2304: Cannot
 find name 'Response'.
node_modules/sp-pnp-js/lib/net/sprequestexecutorclient.d.ts(9,47): error TS2304:
 Cannot find name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/caching.d.ts(20,21): error TS2304: Cannot
find name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(4,14): error TS2304: Cannot fin
d name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(7,14): error TS2304: Cannot fin
d name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(8,30): error TS2304: Cannot fin
d name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(14,14): error TS2304: Cannot fi
nd name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(60,14): error TS2304: Cannot fi
nd name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(63,14): error TS2304: Cannot fi
nd name 'Response'.
node_modules/sp-pnp-js/lib/sharepoint/odata.d.ts(66,14): error TS2304: Cannot fi
nd name 'Response'.

#### Steps to Reproduce
npm install sp-pnp-js -save
added code as follows

import pnp from 'sp-pnp-js';
import { Web }  from "sp-pnp-js/lib/sharepoint/webs"
...

        let w = new Web("{SiteUrl}");
        return Promise.resolve(w.lists.getByTitle("ListName").items.add({
            
        }).then(r =>
        {
            console.log(r);
        }));

npm start

I get the errors as listed above

here is package.json file

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "sp-pnp-js": "^2.0.5",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.1.0",
    "canonical-path": "0.0.2",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "@types/node": "^6.0.46",
    "@types/jasmine": "2.5.36"
  },
  "repository": {}
}

**Comment by Vivek-Muralidaran** [comment]
I am facing the same issue. Can you please let me know the fix for this?

**Comment by ADPangburn** [comment]
For me it was my typescript version was mismatched and so es6 wasn't being seen because they changed how typomgs worked in around 2.2. Did you install 2.2 or above recently?

I set my version path to use the typescript version in my project rather than what typescript was using by default.

**Comment by Vivek-Muralidaran** [comment]
Appreciate the quick response.
So, apparently, I was using an older version of typescript. Updating to the latest version did solve the problem partially. So when I build the project I don't get the error anymore. But when I try to webpack I get the same "Cannot find the name Response" error. Any ideas?

Thanks in advance.

**Comment by ADPangburn** [comment]
So I don't know much about webpack yet though I use angular CLi for my builds so I know it uses tsc to compile. Maybe install typescript globally or install it in the project path where we pack is building from and see if that helps I wish I had more to give you but I'm still learning all this myself :)

**Comment by Vivek-Muralidaran** [comment]
No probs..Thanks for your time. Really appreciate it. :)
