### ISSUE TITLE
profiles.myProperties 404

### ISSUE THREAD

**Issue by adams141** [SharePoint/PnP-JS-Core#483]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.5 ]

#### Expected / Desired Behavior / Question
when calling the method to get properties of the current user, I expect it to return the properties of the current user

#### Observed Behavior
When making this call in javascript on a page in the SitePages library:
`$pnp.sp.profiles.myProperties.get().then(...`

I receive the following error in the console:
`GET http://intranetdev/SitePages/_api/sp.userprofiles.peoplemanager/getmyproperties 404 (Not Found)`

It appears the path to the current page, not just the current web is included in the URL. Removing SitePages from the URL and putting it into the browser returns the correct data.

#### Steps to Reproduce
include pnp.js on a page in the SitePages library.
add the following javascript:
```
$pnp.sp.profiles.myProperties.get().then(function(result) {
			var props = result.UserProfileProperties;
			var propValue = "";
			props.forEach(function(prop) {
				propValue += prop.Key + " - " + prop.Value + "<br/>";
			});
			document.getElementById("sample").innerHTML = propValue;
			}).catch(function(err) {
				console.log("Error: " + err);
			});
```

Thanks!

**Comment by patrick-rodgers** [comment]
For cases where you are operating without a _spPageContextInfo variable available [you'll need to set the base url](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#base-url), in your case "http://intranetdev/".

You can also try delaying your code running until the page is fully loaded in case the _spPageContextInfo object is not written out yet.

Please give either of those options a try and let us know if that gets you going. Thanks!

**Comment by adams141** [comment]
Both methods worked. My test page wasn't using the masterpage, so I was missing the _spPageContextInfo object. Thank you very much for the quick help.

I knew as soon as I put that 'x' next to Bug, that I probably should have put it next to Question.

Thanks again

**Comment by jcollinsks** [comment]
@adams141 I am using the exact same sample you have there, when I run it from a site and reference the script in a script editor it works fine, when I add it as a script link I get your error. Where did you put the _spPageContextInfo to get it to work if you don't mind helping!

**Comment by adams141** [comment]
@jcollinsks , when using a scriptlink, you need to wait for the SharePoint javascript to complete loading, when it will create the _spPageContextInfo object. You can do this by wrapping your code in 

```
SP.SOD.executeFunc('sp.js','SP.ClientContext',runthiscode);

function runthiscode()
{
       // do your stuff here
}
```

Hope this helps
