### ISSUE TITLE
Getting all site collections in SharePoint Addin?

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#484]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version
 [    latest     ]

Is it possible to use pnp-js-core to retrieve all the site collections in a SharePoint Online tenant? 

I'm trying to build a SharePoint hosted application which contains a dropdown of all the Site Collections created in a tenant? 

Thank.

**Comment by patrick-rodgers** [comment]
No, you would need to use the Tenant object, you can see that in [this example](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs#L229). HTH!

**Comment by simkessy** [comment]
Is there anything I can do client-side? I'm not too familiar with C#.

**Comment by patrick-rodgers** [comment]
Not currently no, and to use the Tenant object the account would need to be a tenant admin level - so not something you'd typically do from the client. You could try something with search and scope the query to sites - but that will only ever bring back results for sites to which the current user has access.

**Comment by simkessy** [comment]
Okay, I think I'll have to go with Search then. Thank you.
