### ISSUE TITLE
Confusing LimitedWebPartManager API

### ISSUE THREAD

**Issue by oka-garaio** [SharePoint/PnP-JS-Core#485]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
2.0.5

#### Expected / Desired Behavior / Question
In JSOM we can do something like this
```js
limitedWebPartManager.addWebpart(wepart, zone, index)
```

#### Observed Behavior
In the existing pnp LimitedWebPartManager (https://github.com/SharePoint/PnP-JS-Core/blob/36dc7289a12d6c290aab5e3a3d374c016dd4e656/src/sharepoint/webparts.ts) there is no such method.

I can import a WebPart to a page as following, but not place it where I want it to be.

```js
$pnp.sp.web.folders.getByName("SitePages").files.getByName("Homepage.aspx").getLimitedWebPartManager().import("Some webpart xml...").then(result => {
    console.log(result);
});
```

But the expected method does not exists, as the following error told me:
```
Uncaught TypeError: $pnp.sp.web.folders.getByName(...).files.getByName(...).getLimitedWebPartManager(...).addWebPart is not a function
```

Am I missing something or is not yet supported?

#### Steps to Reproduce
Run the specific code on a sharepoint web's page where $pnp is present.

Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this issue, please _reopen_ if you would like to continue the conversation. Thanks!
