### ISSUE TITLE
Using PnP in provider-hosted add-in without StandardTokens (TypeScript/Angular2)

### ISSUE THREAD

**Issue by caelistic** [SharePoint/PnP-JS-Core#486]
#### Category
[ ] Enhancement

[ ] Bug

[ X ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.4 ]

#### Question
Hi,
I am working on a SharePoint project which is a provider-hosted add-in and written in Typescript/Angular2.
SharePoint calls are working when I am coming from SharePoint or when I am adding the app part to the SharePoint because I have got {StandardTokens} as query parameters and can set the AppWebUrl as baseUrl in the setup of PnP.
But how do I get a SharePoint connection within my add-in when I am just opening the URL of the provider-hosted add-in and I haven't got {StandardTokens}? We are using NTLM for authentication.

Thanks!

**Comment by patrick-rodgers** [comment]
Provider hosted add-ins rely on the standard tokens being present. Without them your add-in cannot know where to connect. You are also getting through the redirect cycle a token posted to your add-in.

You can [set the url of a web](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#get-a-web-directly) to call or [globally for the library](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#base-url), but this won't handle anything with permissions.

**Comment by caelistic** [comment]
Okay, thank you.
Now I thought about preserving the query paramters. The saved url will have the standard tokens, but when I am changing the permissions of the provider-hosted add-in sharepoint gives it a new SPWebAppUrl. Do you know how to handle that?
