### ISSUE TITLE
Superfluous library url .

### ISSUE THREAD

**Issue by mstivoi** [SharePoint/PnP-JS-Core#488]
[ ] Enhancement

[ ] Bug

[x] Question

I am trying to build client side web part .  I create simliest request to SharePoint
pnp.sp.web.get().then(f => 
{
      alert(f);  
}); 
But it always fails . In browser console i see failed request : 
https://MYSPROOT/sites/spdevsite/SitePages/_api/web .

Request fails because it always adds "SitePages" (because my web part on Site Pages page )   
The question is how to construct correct request?

**Comment by patrick-rodgers** [comment]
Either you are on a page without _spPageContextInfo available OR your code is executing before it has a chance to load. You can [set the url of a web](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#get-a-web-directly) to call or [globally for the library](https://github.com/SharePoint/PnP-JS-Core/wiki/Configuration#base-url).

The other option is to delay your code execution until the page is fully loaded. HTH, Thanks!

**Comment by mstivoi** [comment]
Hi Patrick . Yes ,this is Modern page and it have no  _spPageContextInfo.
I used Wed contsructor with url . You can close the issue.

Only one little question .  Is it possible to pass dynamic key in "update" item method ?

list.items.getById(itemId).update({
       Key: Value           }).then(i =>    {
});
I mean use Key as variable , not static . 
Thank You.

**Comment by patrick-rodgers** [comment]
You are passing a plain object so yes it is possible to do that. I'd start with just passing the field names to see things works - then working on making the objects dynamic. I am going to close this issue, but please _reopen_ if you need more help. Thanks!
