### ISSUE TITLE
Trying to get group OwnerID and OwnerIsUser

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#489]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

[    latest     ]

I have a function which returns all the groups in my collection with this information for each group: 

```
    //SOAP CALL RETURNS ALL GROUPS IN COLLECTION
    var promise = $().SPServices({
      operation: "GetGroupCollectionFromSite"
    });

    //IF SUCCESSFUL
    promise.then(function(response) {
        var result = $(response);
        //GET ATTRIBUTES FROM EACH GROUP
        result.find("Group").each(function() {
          var self = $(this);
          //STORE IN ALL GROUPS OBJECT
          allGroups.push({
            id: self.attr('ID'),
            name: self.attr('Name'),
            description: self.attr('Description'),
            owner: self.attr('OwnerID'),
            ownerIsUser: self.attr('OwnerIsUser')
          });
        });
        d.resolve(allGroups);
      },
      function(error) {
        //LOG  ERROR
        var reason = $(error).find('errorstring');
        NoticeService.send('error', reason)
        d.reject('failed');
      });
```

I'm working on converting my application from SPServices to PnpJS so I changed the above function to this: 

```
var getGroups = function () {
    return $pnp.sp.web.siteGroups
        .select("Id", "Name", "Description", "OwnerID", "OwnerIsUser")
        .get()
        .then(result => {
            return result.reduce(function (allGroups, group) {
                allGroups.push({
                    id: group.Id,
                    name: group.Name,
                    description: group.Description,
                    owner: group.OwnerID,
                    ownerIsUser: group.OwnerIsUse
                });
                return allGroups;
            }, []);
        }, error => {
            //LOG ERROR
            var reason = $(error).find('errorstring');
            NoticeService.send('error', 'GetUsers failed: ' + reason);
        });
};
```

The problem I'm noticing is that when I get the groups using PNP it doesn't include **OwnerID** and **OwnerIsUser**

Anyway to get these properties?

**Comment by koltyakov** [comment]
Hi @simkessy,

My little piece of advice is to check for REST API reference in such cases.
In REST API site groups attributes are structured in a different way as in SOAP. To get group Owner data it's necessary to expand 'Owner' and get its attributes explicitly:

```javascript
$pnp.sp.web.siteGroups
  .select("Id", "Name", "Description", "Owner/Id", "Owner/PrincipalType")
  .expand('Owner')
  .get()
  .then(console.log)
```

Hope this will help.

For principal types (as there is no IsUser as I know in Owner), you can check this page https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.utilities.principaltype.aspx

**Comment by KEMiCZA** [comment]
@simkessy how do you know what properties you can extend? For example how did you know here that you could expand "Owner"? Thanks

**Comment by koltyakov** [comment]
Good question =)
I did it by requesting all properties for a single group and checking fields set, e.g.:

```javascript
$pnp.sp.web.siteGroups.getById(6).get().then(console.log);
```

**Comment by simkessy** [comment]
@koltyakov this is really helpful thank you. Also, I didn't realize I could log like that. That's useful, thanks!
