### ISSUE TITLE
Question: adding an item in a folder

### ISSUE THREAD

**Issue by KEMiCZA** [SharePoint/PnP-JS-Core#490]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Question
Hi all. I was wondering if it's possible to create a list item in a folder using REST API's?

``` typescript
pnp.sp.web.lists.getByTitle("TestList").items.add({
	Title: "Test",
	ServerRelativeURL: "/sites/Test2/Lists/TestList/folder"
}).then(() => { });
```

Is there any way I can pass the _path_ of the folder in any way?

Thanks!

**Comment by koltyakov** [comment]
As far as I know, it's not possible in REST as in JSOM for example.
I personally used moveTo method in item creation promise callback.

Something similar to:

```javascript
let subFolderUri: string = '/folderUri';
let listUri: string = '/folderUri';
let itemMetadata = {
    // metadata
};

pnp.sp.web
    .getList(listUri)
    .items.add({
        ...itemMetadata
    })
    .then((item: any) => {
        return pnp.sp.web
            .getFileByServerRelativeUrl(`${listUri}/${item.data.Id}_.000`)
            .moveTo(`${subFolderUri}/${item.data.Id}_.000`);
    })
    .then(console.log)
    .catch(console.log);
```

**Comment by KEMiCZA** [comment]
@koltyakov thanks for the information. I thought so as well, a bit disappointing it's not possible. The moveTo method seems like a solution, I will try it out!

**Comment by KEMiCZA** [comment]
The moveTo method did work as expected, but I stumbled upon another issue later on, so I decided to work without folders and filter based on a field. Thanks again for the input and this thread can be closed.

**Comment by patrick-rodgers** [comment]
Right on, thanks folks!

**Comment by ahsanranjha** [comment]
The user only has permission on specific folder, he do not have access list to root folder, is it possible to add items inside folder directly without moving?

**Comment by koltyakov** [comment]
I believe it just not possible in REST API, for such purposes JSOM should be used instead.

**Comment by koltyakov** [comment]
Some research based on reverse engineering of Modern lists in SPO:

- Items in Modern experience are created with REST API
- There is a feature of creating an item in a folder
- It uses `/_api/web/GetList([list_path])/AddValidateUpdateItemUsingPath()` endpoint
- and the following payload:

```json
{
  "listItemCreateInfo": {
    "__metadata": {
      "type": "SP.ListItemCreationInformationUsingPath"
    },
    "FolderPath": {
      "__metadata": {
        "type": "SP.ResourcePath"
      },
      "DecodedUrl": "/sites/dev-a/Lists/ListA/Folder 1"
    }
  },
  "formValues": [{
    "FieldName": "Title",
    "FieldValue": "Test 1",
    "HasException": false,
    "ErrorMessage": null
  }],
  "bNewDocumentUpdate": false,
  "checkInComment": null
}
```

So, it's possible to cover `AddValidateUpdateItemUsingPath` method. PR are welcomed.

**Comment by ahsanranjha** [comment]
is AddValidateUpdateItemUsingPath is only for rest api or Is there any option for code like pnp.sp.web.lists.getByTitle("TestList").items.add??

I was searching to add items in batch and after creation start workflow and create specific task on each item after created??

**Comment by ahsanranjha** [comment]
Sorry, i was not able to utilize this rest call /_api/web/GetList([list_path])/AddValidateUpdateItemUsingPath()

**Comment by ahsanranjha** [comment]
I used JSOM and promise to create items in job list one by one, then on each success i create task item on each job item created. it is taking long time.

**Comment by ahsanranjha** [comment]
I was not able to utilize AddValidateUpdateItemUsingPath, may be later i learn how to utilize it.

I used JSOM, if one item get exception then it breaks. By doing one by one i can alert user to contact support or try later. so why i consider it to use one call and process another on first success.

  for(var i = 0; i< 5; i++){
    
        var itemCreateInfo = new SP.ListItemCreationInformation();
        var oListItem = oList.addItem(itemCreateInfo);  
        oListItem.set_item('Title', 'My New Item!' + i);  
        oListItem.update();
        itemArray[i] = oListItem;
        clientContext.load(itemArray[i]);
    }

**Comment by ahsanranjha** [comment]
What actually i have requirements to achieve batch processing on following business flow.

There are three list to be effected, each list item will be created inside folder with unique permissions. 

1. Candidate SP List :  Display and list of candidate to be hired,  
2. Job SP List : Create Job item for selected candidates one job for one each candidate selected 
3. Task SP List : on job success -> Create Task on each job created. 
4. Candidate SP List : on job success -> Mark candidates as short listed.
