### ISSUE TITLE
ShareWith - unexpected token

### ISSUE THREAD

**Issue by simonagren** [SharePoint/PnP-JS-Core#491]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     2.0.5    ]

_
#### Expected / Desired Behavior / Question
In an SharePoint Online Developer tenant.
Trying to share a document via share with

```
pnp.sp.web.getFileByServerRelativeUrl("/sites/a/Documents/Document.docx").shareWith("i:0#.f|membership|user@tenant.onmicrosoft.com", SharingRole.Edit).then((result: SharingResult) => {

    console.log(result);
}).catch(e => {
    console.error(e);
});

```

#### Observed Behavior
Getting the file is no propblem,
Getting users etc is no problem.
So pnp js is working.

When trying to share I get the following message:

SyntaxError: Unexpected token < in JSON at position 0

#### Steps to Reproduce

1. Dev tenant
2. From SPFX Extension in modern list (Custom action)
3. Trying to share the file via code

**Comment by patrick-rodgers** [comment]
The sharing functionality is still in beta - we still see different behaviors across different tenants. We called this out [on the sharing wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Sharing). That being said - can you provide the raw data so we can see what was sent and came back? This unfortunately may be a case where we need to wait for the API to lock.

**Comment by simonagren** [comment]
Well, it helped to check in the documents first :)
But now I get this answer 
![image](https://user-images.githubusercontent.com/16558321/27085776-94b409ba-5050-11e7-8ffd-d4139e950ca6.png)

Dont't know if that's raw enough for you? :)

**Comment by simonagren** [comment]
Okey so I figured some things out...hopefully
This made it work for me.
The badguy was includeAnonymousLinkInEmail = true. Since I didnt send any email it messed things up.

1. Compared to when you share via "normal" function how the postbody looked like.
2. If you should not send an Email, the  includeAnonymousLinkInEmail should not be true.
3. So I set includeAnonymousLinkInEmail = false, emailBody = '', sendEmail = false, by default.
4. If there is any emailData these properties are changed.

CHANGED CODE:
```
public shareWith(loginNames: string | string[], role: SharingRole, requireSignin = true, propagateAcl = false, emailData?: SharingEmailData): Promise<SharingResult> {

        // handle the multiple input types
        if (!Array.isArray(loginNames)) {
            loginNames = [loginNames];
        }

        const userStr = JSON.stringify(loginNames.map(login => { return { Key: login }; }));
        const roleFilter = role === SharingRole.Edit ? RoleType.Contributor : RoleType.Reader;

        // start by looking up the role definition id we need to set the roleValue
        return Web.fromUrl(this.toUrl()).roleDefinitions.select("Id").filter(`RoleTypeKind eq ${roleFilter}`).get().then((def: { Id: number }[]) => {

            if (!Array.isArray(def) || def.length < 1) {
                throw new Error(`Could not locate a role defintion with RoleTypeKind ${roleFilter}`);
            }

            let postBody = {
                emailBody: '',
                includeAnonymousLinkInEmail: false,
                peoplePickerInput: userStr,
                propagateAcl: propagateAcl,
                roleValue: `role:${def[0].Id}`,
                useSimplifiedRoles: true,
                sendEmail: false

            };

            if (typeof emailData !== "undefined") {

                postBody = Util.extend(postBody, {
                    emailBody: emailData.body,
                    emailSubject: typeof emailData.subject !== "undefined" ? "" : emailData.subject,
                    sendEmail: true,
                    includeAnonymousLinkInEmail: requireSignin ,
                });
            }

            return this.clone(QueryableShareable, "shareObject", true).postAs<SharingResult>({
                body: JSON.stringify(postBody),
            });
        });
    }
```

**Comment by patrick-rodgers** [comment]
I haven't had a chance to test this, but do you want to put together a pull request with this change? That way I can easily test and you will get the credit for the fix :) Thanks!

**Comment by simonagren** [comment]
Patrick, I'll make a pull request with some changed code. So you can try it.
I only changed requireSigning to false by default.
In other sharing examples I've seen and by looking at fiddler, it seems to be false (includeAnonymousLinkInEmail)

**Comment by patrick-rodgers** [comment]
Thanks, I'll check it out.

**Comment by patrick-rodgers** [comment]
I merged the PR and did a beta release sp-pnp-js@2.0.7-beta.0 so folks can try this out. Thanks!

**Comment by simonagren** [comment]
Np mate :)
