### ISSUE TITLE
Headers case sensibility for Batch requests

### ISSUE THREAD

**Issue by koltyakov** [SharePoint/PnP-JS-Core#492]
Hi there,

#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Version

2.0.5

#### Expected / Desired Behavior / Question

Headers case insensibility for Batch requests.

#### Observed Behavior

If pnp.setup defines 'accept' header in case different from 'Accept' request fails.

E.g.:

```javascript
pnp.setup({
  headers: {
    accept: 'application/json;odata=nometadata'
  }
});
```

Batch execute follows with error:

```bash
POST https://[...].sharepoint.com/sites/site/_api/$batch 400 (Bad Request)
Uncaught (in promise) Error: Invalid response, line 0
    at new BatchParseException (pnp.js:1408)
    at eval (pnp.js:1187)
    at Promise (<anonymous>)
    at ODataBatch._parseResponse (pnp.js:1169)
    at <anonymous>
``` 

With:

```javascript
pnp.setup({
  headers: {
    Accept: 'application/json;odata=nometadata'
  }
});
```

it works as expected.

But cases, when some defaults can be configured in lower case for 'accept' header are relatively high.

**Comment by patrick-rodgers** [comment]
The header name is "Accept" so "accept" would be incorrect - what would be the proposed fix here?

**Comment by koltyakov** [comment]
I was thinking about converting headers to the same case before merging, somewhere in the middle. At least for Accept and Content-Type.

**Comment by koltyakov** [comment]
But maybe just sticking with 'Accept' is alright. I do not know why, but I often provide it in lower case and it works in most places. For instance, in other cases with PnP JS Core get and post requests but not batches.

**Comment by patrick-rodgers** [comment]
Maybe it is a thing in the code that processes batches specifically. Not sure. I'll have a look, shouldn't be too hard to rewrite that (and maybe just for batches). I am working on getting 2.0.6 released but then will have a look. Thanks!

**Comment by patrick-rodgers** [comment]
WELL...digging into this and it is an issue with batching and how we process the headers there. So what is actually happening is that we are ending up with BOTH accept and Accept being sent to the server. Which breaks things. At least knowing what is really wrong I can work on fixing it. Thanks for bringing this one up!

**Comment by patrick-rodgers** [comment]
Fixed and published in beta sp-pnp-js@2.0.7-beta.1. So you should be able to test this out in your code that was previously throwing the error. I am going to close this, but please _reopen_ if you still have problems. Thanks!

**Comment by dev4201** [comment]
Hi Patrick - I just stumbled on this issue but the fix proposed by @koltyakov  did not work for me.  I have a basic setup, plain site with script webpart where I added pnp.js reference.

**Environment**: SP-2013 OnPrem

 ```
$pnp.setup({
        headers: {
            "Accept": "application/json; odata=verbose"
        }
    });
```
```
 var batch = $pnp.sp.createBatch();

        for (var i = 0, len = 25; i < len; i += 1) {
            $pnp.sp.web.lists.getByTitle(listTitle).items
                .inBatch(batch)
                .add({
                    Title: "RandomString_" + $pnp.util.getRandomString('10')
                })
                .then(r => {
                    console.log('Added new item');
                });
        }

        batch.execute().then(() => {
            console.log('Batch items creation is completed');
        });
```
**Error Received**
> pnp.js:1408 Uncaught (in promise) Error: Invalid response, line 0
>     at new BatchParseException (pnp.js:1408)
>     at pnp.js:1187
>     at Promise (<anonymous>)
>     at ODataBatch._parseResponse (pnp.js:1169)

The setup I have in place works fine for a standard non-batch calls.

**Comment by koltyakov** [comment]
@dev4201, SP 2013 do not support batch API. So it's not the issue.
There is no possibility to use batches in 2013. Promise.all can be used in some scenarios.

**Comment by dev4201** [comment]
Appreciate quick response and clarification!
