### ISSUE TITLE
Returned result for getCatalog

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#493]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [     latest    ]

Stupid question but I'm not sure how to handle the returned result from this method: 

`pnp.sp.site.rootWeb.getCatalog(114).then(console.log)`

It returns a List  which has all this properties but not an array of the templates i'm looking for. I'm trying to get an array of the list templates available. 

![image](https://user-images.githubusercontent.com/5871660/27167753-6e6d61f4-5170-11e7-8869-c2c3ba260a38.png)

**Comment by koltyakov** [comment]
How about:

```javascript
pnp.sp.site.rootWeb.getCatalog(114).then((list: pnp.List) => {
	list.items.get().then(console.log);
});
```

?

**Comment by simkessy** [comment]
Ah okay I see how that works now, thank you. 

But I'm getting an empty array using this in Office 365:

![image](https://user-images.githubusercontent.com/5871660/27186108-583d615a-51b5-11e7-8166-5ebce21e6120.png)

**Comment by koltyakov** [comment]
Are you sure you have at least one list saved as template?

**Comment by simkessy** [comment]
Oh, I'm trying to return a list of the different template types. So like Doc Lib, Custom List, Task List, etc.

**Comment by patrick-rodgers** [comment]
I am not aware of a way to query that. There exists an enum with all those values in the CSOM lib so I think you could code that in as I don't believe it is dynamic.

```
public enum ListTemplateType
	{
		InvalidType = -1,
		NoListTemplate,
		GenericList = 100,
		DocumentLibrary,
		Survey,
		Links,
		Announcements,
		Contacts,
		Events,
		Tasks,
		DiscussionBoard,
		PictureLibrary,
		DataSources,
		WebTemplateCatalog,
		UserInformation,
		WebPartCatalog,
		ListTemplateCatalog,
		XMLForm,
		MasterPageCatalog,
		NoCodeWorkflows,
		WorkflowProcess,
		WebPageLibrary,
		CustomGrid,
		SolutionCatalog,
		NoCodePublic,
		ThemeCatalog,
		DesignCatalog,
		AppDataCatalog,
		DataConnectionLibrary = 130,
		WorkflowHistory = 140,
		GanttTasks = 150,
		HelpLibrary,
		AccessRequest = 160,
		TasksWithTimelineAndHierarchy = 171,
		MaintenanceLogs = 175,
		Meetings = 200,
		Agenda,
		MeetingUser,
		Decision = 204,
		MeetingObjective = 207,
		TextBox = 210,
		ThingsToBring,
		HomePageLibrary,
		Posts = 301,
		Comments,
		Categories,
		Facility = 402,
		Whereabouts,
		CallTrack,
		Circulation,
		Timecard = 420,
		Holidays,
		IMEDic = 499,
		ExternalList = 600,
		MySiteDocumentLibrary = 700,
		IssueTracking = 1100,
		AdminTasks = 1200,
		HealthRules = 1220,
		HealthReports,
		DeveloperSiteDraftApps = 1230,
		AccessApp = 3100,
		AlchemyMobileForm,
		AlchemyApprovalWorkflow,
		SharingLinks = 3300,
		HashtagStore = 3400,
		ItemReferenceCollection = 3500,
		ItemReferenceReference,
		ItemReferenceReferenceCollection
	}
```

**Comment by simkessy** [comment]
How come? 

This is the rest endpoint for it: [`_api/web/listtemplates`](https://msdn.microsoft.com/en-us/library/office/jj245602.aspx)

Could it be included as an enhancement?

**Comment by patrick-rodgers** [comment]
So slightly misunderstood what you were asking. This is already possible, you can then do:

```
pnp.sp.web.select("listtemplates").expand("listtemplates").get()
```
or if you want say just the name:

```
pnp.sp.web.select("listtemplates/name").expand("listtemplates").get()
```

**Comment by simkessy** [comment]
Ah perfect, I thought it was stranger it wouldn't be included. 

Exactly what I was looking for thank you @koltyakov  @patrick-rodgers
