### ISSUE TITLE
[Question] How to handle Document Libraries

### ISSUE THREAD

**Issue by Mustachoman** [SharePoint/PnP-JS-Core#495]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

2.0.5

#### Question

In a project of ours, we would like to use a Document Library instead of a Custom List with attachments.
On the Custom List items we can add custom properties so we can filter on those.

If we get items from the Custom List we can expand the "AttachmentFiles" property so we have those files. This can be done in one request.

With the Document Library however we can't get the attached files as easily, we need to get the Document Library items and the files separately; the two don't seem to be connected.

The way I see it, if we want to CRUD Document Library items we need to maintain 2 items, the file itself and the listitem it comes with.

Do you have any recommendations on how to handle this?

**Comment by patrick-rodgers** [comment]
File has the getItem<T> method and Item has the file property as well as the attachmentFiles property. So likely you'd start with the item, but that is how SharePoint works.

If you can describe what you are actually trying to accomplish (i.e. why do you want to use the above design, what problem are you solving)? Perhaps we can provide some more guidance.

**Comment by russgove** [comment]
i think Mustachoman has a custom list with a lookup column that references documents in a document library.  when yo expand that lookup column you cannot get to the file.
 Mustachoman, if this is the case , i believe you will need to make multiple requests,
first get all items in your custom list, and a separate call to get the documents. Like patrick said, if you can  explain how you lists/library are set up, it would help.

**Comment by Mustachoman** [comment]
@patrick-rodgers What we're trying to do is for users to be able to create documents, things like copies of ID's, certain agreements and diaries. They can have custom properties like "Expire Date" so that their ID can be updated when needed. We've done that now with a Custom List with attachments. However, we can't have document templates with Custom Lists. The users should be able to select a document template so that they can easily create new documents from our SPFX webpart.

The users already work with those templates in a Document Library, so we wanted to be able to keep the same functionality.

@russgove Yeah we thought about that, this question is actually based on the wish to use a Document Library as a way to save documents per user. So that we can keep the templates they are already using.

**Comment by patrick-rodgers** [comment]
I think you have more of a design question than anything to do specifically with the library. We surface the REST api so if there is some capability missing in the library that is present in the api we can look at adding it. I am going to close this but would encourage you to post in the [Microsoft Tech Community for SP Dev](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) as folks might have ideas about your design there. Thanks!
