### ISSUE TITLE
Getting file's metadata after a .copyTo

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/PnP-JS-Core#497]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [  2.0.6 ]

#### Expected / Desired Behavior / Question
I am uploading a file by using `web.getFolderByServerRelativeUrl(folderUrl).files.add(fileUrl, file, false)` and `.then(data)` I am copying that file to another folder like `data.file.copyTo(fileUrl)` which works great.

I am in the need now to update metadata unqiuely for each file, In the initial upload, I am using `data.file.listItemAllFields.get().then(metadata)` to get the associated list item, then updating the data.

When i use `.copyTo` I don't get back the same object, I get back 

`{
  odata.metadata: "https://contoso.sharepoint.com/sites/thesite/_api/$metadata#Edm.Null",
  odata.null: true
}`

Nothing there that identifies the file I just uploaded. I do have the `fileUrl` so I can grab the file like `pnp.sp.web.getFileByServerRelativeUrl(fileUrl).get().then(copiedFile)` which gets the newly copied file, but this returned object doesn't have any marker for me to find the associated list item so I can update the metadata.

First, should copyTo be returning the same payload as if I am uploading fresh?
Secondly, how can I get the associated list item of a file in a library?

Thanks!!

**Comment by patrick-rodgers** [comment]
1) The CopyTo method is void on the server so doesn't return anything. We could synthesis a return value - but I tend to not like to do that so we can match the underlying API as much as possible. Let me think on this, probably wouldn't be too hard to return a File object from CopyTo.

2) The File object has the [getItem<T> method](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Files#getitem) that will retrieve the associated item as well as give you an Item instance from which you could chain.

**Comment by patrick-rodgers** [comment]
Tried this out and the immediate problem is that if you use copyTo (or moveTo) with an absolute URL as the destination there isn't a way to parse out the destination web url to construct the File object to return. If you are using server relative paths then it can work. Which leaves me now wanting to implement the change as the behavior would either introduce a bug I am not sure we could fix, or differ based on absolute/relative urls. For now I think this is best left to the external developer to handle, as they would know what kind of url they are supplying and can adjust appropriately. Thoughts?

**Comment by DavidLozzi** [comment]
`.getItem()` is perfect, thanks!
