### ISSUE TITLE
How can I add/update list item with Lookup field

### ISSUE THREAD

**Issue by MCTAhmad** [SharePoint/PnP-JS-Core#501]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

[2.0.6]

#### Expected / Desired Behavior / Question
I'm trying to add/update list item with "lookup field".
I had tried to insert it as an interface of "ID" and "Title", I also tried to insert the ID only, title only. Also, I had tried as a combination string as "ID;#Title".
Any suggestion how should I manage it?

This is my function in TypeScript:
```
protected _listTitle: string;
protected _web: Web;
protected _list: List;
    private _InitiatePNP(): void {
        this._web = pnp.sp.web;
        this._list = this._web.lists.getByTitle(this._listTitle);
    }

    public AddItemUnTyped(item: any): Promise<any> {
        try {
            
            var listItem = this._list.items.add(item).then((result: ItemAddResult) => {
                return result.data;
            });

            return listItem;
        }
        catch (ex) {
            return null;
        }
    }
```
Thanks!

**Comment by KEMiCZA** [comment]
Hi @MCTAhmad, you need to add Id after your internal name. If you have a lookup field with internal name "Country" and you want to add an item you would do it like this:

``` typescript
pnp.sp.web.lists.getByTitle("Stock").items.add({Title: "Test", CountryId: 1}).then();
```

Note the internalname _Country_**Id**
The value should be the id of them item in the lookup list.

**Comment by MCTAhmad** [comment]
It worked :)

Thank you very much @KEMiCZA !

**Comment by jca38** [comment]
Thanks KEMiCZA,
However what is the syntax for LookupMulti Fields ?
I tried with an array of numbers but it did not work :

**Comment by koltyakov** [comment]
https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#lookup-fields
