### ISSUE TITLE
Getting web.url on modern SharePoint pages

### ISSUE THREAD

**Issue by cwdata** [SharePoint/PnP-JS-Core#502]
#### Category
[X ] Question

#### Version
[ 2.0.6 ]

#### Expected / Desired Behavior / Question
The code 
pnp.sp.web.get().then(web => {
    console.log('Url: ' + web.Url);
});
outputs the current web's URL to the console. On classic pages this is the full URL including the path "/sites/nameofsite".
If I do the same on a modern page (inside a O365 group for example) it logs only the server part of the URL i.e. "https://mytenant.sharepoint.com" without the path to the web.
Is this behavior intended? And if so, is there any other way to get the full URL of the current site on a modern page?

Thanks and regards
  Christian

**Comment by patrick-rodgers** [comment]
If you just need the current web url what you need might be on [the context](https://dev.office.com/sharepoint/reference/spfx/sp-page-context/pagecontext) object (within SPFx).

If not you could try the ServerRelativeUrl property instead. This isn't something we control so it would be SharePoint sending that value back. I haven't personally seen this on modern pages but can try and take a look - though there won't be a "fix" we can provide.

**Comment by cwdata** [comment]
Thanks for the quick response. It works well using the pagecontext in both classic and modern worlds.
