### ISSUE TITLE
How can I set read only fields of folders

### ISSUE THREAD

**Issue by fela98** [SharePoint/PnP-JS-Core#508]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

Hi there,

I recently had a case where I had to copy a OneNote document from one document library to another using JSOM and the pnp library. The thing with OneNote documents is that it essentially is a folder which again contains two other files. In order to make the folder display as a OneNote document I have to set the HTML_x0020_File_x0020_Type field to "OneNote.Notebook". The problem however is that this field is read only which means that it can't be changed after the item has been created. Neither did I find anywhere to supply this when creating the folder which I do using the` Folders.prototype.add(url)` method.

Is there any way I can copy the OneNote document. Is it possible to use the `Items.prototype.add()` method on the document library instead and include the field there?

Thanks in advance!

**Comment by patrick-rodgers** [comment]
By definition read only fields can't be set, I think you are really asking how you can create a new OneNote? There is an entirely separate API for OneNote you can check out [this introductory video](https://channel9.msdn.com/Series/OneNoteDev/Getting-Started-with-the-OneNote-API). I'll take a quick look at setting properties for new folders, but wouldn't count on that.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ if you need additional help. Thanks!
