### ISSUE TITLE
Testing PnP JS Core. webhook

### ISSUE THREAD

**Issue by jquintozamora** [SharePoint/PnP-JS-Core#510]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

I was running "gulp test" but there was one test failing about createSubscription in the Documents list.
I just notice there is a documentation here> https://github.com/SharePoint/PnP-JS-Core/wiki/Testing-Against-SharePoint

But there is a missing configuration>

    testing: {
        clientId: "{ client id }",
        clientSecret: "{ client secret }",
        enableWebTests: true,
        siteUrl: "{ site collection url }",
        notificationUrl: "{ notification url }",
    }

What should we use to mock or provide the proper notificationUrl ? 

Thanks!

**Comment by patrick-rodgers** [comment]
You can setup a simple responder - I wrote about it in [this post](https://blogs.msdn.microsoft.com/patrickrodgers/2017/02/16/travisci-and-sp-pnp-js/) for setting up the testing. Just reviewed it and nothing has really changed so info should all still be good.

**Comment by giuleon** [comment]
There is also a version in javascript (Azure Function) by @johnnliu 
http://johnliu.net/blog/2016/9/working-with-sharepoint-webhooks-with-javascript-using-an-azure-function

**Comment by jquintozamora** [comment]
Thank you both! 
Eventually I used the quick start which actually has "Webhook + API" option.
![image](https://user-images.githubusercontent.com/12530031/27798158-227c402a-6008-11e7-9312-b7814760522c.png)

It worked fine!
