### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#511]
I'm having trouble logging out errors and wondering if I'm doing it the wrong way: 

```
// Remove BA fields from list
projectList.fields.getByTitle(baColumnName).delete().then(function () {
	// Remove SI field from list
	return $pnp.sp.web.lists.getByTitle("Projects").fields.getByTitle(siColumnName).delete()
		.catch((e) => console.log(e.odata.error.message));
}).catch((e) => console.log(e.odata.error.message));
```

I'm trying to catch the error object that the REST call returns but instead I get 

> Error: Error making HttpClient request in queryable: [400] Bad Request
>     at new t (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:22398)
>     at https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:12294
>     at <anonymous>
> From previous event:
>     at t.e.parse (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:11922)
>     at https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:28821
> From previous event:
>     at https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:28788
> From previous event:
>     at Function.e.send (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:28321)
>     at r.value (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:26645)
> From previous event:
>     at r.value (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:26656)
>     at i (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:25939)
>     at Object.a [as pipe] (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:25964)
>     at https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:8451
> From previous event:
>     at t.e.post (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:145:8425)
>     at t.delete (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:148:1875)
>     at Object.v [as deleteGroup] (https://mysite.com/sites/Design/SPDashDev/bundle/spdash.min.js:9:19016)
>     at Object.delete (https://mysite.com/sites/Design/SPDashDev/bundle/spdash.min.js:8:29607)
>     at fn (eval at compile (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:34:26131), <anonymous>:4:271)
>     at t (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:33:838)
>     at o (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:35:13662)
>     at d.$eval (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:33:10749)
>     at d.$apply (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:33:10982)
>     at HTMLButtonElement.<anonymous> (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:35:13714)
>     at HTMLButtonElement.dispatch (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:25:3616)
>     at HTMLButtonElement.m.handle (https://mysite.com/sites/Design/SPDashDev/bundle/bundle.js:25:318)

**Comment by patrick-rodgers** [comment]
Unsure what you are looking for? The error is a Bad Request - if you need to see more details they should all be included. We are throwing a custom error of type "ProcessHttpClientResponseException". Do you not see the full information if you just log the "e" object to the console?

**Comment by simkessy** [comment]
Hi @patrick-rodgers, 

When I log `e` I get the text above but when I inspect the response in Dev Tools, the REST request returns an actual object `odata.error.message` which in this case is "The field could not be found". 

I'm trying to get that error message telling why the request failed. The stuff above `Error making HttpClient request in queryable: [400] Bad Request` is not has useful as the actualy REST response.

**Comment by patrick-rodgers** [comment]
I guess that is the underlying Error's toString being called. What if you log e.data? That should give you the information, or more specifically e.data.responseBody.

**Comment by simkessy** [comment]
Ah okay I see how to get it now. The error message can be reached like this: `e.data.responseBody['odata.error'].message.value`

Thanks for the help.
