### ISSUE TITLE
Trying to update Group Owner

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#512]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [    latest    ]

#### Expected / Desired Behavior / Question

I'm trying to update the Owner of a SP Group. This is what I've tried: 

```
import pnp from "pnp";

let newgroup = {};
pnp.sp.web.siteGroups.getByName("BA_Actuarial").get().then(function(g) {
	newgroup = g
})

let group  = pnp.sp.web.siteGroups.getByName("BA_SargonTest").expand("owner")

group.get().then(data => {
	console.log(data, newgroup)
	group.update({
		Owner: newgroup
	})
})
```

**Comment by koltyakov** [comment]
Hi @simkessy,

As far as I know, REST API has this bug which makes it impossible to write to group's owner property.
At least I tried a couple of different combination and didn't find a way.
But it should work in JSOM.

**Comment by simkessy** [comment]
Ah okay good to know, I can stop looking into it than. Cheers.
