### ISSUE TITLE
"temp.headers.forEach is not a function" in FF 46.0

### ISSUE THREAD

**Issue by forgetalex** [SharePoint/PnP-JS-Core#513]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
[2.0.6]

#### Observed Behavior
When using the library with Firefox 46.0 following error is thrown: "temp.headers.forEach is not a function" in line 5299 of pnp.js stopping it from working.

#### Steps to Reproduce
A standard list query like this: 

$pnp.sp.web.lists.getByTitle("My List").items.get().then((items) => {
    console.log(items);
});

should already throw the error.

**Comment by patrick-rodgers** [comment]
You can polyfill it as below:

```JavaScript
  Headers.prototype.forEach = function(callback) {
    var self = this
    Object.getOwnPropertyNames(this.map).forEach(function(name) {
      callback(name, self.map[name])
    })
  }
```

Will have to take a look at this - everyone else supports forEach so not sure this is a bug with us as much as a different API surface for Firefox. Thanks for reporting it.

**Comment by forgetalex** [comment]
Hey thanks for the help but even after polyfilling it I get another error:
"TypeError: can't convert undefined to object"

**Comment by patrick-rodgers** [comment]
OK, thanks. Let me look at that line and see if I can rework it to not use the forEach at all.

**Comment by patrick-rodgers** [comment]
In testing this the version of FF I have (50) supports the forEach method for headers. Is there something forcing you to an older version of FF? I am not compelled to rewrite this for a browser with very low overall usage (FF.46). Help me understand your case and perhaps we can work out a better polyfill. Or is this a case where you have a set of automated tests that covers FF 46 and those tests are failing?

My recommendation would be to update FF if possible.

**Comment by forgetalex** [comment]
If the newest FF version supports forEach for headers, its good enough for me. Thank you very much for the help.

**Comment by patrick-rodgers** [comment]
Ok, sounds good. If you continue to see issues please let us know, certainly not looking to block FF or any browser. Thanks!
