### ISSUE TITLE
Accessing Items sith PnP on SP online

### ISSUE THREAD

**Issue by suoko** [SharePoint/PnP-JS-Core#514]
Hi,

I tried installing your library on SP online downloading it from https://github.com/OfficeDev/PnP-JS-Core/blob/master/dist/pnp.js

I can get a subsite title, I can add items to a list but I'm not able to get the list items, I always get an "undefined" error.
I'm testing the following code:

$pnp.sp.web.lists.getByTitle("testlist").items.getById(3).get().then(function(list) {
   alert(list.items);  
});   

I'm sure the item with ID=3 is there:
/Lists/testlist/DispForm.aspx?ID=3

Am I missing a second library ? Is it working with SP online ?

**Comment by koltyakov** [comment]
Hi @suoko,

The library is based on ES6 Promises and Fetch client.
To make it work in IE [Polyfill](https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Install-&-Use#polyfill) should be used.

But you just faced an error in your code. Please check in the following way:

```javascript
$pnp.sp.web.lists.getByTitle("testlist").items.getById(3).get().then(function(item) {
   alert(item);
});
```

**Comment by suoko** [comment]
Hi,

thanks a lot for the fix. 
I can access items now easily.
Just checked with alert(item.Title) and it works great.

+1 for this project !

**Comment by patrick-rodgers** [comment]
Thanks @suoko & @koltyakov - going to close this as it appears answered, please do _re open_ the issue if needed.
