### ISSUE TITLE
pnp.util.dateAdd() doesn't obey local date format

### ISSUE THREAD

**Issue by LarterStyles** [SharePoint/PnP-JS-Core#515]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version
2.0.5

#### Expected / Desired Behavior / Question
Current time is **4 July 2017 12:00:00**

`$pnp.util.dateAdd(new Date(), 'hour', 1);` should yield **4 July  2017 13:00:00**, but...

#### Observed Behavior
`$pnp.util.dateAdd(new Date(), 'hour', 1);` actually yeilds **7 April  2017 13:00:00**

It seems the Australian date format **DD/MM/YYYY** format is being incorrectly interpreted as **MM/DD/YYYY** (i.e. today's date is represented locally as 04/07/2017, but is being interpreted as 07/04/2017).
 
![image](https://user-images.githubusercontent.com/2833830/27803180-c8845cda-605a-11e7-9625-9fd56b67f1a9.png)

#### Steps to Reproduce
I can repro this in Edge by simply typing the line of code above into the console.

**Comment by patrick-rodgers** [comment]
Can you suggest a fix? I don't often deal in Australian dates [but the code](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/utils/util.ts#L78) is using toLocalString which was added a while back to fix someone else's local date issue. This function came from [here](http://stackoverflow.com/questions/1197928/how-to-add-30-minutes-to-a-javascript-date-object), so open to other options. We could go back to not having the toLocalString - but I'd have to find the previous issue and ensure we don't rebreak that.

**Comment by LarterStyles** [comment]
Removing toLocaleString() appears to fix the issue, as the Date objects are allowed to just _do their thing_ using the browser's locale:

![image](https://user-images.githubusercontent.com/2833830/27804395-48c58cec-6061-11e7-9b0d-b431101af10d.png)

Are you able to dig up the reason why the date was converted into a string representation in the first place?

**Comment by patrick-rodgers** [comment]
I went ahead and made this change in #516 - if you get a chance grab it and verify latest. I will close this issue, please _reopen_ if it is not fixed. Thanks!
