### ISSUE TITLE
Unable to parse URL from '' when using within a Web Worker

### ISSUE THREAD

**Issue by Oceanswave** [SharePoint/PnP-JS-Core#518]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.6]

#### Expected / Desired Behavior / Question
When using sp-pnp-js within a web worker an error occurs when attempting to the most basic of operations.

#### Observed Behavior
Error: Failed to construct 'Request': Failed to parse URL from at HttpClient.mergeHeaders (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:5298:24) at HttpClient.fetchRaw (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:5243:14) at HttpClient.fetch (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:5236:21) at https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:9174:24 at Promise (<anonymous>) at Function.PipelineMethods.send (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:9158:16) at descriptor.value (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:9095:27) at next (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:9055:30) at https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.js:9095:76 From previous event

#### Steps to Reproduce
1. Create a page that creates a web worker.
2. Within the web worker, include the sp-pnp-js library.
3. attempt to perform an action such as:

``` javascript
let w = new Web("https://mytenant.sharepoint.com");
let webData = await w.get();
```

**Comment by patrick-rodgers** [comment]
Can you share any other information? Such as browser/version - other code? There shouldn't be anything special required for web workers and I know others use the library with them. The only thing I see is that we create a Request with an empty url to use to merge the headers - so perhaps that is not allowed in your case?

**Comment by Oceanswave** [comment]
Trying to build a simple repro but it's Google Chrome: Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by Oceanswave** [comment]
If I monkeypatch Request using the following:

``` javascript
let __nativeRequest = Request;
Request = function(input, init) {
    if (!input) {
        input = location.origin;
    }

    return new __nativeRequest(input, init);
}
```

everything becomes happy.

Thanks, and closing.

**Comment by patrick-rodgers** [comment]
Great, glad to hear you got it working and for letting us know. Hope you enjoy using the library! Thanks!
