### ISSUE TITLE
Error: Error making HttpClient [400] Bad Request Batching

### ISSUE THREAD

**Issue by Ragnarok99** [SharePoint/PnP-JS-Core#521]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [  "sp-pnp-js": "^2.0.6"  ]

#### Expected / Desired Behavior / Question
Hi, i'm trying to save data in a list using **batch** in my SPFx webpart, I'm using the example provided in the docs like so:

```
let batch = pnp.sp.createBatch();

pnp.sp.web.lists.getByTitle("Test").items.inBatch(batch).add({
    Title: "My Item Title 2"
}).then(r => {
    console.log(r)
});
batch.execute().then(() => console.log("All done!"));
```
And I get 

> exceptions.js:24 Uncaught (in promise) Error: Error making HttpClient request in queryable: [400] Bad Request

I wonder if am I doing something wrong.

Thanks!

**Comment by patrick-rodgers** [comment]
Did you setup the spfxContext as [shown here](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework#establish-context)? That is the most likely issue. Other things to check are that the list "Test" exists. Please check those things and let us know. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this as inactive - if you are still stuck please _reopen_ and we'll do our best to help. Thanks!
