### ISSUE TITLE
SP PnP JS REST requests are not working on modern pages.

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/PnP-JS-Core#522]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [^2.0.6]

#### Expected / Desired Behavior / Question
SP PnP JS REST requests work on modern pages
#### Observed Behavior
SP PnP JS REST requests are not working on modern pages.

code snippet:
```
pnp.sp.web.get().then((web: any) => { console.log(web); });
```

Console output: GET https://contoso.sharepoint.com/SitePages/_api/web 404 (Not Found)
The URL contains /SitePages that shouldn't be included.

#### Steps to Reproduce

- Go to SharePoint site
- Create or open a modern page
- Run the SP PnP JS request on the page

Let me know if you want me to create sample client-side web part example for the issue.

**Comment by KEMiCZA** [comment]
If you're using SharePoint Framework check out this wiki: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

**Comment by patrick-rodgers** [comment]
Did @KEMiCZA 's answer get you sorted?

**Comment by AJIXuMuK** [comment]
@patrick-rodgers totally!
@KEMiCZA thanks a lot for the link. My bad - I've missed the article.
