### ISSUE TITLE
.filter() not working on Custom Yes/No Column

### ISSUE THREAD

**Issue by kmartindale** [SharePoint/PnP-JS-Core#523]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 2.0.6

#### Expected / Desired Behavior / Question
When adding .filter() should return results the same as the api end point

#### Observed Behavior
When running: 
return pnp.sp.web.lists.getByTitle('Pages').items.filter('Display_x0020_in_x0020_Navigation eq true').get().then((items: any) => {
          console.log(items);
          return items;
      }) as Promise<IListItems>;

and Display_x0020_in_x0020_Navigation is a custom Yes/No column (appears to work for a custom Number field) the filter is not returning anything. When I hit the API endpoint directly with the filter param in the url, I get the expected results.

.filter('Display_x0020_in_x0020_Navigation eq null') appears to return expected results but not false or true

#### Steps to Reproduce
Create a new list column that is a Yes/No
Run a filter on the list with the new column

Any help would be greatly appreciated. Thanks!

**Comment by patrick-rodgers** [comment]
I think you want to use 1 or 0 to filter on yes/no columns. That works for me in testing. Can you give that a shot?

**Comment by kmartindale** [comment]
Well that looks like magic to me! Is that documented anywhere? Kind of confusing that the api url takes true or 1 but the lib only takes 1. 

Regardless thank you for the quick response! That saved me lots of time.

**Comment by patrick-rodgers** [comment]
We don't do anything to limit things in the library - I thought that is how REST always behaved. We just send the request as built. If you see a difference in what we send vs what you say works please let me know certainly don't want to block anything from working.
