### ISSUE TITLE
Error uploading large files

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/PnP-JS-Core#530]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  2.0.6   ]

#### Expected / Desired Behavior / Question
I am uploading files using the following, when a file is over 5MB. 

```
web.getFolderByServerRelativeUrl(uploadTo.folderUrl).files.addChunked(uploadTo.fileUrl, file, data => {
            moveProgress(statusWrapper);
          }, false, this.UPLOADCHUNKSIZE)
            .then(data => {
              copyFile(data, statusWrapper, file.name);
              setFileSPMetadata(data, statusWrapper, firstUpload, uploadTo);
            })
            .catch(data => { 
              uploadError(data, statusWrapper);});
```
Arbitrarily, this will error when uploading larger files, like ~2GB+. My client is dependent on SP's ability to host up to 10GB files. I have uploaded a 2GB file and a 4GB file about 2-3 times each, and I got it to error once. 

The error I get is super a generic 400 error, and I dug in deeper up the call stack to find more details, but I can't get the good stuff out of it.

Screenshots below, here are some **questions**

1. It appears random and probably has to do with a random process, internet connection blip, etc. Is there a way to continue the upload in the event this errors?
2. Can we get more error information out of this to understand why it's happening?
3. My catch above never catches, the error itself occurs and the .catch does nothing

Screen shots
**Where the error is being reported**
![image](https://user-images.githubusercontent.com/3543383/28077996-60049a9e-6631-11e7-8707-0c5864f3b974.png)
_Note the console log for the actual error we're getting_

**Up the callstack**
![image](https://user-images.githubusercontent.com/3543383/28078028-798dabc2-6631-11e7-9938-8f8fb2be51e8.png)
_still unhelpful except maybe for the < in JSON note?_

**Network**
![image](https://user-images.githubusercontent.com/3543383/28078062-9a13f4aa-6631-11e7-8a9a-9623675ccc3d.png)
_Note it was running great for some time, then NOPE. This example ran over an hour before it died._

**Comment by patrick-rodgers** [comment]
You might be running into is the [2GB limit](https://dev.office.com/sharepoint/docs/sp-add-ins/working-with-folders-and-files-with-rest) for the rest interface. Which seems to match our experience as you say above you see this with files over 2GB.

You can get more information by using the [logging framework](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Logging#subscribing-a-listener). If you are uploading very large files and it is working, then occasionally failing it may just be timeouts or other issues. The 404 listed is strange to see.

If you are running hours long uploads in browser it might work better to try the sync client (i.e. sync the library locally and paste files in and let that handle the upload).

I will take a look to see if we are swallowing the exception that is preventing the catch from working.

**Comment by DavidLozzi** [comment]
Hmm so my 4GB tests have worked, the file gets uploaded as expected. Tried 3.5GB as well, works most times. If there is a 2GB limit, how is it enforced?

I'll check out the logging framework.

**Comment by patrick-rodgers** [comment]
I don't know how it is enforced at the code level, but that is the published limit. I checked with some folks and that guidance is still correct. It might be that if things take too long the temp file is dropped (hence you getting a 404 error in your screenshot) but that is 100% a guess on my part.

**Comment by DavidLozzi** [comment]
Running logging now...

Question, the 2GB limit looks like a limitation on a single request, using `/add`, I don't see reference on that page to the `/continueUpload` api like the pnp library is using:

https://tenant.sharepoint.com/sites/sitename/_api/web/getFolderByServerRelativeUrl('pathtofolder')/files('pathtofile')/**continueUpload**(uploadId=guid'aguid',fileOffset=613416960)

Other pages hint to _unlimited_ https://github.com/SharePoint/PnP/tree/dev/Samples/Core.LargeFileUpload#what-upload-method-to-use

**Comment by DavidLozzi** [comment]
Got the response from the failed call, not helpful but I think i'd post it

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Request Error</title>
    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p>The server encountered an error processing the request. See server logs for more details.</p>
    </div>
  </body>
</html>
```

**Comment by DavidLozzi** [comment]
Microsoft Support confirmed the 2GB/4GB limit. said 4gb "worse case" but should expect 2GB..... rethinking our approach now. Thanks!
