### ISSUE TITLE
Using join query 2 lists

### ISSUE THREAD

**Issue by JackHu88** [SharePoint/PnP-JS-Core#531]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Expected / Desired Behavior / Question
I have 2 lists, the first one named "List1" have 2 columns, ProjectTitle, ChargeCode.
The second list named "List2", have 2 cloumns, PRNo,Code(lookuped the ChargeCode in List1 ),
I want use the "join" to query the fields in the 2 lists.

#### Observed Behavior
I using the code below, but the ProjectTitle didn't return, only returned PRNo.
```
var camlQuery={ 
    	ViewXml: '<View>\
  <ViewFields>\
   <FieldRef Name="ProjectTitle"/><FieldRef Name="PRNo"/>\
  </ViewFields>\
  <ProjectedFields>\
   <Field Name="ProjectTitle" Type="Lookup" List="List1" ShowField="ProjectTitle" />\
  </ProjectedFields>\
  <Joins>\
   <Join Type="Left" ListAlias="List1">\
    <Eq>\
     <FieldRef Name="Code" RefType="ID" />\
     <FieldRef List="List1" Name="ID" />\
    </Eq>\
   </Join>\
  </Joins>\
  <Query>\
   <OrderBy>\
    <FieldRef Name="Modified" />\
   </OrderBy>\
  </Query>\
</View>'
    };   
    $pnp.sp.web.lists.getByTitle("List2").getItemsByCAMLQuery(camlQuery).then(function (listitems) {
    	console.log(listitems);
    });
```

**Comment by patrick-rodgers** [comment]
Based on [this article](https://msdn.microsoft.com/en-us/library/office/ee539975(v=office.14).aspx) you might need to add a projected field to include it?

Since this isn't a question specifically about the library it might in the future be better asked in [the tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev).

**Comment by JackHu88** [comment]
Thanks

**Comment by swapnilphatale** [comment]
I am still not able to get Projected Fields. Any suggestions?
