### ISSUE TITLE
Get only libraries and not lists?

### ISSUE THREAD

**Issue by levalencia** [SharePoint/PnP-JS-Core#532]
Hello

Is it possible to get only libraries and not all site lists? If so, which method should I use?

#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

**Comment by joelfmrodrigues** [comment]
You can simply filter lists by BaseTemplate and Hidden properties. For example, something like this:
......filter('BaseTemplate eq 101 and Hidden eq false').get()

**Comment by patrick-rodgers** [comment]
Yep, what @joelfmrodrigues said - no difference from normal REST api.

**Comment by patrick-rodgers** [comment]
Closing this as answered. Please _reopen_ if you need further assistance. Thanks!
