### ISSUE TITLE
URL is too long using file.copyTo - help to change

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/PnP-JS-Core#533]
#### Category
[x] Enhancement

[x] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [  2.0.6  ]

#### Expected / Desired Behavior / Question

**Bug**
I am trying to copy a file using file.copyTo but the URL is too long (476 chars), here's the REST that is called
```
https://tenant.sharepoint.com/sites/site-name-test/_api/web/getFolderByServerRelativeUrl('/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final')/files('/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final/Working%20On%20It%20Large_20170712AB.gif')/copyTo(strnewurl='/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final/Working%20On%20It%20Large_20170712YZ.gif',boverwrite=true)
```
_yes, this is all fake data, we're not really copying in the same folder_

The "fix" is to use parameters in the REST URL, where the URL is now only 147 chars:
```
https://tenant.sharepoint.com/sites/site-name-test/_api/web/getFolderByServerRelativeUrl(@fldr)/files(@fle)/copyTo(strnewurl=@new,boverwrite=true)?@fldr='/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final'&@fle='/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final/Working%20On%20It%20Large_20170712AB.gif'&@new='/sites/site-name-test/documents/Kennedy,%20Fitzgerald%20Francis/Correspondences/Final/Working%20On%20It%20Large_20170712YZ.gif'
```

**Enhancement**
To fix it, I'd like to update the project to utilize this but not 100% sure where/how to do it. I found the copyTo code and changed it to
```
 public copyTo(url: string, shouldOverWrite = true): Promise<void> {
        return this.clone(File, `copyTo(strnewurl=@cnu,boverwrite=${shouldOverWrite})?@cnu='${url}'`, true).postCore();
    }
```
adding the `cnu` param. 

**Question**
I think this should be done on the file and folder level too, but unsure how the final REST is concatenated as I think making the same change in other places might do something odd like `/file(@file)?@file=thefile/@copyTo(strnewurl=@cnu)?@cnu=thenewurl`

So, for the **short term**, I'd like just to update the copyTo as that'll shorten this URL significantly. How do I test this PnP-JS-Core project in my project to confirm this approach works?

**Long term**, I'd be up for applying a better fix across for files/folders, but I have a feeling this will be a bigger change, and will need some guidance from one of the original contributors.

**Comment by patrick-rodgers** [comment]
This is already done, would encourage you to visit [the developers guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide), in this case specifically the section on [parameter aliasing](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Aliased-Parameters).

To test changes in your own project you can pull down this library, make your changes locally, and do an npm install from the file system:

```
npm install file://c:/my/path/to/project/root
```

**Comment by DavidLozzi** [comment]
GENIUS! Thank you on both counts!!!
