### ISSUE TITLE
Generic method for calling other SharePoint endpoints

### ISSUE THREAD

**Issue by halshing** [SharePoint/PnP-JS-Core#536]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  2.0.6  ]

#### Expected / Desired Behavior / Question
I'm using the Fabric UI People Picker component in my application and I need to wire it up as a People Picker control so users can search for a person by their name, email, login, etc. I'd like to use the REST endpoint _api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser to get the data to use in my people picker, however this endpoint doesn't exist (yet!) in the PnP JS Core library. I know I can use jQuery to get this working, but I am already using PnP JS Core for everything else and I'd rather not use two different libraries to develop against the SharePoint REST API.

While I understand you may not want to include all endpoints as part of the library, but it would be great to have a generic method where I can call whatever endpoint I want directly and have the data returned.

Something like:

```javascript
pnp.executeEndPoint(endpoint, data).then(function (result) { console.log(result); });
// Example: pnp.executeEndPoint("SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser", { QueryString: "john doe" }).then(function (result) { console.log(result); });
```

This way, we can still utilize the other endpoints available without you guys having to add all of them to the library.

Thanks!

**Comment by koltyakov** [comment]
Hi @halshing,

I would recommend using Fetch client rather than adding jQuery dependency (for ajax only purposes) for temporary missed REST endpoints.
PnP JS Core is based on Fetch. Fetch is a native feature for modern browsers, for IE polyfills are used. But, anyway, these polyfills are mandatory for sp-pnp-js too. So if you have PnP JS Core dependency you can bravely use fetch client for requests without any other dependency.

**Comment by koltyakov** [comment]
And the sample:

```javascript
var searchString = 'andrew';
var endpointUrl = `${_spPageContextInfo.webServerRelativeUrl}/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`.replace(/\/\//g, '/');

fetch(endpointUrl, {
    method: 'POST',
    credentials: 'same-origin',
    headers: {
      'Accept': `application/json; odata=verbose`,
      'Content-Type': `application/json; odata=verbose`,
      'X-RequestDigest': document.getElementById('__REQUESTDIGEST').value
    },
    body: JSON.stringify({
        queryParams: {
            __metadata: {
                type: 'SP.UI.ApplicationPages.ClientPeoplePickerQueryParameters'
            },
            AllowEmailAddresses: true,
            AllowMultipleEntities: false,
            AllUrlZones: false,
            MaximumEntitySuggestions: 50,
            PrincipalSource: 15,
            PrincipalType: 15,
            QueryString: searchString,
        }
    })
})
    .then(response => response.json())
    .then(data => {
        console.log(data);
    });
```

**Comment by russgove** [comment]
why not just use the pnp search function?

On Wed, Jul 19, 2017 at 10:56 AM, Andrew Koltyakov <notifications@github.com

**Comment by patrick-rodgers** [comment]
You can do what @koltyakov said, or use search as suggested by @russgove, or you can also take a look at the [resolvePrincipal](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-SP.Utilities.Utility#resolveprincipal) or [searchPrincipals](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-SP.Utilities.Utility#searchprincipals) methods. You could also import the [HttpClient](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/net/httpclient.ts) and use its fetch method to gain the benefits of retry and setup of the digest.

**Comment by halshing** [comment]
Great, thank you all for the feedback! @koltyakov suggestion lead me to the HttpClient which I ended up using. Thanks again.
