### ISSUE TITLE
Format for webs.add additionalSettings parameter - Inherit Navigation

### ISSUE THREAD

**Issue by hankanman** [SharePoint/PnP-JS-Core#537]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [2.0.7]

#### Expected / Desired Behavior / Question
There is a lack of documentation for creating a new web with the api, i have been able to create the web but there is no documentation for how the additionalSettings parameter should be filled. Essentially i need to set the navigation of the created web to inherit from its parent web on creation.

Thanks!

**Comment by patrick-rodgers** [comment]
There isn't a setting in the web properties that controls that, you can see [this thread](https://sharepoint.stackexchange.com/questions/104715/configure-navigation-inheritance-when-create-site-with-rest-api) for details. You need to setup the UseShared property of the navigation object - but we don't have an update method currently on the Navigation object, so I am marking this as an enhancement and will look to get it added in for the next release.

You can check out the [docs here](https://msdn.microsoft.com/en-us/library/office/dn499819.aspx#bk_WebProperties) that list the properties. Generally anything marked read/write you can pass in the additional settings. I don't think we'll ever duplicate all the REST documentation here in this project, nor would that be appropriate.

**Comment by hankanman** [comment]
Hi Patrick, thanks for that, so the best way is just to run it through ajax?

Also the second part of my query is how you use the additionalSettings parameter?

Finally there isn't any documentation for creating a web, i can see it from intellisense but would be good to have this in docs explaining the parameters

**Comment by patrick-rodgers** [comment]
I've added a [section on creating a web](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#add-a-web) to the wiki. After investigating there is not currently a way to update UseShared with REST - so you'd need to use CSOM for that. I am going to close this as I think we've answered the questions, but please _reopen_ the issue should you need to continue the conversation. Thanks!
