### ISSUE TITLE
Folder creation not invalidating cache for related ListItem

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#538]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.7]

#### Expected / Desired Behavior / Question
HTTP Caching interferes with folder creation and item updates providing the old values of the associated list item. Cache should be invalidated for item related to folder when creating a folder.

#### Observed Behavior
We're getting old values for the list item associated to a folder we just created when creating a folder with the same path as one previously created and deleted.

#### Steps to Reproduce
create a folder with this kind of code
```
pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME).rootFolder.folders.add(agendaitem.topic)
            .then((data) => {
                // tslint:disable-next-line:no-console
                console.log(data);
                return data;
            }).catch((err) => {
                // tslint:disable-next-line:no-console
                console.log(err);
                return undefined;
            });
```
delete the folder manually. and create it again using the same code.
Let's say we now want to update the folder's metadata with the following code (providing the same path/name is really important in that context)
```
pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME).rootFolder.folders.getByName(agendaitem.topic).getItem().then((item: any) => {
                // see if we got something
                console.log(item);
                pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME).items.getById(item.Id).update({
                    ContentTypeId: this.CT_AGENDATOPIC_NAME_ID,
                }).then((i) => {
                    console.log(i);
                });
            });
```
Then we're getting this error message: ![pnpiissue2](https://user-images.githubusercontent.com/7905502/28585765-5327e7ea-713f-11e7-908f-9ed8e86af7cc.png)
That's because the underneath request for the list item returns a 304 when it should return actual data.
![pnpissue](https://user-images.githubusercontent.com/7905502/28585826-9639bbee-713f-11e7-9596-dd5d6dbeb07b.png)
The reason behind that is because the If-Not-Modified request header is set when it should not, my interpretation is that there's a cache invalidation missing on folder's creation in pnp-js-core.
We also tried to add that to make sure caching was disabled
```
pnp.setup({
                defaultCachingStore: 'session',
                defaultCachingTimeoutSeconds: 30,
                globalCacheDisable: true,
            });
```
Test was run under Chrome on Windows

**Comment by patrick-rodgers** [comment]
There is a bit of confusion - the globalCacheDisable and other settings are related to the usingCaching method and do not impact anything with Http browser caching.

We do not do anything, by design, with http caching - and the headers you are referring to are added by the browser, not the library. I would suggest that you use the new "configure" method to set the cache option for that particular request. This might solve your issue.

```TypeScript
pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME).rootFolder.folders.getByName(agendaitem.topic).configure({
    cache: "no-cache",
}).getItem().then((item: any) => {
    // see if we got something
    console.log(item);
    pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME).items.getById(item.Id).update({
        ContentTypeId: this.CT_AGENDATOPIC_NAME_ID,
    }).then((i) => {
        console.log(i);
    });
});
```

HTH

**Comment by baywet** [comment]
Thanks for the quick reply @patrick-rodgers when implementing the following code, it builds fine, however we're getting the following error at runtime `Uncaught (in promise) TypeError: pnp.sp.web.lists.getByTitle(...).rootFolder.folders.getByName(...).configure is not a function`

**Comment by patrick-rodgers** [comment]
Just to double check you are on 2.0.7? I'll have to have a look, it is new so I might have pasted incorrect code.

**Comment by baywet** [comment]
Yes we are on 2.0.7, thanks for your help

**Comment by s-KaiNet** [comment]
@baywet How do you install pnp-js into your project? Using bower or npm?

**Comment by baywet** [comment]
npm. And our pipeline is using webpack, the library is referenced as an external.

**Comment by s-KaiNet** [comment]
That's strange, below code
```javascript
pnp.sp.web.lists.getByTitle(this.AGENDA_LIST_NAME)
.rootFolder.folders.getByName(agendaitem.topic).configure({
    cache: "no-cache",
}).getItem().then()....
```
works fine for me.

**Comment by s-KaiNet** [comment]
Can you please open `[your project folder]/node_modules/sp-pnp-js/package.json` and make sure you have `"_id": "sp-pnp-js@2.0.7"` version?

**Comment by baywet** [comment]
Investigating on our end we found we had a deployment issue that we fixed.
Re-running the tests with the code provided by @patrick-rodgers we're not getting a JS runtime error anymore but the configuration nocache seems to have no effect on the request if you look at the request headers.
![pnpissue3](https://user-images.githubusercontent.com/7905502/28675700-9a9eec2c-72b6-11e7-85c0-fd6dd5ea7a10.png)

**Comment by patrick-rodgers** [comment]
What browser are you using? And are you polyfilling fetch?

You could also try and pass the cache control headers through configure and see if that triggers the correct behavior.

**Comment by baywet** [comment]
Chrome on windows 10 Version 59.0.3071.115 (Official Build) (64-bit) 
We're using 'core-js', 'whatwg-fetch' for polyfills/shims (no babel or so in the pipeline).
What headers do you want us to try in the configuration specifically?
Thanks for your time.

**Comment by patrick-rodgers** [comment]
You can try the Cache-Control: 'no-cache' header, but it might be ignored by the browser. This isn't something we control within the library. Perhaps you can add a delay into your code when deleting and recreating a folder with the same path? It seems like an uncommon operation and I am not sure we have a remedy to offer.

**Comment by baywet** [comment]
Thanks for the reply @patrick-rodgers and sorry for the delay, summer time :)
It works with the latest suggestion you made, thanks.
