### ISSUE TITLE
export File and Files objects to inherit 

### ISSUE THREAD

**Issue by jquintozamora** [SharePoint/PnP-JS-Core#542]
#### Category
[ x] Enhancement
[ ] Bug
[x ] Question

#### Version
Please specify what version of the library you are using: [    2.0.7     ]

#### Question
I'm wondering if it's possible to export "File" and "Files" objects in order inherit them.
https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/index.ts#L13-L20

**Comment by patrick-rodgers** [comment]
Sure, that's easy.

**Comment by patrick-rodgers** [comment]
Done and merged in #550. Thanks!
