### ISSUE TITLE
Add a document set to a document library

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/PnP-JS-Core#544]
#### Category
- [ ] Enhancement

- [ ] Bug

- [x] Question

I'm trying to add a document set to a document library, according to this I could be done:
http://sureshannamalai.blogspot.nl/2012/06/add-document-set-using-managed-client.html

I cannot figure out how I could achieve this using the PnP-JS-Core. Any help would be greatly appreciated.

**Comment by patrick-rodgers** [comment]
Unfortunately there isn't a reliable way to do this via SP REST. There is a document set API and you can also see [this issue](https://github.com/SharePoint/PnP-JS-Core/issues/332)

You can also have a look at [this thread](https://sharepoint.stackexchange.com/questions/114882/is-it-possible-to-create-a-document-set-using-rest-api) and [this thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/843245e1-163a-4175-a146-501f95d9b1ff/document-set-creation-in-document-library-using-rest-api-in-sharepoint-2013?forum=sharepointdevelopment)

**Comment by RoelVB** [comment]
Thanks your for the feedback.

We've created a workaround using a workflow. So we create a listitem, which triggers a workflow that creates the documentset. Not pretty, but it works.
