### ISSUE TITLE
Accents in file names causing error when using Batch operations 

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#549]
#### Category
[ ] Enhancement

[X ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [    2.0.7     ]

#### Observed Behavior

I am getting this error when trying to run batch operations with files that contains accents

```
--batchresponse_cb51e97f-d33b-485b-a50e-7296b98cd44d
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

{"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The expression \"web/getFileByServerRelativeUrl('/grants/1/Appjlapp1/Documents/E\" is not valid."},"innererror":{"message":"The expression \"web/getFileByServerRelativeUrl('/grants/1/Appjlapp1/Documents/E\" is not valid.","type":"Microsoft.SharePoint.Client.InvalidClientQueryException","stacktrace":"   at Microsoft.SharePoint.Client.Rest.EdmExpressionParser.Expect(Tokens tokType)\r\n   at Microsoft.SharePoint.Client.Rest.EdmExpressionParser.ParseIdentifier(Boolean allowMethodCall, EdmParserNode& node)\r\n   at Microsoft.SharePoint.Client.Rest.EdmExpressionParser.ParsePath()\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPath(Boolean mainRequestPath, String path, String pathForErrorMessage)\r\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.Process()\r\n   at Microsoft.SharePoint.Client.Rest.RestBatchRequestProcessor.ProcessOneOperation(ODataBatchOperationRequestMessage requestMessage, ODataBatchOperationResponseMessage responseMessage, Int32 batchItemIndex)"}}}
--batchresponse_cb51e97f-d33b-485b-a50e-7296b98cd44d--

```

![image](https://user-images.githubusercontent.com/5871660/28841898-b65dfcc0-76c9-11e7-8b56-7a1cdca3806a.png)

**Comment by patrick-rodgers** [comment]
What is the urlencoded character for the accent you are using? "%27"?

**Comment by simkessy** [comment]
Not sure, the value is "é" but I'd need to ensure all accents can be handled.

**Comment by patrick-rodgers** [comment]
In the past we have not handled encoding special chars within the library as there are so many possibilities. Is it possible for you to encode it before passing it into the function? That way you fully control what is sent vs something we might encode and then we would end up chasing bugs from folks because we encode it differently then they might want.

Asked a different way, how would you encode it using REST without this library?

**Comment by patrick-rodgers** [comment]
Going to close this as won't fix. Previously we have stated it is the callers responsibility to properly encode strings and I want to stick with that. There are too many character sets in the world for us to internalize that logic. Solution here is to encode the string as you would like it encoded before passing into the library - that also allows the caller full control of the string that is sent. For example in Kanji.
