### ISSUE TITLE
Cannot insert List item, with 400 Bad request as response

### ISSUE THREAD

**Issue by pchc2005** [SharePoint/PnP-JS-Core#551]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [2.0.7]

#### Expected / Desired Behavior / Question
I can't insert items to the list in my Sharepoint site. 

The structure of my list is:
- Site name -> String
- Site link -> String
- Site owner(s) -> User
- Purpose -> String

Below is the request body.
```
{
    "_x007a_ak5": "test",     //siteName
    "kx2b": "test",     // siteLink
    "Site_x0020_OwnerId": {
        "results": [9, 11]
    }, 
    "s8c5": "test"     // purpose
}
```

The expected result obviously is that the list item is successfully inserted.

#### Observed Behavior
400 Bad Request is received.

Please tell me if anything more is needed. Thanks!

**Comment by koltyakov** [comment]
Hi Peter,

What is the error message in network tab of the dev tools. The meaningful message is usually can be seen in an error response.

Is it in SP 2013? If so, please check with Accept header configures with odata=verbose before the api call:

```javascript
pnp.setup({
  headers: {
    Accept: 'application/json; odata=verbose'
  }
});
```

Does it work for any other lists, e.g. a new custom list with simple metadata, like `{ Title: 'New title' }`?

**Comment by pchc2005** [comment]
Hi @koltyakov, 

> What is the error message in network tab of the dev tools? The meaningful message is usually can be seen in an error response.

Here is the error message:

```
{
    "odata.error":{
        "code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message":{
            "lang":"en-US",
            "value":"The property '_x007a_ak5' does not exist on type 'SP.Data.Test_x0020_Simple_x0020_ListListItem'. 
Make sure to only use property names that are defined by the type."
        }
    }
}
```

Where can I find the property name? I can't find a property named like property in SPField. 

> Is it in SP 2013?

Nope. I am currently developing on O365.

> Does it work for any other lists, e.g. a new custom list with simple metadata, like { Title: 'New title' }?

Actually it worked last week. Just not working this week. I didn't make any code changes about the function of list item creation. I think it is related to the 'property name' problem.

Thanks. :)

**Comment by koltyakov** [comment]
So the error message is saying `The property '_x007a_ak5' does not exist on type 'SP.Data.Test_x0020_Simple_x0020_ListListItem'. Make sure to only use property names that are defined by the type.`. Which already makes sense.
This means that you are trying to write data to a field which is absent in the list.

>> Actually it worked last week. Just not working this week. I didn't make any code changes about the function of list item creation. I think it is related to the 'property name' problem.

Someone could have changed the list's fields.
You can navigate to the list's settings find the field and check its internal name (it presented in the URL when editing the field). Or you can extract lists schema with PnP JS core as well:

```javascript
pnp.sp.web.lists
	.getByTitle("[Lists_Title]")
	.fields
	.select('Title,InternalName')
	.filter('Hidden eq false')
	.get().then(result => {
		console.log(result);
	});
```

You should use correct InternalNames in the request.

**Comment by pchc2005** [comment]
> Someone could have changed the list's fields.

I have already checked the history. No one has changed the code.

> You should use correct InternalNames in the request.

To compose the request object, I have created a mapping which maps the Title and InternalName. The request object is here:
```
{
    "_x007a_ak5": "test",     //siteName
    "kx2b": "test",     // siteLink
    "Site_x0020_OwnerId": {
        "results": [9, 11]
    }, 
    "s8c5": "test"     // purpose
}
```

The key of this object is the internalName I get from the list.

**Comment by koltyakov** [comment]
Sorry, I didn't get did you check if the field with internal name `_x007a_ak5` exists in your list?

**Comment by pchc2005** [comment]
Yes, it's in my list. Sorry about that.

**Comment by pchc2005** [comment]
I have solved this by using EntityPropertyName instead of InternalName. Is it supposed to be done by this?

**Comment by pchc2005** [comment]
Hello @koltyakov , 

Any follow-ups in these days? :)

**Comment by koltyakov** [comment]
Hey Piter,

I thought you figured out what was wrong with your field names.
As a general recommendation, I would recommend provisioning artifacts (with use of PnP Provisioning or SPMeta2) with meaningful internal names from the beginning. If you do it manually, then create a field with a correct internal name (excluding spaces, special symbols) and only after rename to the desired display name.

Yes, `EntityPropertyName` should be used (this is correct), though, in most cases (with the field name patterns I always use - 'FieldName01') it's the same as `InternalName`.
If creating a field with in non-supported pattern, internal name is generated with some replacements. E.g. field name with non-latin characters will be transformed into something like `_x0414__x043d__x043e_` which is not a valid OData property I guess and in REST the entity name is further transformed to `OData__x0414__x043d__x043e_`.

**Comment by patrick-rodgers** [comment]
Thanks @pchc2005 & @koltyakov for the great discussion. This appears to be resolved by the usage of internal names. Going to close this as answered, please _reopen_ to continue the discussion. Thanks!
