### ISSUE TITLE
Cannot copy file - File Not Found

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/PnP-JS-Core#552]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [2.0.7 ]

#### Expected / Desired Behavior / Question
I'd expect the publishing page to be copied. I was wondering if I am doing something wrong, is it possible to copy files between site collections in the same tenant?

#### Observed Behavior
When copying to target web, it throws File Not Found error.

#### Steps to Reproduce

Simply run the following code in the browser's dev console:

`var targetWeb = new $pnp.Web("https://tenant.sharepoint.com/sites/target-web"),
       fileName = window.location.pathname.substr(window.location.pathname.lastIndexOf("/") + 1; // in my case I am trying to copy a publishing page
$pnp.sp.web.getFileByServerRelativeUrl(window.location.pathname).getBlob().then(function (sourceFile){
	targetWeb.getFolderByServerRelativeUrl("/sites/target-web/sub-site/Pages/").files.add(fileName, sourceFile, false).then(function (r) { 
        console.log(r); });
});`

Thanks!

**Comment by patrick-rodgers** [comment]
You could try [copyTo](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/files.ts#L181) or [moveTo](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/files.ts#L228) and see if that works for you. Would be simpler code as well. HTH

**Comment by patrick-rodgers** [comment]
You might also want to take care as publishing pages have a lot of behind the scenes dependencies so might not work across site collections. If you are working on a provisioning solution something like the PowerShell or managed CSOM solutions might be more appropriate.

Closing this due to no response. Please _reopen_ if you need to continue the conversation. Thanks!
