### ISSUE TITLE
Incorrect behaviour when using configure with getParent on Queryable

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP-JS-Core#553]
#### Category
[x] Bug

#### Version

[  2.0.07  ]

#### Expected / Desired Behavior 
If Queryable uses `getParent()` method somewhere in a chain, configuration should be propagated to parent Queryable

#### Observed Behavior
If Queryable uses `getParent()` method somewhere in the chain, configuration is not propagated to parent Queryable. For example when calling `ensureListItemEntityTypeName` it uses `this.getParent(List)`. List object doesn't inherit configuration options from child object

#### Steps to Reproduce
Use new `configure` method for creating a new variable and try to add a new item without specifying entity type name:

```javascript
const sp = pnp.sp.configure({
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            }, req.user.authData.spHostUrl);

            const result = await sp.web.lists.getByTitle('Test list').items.add({
                Title: 'New item from Express web app'
            });
``` 
You will get Access denied because `Authorization` didn't propogated.

**Comment by patrick-rodgers** [comment]
Thanks @s-KaiNet for the fix! Closing this as fixed in PR #554.
