### ISSUE TITLE
Error when caching greater than client storage quota

### ISSUE THREAD

**Issue by matthewrobb** [SharePoint/PnP-JS-Core#555]
I'm seeing an issue when using caching where by the response is greater than 5MB in chrome and resulting in a DOM error that brings the application down. I would imagine that if any exception were thrown in the process of hitting the cache that it would just skip the cache. Hope this helps, thanks! (I am able to work around it but thought it worth bringing up here)

**Comment by patrick-rodgers** [comment]
Why would you want us to hide the error? That seems like an unexpected behavior - if I am trying to cache more than I am allowed I'd wnt the error so I can look at either reducing the data returned by the query or  not caching that. Also, a rest response over 5MB is really really big - I wouldn't recommend caching file contents. HTH

**Comment by matthewrobb** [comment]
I cannot always control the size of the response data coming from a client's SharePoint environment. The 5MB limitation on client storage is a browser limitation that I also cannot simply control or extend. If I am opting into a caching optimization for simple list requests and the response size grows over time to eventually surpass that 5MB it will cause a previously working application to suddenly break. In my mind I would rather not benefit from the caching optimization in this case.

So I can globally disable or avoid using the caching optimizations which hurts the more common cases or I can wrap all requests with my own catch to check if it's this type of problem and THEN reissue the request without caching (despite already having the data it just got lost up the promise chain).

Does that help in understanding why it seems logical not to reject the request in the instance of this error? I think any interactions with the caches should happen outside of the requesting promise chain and if it should throw it would do so out of band of the response propagating up to being resolved.

**Comment by patrick-rodgers** [comment]
I think you statement "I cannot always control the size of the response data coming from a client's SharePoint environment." isn't accurate. select and rowlimit allow this.

If one writes code that says "get this data and put it in the cache then give it back to me" and that statement throws an error then there is an error in the code as written, no? And the library should, in my view throw that so as not to hide it. Does .catch not handle that error and allow you to take some action - possibly removing some items from the cache?

That being said, I am not going to silently hide an error. But, I will take a look at possibly removing expired items when new things come in and providing a public method for that as well to help callers manage the cache. Perhaps that will help free up some space and help avoid filling the cache.

**Comment by patrick-rodgers** [comment]
I have added the ability to clear the cache of expired items as well as enable automated cache expiration on long running pages. You can see the [update docs](https://github.com/SharePoint/PnP-JS-Core/wiki/Caching#cache-expiration) and this will go out as part of 2.0.8. Thanks!
