### ISSUE TITLE
pnp.sp.utility.sendEmail not working on Modern Pages

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [SharePoint/PnP-JS-Core#556]
#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version
[ 2.0.7 ]

#### Expected / Desired Behavior
pnp.sp.utility.sendEmail should send an email to the user on both classic page and modern page

#### Observed Behavior
User receives the email when this is used on a Classic Page
User does not receive the email when used on a Modern Page. Receives a 404

#### Steps to Reproduce
1. Use the following code on a Classic Page and Modern Page (through SPFx webpart)

```
import pnp, { EmailProperties } from "sp-pnp-js";
const emailProps: EmailProperties = {
    To: ["user@site.com"],
    CC: ["user2@site.com", "user3@site.com"],
    Subject: "This email is about...",
    Body: "Here is the body. <b>It supports html</b>",
};
pnp.sp.utility.sendEmail(emailProps).then(_ => {
    console.log("Email Sent!");
});

```
2. User receives the mail when used on a Classic page
3. On a modern page, this fails with a status code 404
The REST call is made to http://site-url/SitePages/_api/SP.Utilities.Utility.SendEmail
(it should be http://site-url/_api/SP.Utilities.Utility.SendEmail)
I guess, this call fails due to the unwanted **SitePages** in the url.

**Comment by patrick-rodgers** [comment]
Are you following [the guidance](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework) when using the framework within SPFx?

**Comment by RamPrasadMeenavalli** [comment]
Hi Patrick,
My mistake. I was not aware, and missed the guidance.
After updating my code as described in the guidance, this is working fine. Thank you.
