### ISSUE TITLE
Update RootFolder Properties of a list

### ISSUE THREAD

**Issue by raminahmadi1986** [SharePoint/PnP-JS-Core#557]
Hello ,
I want to enable the rating settings of a list , as I know we can achieve that by updating the properties bag of the rootfolder . pnp gives me an ability to get the rootfolder properties by below code :
pnp.sp.web.lists.getByTitle("news").rootFolder.properties

but it wouldn't let me to update a property.
any solutions regarding this issue ?

**Comment by patrick-rodgers** [comment]
You cannot currently update the property bag via REST. This is a limitation in the product and not the library so unfortunately nothing we can do currently. The work around is to use the JSOM for now. This is also a duplicate of #455 in that both require the ability to update properties - so I'll close this one. Thanks!

**Comment by raminahmadi1986** [comment]
Hi Patrick , thanks for your reply :)
