### ISSUE TITLE
Working With: Files

### ISSUE THREAD

**Issue by fabiovg9** [SharePoint/PnP-JS-Core#558]
Hi, how do upload a file with all properties or fields values to a sharepoint library?

#### Category

[X]Question

#### Version 

PnP-JS-Core 2.0.7

Thanks!

**Comment by patrick-rodgers** [comment]
You would upload the file and then set the properties on the associated item to that file. You can use a combination of [this example](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Files#adding-files) and getItem to accomplish this. I added [a snippet to demonstrate](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Files#setting-associated-item-values) this.

Going to close this as answered, please _reopen_ the issue should you have further questions. Thanks!
