### ISSUE TITLE
How to use the Expand option of List getItemsByCAMLQuery

### ISSUE THREAD

**Issue by DennisKuhn** [SharePoint/PnP-JS-Core#564]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement
[ ] Bug
[x] Question

#### Version
Please specify what version of the library you are using: 2.0.7

#### Expected / Desired Behavior / Question
Fields that I specify to be expanded are expanded in the returned items.

#### Observed Behavior
Instead of `Author/Email` and `Author/Title` I receive `AuthorId`.

#### Steps to Reproduce
My query

    let camlQuery: CamlQuery = {
        ViewXml: `<View><Query><Where><IsNull><FieldRef Name=\'ResolvedBy1\'/> 
        </IsNull></Where></Query><RowLimit>${this._itemLimit}</RowLimit><ViewFields><FieldRef Name='Author' /><FieldRef Name='Author\EMail' /><FieldRef Name='Author\Title' /></ViewFields>    </View>`
    };

The following runs without errors:

    this._list.getItemsByCAMLQuery(camlQuery, "Author\Title", "Author\EMail")

but the returned items just have an `AuthorId` field:

    0:Object {odata.type: "SP.Data.ILogListItem", odata.id: "e3e451a2-b3ef-4cd4-9752-bc9a3725eb65", odata.etag: ""2"", …}
    AuthorId:21
    Created:"2017-08-14T13:57:17"
    FileSystemObjectType:0
    Id:429
    ID:429
    Modified:"2017-08-14T13:57:20"
    odata.editLink:"Web/Lists(guid'2ebdeb59-7bd3-4556-858f-e31fc65db871')/Items(429)"
    odata.etag:""2""
    odata.id:"e3e451a2-b3ef-4cd4-9752-bc9a3725eb65"
    odata.type:"SP.Data.ILogListItem"
    ServerRedirectedEmbedUri:null
    ServerRedirectedEmbedUrl:""
    __proto__:Object {__defineGetter__: , __defineSetter__: , hasOwnProperty: , …}

When I try to expand `Author`

    this._list.getItemsByCAMLQuery(camlQuery, "Author")

or

    this._list.getItemsByCAMLQuery(camlQuery, "Author", "Author\Title", "Author\EMail")

I get the following error:

    Error: Error making HttpClient request in queryable: [400] Bad Request
      at new t (https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.7/pnp.min.js:1:18830)
      at https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.7/pnp.min.js:1:11829
      at <anonymous>

**Comment by koltyakov** [comment]
Are any objective reasons using getItemsByCAMLQuery instead of OData? You can't expand lookup fields in case of the CAML.
But you can do it with OData:

```javascript
pnp.sp.web.getList('...')
	.items
	.select('Author/Id,Author/Title,Author/Name,Author/EMail')
	.expand('Author')
	.get()
	.then(console.log)
```

**Comment by DennisKuhn** [comment]
I am using `getItemsByCAMLQuery` because I need to filter for `null` fields.

**Comment by koltyakov** [comment]
Won't `.filter('ResolvedBy1Id eq null')` work?
Is it a lookup/people picker field?

**Comment by DennisKuhn** [comment]
Yip, `ResolvedBy1` is a people/lookup field. I thought when I implemented using REST, `null` filtering was not supported. I give it try and come back ... (Thanks for your swift reply)

**Comment by koltyakov** [comment]
It should work. I tested with people picker just before posting the previous answer (with `eq null`, `ne null`).
The lookup field name in filter condition should contain `Id` at the end. So, if your field's internal name is `ResolvedBy1`, the `ResolvedBy1Id` have to be in an OData request. Just like in the previous example.

**Comment by DennisKuhn** [comment]
Thank you, my bad :-) It worked sweet, even using filters including AND/OR.
