### ISSUE TITLE
Unable to get ViewFields in getItemsByCAMLQuery working

### ISSUE THREAD

**Issue by SurinderTaneja** [SharePoint/PnP-JS-Core#566]
I am trying to use pnp.sp.web.lists.getByTitle("some List").getItemsByCAMLQuery() and specifying Viewfields in ViewXml but it is not returning the fields mentioned in ViewFields. I am using following query in ViewXML

ViewXml:
          ViewXml:
                    `<View> 
                    <RowLimit> 
                        3 
                    </RowLimit> 
                    <Query>
                        <OrderBy>
                            <FieldRef Name='Id' Ascending='False' />
                        </OrderBy>
                    </Query> 
                    <ViewFields> 
                        <FieldRef Name='FileLeafRef' /> 
                        <FieldRef Name='FileName' /> 
                    </ViewFields> 
                </View>`

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version
2.0.7

Thanks!

**Comment by patrick-rodgers** [comment]
Is there any particular reason the following doesn't work for your case? The OData operators are the preferred method when dealing with REST. The CAML method is there to support backwards compatibility.

```TypeScript
    pnp.sp.web.lists.getByTitle("some List").items.select("FileLeafRef", "FileName").orderBy("Id", false).top(3).get().then(r => {

      // r will by an array of your items.
    });
```

**Comment by SurinderTaneja** [comment]
Hi Patrick,

Thanks for your quick response. I have to display the list items based on the selected list view. For this, I am fetching up the ViewXML from View and then usinggetItemsByCAMLQuery to get the list items by using the ViewXML as query.

**Comment by patrick-rodgers** [comment]
I think then this is a limitation with the getItems method. Likely it is looking at items on the back end where FileLeafRef isn't a property. There isn't a bug to fix as we are passing the ViewXml to the server and reporting the result. I understand your situation - but unfortunately we don't have a remedy to offer.

You could try calling the getItemsByCAMLQuery method and include the second parameter "File" to expand the file and then grab the Name value from there, which will be the filename if that is what you are after. Something like:

```TypeScript
pnp.sp.web.lists.getByTitle("Documents").getItemsByCAMLQuery({
    ViewXml: "<View><RowLimit>3</RowLimit><Query><OrderBy><FieldRef Name='Id' Ascending='False' /></OrderBy></Query></View>",
}, "File", "Folder").then((r: [{ File?: { Name: string }, Folder?: { Name: string } }]) => {

    for (let i = 0; i < r.length; i++) {
        if (r[i].File) {
            // files
            console.log(`File: ${r[i].File.Name}`);
        } else if (r[i].Folder) {
            // folders
            console.log(`Folder: ${r[i].Folder.Name}`);
        }
    }

}).catch(e => {

    console.error(e);
});
```

HTH, Patrick
