### ISSUE TITLE
Expanded properties being wrapped in a "results" array

### ISSUE THREAD

**Issue by Tinathnath** [SharePoint/PnP-JS-Core#567]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [ v2.0.5 ]

Hi everyone !

I don't really know if my "bug" is pnp-related issue but I've never seen it in another context.

I have the following request with expanded properties, the aim is to fetch all sub-webs from a collection, including users of those webs (not sitecollection's users only):
`$pnp.sp.site.rootWeb.webs.select("Title", "AllProperties", "Description", "Created", "Url", "Id", "HasUniqueRoleAssignments", "RoleAssignments", "RoleAssignments/Member", "RoleAssignments/Member/Title", "RoleAssignments/Member/Users").expand("AllProperties", "RoleAssignments/Member", "RoleAssignments/Member/Users").get().then(<code>);`

When I test it in my browser console (tested on Chrome and IE) I get the folowing data structure, which is fine:

![image](https://user-images.githubusercontent.com/3273299/29708628-a19cb088-8989-11e7-86c3-3ba27dfeab3d.png)

Then I use the same code in my .js file and execute it on the page. It fails.
The `RoleAssignments` property is no longer an array of RoleAssignments but an object containing a `results` key which is an array of RoleAssignments.

![image](https://user-images.githubusercontent.com/3273299/29708744-18664134-898a-11e7-85c2-6b67a0546b36.png)

I had the same behavior when I fetched the `SiteUsers` expanded property. Does anybody have the same issue ? Or is it a JS -related behavior ?
You guys actually made me debugging JS in IE's developper "tools", you'd better have an answer 😃 

By the way, good job with PnP, I love it 😉 
Have a great day

**Comment by koltyakov** [comment]
Hi @Tinathnath,

Could you try with definite Accept header declaration before triggering PnP request?

```javascript
pnp.setup({
   headers: {
      Accept: 'application/json; odata=verbose'
      // Accept: 'application/json; odata=minimalmetadata'
      // Accept: 'application/json; odata=nometadata'
   }
});
```

**Comment by Tinathnath** [comment]
Hi @koltyakov 
Thanks for the reply
This headers definition is already in the code :/

**Comment by koltyakov** [comment]
Headers setup can be redefined in a runtime.
My idea was to check that you're using the same odata mode in a console during testing and in your JS functions.

Let's imagine:

```javascript
pnp.setup({ ...minimalmetadata_headers });
await pnp.sp.web.[somerequest]; // Receive one type of a responce structure
pnp.setup({ ...verbosemetadata_headers });
// Run `pnp.sp.web.[somerequest]` in a console => Receive another type of a response structure 
```

**Comment by Tinathnath** [comment]
@koltyakov You were right. I actually tested in console with the `$pnp.setup` call before the query. Here's the result:
![image](https://user-images.githubusercontent.com/3273299/29776425-dfd2eee0-8c08-11e7-8855-bd01e1a66ce2.png)

I actually have a `results` key in the data. So this is a odata-related issue ? It changes the data structure depending on the mode it is being queried ? Is there a technical reason to wrap arrays like that ?

**Comment by koltyakov** [comment]
What's how REST works in SharePoint.
OData modes (verbose, minimalmetadata, nometadata) represent slightly bit different structure.
PnP JS Core does not try changing this output. 
The application should be OData-mode-aware. Luckily the difference is not huge.

**Comment by Tinathnath** [comment]
Ok, good to know.
Thanks for your help !
