### ISSUE TITLE
Batching multi item updates creating a call for each item

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#569]
I'm trying to do a batch update of list items and reduce the get list item calls: 

![image](https://user-images.githubusercontent.com/5871660/29735196-1723c6b2-89c5-11e7-81eb-41dff7e420c6.png)

I thought batch or caching would help here but I think I'm missing something. 

```
import pnp from "pnp";

var list = pnp.sp.web.lists.getByTitle("Projects");
list.items.get().then(function(items) {
	var batch = pnp.sp.createBatch()
	// see if we got something
	if (items.length > 0) {
		items.map(function(item, index) {
			list.items.usingCaching().getById(items[index].Id).inBatch(batch).update({
				"BA_GroupRenameAgain": "Unassigned",
			}).catch(console.log)
		})
	}
	batch.execute().then(() => console.log("All done!"));
});
```

**Comment by russgove** [comment]
looks like yore creating a separate batch for each list item. move the createbacth and execute batch outside the loop

**Comment by koltyakov** [comment]
Hi @russgove, in the code from @simkessy batch execution is outside the loop actually. Yet, it's better to use `forEach`, not `map` in this case.
It's really happening that per each update within the batch ListItemEntityTypeFullName is requested.
I saw this on my projects too sometimes ago, but didn't pay my attention as a cache (I hope) was used and not physical requests to the server.

Interesting, going to check this in my environment...

**Comment by koltyakov** [comment]
Just have tested in On-Prem 2016 and SPO, PnP JS Core 2.0.8 (within Chrome SP Editor):

```javascript
import * as pnp from 'pnp';

var list = pnp.sp.web.lists.getById(_spPageContextInfo.pageListId);
list.items.select('Id,Title').get().then((items) => {
	var batch = pnp.sp.createBatch()
	items.forEach(item => {
		list.items.getById(item.Id).inBatch(batch).update({
			Title: item.Title
		});
	})
	batch.execute().then(() => {
		console.log("All done!");
	}).catch(console.log);
});
```

![batchupdate](https://user-images.githubusercontent.com/7816483/29743823-a77a2e5e-8aa1-11e7-9b0d-2bd5906678b5.png)

Per each update, there is an actual physical request to get the same exact `ListItemEntityTypeFullName`.

**Comment by simkessy** [comment]
So you're seeing the same thing as me eh, any thoughts on a solution? 

Also, I'm not sure I understand why forEach or map would be different. They kind of do the same thing no?

**Comment by koltyakov** [comment]
I have never checked the code part with batching in details. I consider this will be a straightforward thing for @patrick-rodgers right after he has a chance to take a glance at this issue.

> Also, I'm not sure I understand why forEach or map would be different. They kind of do the same thing no?

`forEach` iterates through the items in an array.

`map` also iterates but is created for transformation one array into another. So, when I look into the code with `map` I expect that there is a return statement inside map's callback and that some new array is assigned. When I do not see this I'm starting thinking about potential error or misusing of the functionality.

It's the same as naming a function with 'jumpHigh' when an actual behavior is 'runFast'. Yep, it will work, but somebody looking into the code might be confused. And when we come back to our own code after a while it's always a different "person" looking and asking himself who wrote this code. =)

**Comment by patrick-rodgers** [comment]
Please have a look at this [wiki entry](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#add-multiple-items). We have to retrieve the ListItemEntityTypeFullName from the list for the update as SP requires it is used. SO we do that on a per request basis as the requests don't (and shouldn't) know about or rely on other requests. This is suboptimal when adding lots of items, hence the pattern linked in the wiki article. That should get you sorted. Thanks!

**Comment by koltyakov** [comment]
Just an idea: 
What about optional passing of `{__metadata: { type: listItemEntityType }}` to update/add methods and ignoring `this.ensureListItemEntityTypeName(listItemEntityTypeFullName)` promise if `__metadata.type` has been provided strictly?

**Comment by koltyakov** [comment]
My bad, I didn't know about this option of strict providing of `entityTypeFullName`. Perfect!

**Comment by patrick-rodgers** [comment]
All good, always happy when we've already got an answer for stuff :)

**Comment by patrick-rodgers** [comment]
Thanks, closing this as answered.

**Comment by simkessy** [comment]
Thanks for the help guys.

**Comment by simkessy** [comment]
@patrick-rodgers 

I'm trying to follow the pattern from the wiki link but I'm not sure how to adapt it to making updates to list items. 


```
import pnp from "pnp";

pnp.setup({
	headers:{
		"Accept": "application/json; odata=verbose"
	}
})

let list = pnp.sp.web.lists.getByTitle("Acts");

list.getListItemEntityTypeFullName().then(entityTypeFullName => {

    let batch = pnp.sp.web.createBatch();

	let items = list.items.inBatch(batch)
	
	items.get().then(function(items) {
		if (items.length > 0) {
			items.map(function(item, index) {
				item.inBatch(batch).update({
					"Status": "Not Started",
				}).catch(console.log)
			})
		}
	});

    // list.items.inBatch(batch).add({ Title: "Batch 6" }, entityTypeFullName).then(b => {
    //     console.log(b);
    // });

    batch.execute().then(d => console.log("Done"));
});
```
