### ISSUE TITLE
Open Discussion - Merge/Enhance office-pnp-js and gd-sprest Frameworks

### ISSUE THREAD

**Issue by gunjandatta** [SharePoint/PnP-JS-Core#572]
#### Category
[X] Question

#### Question
Per feedback from a twitter conversation, I'm opening an issue to discuss the possible merge or enhancement of the office-pnp-js and the gd-sprest libraries. I do understand that they currently can't be merged, due to having different concepts to achieve a similar framework. I'm not sure if this is something that can be considered in the future, or if the office-pnp-js library can be enhanced from the gd-sprest library.

The concept of the [gd-sprest](https://gunjandatta.github.io/sprest/) library, essentially is a request builder. It uses a mapper class to build the REST api request, which can be used in many different ways. The mapper will allow the library to be easily extended to use new apis (Graph, Office, OneDrive).
* [OData Requests](http://dattabase.com/sharepoint-rest-api-odata/) - Blog post going over odata requests. There are code examples at the bottom which may be useful to explain how to use the framework.
* [Project Wiki](https://github.com/gunjandatta/sprest/wiki) - The wiki page for the library. This needs to be rewritten, but has a lot of useful information.

Add-In Helper:
There is a global flag for the app-web. This will help when trying to execute requests against the current web and/or host web. There are helper files for copying assets to the host as well.

NodeJS Scripts:
The request information can be generated and passed to the XMLHttpRequest or $.ajax request.

PowerShell-Like Experience:
The library has an "executeAndWait" method for synchronous calls. This feature allows the developer to execute requests in the browser console window, creating a "Powershell-Like" experience. This can be useful when you don't have access to the server, but have rights in a web. The variables will return the available methods, so you can get intellisense. A recent example of this feature would be fixing a broken lookup field during migration. I was able to update the list lookup id in the schema xml, in order to fix a broken lookup field. I generally execute live requests to test during development. This saves a lot of time during the development phase.

Automation:
The library has an automation feature, which allows for SharePoint assets to be created on the fly. It allows for Content Types, Fields, Lists, WebParts and User Custom Actions to be created. Refer to this [blog post](http://dattabase.com/sharepoint-configuration/) for additional information on this feature.

Intellisense:
I've spent a lot of time trying to perfect the intellisense of the library. The developer will no longer need to define the output type of the execution. The library will automatically set the output, based on the method/property/odata request. The library includes the interfaces, so you will have intellisense for NodeJS, JavaScript and TypeScript files. There is no need to download additional libraries.

React Library:
I've recently created a react add-on library in [GitHub](https://github.com/gunjandatta/sprest-react), which includes common components. The webpart component was designed for SharePoint 2013, which we can port over to SPFX easily when the client is ready to move to SP2016 or O365. The webpart works in both wiki and webpart pages, and allows for a custom configuration panel when the page is in edit mode. There are classes (WebPartCfg and WebPartListCfg) that can be used or extended, so the developer doesn't need to start from scratch.
* [SP2013 Modern WebParts](http://dattabase.com/sharepoint-2013-modern-webpart/) - Blog post going over the webpart, including developing one from scratch and deployment.
* [React Components](http://dattabase.com/sharepoint-react-components/) - Blog post going over the react components.

I'm happy to discuss anything in detail, and/or have direct conversations. I hope there is useful information in here that will help enhance the office-pnp-js library.

Thanks,
Gunjan

**Comment by bcameron1231** [comment]
+1 from me! I am a huge fan of your gd-rest library.

**Comment by patrick-rodgers** [comment]
We've talked through this several times in the past and I will ask again the same question: what specifically do you want to add/change/enhance? What is your goal with this post - other than to advertise your library and other work? **Turn this into an actionable statement** - "I think we can add X feature" or "What about updating X functionality to include Y".

Another approach would be to submit a PR with a proposed change that folks can see and comment on its merits.

The two libraries are written differently with different approaches and choices, there is not a clear path to "merge" them. Different doesn't mean better/worse in either case, it simply means that problems were solved with differing choices and trade offs. There will always be more than one way to solve a given problem in programming and that is one of the things that makes it so fun, interesting, and rewarding. There is no reason both libraries can't exist in parallel and why I helped you as you were getting started with suggestions and ideas for your work.

**Comment by gunjandatta** [comment]
Hi Patrick,

First off, thank you for your initial feedback about a year ago. It really got me to think outside-the-box, and I've ended up having to rewrite most of the library to get it to its current state.

As I indicated in the beginning, I do understand that they can't be merged in its current state. I have very low expectations of this happening, based on the discussions we have already had. This "issue" was created based on feedback from Waldek Mastykarz, to create an open discussion. I thought it was a good idea, so I created it yesterday. The goal of this post is not to advertise this library. I wanted to give a list of the HL features to see if there is anything in my library that can help enhance the Office-PnP-JS library.

To respond to your question:

New Feature:
I think the Office-PnP-JS can add a feature to make live requests in the browser console window. Being able to make queries in the browser console window directly is extremely helpful for R&D and troubleshooting/fixing issues. I hope the example of fixing a broken lookup field after a migration helps explain a need for this.

Intellisense Help:
I'm not sure if the intellisense for the office-pnp-js library needs any enhancements. I've been able to figure out how to set the output dynamically, based on the methods. If there is something in this library that can help enhance the office-pnp-js intellisense, I can work with others to show how I achieved it.

**Comment by patrick-rodgers** [comment]
There exists a [fantastic chome extension](https://chrome.google.com/webstore/detail/sp-editor/ecblfcmjnbbgaojblcpmjoamegpbodhd) by @tavikukko for doing in browser work. Included in the feature set is an intellisense enabled editor for sp-pnp-js which exceeds anything we could support in the library. Code execution in the console isn't a critical use case in my eyes given the extension and its rich capabilities - but if folks want something like that a PR would be appropriate. But that needs to be balanced with file size (something we already identify as an issue) to usefulness. This is a good example of how libraries make different decisions on priorities as I recognize this is a key feature for you.

We have extensive intellisense support, but I am sure there are places where we can do better and add more interfaces for return types or parameters, again a PR would be appropriate to add that support where needed.

**Comment by gunjandatta** [comment]
Understood, and you are right with your assumptions and priorities. The environments and focus of both projects are different, so I completely understand if you want to go ahead and close out this discussion. I apologize if this was taken in a way to "advertise" the library. This was not my goal or intention.
