### ISSUE TITLE
copyTo randomly erroing, workaround?

### ISSUE THREAD

**Issue by DavidLozzi** [SharePoint/PnP-JS-Core#575]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.8  ]

#### Expected / Desired Behavior / Question
using copyTo, like `file.copyTo("!@c1::" + uploadTo.fileUrl).then` and it works some of the time, but now more often than not it errors out randomly. We're moving a few files at once, and the bulk of them copy, but then some error out. Screenshots below.

We are letting the user upload 3 files, then those 3 files get copied to 4 or 5 different folders. Uploaded once, then using CopyTo to copy to the other locations. The initial files always upload, and copy to most of the folders but errors on some. The error doesn't make sense as the file is valid. 

*Is there a workaround?* It feels like it could be a timing issue, i could try doing it all sync instead of async, but that would be longer for the user. Thoughts?

#### Observed Behavior
![image](https://user-images.githubusercontent.com/3543383/29886774-41dff70a-8d89-11e7-8d6c-b3d3635b0959.png)
Note the long list of copyTo, most worked, some didn't. 

![image](https://user-images.githubusercontent.com/3543383/29886785-4b4a38aa-8d89-11e7-90a2-76e1f8c53c11.png)
Console log of the errors

#### Steps to Reproduce
It was random but now happening more and more.

**Comment by DavidLozzi** [comment]
I modified code so it runs a little *slower*, it was running sync per file, but each 3 files are uploading async. setTimeout from 400 to 900 to slow it down, still occuring. Anything I can do to rectify?

**Comment by DavidLozzi** [comment]
Wee bit more detail. One of the copyTo URL that works

https://massbbo1.sharepoint.com/sites/obc-cases-test/_api/web/getFolderByServerRelativeUrl(@p1)/files(@p2)/copyTo(strnewurl=@c1,boverwrite=true)?@p1=%27/sites/obc-cases-test/documents/Glen%20659032/3-17-00247472/Dockets%27&@p2=%27/sites/obc-cases-test/documents/Glen%20659032/3-17-00247472/Dockets/BBO_Logo_DN-1391094.png%27&@c1=%27/sites/obc-cases-test/documents/Glen%20659032/3-13-0106/Dockets/BBO_Logo_DN-1391097.png%27

then right after that this one errors
https://massbbo1.sharepoint.com/sites/obc-cases-test/_api/web/getFolderByServerRelativeUrl(@p1)/files(@p2)/copyTo(strnewurl=@c1,boverwrite=true)?@p1=%27/sites/obc-cases-test/documents/Glen%20659032/3-17-00247472/Dockets%27&@p2=%27/sites/obc-cases-test/documents/Glen%20659032/3-17-00247472/Dockets/BBO_Logo_DN-1391094.png%27&@c1=%27/sites/obc-cases-test/documents/Glen%20659032/3-16-0024/Dockets/BBO_Logo_DN-1391098.png%27

with error
The URL '/sites/obc-cases-test/Documents/Glen 659032/3-17-00247472/Dockets/BBO_Logo_DN-1391094.png' is invalid.  It may refer to a nonexistent file or folder, or refer to a valid file or folder that is not in the current Web."

**Comment by patrick-rodgers** [comment]
Hi @DavidLozzi - sorry for the delay in responding but have been focused on refactoring work. It seems perhaps you are making the calls too quickly or possibly not waiting for one to complete before executing the next? It can get tricky chaining calls and I often have to ensure things are firing in the order expected.

Are you still having issues related to this? It doesn't seem to be an issue with the actual method, but timing as it works some of the time.

**Comment by DavidLozzi** [comment]
I am now handling it all in a serial manner, and no more errors!
Thanks

**Comment by patrick-rodgers** [comment]
Great news - thanks for letting us know. I'll close the issue, please _reopen_ if needed or create a new issue. Thanks!
