### ISSUE TITLE
Issue ? on add item when column have special character

### ISSUE THREAD

**Issue by mame13fr** [SharePoint/PnP-JS-Core#577]
#### Category
[ ] Enhancement

[X] Bug

[X] Question

Hi all,

I will try to add an SP list item.
No problem with standard column name.

But with a column with a name like "_x0042_P1" (BP1)
It is impossible to add an item.

return pnp.sp.web.lists.getById(idList).items.add({
            Title: "Mod By Me",
            _x0042_P1: "true"     //same problem with _x0042_P1: "true"   
        }).then((iar: ItemAddResult) => {
            console.log(iar);
        });

Anyone can help me please ?

Thanks a lot !!!

**Comment by patrick-rodgers** [comment]
Can you try enclosing the property name in quotes? That should work.

```
return pnp.sp.web.lists.getById(idList).items.add({
Title: "Mod By Me",
"_x0042_P1": "true" //same problem with _x0042_P1: "true"
}).then((iar: ItemAddResult) => {
console.log(iar);
});
```

**Comment by mame13fr** [comment]
I tried, but not working :(

I tested with : 
"_x0042_P1": "true"
'_x0042_P1': "true"
_x0042_P1: "true"
"x0042P1": "true"
x0042P1: "true"
"BP1": "true"

Nothing work !! :'(

**Comment by patrick-rodgers** [comment]
true should not be in quotes I think. What type of field is it? Do you have the correct internal name?

**Comment by mame13fr** [comment]
I tried with different type field (Checkbox and single line text)

I create the column in sharepoint with "BP1" name.
SharePoint automatically rename the field in "x0042_P1"

**Comment by KEMiCZA** [comment]
Also try "1" or "0" for settings booleans.

**Comment by mame13fr** [comment]
Thanks, but the problem occur also on single line text

**Comment by mame13fr** [comment]
With a column named like this : test_x0020_col: "text"
There is no problem...

I think the issue appear only when the special character is at the beginning

**Comment by s-KaiNet** [comment]
As far as I know, OData has some issue when dealing with some properties starting from underscore '`_`' symbol. That's why you need to use `EntityPropertyName` when adding\updating an item instead of internal name:  

![entity](https://user-images.githubusercontent.com/10658276/29931441-f44dc746-8e79-11e7-9efd-84cd7d46339c.png)  

I believe you can generate valid property by adding `OData_` to all properties starting from underscore.

**Comment by mame13fr** [comment]
IT WORKS !!!!
You save my day !!

Thanks a lot !!!

**Comment by koltyakov** [comment]
The same kind of question with `EntityPropertyName` was in #551. Just want to link the issues together.

**Comment by patrick-rodgers** [comment]
Thanks folks, going to close this issue as solved.
