### ISSUE TITLE
GetAllSubWebCollection using pnp.js

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#578]
Hey, 

I'm using version 2.0.8 and i'm trying to recreate the code below with pnp but I can't seem to find an equivalent.: 

		$().SPServices({
			operation: "GetAllSubWebCollection",
			async: true,
			completefunc: function (xData, Status) {
				createMap(xData.responseXML);
			}
		});
                // https://mysite.sharepoint.com/sites/spfx/_vti_bin/Webs.asmx

I've noticed that expanding the webs property on the web object will show me if there are subsites and I'm wondering if I'd need a recursive function to go through each site, find if there are subsites and build a site map that way? 

```
pnp.sp.web.expand("Webs").get().then(function() {
	
});
```

https://msdn.microsoft.com/en-us/library/webs.webs.getallsubwebcollection(v=office.12).aspx

**Comment by simkessy** [comment]
This works pretty well:

```
import pnp, { Web } from "pnp";

var result = this.window.result = [];
var b = pnp.sp.createBatch();

// Recursive to create results of all sites 
var checkWeb = function(webUrl) {
	let web = new Web(webUrl);

	web.select("Title, Url, Webs").expand("Webs").inBatch(b).get().then(w => {
		console.log("Site", w.Title)
		// Check if any subsite
		if(w.Webs.length > 0) {
			w.Webs.forEach(function(subsite) {
				// Add subsites to array
				result.push({
					title: subsite.Title,
					url: subsite.Url
				})
				// Call recursive for current subsite
				checkWeb(subsite.Url);
			})
		}
	});
};

// Get current site call recursive 
pnp.sp.web.inBatch(b).get().then( w => { 
	result.push({
		title: w.Title,
		url: w.Url
	})
	checkWeb(w.Url)
 })

```

I end up with this object of all the sites: 

![image](https://user-images.githubusercontent.com/5871660/30001265-babdfbac-9056-11e7-91d2-fcd0370bcee0.png)

I think I just need to figure out batching, on a large collection this approach would make too many calls. 
It doesn't seem possible since the first call needs to finish first so I can know how many webs there are and loop through that so I don't see how I could do this with batching but if anyone has an approach :)

**Comment by patrick-rodgers** [comment]
Does webinfos get you what you need?

```
pnp.sp.web.webinfos.get().then(...)
```

**Comment by simkessy** [comment]
Not example, it seems to be equivalent to doing `pnp.sp.web.expand("Webs").get()` from what I can see. 

For example. My collection has subsites 3 levels down or more, this seems to only return the first level. 

I tried this as well: `pnp.sp.web.webinfos.expand("Webs").get()`

**Comment by patrick-rodgers** [comment]
There isn't a specific API for us to implement to solve this, so looping through the webs to get sub webs is as good an answer as is currently possible. You could also try search and see if you get the information you need that way.

Going to close this as answered, please _reopen_ if you need to continue the discussion. Thanks!

**Comment by simkessy** [comment]
Hey @patrick-rodgers , that's fine, I think the looping works well enough. 

Thanks.
