### ISSUE TITLE
pnp.sp.site.getWebUrlFromPageUrl(window.location.href) API is being called with wrong URL if it is running under Site pages

### ISSUE THREAD

**Issue by devoooo4u** [SharePoint/PnP-JS-Core#579]
#### Category
[ Bug ]
#### Version
[ 2.0.8 ]

#### Expected / Desired Behavior / Question
if pnp.sp.site.getWebUrlFromPageUrl must call api using https://xxxxx.sharepoint.com/sites/<site_name>/_api/sp.web.getweburlfrompageurl(@v)?@v=%27https://xxxxx.sharepoint.com/sites/site_name/SitePages/Regions.aspx%27

#### Observed Behavior
rather in my case it being run in wrong url: https://xxxxx.sharepoint.com/sites/<site_name>/_SitePages/_api/_sp.web.getweburlfrompageurl(@v)?@v=%27https://xxxxx.sharepoint.com/sites/site_name/SitePages/Regions.aspx%27

#### Steps to Reproduce
1. Deploy the spfx webpart code to SharePoint site.
2. Add your web part to a site page which is residing inside "Site Pages" Library
3. use chrome debugger to see how api is being called !. Below is the sample code  
pnp.sp.site.getWebUrlFromPageUrl(window.location.href)
 .then(res => {
 alert(res);
});

## Refer the Screen shot for more clarity.
Please Note: This works fine if current page url is workbench.aspx. This issue appears only when current page url is coming from a site page residing under Site Pages library..

![capture](https://user-images.githubusercontent.com/19596216/30033219-a0bdfca4-91b7-11e7-8896-096ed2f334b9.JPG)

**Comment by KEMiCZA** [comment]
I think I had the same issue before when using SPFx in combination with pnp-js. Check the following page on how to use the library with the spfx framework: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

**Comment by devoooo4u** [comment]
Thank you for reply, But I am using Knockout.js and this.context.pageContext.web.absoluteUrl works on webpart.ts file only. However my core logic is written under webpartViewModel.ts file.

**Comment by patrick-rodgers** [comment]
Setting the value once should set it globally. If that doesn't work for however you are doing your work you can always [set the web url manually](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Webs#get-a-web-directly). This isn't a bug we can fix as we can't guess the paths within your site from the url and there is no global context available when operating within SPFx for us to use - and the only valid context within an SPFx container is the this.context. HTH

**Comment by devoooo4u** [comment]
Thank you Patrick for clarifications
