### ISSUE TITLE
Getting and updating a collection - using batching?

### ISSUE THREAD

**Issue by simkessy** [SharePoint/PnP-JS-Core#580]
Hey,

I'm looking at the wiki section for Updating multiple items and I'm trying to figure out how it could be done using batching

```

import pnp from "sp-pnp-js";

// you are getting back a collection here
pnp.sp.web.lists.getByTitle("MyList").items.top(1).filter("Title eq 'A Title'").get().then((items: any[]) => {

    // see if we got something
    if (items.length > 0) {

        pnp.sp.web.lists.getByTitle("MyList").items.getById(items[0].Id).update({
            Title: "Updated Title",
        }).then(result => {

            // here you will have updated the item
            console.log(JSON.stringify(result));
        });
    }
});
```

The example provided shows how to do it with only 1 item, not really a collection.

I've tried this: 

```
let list = pnp.sp.web.lists.getByTitle("Acts-Backup");

list.getListItemEntityTypeFullName().then(entityTypeFullName => {


	let items = list.items
	
	items.get().then(function(listItems) {
		let b = pnp.sp.createBatch()

		listItems.forEach(function(item, index) {
			console.log(item)
			items.getById(item.Id).inBatch(b).update({
				"Status": "Start",
			}).catch(console.log)
		})

		b.execute().then(console.log).catch(console.log)
	});

});
```

But I get a `getByTitle('Acts-Backup')?$select=ListItemEntityTypeFullName` for each item (a few hundreds) and the batch errors out: 

![image](https://user-images.githubusercontent.com/5871660/30069034-97081f52-922d-11e7-9a1e-a409ce49b736.png)

This is related to issue #569

**Comment by russgove** [comment]
hey, don't know if it's related but i've always had issues updating more than 200 items in a batch--at least quit standard csom i' did. 
i did you try with a small number of items? you may need to cut down your batch size.

**Comment by s-KaiNet** [comment]
For me it looks like a bug\issue with `update` method, because it lacks `listItemEntityTypeFullName` param (besides `add` method has it) and doesn't use `ensureListItemEntityTypeName` method inside.

**Comment by simkessy** [comment]
I think it would be pretty useful to batch update items like this, do you think that's something possible? I don't think the wiki example for batch update of list items is really representative.

**Comment by patrick-rodgers** [comment]
The wiki section you highlighted wasn't intended to show how to update a collection, but one item from that collection. It was put there in response to a question a long time ago.

The update method does not currently support passing in the listItemEntityTypeFullName but that is something we can add easily enough.

**Comment by patrick-rodgers** [comment]
And done in #587. For stuff like this you can always make the change and submit a PR :)

**Comment by simkessy** [comment]
THanks @patrick-rodgers , I'll have to study some TypeScript a bit more first before I feel comfortable making PRs. 

Cheers.

**Comment by patrick-rodgers** [comment]
It is a great way to learn. You get to read the code and see how things work and the design. Not saying the code in the library is perfect or the only way - but does give good examples of various patterns. Even if you don't end up submitting the PR it is still a good way to learn. Can you make it do what you want. Thanks for using the library!
