### ISSUE TITLE
Unable to inherit the interface after import pnp in typescript

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#582]
Hi,
I am working in SharePoint Online project with Typescript along with pnp js. I installed the sp-pnp-js via package.json file. In my code, I am using interface and I want to implement the interface in the class. In that class I want to use pnp code. Please find the code below.

**test123.ts - interface**
```
namespace Test123 {
      export interface IListService {
             getAllLists(): Promise<any>;
      }
}
```

After I import the pnp in the below code,  I am unable to inherit the interface.

**test.ts - class file**
```
import pnp from "sp-pnp-js;
namespace Test123 {
     export class PnpListService implements IListService {     
     }
}
```
I got the error as Cannot find name 'IListService'.
Kindly provide the solution to fix the error.

Thanks
Philip

**Comment by patrick-rodgers** [comment]
Hi Philip - this is a general development question and would be more appropriate for the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev). Having a quick look you need to also import the interface within your project. HTH

**Comment by spvjebaraj** [comment]
Thanks rodgers.
