### ISSUE TITLE
Any Planned Support For RenderListDataAsStream

### ISSUE THREAD

**Issue by rgarita** [SharePoint/PnP-JS-Core#584]
Hello

I'm wondering if there are plans to support RenderListDataAsStream, for lists. I just see RenderListData, on the library. 

Before any effort to add it and collaborate on the library, I'm wondering if there is a reason behind not supporting it now. As far I understood RenderListDataAsStream provides better performance than /Items endpoint

#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [  Latest       ]

**Comment by patrick-rodgers** [comment]
Just added it in #588. What would be great is if you could update the wiki page for items with a section on using that method. Any examples you have and an explanation - it isn't one where a lot of documentation exists.
