### ISSUE TITLE
User field

### ISSUE THREAD

**Issue by mame13fr** [SharePoint/PnP-JS-Core#586]
[ ] Enhancement

[ ] Bug

[X] Question

#### Expected / Desired Behavior / Question
Hello all,

I have a question.
I try to update an SP list item with a user field.
But, I can't update set the user field with an sharepoint loginname (example : z123456) 

What is the data to put into the user field please ??

Thanks for your help !!

Best regard

**Comment by koltyakov** [comment]
Hi @mame13fr,

REST API payload format reference can be helpful. PnP JS Core, as a REST API wrapper, uses native API interfaces.

To make a long story short:

```javascript
pnp.sp.web.getList('/sites/site/lists/list').items
  .add({
    UserFieldNameId: 12, // User/group id as a number
    MultiUserFieldNameId: {
      results: [1, 3] // User/Groups ids as an array of numbers
    },
  })
  .then(console.log)
  .catch(console.log);
```

**Comment by mame13fr** [comment]
Not working on my computer.

let list = pnp.sp.web.lists.getById(idList);
        return list.items.add({
            Title: "mon titre",
            userField: 17


           }).then ((iar: ItemAddResult) => {
            console.log("Ajout OK - ListId:" + idList + " ItemId:" + iar.data.ID);
            return iar.data.ID;
        }).catch(_ => {
            return false;
        });

Is there a configuration on SharePoint field ?
Show field : ID

**Comment by koltyakov** [comment]
You're providing wrong user field entity name. User field `EntityPropertyName` can be such (userField).
The lookup fields entity property names are ended with `Id` suffix.
Please check this [issue](https://github.com/SharePoint/PnP-JS-Core/issues/577) for details.

To make sure in properties names the following request can help:
```javascript
pnp.sp.web.lists
  .getByTitle("[Lists_Title]")
  .fields
  .select('Title,EntityPropertyName')
  .filter('Hidden eq false')
  .get()
  .then(console.log);
```

It's a very frequently met question, actually.

**Comment by patrick-rodgers** [comment]
@koltyakov - agree this seems to be coming up a lot recently. If you get a chance could you add a short section in the wiki about it? I will also try to remember but not sure when I'll get to it. Maybe on the [items](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items) page?

**Comment by koltyakov** [comment]
@patrick-rodgers - I've added [Resolving field names](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#resolving-field-names) section, please take a glance when you have a chance.

**Comment by patrick-rodgers** [comment]
Looks good, thanks!

**Comment by mame13fr** [comment]
Thanks a lot !!
