### ISSUE TITLE
Strong type support for property bag

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#590]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.8]

#### Expected / Desired Behavior / Question
It'd be nice to have a class to represent [SP.PropertyValues](https://msdn.microsoft.com/en-us/library/office/jj247075.aspx) and add a property on the [web class for AllProperties](https://msdn.microsoft.com/en-us/library/office/dn499819.aspx)
Something we could use like pnp.sp.web.allproperties.get() as a shortcut for https://github.com/SharePoint/PnP-JS-Core/issues/253
Having this on SPFolder as well would be good.
(we already have that for the role assignements for example)
Thanks!

**Comment by patrick-rodgers** [comment]
We talked through the strong typing in the other issue, let us know if you are still have questions. We have generally been avoiding adding properties to the objects such as AllProperties as you can select it out and each thing we add makes the file size larger (something that also gets mentioned frequently). The difference here in the case of AllProperties is that it is itself selectable (it is a collection) so it would give folks a way to get just the props they want. Let me think about it a little.

**Comment by AlexeyRipenko** [comment]
Hi,

I don't want to create an issue.
How can I add, update, delete property from allproperties?

**Comment by patrick-rodgers** [comment]
Hi @AlexeyRipenko - you cannot currently manage AllProperties via REST, you would need to use the CSOM libraries. This feature has already been requested (#455) and we can add support once it is available. Thanks!

**Comment by baywet** [comment]
Hey Patrick,
You removed the issue from 3.0.2 milestone, the original intent of that post was to get shorthands and type support for the properties.
Is it possible to get it back on? or for 3.0.3?
Thanks!

**Comment by patrick-rodgers** [comment]
I am not sure of the value of creating

**Comment by patrick-rodgers** [comment]
Added support for allproperties property on web object in #681. Closing this issue as resolved.

**Comment by baywet** [comment]
thanks !
