### ISSUE TITLE
not working for IE11

### ISSUE THREAD

**Issue by smguljar** [SharePoint/PnP-JS-Core#592]
#### Category
[ ] Enhancement

[ ] Bug

[* ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I was expecting it to work with IE11.

#### Observed Behavior
It says header missing

#### Steps to Reproduce
I followed [this link ](http://trycatchlearn.com/index.php/2017/05/08/develop-sharepoint-2013-addin-with-angular4-and-webpack-2/)to build a add in and using sp pnp js typescript library. It works for Firefox. But my users are mainly using IE11 as this is an internal application.

I found some guide but couldn't find how I can make it work in the way I am building using typescript and webpack as mentioned in the link above.

Thanks,

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by koltyakov** [comment]
For IE, you should load ES6-Promise and Fetch [polyfills](https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Install-&-Use#option-2---module-loader) before PnP JS Core.

**Comment by patrick-rodgers** [comment]
@smguljar - did you get a change to try @koltyakov 's suggestion? That should be all you need.

**Comment by quachhongak** [comment]
I was able to make it work but had to add "defer"... You got to love IE...

![image](https://user-images.githubusercontent.com/5651549/40014636-3d5d79b0-57db-11e8-8cc3-f4a8fc0b16dd.png)
