### ISSUE TITLE
Support for /_api/web/getsubwebsfilteredforcurrentuser

### ISSUE THREAD

**Issue by jpalo** [SharePoint/PnP-JS-Core#593]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Expected / Desired Behavior / Question
Please consider adding support for /_api/web/getsubwebsfilteredforcurrentuser. It is the only way AFAIK to get subsites (SPWebs) that works also for users with only Visitor (read-only) permissions.

#### Excuses
I'd love to do a PR, but due to Ignite and other things incoming I may not have possibility to do it in near future...

**Comment by patrick-rodgers** [comment]
This was submitted in a PR but can't be merged as is. I have asked for some changes - but we can get this added easily, thanks for the suggestion.

**Comment by patrick-rodgers** [comment]
This was just merged in #599 and will be part of the 3.0.1 release.
