### ISSUE TITLE
cannot find name 'PermissionKind' 

### ISSUE THREAD

**Issue by hmendezm** [SharePoint/PnP-JS-Core#594]
Hi Guys,

I am trying to use your example of permissions but I get the message cannot find name 'PermissionKind'.

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [  3.0.0       ]

#### Expected / Desired Behavior / Question
Able to use the example and get the current user permissions using pnp.sp.web.getCurrentUserEffectivePermissions, pnp.sp.web.hasPermissions and PermissionKind

#### Observed Behavior
I get the error "cannot find name 'PermissionKind'

#### Steps to Reproduce
I have a simple service with the following import and function
 import pnp from 'sp-pnp-js';
`
 getRoleAssignments() {

         // This is working
        pnp.sp.web.lists.getByTitle('Contract Details').items.orderBy('Modified').configure({
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json;odata=verbose'
            }
        }).get().then(r => {
            console.log(r);
        });
        
        // this is not working
        pnp.sp.web.getCurrentUserEffectivePermissions().then(perms => {

                if (pnp.sp.web.hasPermissions(perms, PermissionKind.AddListItems)
                        && pnp.sp.web.hasPermissions(perms, PermissionKind.DeleteVersions)) {

                   console.log('has permissions');
                }
            });
    }
`
Best regards
Hmendezm

**Comment by hmendezm** [comment]
Hi guys, 
I think I found my problem. I did not import 'sp-pnp-js/lib/sharepoint/types' is it right?

import { PermissionKind } from 'sp-pnp-js/lib/sharepoint/types';

Best regards
Henry

**Comment by patrick-rodgers** [comment]
I think that is exported within sp. [We moved](https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-2.0.*-to-3.0.*#exports-refactoring) around the exports in 3.0.0. The below should be all you need:

```
import { PermissionKind } from "sp-pnp-js/sp";
```

**Comment by patrick-rodgers** [comment]
I am in the process of rolling back the change to exports so in version 3.0.1 (not yet released) this will be:

```
import { PermissionKind } from "sp-pnp-js";
```
