### ISSUE TITLE
Upgrade to v3 doesn't work anymore with webpack externals and CDN version

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#595]
#### Category
[ ] Enhancement

[x] Bug

[x] Question

#### Version
Please specify what version of the library you are using: [3.0.0] (prev 2.0.8)

#### Expected / Desired Behavior / Question
Webpack external reference to work properly with CDN for performance reasons.

#### Observed Behavior
Following error message at runtime
```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at i (folders.js:7)
    at folders.js:66
    at Object.<anonymous> (folders.js:208)
    at n (bootstrap c4928171584e34d2af57:54)
    at Object.<anonymous> (lists.js:25)
    at n (bootstrap c4928171584e34d2af57:54)
    at Object.<anonymous> (webs.js:14)
    at n (bootstrap c4928171584e34d2af57:54)
    at Object.<anonymous> (sharepointqueryableshareable.js:14)
```

#### Steps to Reproduce
- Create a modern web project with webpack (not necessarily spfx).
- Add sp-pnp-js as an external in the webpack (2.X) config ('sp-pnp-js': 'window.$pnp',)
- Reference the web class as instructed by the [upgrade documentation] (https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-2.0.*-to-3.0.*) (`import { Web } from 'sp-pnp-js/sp';`, prev `import * as pnp from "sp-pnp-js";  and then pnp.Web`) 
- Reference the CDN version of sp-pnp-js 

#### workaround
Remove the external

**Comment by patrick-rodgers** [comment]
I'll have a look, likely this is due to not exporting everything at the root of the library. Unless you require something in 3.0.0 I'd say stick with 2.* if this is a key use case.

**Comment by patrick-rodgers** [comment]
I am reverting the change and will have everything published at the root as it was before. This should resolve the issue. I have just published a beta with that change, can you install the beta and give it a try?

```
npm install sp-pnp-js@beta
```

**Comment by baywet** [comment]
Thanks Patrick for looking into that, is the beta version hosted on a CDN somewhere? (if no I can push it to a web server for testing purposes)

**Comment by patrick-rodgers** [comment]
No, the beta ones don't get pushed to the cdn. Inside the package's dist folder should be the pnp.js which is the same file that would be.

**Comment by patrick-rodgers** [comment]
This appears fixed to me, so closing the issue and publishing the new version now. Thanks and sorry for the issue.

**Comment by baywet** [comment]
Thanks Patrick, and sorry for not trying it out earlier, I'm on something else ATM.
Did you revert that as well  (import { Web } from 'sp-pnp-js/sp';, prev import * as pnp from "sp-pnp-js"; and then pnp.Web) ??

**Comment by baywet** [comment]
investigating I could see you removed the upgrade sequence from the wiki.
I also took time to go across all our projects, noticing some imports are done using sp-pnp-js/... and not the global alias because the interfaces/classes are not exposed.
From a bundling perspective, with the external, it results in duplicated imported code.
Is it possible to expose PnPClientStore and SiteUserProps ?

**Comment by patrick-rodgers** [comment]
Yes, can you please create a separate issue - I know that is a pain, but helps us track things.
