### ISSUE TITLE
Shouldn't be SiteUser exported in sp-pnp-js/sp?

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#596]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [3.0.0]

#### Expected / Desired Behavior / Question
`pnp.sp.web.siteUsers.getbyEmail()` returns a `Promise<SiteUser>`  
`pnp.sp.web.siteUsers.get()` return `Promise<any>` because of the way `ODataQueryable` are built. The proper way to get strong types and compile time validation is to use `getAs()`.   
One would asume `getAs<SiteUser[]>()` would be the proper thing to do, however that class isn't exported which forces the consumer to either leverage either SiteUserProps or do a direct import of the class (via sp-pnp-js/lib/sharepoint/siteusers').  
What would be the proper approach?

**Comment by patrick-rodgers** [comment]
You are conflating the class we use internally "SiteUser" to build the rest request with data returned by that class. If you look at the SiteUser class it doesn't contain any properties. The idea behind the getAs is that you would have a data class you are using with the properties you want. [This article](https://github.com/SharePoint/PnP-JS-Core/wiki/Extending-with-Custom-Business-Objects) in the wiki tries to explain the getAs function. We don't export SiteUser class as it is unlikely folks would have a use for it - easy enough to change if that helps a use case you can outline.

getByEmail doesn't return any data, it just gives you the next piece in the method chain (and doesn't return a promise if I am looking [at the right spot](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/sharepoint/siteusers.ts#L35).

The idea behind this is that we don't know what properties you want at design time, so we can either include interfaces listing every property on every object (as you mention in #590) or let the developers handle it, which in my opinion is correct as you would know what properties you want and often want to add your own methods, etc.

Does that help explain things?

**Comment by baywet** [comment]
**For the SiteUsers:** 
Thanks @patrick-rodgers that clarifies a lot the point. We'll leverage SiteUserProps as we're only interested in the default props in that case.

**For the general library:** 
 I think then my only "issue" is that get returns Promise<any>. **That takes away a lot of the benefits of TypeScript and junior devs won't look at getAs<T>.**
This is the same kind of discussion we were having here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19430 (I still need to write the PR for that...)

Having it leveraging generic types would be a way to enforce best practices (comes at the cost of a breaking change now), and people can sill call get<any> if they're not happy with having types :)
**I don't thing this is something worth changing now in the lib since you have getAs<>, but I think the doc should push people to leverage getAs instead of get (samples, getting started...)**
Does that make sense?

**Comment by patrick-rodgers** [comment]
Get returns in many cases a Promise<any>, yes - but you can always type that. Meaning the below is valid:

```TypeScript

interface MyFields {
   Title: string;
   Description: string;
}

pnp.sp.web.lists.getByTitle("MyList").items.top(5).select("Title", "Description").get().then((items: MyFields[]) => {
// ...stuff happens
});
```

The typing stuff is really just there for convenience at the end of the day it is all removed once you transpile to JS. I envision folks creating their own interfaces as needed for simple intellisense/type checking OR using getAs when they want to create a custom class inherited from one of our base classes.

**Comment by baywet** [comment]
Thanks for the precision.
Again I feel that pushing people to leverage generic typing would help them leverage compile time validation by default rather than not knowing and writing tons of implicit any. Adding `:MyFields[]` is not obvious for most of the devs and running the chance in having run time errors that could have been avoided.
Using noImplicitAny in tsconfig is not the best solution because some libs bring implicit any.
Closing for now as I don't think anything will be changed at this point.
