### ISSUE TITLE
creating 2 related items in 2 deferent sharepoint list using pnp in Sharepoint hosted Addin

### ISSUE THREAD

**Issue by sbhamouda** [SharePoint/PnP-JS-Core#598]
Category :
[X ] Question
Version :
last version

Desired Behavior / Question :

i want to create 2 item in 2 different list "RequestList"  and "History" the problem that i couldn't succeed because in the second item I need the id of the first created. 
when i put a static value in the second list title it works but when i need to passe the id of the item created in first I get a null value in the title always. so any idea or suggestion to get this through, would be a life savior ( @patrick-rodgers @koltyakov ) . 

my code is like below : 
****************************************************************************************************
function createNewRequest(){
var currentItemID ;
    var myDate = new Date();
    var itemDero = { 
       Title: myDate, 
       CodeRequest: "1234",
       Requester : "Ben"};
    $pnp.sp.crossDomainWeb(addinweb1,hostWeb1)
          .lists.getByTitle("RequestList")
          .items.add(itemDero)
          .then(function (result) {
                     console.log("Item Request Added");
                     console.log(result.data);
                     console.log(result.data.Id);  
                     currentItemID = result.data.Id;
                      console.log("currentcreatedID",currentItemID );
           }).catch(function (err) {
                      console.log(err);
                      console.log("Item Request failed");
    });;

    $pnp.sp.crossDomainWeb(addinweb1, hostWeb1)
                     .lists.getByTitle("History")
                     .items.add({
                            Title: currentItemID
                      }).then(function (r) {
               console.log("Item History Added");
              console.log(r.data);
              console.log(r.data.Id);
          }).catch(function (err) {
               console.log(err);
               console.log("Item History failed");
           });
}
****************************************************************************************************

**Comment by patrick-rodgers** [comment]
This is a question more appropriate for the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) as it is a general development question.

You would need to chain the results to add the first item, then add the second item in the "then" clause. Something like:

```
pnp.sp....items.add({}).then(r => {
  pnp.sp....items.add({
    Title: r.data.Id,
  });
```
