### ISSUE TITLE
PnPClientStore and SiteUserProps interfaces are not exposed

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#603]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.1]

#### Expected / Desired Behavior / Question
Follow up bug of https://github.com/SharePoint/PnP-JS-Core/issues/595
Interfaces PnPClientStore and SiteUserProps (and maybe others but these are the ones I need) are not being exposed on the pnp module preventing from referencing those like that 
```
import * as pnp from 'sp-pnp-js';
///... 
pnp.PnPClientStore
```

This causes an issue during bundling process (basically duplicates the code) with external references from CDN.

These interfaces should be exposed at the pnp module

**Comment by patrick-rodgers** [comment]
SiteUserProps was previously exported so that one should be there. I have just added, #611, exports for everything exported from the storage utils/module so next version will surface those.

**Comment by baywet** [comment]
Thanks, I'll watch for the next version!
