### ISSUE TITLE
Error with v3.0.1 before deploy on SP16

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/PnP-JS-Core#604]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

-------------------------------------------------------------------------------------------------------------------

Before deploy my SPFx v1.0.2 webpart in SP16 I execute **gulp bundle --ship** and terminal gives me following error:

> [09:09:07] ==================[ Finished ]==================
> Error - typescript - src/webparts/spFxOnPrenPnPjs/SpFxOnPrenPnPjsWebPart.ts(19,8): error TS2345: Argument of type '{ headers: { "Accept": string; }; }' is not assignable to parameter of type 'LibraryConfiguration'.
> Error - 'typescript' sub task errored after 1.74 s

The version of pnp is lastest  - **v3.0.1;** Code works good with pnp - **v2.0.8**

![My Code](https://user-images.githubusercontent.com/14110861/30681496-554b6730-9eae-11e7-87e4-73d7a0884335.png)

I use code from this sample : [HERE](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/sharepoint-crud/src/webparts/spPnPJsCrud/SpPnPJsCrudWebPart.ts)

**Comment by s-KaiNet** [comment]
In 3.x you need to write  
```javascript
pnp.setup({
    sp: {
        headers: {
            'Accept': '.....'
        }
    }
})
```

**Comment by geogikk92** [comment]
This is working! Best regards 👍

**Comment by patrick-rodgers** [comment]
Thanks @s-KaiNet! @geogikk92 it looks like you are all set, will close this issue.
