### ISSUE TITLE
SourceId within Search is not working

### ISSUE THREAD

**Issue by ttalies** [SharePoint/PnP-JS-Core#605]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.0]

#### Expected
Result Source is choosen for search results

#### Observed Behavior
No results from choosen result source are delivered.

#### Steps to Reproduce
Hi,
I ran into the same problem. When I try to set the SourceId within the search, it is ignored.

We defined a custom result source and set it as default. Now I want to get the results of the OOTB resulte source "Local SharePoint results" ID 8413cd39-2156-4e00-b54d-11efd9abdb89.

But all results I get are within the custum result source.

Here is my code:

pnp.sp.search({
Querytext: "test",
RowLimit: "10",
SourceId: "8413cd39-2156-4e00-b54d-11efd9abdb89",
EnableInterleaving: true,
}).then((results) => {
let _resultset = [];
for (var i=0; i < results.PrimarySearchResults.length; i++)
{
_resultset.push(results.PrimarySearchResults[i]);
};
this.setState({resultset1: _resultset});
}
);

**Comment by ttalies** [comment]
Maybe it helps:

The error i get back is:
400 BAD REQUEST

Response:
{"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"de-DE","value":"Ein primitiver Wert kann nicht in den erwarteten Typ \"Edm.Guid\" konvertiert werden. Detailinformationen finden Sie in der inneren Ausnahme."}}}

**Comment by patrick-rodgers** [comment]
I don't remember much german from school, but that looks to me like a guid format error? If so you can try different variations of the GUID format. For example with the "{...}" brackets or all in lower/upper case.

**Comment by patrick-rodgers** [comment]
Going to close this as we haven't heard back on the guid format suggestion. If you are still having trouble please _reopen_ this issue so we can assist. Thanks!
