### ISSUE TITLE
getFolderByServerRelavtiveUrl in modern Site Page includes '/SitePages' in get request

### ISSUE THREAD

**Issue by TrustLRon** [SharePoint/PnP-JS-Core#606]
#### Category
[ ] Enhancement

[ X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.0.1 ]

#### Expected / Desired Behavior / Question
I have a webpart on a modern SitePage "TestSitePage" in a modern team site (located at "https://mytenant.sharepoint.com/sites/Test"), using `pnp.sp.web.getFolderByServerRelativeUrl('TestFolder').folders.get()` should call a GET request on `https://mytenant.sharepoint.com/sites/Test/_api/web/getFolderByServerRelativeUrl('TestFolder')/folders`

#### Observed Behavior
instead, the GET request call `https://mytenant.sharepoint.com/sites/Test/SitePages/_api/web/getFolderByServerRelativeUrl('TestFolder')/folders` and i get a 404 on the request

if i use the same webpart with the same function call on a wiki page it works fine.
tested with the full relative path ("/sites/Test/TestFolder") and got the same result.

#### Steps to Reproduce
1. create a modern team site
2. create a modern site page on that team site
3. add a webpart on that page that uses getFolderByServerRelativeUrl to get a folder from the site collection
4. get a 404

5. try same steps on a wiki page and it works ok

Thanks!

**Comment by KEMiCZA** [comment]
Hi @TrustLRon,

Check out this wiki: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

Also issues: [579](https://github.com/SharePoint/PnP-JS-Core/issues/579) & [522](https://github.com/SharePoint/PnP-JS-Core/issues/522)

**Comment by TrustLRon** [comment]
Awesome, thanks for pointing me in the right direction.  Setting the `spfxContext `in the `oninit ` in my `webpart.ts` has fixed the issue.
