### ISSUE TITLE
Create folder using a custom content type

### ISSUE THREAD

**Issue by NigelWit** [SharePoint/PnP-JS-Core#607]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Question

Is it possible to create a folder of a custom content type (I.e. A content type that inherits the ootb 'Folder' content type), and then set some metadata values on the created folder item??

**Comment by NigelWit** [comment]
Ok figured it out - need to create the folder, then get the associated item by id, then set content type:

// create the folder
    await web
      .lists
      .getByTitle(listTitle)
      .rootFolder
      .folders
      .add(folderName)
      .then(results => {

        // get the id of the created folder
        return results
        .folder
        .listItemAllFields
        .get()
        .then(folderAllFields => {
           

          // update the associated list item to the desired content type and field values
          return web
          .lists
          .getByTitle(listTitle)
          .items
          .getById(folderAllFields.ID)
          .update({
            Title: folderName,
            ContentTypeId: ctId,
            CustomField: customFieldValue
          });
        })


Thanks!

**Comment by patrick-rodgers** [comment]
Nicely done! Sorry for the delay in responding, I am out on family leave. Thanks for using the library.
