### ISSUE TITLE
Is it possible to query using the Result Source name instead of using the id

### ISSUE THREAD

**Issue by kmcknight1973** [SharePoint/PnP-JS-Core#608]
Category

[ ] Enhancement

[ ] Bug

[ X] Question

**Question**
Apologies if I've overlooked this, but is it possible to give a source name instead of SourceId for SharePoint search as from what I've read it doesn't seem possible unlike a direct ajax call?

Example taken from [(How to query using the Result Source name instead of using the id):](http://www.techmikael.com/2015/01/how-to-query-using-result-source-name.html)

> https://server/site/_api/search/query?querytext='*'&properties='SourceName:Your Source Name,SourceLevel:SPSite'

Thanks.
Keith

**Comment by patrick-rodgers** [comment]
Yes, the below works for me. You need to create the two properties and add them to the query. I used the query builder class to help with that, though would work the same to construct and pass a plain object for the SearchQuery value. HTH.

```TypeScript
import pnp, {
    SearchQueryBuilder,
    SearchProperty,
    QueryPropertyValueType,
} from "sp-pnp-js";

const q = SearchQueryBuilder.create().properties({
    Name: "SourceName",
    Value: {
        QueryPropertyValueTypeIndex: QueryPropertyValueType.StringType,
        StrVal: "{{Your SourceName }}",
    },
}, {
        Name: "SourceLevel",
        Value: {
            QueryPropertyValueTypeIndex: QueryPropertyValueType.StringType,
            StrVal: "SPSite",

        },
    });

pnp.sp.search(q).then(r => {

    console.log(JSON.stringify(r, null, 4));

});
```

**Comment by patrick-rodgers** [comment]
Closing this as answered, please _reopen_ if you continue to have issues. Thanks!
