### ISSUE TITLE
New web(url) and get list items

### ISSUE THREAD

**Issue by hmendezm** [SharePoint/PnP-JS-Core#609]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 3.0.1]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Observed Behavior
I am developing a dashboard that it gets data from different subsites and list. So I need to dynamically  change the subsite and get the data from different list so I have the following code
`
    private function(siteUrl: string, listName: string, year: number) {

        const web = new Web(siteUrl);

        web.lists.getByTitle(listName).items.get().then(result => {
            console.log(result);
        });

    }
`
If I have web.lists.getByTitle(listName).items I got the below error. If I have web.lists.getByTitle(listName) it is working but I do not know how to get the data (see image below).  

**_ERROR Error: Uncaught (in promise): ProcessHttpClientResponseException: Error making HttpClient request in queryable: [500] Internal Server Error_**

![image](https://user-images.githubusercontent.com/1881431/31036201-2c1c504a-a539-11e7-85ec-29b511892454.png)

**Comment by patrick-rodgers** [comment]
Your code looks fine. Are you able to get the inner exception message that might give us a clue as to what is failing when you request the items. Can you access this list through the UI and see the items? Can you switch the list name and get items from others lists in the same site?

**Comment by hmendezm** [comment]
I fixed this by adding .select.  sorry that I did not come back to update this.

 const web = new Web(siteUrl);

    web.lists.getByTitle(listName).items.select(....).get().then(result => {
        console.log(result);
    });
}

**Comment by patrick-rodgers** [comment]
Great, glad you're unblocked. Thanks!
