### ISSUE TITLE
Ability to manage workflows

### ISSUE THREAD

**Issue by araver** [SharePoint/PnP-JS-Core#610]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.0 ]

#### Expected / Desired Behavior / Question
I think it be nice to have the ability to start and stop workflows.  This functionality is available through the regular rest API.

**Comment by patrick-rodgers** [comment]
Is this something you would be interested in developing and submitting via a Pull Request?

**Comment by araver** [comment]
Yes.

**Comment by patrick-rodgers** [comment]
Did you have a chance to work on adding this functionality?

**Comment by araver** [comment]
I've started a fork. But I haven't made very much progress yet.

**Comment by dcgit** [comment]
What are the intended workflow versons that will be supported?

**Comment by patrick-rodgers** [comment]
@araver - did you have any details on your plans or releated to @dcgit 's question?

**Comment by araver** [comment]
I was planning on doing it for 2013 workflows. I'm not familiar with any 2010 workflow APIs.

**Comment by russgove** [comment]
can you do that with rest? i thought tat was only in jsom.

**Comment by koltyakov** [comment]
@russgove, there is something in REST for managing workflow instances. E.g.: `/_api/SP.WorkflowServices.WorkflowInstanceService.Current/StartWorkflowOnListItemBySubscriptionId(subscriptionId=`${WorkflowGUID}',itemID=${ItemID})`

**Comment by dcgit** [comment]
Also of note, im using the older spservices library to run 2010 workflows clientside so im not sure what thats doing but it for sure it different for 2013. Not sure about 2016 but maybe plan on targeting versions in your implementation athough i wouldny expect you to have to implement them all right now.

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity. If you do pick back up the work to add support for workflow management please do reopen so we can track. Thanks!
