### ISSUE TITLE
Converting property values of fieldValueAsHtml to normal field static name

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP-JS-Core#612]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

Is there any utility function in pnp that converts fieldValueAsHtml property values into normal field static name?

E.g:
**Normal field Title:**
test field
**In FieldValuesAsHtml:**
test_x005f_x0020_x005f_field
**While in field StaticName:**
test_x0020_field

Another sample:
**Normal field Title:**
test yes/no
**In FieldValuesAsHtml:**
test_x005f_x0020_x005f_yes_x005f_x002f_x005f_no
**While in field StaticName:**
test_x0020_yes_x002f_no

Not quite sure whether it's just gonna be a simple "_x005f" matching.

**Comment by koltyakov** [comment]
Hi @jonathanhotono,

It's mostly the question not to the library but to the way how REST and SharePoint behave in particular.
When a field with unsupported character(s) in the name is created the internal name changes. Then using REST EntityPropertyName also can be different in some circumstances. 

What I usually recommend in such a case:

- Create new fields with reliable for programming names, e.g.:
  - Let's take a `test field` you mentioned
  - First, creating the field it better to use internal names style, it can be `TestField01` (no spaces, no special characters, no numbers in the beginning, `fieldName === encodeURIComponent(fieldName)`)
  - After the field is created, rename its display name to anything else like `Test Field` the internal name stays the same
  - EntityPropertyNames are also predictable with this approach
- Steps above can be avoided using provisioning tools and managing internal names (anyway the name should be programming-friendly)
- Deal with already created and 'spoiled' fields field names and entity properties names can be requested strictly before applying further business logic, please check [this wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#resolving-field-names)

**Comment by patrick-rodgers** [comment]
Closing this as answered, please _reopen_ if you have further questions on this topic. Thanks!

**Comment by jonathanhotono** [comment]
@koltyakov Thanks. Yes, my case is dealing with already created/spoiled fields field names.
