### ISSUE TITLE
Is it possible to override savePage method on click Save and Close button from SPFX

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/PnP-JS-Core#614]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [   
"microsoft/microsoft-graph-types": "^1.0.1",
    "microsoft/sp-core-library": "~1.2.0",
    "microsoft/sp-webpart-base": "~1.2.0",
    "types/webpack-env": ">=1.12.1 <1.14.0",
    "he": "^1.1.1",
    "office-ui-fabric-react": "^5.1.0",
    "sp-client-custom-fields": "^1.3.7",
    "sp-pnp-js": "^3.0.1"     ]

#### Expected / Desired Behavior / **Question**
I have a modern page with custom spfx webparts. My spfx webparts contains office ui fabric react components such as PeoplePicker and TaxonomyPicker. 

After user enters the data and clicks save or save and close button, I need to override the event handler for Save event to save the information into the page. My idea is that I should override that Save event handler method so that my webpart callback handler will be called and updates the Page ListItem metadata. I also found onDisplayModeChanged event in the webpart from here, I am not sure how to find if the event is Save and close or Discard Changes. 

Can anyone please suggest which is the elegant way to do that?

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @arunakshi - as this is a general development question and not related directly to the library I'd encourage you to post it in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev). Thanks!

**Comment by arunakshi** [comment]
Hi Patrick, thank you for your reply. I will post the same in tech community.
