### ISSUE TITLE
Is this Library going to be supported ongoing?

### ISSUE THREAD

**Issue by pconnell99** [SharePoint/PnP-JS-Core#617]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ PnP-JS-Core ]

#### Question

I have been trying to use the library for short while now, and am worried that, due to the seeming lack of documentation/features that this library is a dead-end for ongoing commercial development purposes.

Is there any assurance that this library will be enhanced and expanded ongoing in the near future, and sufficient resources are going to be assigned to it, or should I just cut my losses now and migrate to another library?

**Comment by koltyakov** [comment]
Hey @pconnell99,

There are no reasons to worry, IMO.
You can definitely use the lib as a dependency on your projects, without great fear of `dead-end`.
There is some work in migrating sp-pnp-js to [@pnp/sp](https://github.com/pnp/pnp) (it's in beta). The reasons of moving the lib to @pnp namespace are to add more modularity and a room for extending APIs (e.g. add Graph API wrapper). And this is a good news, that any kind of worries.

We decided to keep using sp-pnp-js 3.x on production projects and switch to @pnp/sp on its release next year.

P.S. I also tried the beta on some of my projects and it worked without great changes to the code. In our team, we think about it (new namespace) as a planned major update, which should not be complex.

**Comment by patrick-rodgers** [comment]
HI @pconnell99 - to add to what @koltyakov says: This library will be supported for at least 6 more months, at which point we will encourage folks to transition to the @pnp scoped libraries. Once we get to that point we'll have a clear transition guide.

Regarding the documentation & features comment you made. If you have suggestions for missing features, you can always submit them as an issue and we'll review and see if it fits - or you can always submit a PR with new functionality. For documentation p[lease do check out the wiki](https://github.com/SharePoint/PnP-JS-Core/wiki) if you haven't. We do our best to write docs and update as possible, but there is always room for improvement. Again, an issue describing missing docs is appropriate and helps us prioritize.

Thanks!

**Comment by pconnell99** [comment]
One particular area  was webpart support, documentation was sparse, and the NodeFetchClient config was wrongly documented (I edited the wiki for that though).

It's all a bit of a mess at the moment, my boss is saying we'd move to C# as it's better supported.  Not sure how to counter that.  Happy to close though.
