### ISSUE TITLE
addAvailableContentType throws error if ct contains field with validation formula

### ISSUE THREAD

**Issue by gruering** [SharePoint/PnP-JS-Core#618]
We have a content type containing fields with validation formulas. The content type cannot be bound to a list via pnp js. 

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

[PnPCoreJS:2.0.5]

#### Expected / Desired Behavior / Question
is this a bug in the rest service: /contenttypes/addAvailableContentType  ?
Our current workaround is to remove the formulas. 
We would like to add content types having fields with validation formulas.

#### Observed Behavior
Adding the content type via the UI works fine. The formulas of the fields do not contain any errors.
The error only happens while adding the content type programmatically

Response Body:
{
  "error": {
    "code": "-2130575270, Microsoft.SharePoint.SPException",
    "message": {
      "lang": "de-DE",
      "value": "Die Formel enthält einen Syntaxfehler oder wird nicht unterstützt."
    }
  }
}

Looks like a localization issue to me. 

#### Steps to Reproduce
create a site column containing a validation formula (on a site with de-de language as default language)
add this column to a content type
add the content type to a list via addAvailableContentType API  -> error 500

**Comment by patrick-rodgers** [comment]
That doesn't seem like a bug with the library, but open of course to fixing it if it is. That error translates to "The formula contains a syntax error or is not supported."

Have you tried via the CSOM library just to test if that works programatically? I haven't looked but I believe these share the same code path internally. Also, can you share your code or the formula in question?

**Comment by gruering** [comment]
Agree, it looks like an error in the rest service and not the library. 
The formula is: 
`=[Fertigstellung]<>""=(ODER([Fertigstellung]>HEUTE()))`
I will try via CSOM and let you know if that works.  I assume it has something to do with the culture.

**Comment by gruering** [comment]
Same error via CSOM.
However translating the formula to english did resolve the error.
Thank you for your support.
