### ISSUE TITLE
Setting Default Content Type

### ISSUE THREAD

**Issue by jtgdnet** [SharePoint/PnP-JS-Core#619]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
3.0.1

#### Question
Hi, I am trying to find the relevant methods/approach to set the default content type for a SharePoint list, but cant seem to find anything anywhere, either in documentation or an example.

Can anyone point me to a resource or in the right direction to achieve this?

Thanks.

James.

**Comment by patrick-rodgers** [comment]
You set the default content type by setting the content type order in the list. We don't currently have that method implemented as it doesn't appear to work via rest (the execution is ignored). So unfortunately the CSOM or JSOM is the best way to achieve this currently. If someone can come up with a working test we can def add to the library, but my tests in the past have failed.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ if you have additional questions. Thanks!
