### ISSUE TITLE
Check user access to specific site.

### ISSUE THREAD

**Issue by hmendezm** [SharePoint/PnP-JS-Core#620]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

 [ 3.0.1 ]

#### Expected / Desired Behavior / Question
SiteCollection has many subsites. Users have access to all subsites or some subsites. I am working in a dashboard that goes in the Site collection level. I have information that comes from subsites and for this reason, I need to check what subsites the logged in user has access. 

I am using the code below but I have the problem that every time the code check permission in subsite where the user does not have access is prompting the login window(which kinda makes senses). The idea behind the dashboard is to avoid this window and just show the user the calculations and information in a centralized way. 
`

 const web = new Web(siteUrl)

        web.getCurrentUserEffectivePermissions().then(perms => { //WINDOWS POPUP HERE//

             if (web.hasPermissions(perms, PermissionKind.AddListItems)
                 && web.hasPermissions(perms, PermissionKind.EditListItems)) {

                 userHasPermission = true;
                 console.log('Access');
             }
             else {
                 userHasPermission = false;
                 console.log('NOT Access');
             }
        })
        .catch(err => console.log(err));

`

I really need help!!!

Thanks!

**Comment by russgove** [comment]
Couldn't you use search to see what sites the user has access to?

**Comment by patrick-rodgers** [comment]
Sure, but if you don't have a list of all the sites you can't say they don't have access to a site they can't see. It really depends on the particulars of what the goal of this is.

**Comment by hmendezm** [comment]
Hi Patrick, the dashboard is not about permissions. This dashboard is more bring data from different subsites to a centralized dashboard. Subsites are maintaining by a different group of people and their managers need to see in a  concentrated way the information from the subsites.
 So I change my approach and I am using getSubwebsFilteredForCurrentUser. I do not like to use elevated permission. I like more depend in the Security trim from SharePoint and let SharePoint to filter what user can see or no. The only thing I have to do is to give visitor access to the users in the site collection level(not big deal for this case) and use the following code:

`
   const web = new Web([sitecollectionUrl]);

        return web.getSubwebsFilteredForCurrentUser().get()
            .then(function (searchResult) {
                return searchResult.map(function (x) { return { title: x.Title, relativeUrl: x.ServerRelativeUrl } });
            })
            .catch(function (error) {
                console.log(error);
            });
`
Thanks for your replies
best regards
Henry

**Comment by patrick-rodgers** [comment]
Yes, 100% agree about relying on SP security trimming, was just brain storming. Sounds like you got things figured out, glad to hear it! I am going to close this thread, but please do _reopen_ if you need to ask additional questions on this topic. Thanks!
