### ISSUE TITLE
Creating ClientSidePages

### ISSUE THREAD

**Issue by hohenp** [SharePoint/PnP-JS-Core#623]
#### Category
[x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Would be great to have an easy way to create client side pages using pnp-js. In PNP-Powershell there is the method "AddClientSidePage" within the web class to do that very easy. Would it be possible to have that within PNP-JS-Core?

Thanks!

**Comment by gitzimm** [comment]
I take it your saying...
1. Create a page (like wiki)
2. Add Web Part to zone X (like Content Editor)
3. Update Web Part Properties (like link to HTML file to show in CE Web Part)

I'd Love this as well!

Thanks

**Comment by patrick-rodgers** [comment]
Issue is there is not the same level of support or creating pages and adding web parts via REST as there is for CSOM library. Agree it would be a great feature but we don't have the API to call to enable this.

Once I am back from leave I am hoping we'll have more for modern sites so we can provision things at least there.

**Comment by Halwsa** [comment]
+1 I would also love to create modern pages through PnP-JS-Core.

@patrick-rodgers Did I understand right that we cannot create modern pages from javascript OOTB APIS, if we can do it with csom we can do it with a rest call correct ?

**Comment by patrick-rodgers** [comment]
CSOM and REST are different APIs so being able to do it in one does not always mean it is available in the other. That being said, I am still on leave but when I get back need to reviews the updates to the REST api - we may very well be able to add this functionality. Thanks!

**Comment by patrick-rodgers** [comment]
It took some time but have now added support to add and edit client side pages with PR #719 which will be part of 3.0.5 version to be released on Feb 12. Going to close this issue as resolved. Added [a wiki page on usage](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Client-side-Pages) as well.
