### ISSUE TITLE
Assigned To Name

### ISSUE THREAD

**Issue by aremorgan** [SharePoint/PnP-JS-Core#625]
[ ] Enhancement

[ ] Bug

[X] Question

v3.0.1 Version

Sorry if this has been asked before, i couldn't find a complete example anywhere and i realise it must be something simple.

I have a out of the box task list, how can i get the Name of the person in the Assigned To field?

I have 

$pnp.sp.web.lists.getByTitle("Tasks").items.select("ID, Title, AssignedTo/Name, AssignedTo/Id").expand("AssignedTo").get().then(function(result) {
    var fieldInfo = "";
    for (var i = 0; i < result.length; i++) {
        fieldInfo += "Title: " + result[i].Title + "<br/>";
        fieldInfo += "ID:" + result[i].Id + "<br/>";
        fieldInfo += "assigned To:" + result[i].AssignedTo + "<br/><br/>";      
    }
    document.getElementById("sample").innerHTML = fieldInfo;
}).catch(function(err) {
    alert(err);
});

All i get in result[i].AssignedTo is [object Object] how ever i try and show the details i get different errors.

thanks

**Comment by koltyakov** [comment]
Hey,

`AssignedTo` field in the OOTB Tasks list `SP.FieldUser` with `AllowMultipleValues` = true.
So it has the shape of an array of object in the response.

You need to take out props from it, e.g. `result[i].AssignedTo[0].Name` or `result[i].AssignedTo.map(function(user) { return user.Name; }).join(', ')`.
You can always console.log the object and check its shape in browser Dev Tools.

Maybe the following also would be good to know:
- Name stands for the login information
- More info can be extracted from user lookups (e.g. AssignedTo/Id, AssignedTo/Title, AssignedTo/EMail, AssignedTo/Name) - Title stands for user display name

**Comment by aremorgan** [comment]
Thanks Andrew, that's a big help.
