### ISSUE TITLE
Delete Multiple Attachments to a list item

### ISSUE THREAD

**Issue by CoderGeet** [SharePoint/PnP-JS-Core#626]
[X] Enhancement

[ ] Bug

[ ] Question

Version: 3.0.1
SharePoint On Premise

We have an addMultiple method that we can use to upload multiple attachments to a SharePoint list item. Can we have a **deleteMultiple** functionality as well which we can use to delete multiple attachment files from a list item. This method will help in take care of chaining operations.

Thanks!

**Comment by patrick-rodgers** [comment]
Funny you should ask, this very method is [currently sitting in the dev branch](https://github.com/SharePoint/PnP-JS-Core/blob/dev/src/sharepoint/attachmentfiles.ts#L70). It will be part of the next release - which will be once I am back from family leave here in a few weeks. This was actually [submitted as a PR](https://github.com/SharePoint/PnP-JS-Core/pull/621) and merged (I think) last week.

I'll leave this open until the release is made.

Thanks!

**Comment by CoderGeet** [comment]
That is awesome Patrick. Thank you so much. Looking forward for the next release. 

Thanks!
