### ISSUE TITLE
creating a 'Document Set' possible?

### ISSUE THREAD

**Issue by setras** [SharePoint/PnP-JS-Core#627]
Hi,
 I need to create a 'document set' in an Sharepoint Online document library but can only find a folder create function. Is it possible?

The only REST examples I could find  use the `url: webUrl + "/_vti_bin/listdata.svc/" + listName,` endpoint, which I can't get working, get an 500 Error.

**Comment by koltyakov** [comment]
Hi @setras,
 
Everything dull with DocSets. There is not REST API for them. A workaround is using JSOM. Please check this issue https://github.com/SharePoint/PnP-JS-Core/issues/332, the current one is a duplicate of it.

**Comment by setras** [comment]
Thanks @koltyakov for the Info. 
As I'm new to JSOM and PnP-JS, I need to use it in a Content/Script Editor WebPart correct?

**Comment by koltyakov** [comment]
JSOM/REST in general cases are used as a client-side solutions.

In SharePoint, there is a bunch of possibilities delivering client-side code. Some of them are:

- CEWP (content editor web part)
- SEWP (script editor web part)
- Script link User custom action
- Part of the page
- Part of page layout
- Part of masterpage
- SPFx web parts
- Search templates
- CSR (forms, list views, fields)
- and so on...

But it's a separate story from PnP JS Core as it's more generic question about SharePoint development.
Feel free to ping me in Gitter with generic SharePoint questions, sometimes I have some time to chat and answer.

**Comment by setras** [comment]
will do thanks
