### ISSUE TITLE
Get URL of List Item not the list.

### ISSUE THREAD

**Issue by aremorgan** [SharePoint/PnP-JS-Core#628]
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

v3.0.1 Version

Hi I have a requirement to read items from a list that exists in a lot of Sub Sites (around 300).
The code is below.
` function buildTargets(){
    for (j=0; j<projects.length; j++){
        var parent = projects[j].ID
        var web = new $pnp.Web("https://xxx/Project/"+projects[j].ID);
        web.lists.getByTitle('Targets').items.get().then(function(result) {
            for (var i = 0; i < result.length; i++){
                var title = "***URL***"
				var newId = result[i].Id
				addNode(parent, title, newId,false)
            }
        }).catch(function(err) {
             alert(err);
        });
    }
 }`
The "Projects" object holds the url of all the subsites that I need to read. my issue is that when reading the items from the list I need the variable title to hold the URL of the list. Obviously cannot use the variable "parent" within the loop and I canot find a property against the list item that will tell me it's list url.

I'm I missing something obvious?

Thanks
Andrew

**Comment by koltyakov** [comment]
Hey Andrew,

300+ requests is a huge and heavy operation, it's recommended using search API for such roll-up.
There will be some delay in data relevance but no performance issues.
If it were a number around 10 webs/lists to roll-up I would suggest something like (definitely in TypeScript):

```typescript
// nometadata - saves some traffic reducing response packages size
// works in SPO, 2016 out of the shelf, 2013 require some OData server setup
pnp.setup({
  sp: {
    headers: {
      Accept: 'application/json; odata=nometadata'
    }
  }
});

let getRollupData = async (websNames: string[], listName: string, selectFields: string) => {
  let rolledUpItems = [];
  for (let webName of websNames) {
    let webUrl = `${_spPageContextInfo.webAbsoluteUrl}/${webName}`;
    let web = new pnp.Web(webUrl);
    let items = await web.lists.getByTitle(listName).items.select(selectFields).get();
    rolledUpItems = rolledUpItems.concat(items.map(item => {
      return {
        ...item,
        webUrl 
      };
    }));
  }
  return rolledUpItems;
};

getRollupData(['web1', 'web2', 'web3'], 'Target', 'Id,Title')
  .then(console.log)
  .catch(console.log);
```

But this is damn heavy for hundreds of lists, so search/pre-calculations is an architectural choice.

**Comment by aremorgan** [comment]
Thanks for the advice Andrew.
