### ISSUE TITLE
The parameter matchUserInfoList does not exist in method ResolvePrincipalInCurrentContext.

### ISSUE THREAD

**Issue by SvenLauterbach** [SharePoint/PnP-JS-Core#632]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    sp-pnp-js v3.0.1     ]

#### Expected / Desired Behavior / Question
I'm trying to call "pnp.sp.utility.resolvePrincipal" in a SharePoint 2013 On-Prem installation:

    function getUserPrincipal(loginName) {
        return pnp.sp.utility.resolvePrincipal(loginName,
                pnp.PrincipalType.All,
                pnp.PrincipalSource.All,
                false,
                true);
    }

#### Observed Behavior
The calls fails with a HTTP 400 Bad Request and this error message:

"The parameter matchUserInfoList does not exist in method ResolvePrincipalInCurrentContext."

The Request does contain the following body:

    {
        addToUserInfoList: true
        input: <loginName>
        inputIsEmailOnly: false
        matchUserInfoList: false
        scopes: 15
        sources: 15
    }

#### Steps to Reproduce

call pnp.sp.utility.resolvePrincipal with a claims login name in a sharepoint 2013 on-prem environment.

Thanks!

**Comment by patrick-rodgers** [comment]
I think this is a difference between on-prem and online - or maybe specific to 2013.. Will try and investigate but might not be a bug as such. Thanks for reporting!

**Comment by SvenLauterbach** [comment]
Would be great to know what the default behaviour for Office 365 is, if the "matchUserInfoList" Parameter is omitted. If the default behaviour is "matchUserInfoList: false" the parameter could be added to the "resolvePrincipal()" function, so the user could explicitly set it to "true" if needed. If not explicitly set to “true” the parameter could be removed from the request.

**Comment by patrick-rodgers** [comment]
It defaults to false if no value is supplied. So we could make it an optional argument in the method and not include it in the call if it is not supplied (i.e. only send a value if it is set to true) - but that doesn't "fix" the issue as someone setting it to true would still report a bug as they would get the above error, right? As this is only (so far as I know, please correct me if I am wrong) an issue with 2013 (and maybe not all versions) I am not sure there is any action to take here. Instead I'd offer this code for folks wanting to call the method in 2013 that can be used in their applications.

```TypeScript
import pnp, {
    SharePointQueryable,
    UtilityMethod,
    PrincipalInfo,
    PrincipalType,
    PrincipalSource,
} from "sp-pnp-js";

// shim class to support a 2013 method
class UtilityMethod2013 extends UtilityMethod {

    constructor(baseUrl: string | SharePointQueryable) {
        super(baseUrl, "");
    }

    public resolvePrincipal2103(input: string,
        scopes: PrincipalType,
        sources: PrincipalSource,
        inputIsEmailOnly: boolean,
        addToUserInfoList: boolean): Promise<PrincipalInfo> {

        const params = {
            addToUserInfoList: addToUserInfoList,
            input: input,
            inputIsEmailOnly: inputIsEmailOnly,
            scopes: scopes,
            sources: sources,
        };

        return this.clone(UtilityMethod, "ResolvePrincipalInCurrentContext", true).excute<PrincipalInfo>(params);
    }
}

// this code makes the call:
const utils2013 = new UtilityMethod2013(pnp.sp.web);
utils2013.resolvePrincipal2103("patrick", PrincipalType.All, PrincipalSource.All, false, false).then(r => {

    console.log(JSON.stringify(r, null, 4));
});
```
