### ISSUE TITLE
Getting All User through PnP-Js

### ISSUE THREAD

**Issue by fanch2** [SharePoint/PnP-JS-Core#633]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [  2.0.6       ]

In my development, there is request to have a multi-selection box to choose from all user in my organization, is there any function to do so without using GRAPH API? Tried "pnp.sp.web.siteUsers.get()" can only get the site users, not all the users

Thanks!

**Comment by koltyakov** [comment]
Hey @fanch2,

It's possible with search API and then ensuring user on-site collection.
Also, you can use any endpoint using HttpClient - the part of PnP JS Core.

There is a suitable endpoint which is used in people picker:
`/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`

One can perform a control with something like:

```TypeScript
import { HttpClient } from 'sp-pnp-js';
let client = new HttpClient();

let searchString = 'andrew';
let endpointUrl = `${_spPageContextInfo.webServerRelativeUrl}` +
    `/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`
    .replace(/\/\//g, '/');

client.post(endpointUrl, {
    headers: {
        'Accept': `application/json; odata=verbose`
    },
    body: JSON.stringify({
        queryParams: {
            __metadata: {
                type: 'SP.UI.ApplicationPages.ClientPeoplePickerQueryParameters'
            },
            AllowEmailAddresses: true,
            AllowMultipleEntities: false,
            AllUrlZones: false,
            MaximumEntitySuggestions: 50,
            PrincipalSource: 15,
            PrincipalType: 15,
            QueryString: searchString
        }
    })
})
    .then(response => response.json())
    .then(data => {
        console.log(JSON.parse(data.d.ClientPeoplePickerSearchUser));
    });
```

**Comment by patrick-rodgers** [comment]
Assuming the above answer gets you what you need, going to close this as answered, please _reopen_ should you require additional assistance. Thanks!
