### ISSUE TITLE
List update operation throw aborted in IE9

### ISSUE THREAD

**Issue by aldvintumbelaka** [SharePoint/PnP-JS-Core#634]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 3.0.1

#### Expected / Desired Behavior / Question
In IE9, list item update / file property operation is returning "aborted" and promise fails while it's actually updated successfully on the list (normally returning 204 - No Content).
![image](https://user-images.githubusercontent.com/33532350/32637173-756796da-c60c-11e7-9fcc-dc6763f975de.png)

This issue is probably reported before and I do notice that we will need to perform a manual check against it for version < IE10
https://stackoverflow.com/questions/10046972/msie-returns-status-code-of-1223-for-ajax-request

`// Normalize IE's response to HTTP 204 when Win error 1223.
status : (conn.status == 1223) ? 204 : conn.status,
// Normalize IE's statusText to "No Content" instead of "Unknown".
statusText : (conn.status == 1223) ? "No Content" : conn.statusText`

**Comment by patrick-rodgers** [comment]
This may also be a quirk of the library you are using to polyfill for fetch. This is likely not something we could fix within the library as we don't control how the browser would report the result. Meaning we would also see the aborted response and report it as such. I'll have a look once I am back from leave but want to set your expectations for this potentially not being a "fixable" item. Thanks!
