### ISSUE TITLE
sp-pnp-js List Item Paging

### ISSUE THREAD

**Issue by Mike-tech** [SharePoint/PnP-JS-Core#636]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[ #] Question

#### Version

Please specify what version of the library you are using: [  3.0  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Some my question was addressed in #115 , but i need to know how to use the paging on the pnp API properly. This is how i am currently using the paging:

I do an initial .get() with filter, then when the user scroll to bottom i call this method:
   await this._getListDataMoreAsync().then((response) => {
        console.log(response.hasNext);
        this._renderView(response.results, this.state.NoNewsItem);
      }).catch((error) => {
        console.log(error.message);
      });

This is the call for getListDataMore:
 private async _getListDataMoreAsync(): Promise<any> {
    const web = new Web(this.props.siteUrl);
    return await web.lists.getByTitle("listName").items.top(5).orderBy("OrderNo", false)
    .getPaged().then(d => {
      return d.getNext();
    });
  }

In the response i'm seeing the initial query being returned along with the paged response:
![image](https://user-images.githubusercontent.com/21954124/32834036-edcf91c8-c9f8-11e7-87b2-ff2944592370.png)

1) How to you return just the paged and not the initial query which i already have.
2) The response seems to be infinite and keeps returning items (repeated items) and response.hasNext is always true

Please let me know what i'm doing wrong.

Thanks!

**Comment by Mike-tech** [comment]
I actually got more clarity on how getPaged is used from this link:
https://github.com/SharePoint/PnP/blob/master/Samples/SharePoint.pnp-js-core/SharePoint.pnp-js-core/Samples/ReadListItemsPaged.html

This lead me to further question, as in how do you used the .getNext() at a separate event. So i initially load my list, then when user click a button for more, how would I call .getNext().

I had to result to spHttpClient where i can check and store response["@odata.nextLink"]. I'm surprise the sp-pnp-js api don't allow that.

If there is a way to achieve my aim, it will be good to find out how.

Thanks

**Comment by jawa-the-hutt** [comment]
@Mike-tech 

I did something like the following.  It's ES6/ES7 and not typescript, but hopefully it will match what you were trying to do overall.  

Make a call to getAllItems and pass in the `web` and `query` parameters.  The name of the list is `query.listTitle` and your page size is `query.top`.  

the `pageData` function is recursive so it should iterate through all your pages.

```
// get all the items from a list
getAllItems = async (web, query) => {
    try{
        let returnedItems = [];

        const getData = await web.lists.getByTitle(query.listTitle).items.top(query.top).getPaged().then(page => {
            if(page) {
                // data was returned, so concat the results
                returnedItems = returnedItems.concat(page.results);
                return page;    
            } else {
                return returnedItems;
            }
        });

        if(getData.getNext) {
             return returnedItems.concat(await pageData(getData).then(result => {
                return result;
            }));
        } else {
            return returnedItems;
        }

    } catch (e){
        console.log('error - ', e);
        return {
            body: e.data.responseBody ? e.data.responseBody['odata.error'].message.value : e,
            status: e.status,
            statusText: e.statusText
        }
    }
}

pageData =  async (data) => {
    try{
        let returnedItems = [];

        const getPage = await data.getNext().then(page => {
            if(page) {
                // data was returned so concat the results
                returnedItems = returnedItems.concat(page.results);
                return page;
            } else {
                return;
            }
        }); 

        if(getPage.nextUrl) {
            // still have more pages, so go get more
            return returnedItems.concat(await pageData(getPage));
        } else { 
            // we've reached the last page
            return returnedItems; 
        }
    } catch (e){
        return {
            body: e.data.responseBody ? e.data.responseBody['odata.error'].message.value : e,
            status: e.status,
            statusText: e.statusText
        }
    }
}
```

**Comment by Mike-tech** [comment]
@jawa-the-hutt 
In SPFx i don't have nextUrl. Using your example, the page arrow function does have a hasNext parameter, which i guess is equivalent to nextUrl.

Looking at your code, if you loading all pages to returnedItems, is that not the same as getting all items at once?

As i asked in my second comment, as far as i understand you have to manually check hasNext - which won't work if you have many pages.

**Comment by wuliwux** [comment]
@Mike-tech 
i have the same interesting behavior...

i call the 2 request in the browser and everything is ok in the sp-pnp-js i always get returned the first page.

have you found a solution?

**Comment by Mike-tech** [comment]
@wuliwux 
Which two request. You only need to call the one request which is shown in the link i posted in my second comment:
 list.items.top(2).orderBy("Title").getPaged()

My issue was the lack of ability to call ".getNext()" from an outside event, as in, when needed. Unless your stored all your results in a variable, which to me defeat the purpose of paging.

My solution was to use spHttpClient where i can check and store the next page link from ["@odata.nextLink"].

I wonder if this is why it's not covered in the sp-pnp-js wiki?

**Comment by wuliwux** [comment]
hehe....
i have found **my** bug...

i wrote an net core sharepoint rest middleware (local webpack development :-) ) and forgot to parse the query from the request to the response.

greets

**Comment by patrick-rodgers** [comment]
Hi @Mike-tech - I am back from family leave and following up on issues. The getPaged method returns an object that has two properties: results and hasNext. It also has the getNext method. So you would need to store that object in some type of context value and on button click call the getNext method of that object to get your results. This would be the same as storing the link, just that you would store the object.

Going to close this as answred, please _reopen_ if you need additional assistance on this. Thanks!

**Comment by Mike-tech** [comment]
Hi @patrick-rodgers, thanks for the pointer. I initially tried to store the getNext as an object but i had trouble exposing its methods. I've just re-looked this and i'm able to create a state object as Promise<PagedItemCollection<any>> and assigned getNext correctly.

Cheers
