### ISSUE TITLE
SPFx webpart: SitePages is in the rest query when using pnp.sp.web.lists.getByTitlelist on a modern team site page

### ISSUE THREAD

**Issue by spdavid** [SharePoint/PnP-JS-Core#637]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.0.1      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
when doing a get on a list similar to the following in a React SharePoint webpart

 pnp.sp.web.lists.getByTitlelist
      .select("Title", "Created", "SiteStatus")
      .filter("some filter")
      .get()

I should get my results back

#### Observed Behavior
Works fine in the  workbench. 
https://tenant.sharepoint.com/sites/[site]/_api/web/lists/getByTitle('List')/items...
But not when I add the webpart onto a page in a modern team site i get the SitePages inserted into the query. And therefore it breaks.  
https://tenant.sharepoint.com/sites/[site]/SitePages/_api/web/lists/getByTitle('List')/items...

#### Steps to Reproduce
1. Create react spfx web part. 
2. do a get call similar to the below on a list. 
3. add it to a page in a modern team site. 

 pnp.sp.web.lists.getByTitlelist
      .select("Title", "Created", "SiteStatus")
      .filter("some filter")
      .get()

**Comment by koltyakov** [comment]
Hi @spdavid,

Please check this wiki page for more details of usage sp-pnp-js in SPFx solutions: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

**Comment by bva999** [comment]
Try  set baseUrl. I had similar problem. 
```
setup({
        sp:{
          baseUrl: this.context.pageContext.web.absoluteUrl
        }});
```

**Comment by spdavid** [comment]
Yep, I forgot the onInit code. It works. Thanks for the help.
