### ISSUE TITLE
How to read aspx content using GetFileByServerRelativeUrl API

### ISSUE THREAD

**Issue by kanthan-r** [SharePoint/PnP-JS-Core#638]
Hi,

I am facing an issue while trying to get the content of an aspx file using GetFileByServerRelativeUrl API.
I am using postman REST client and here's my requrest:
Method: GET
Headers: Authorization and Accept headers with right values 
URI: https://<site url>/_api/web/GetFileByServerRelativeUrl('/<path>/sample.aspx')/$value

Response:
{
    "error": {
        "code": "-2147024891, System.UnauthorizedAccessException",
        "message": {
            "lang": "en-US",
            "value": "Access denied. You do not have permission to perform this action or access this resource."
        }
    }
}

**The problem occurs only with the aspx files and not with html, txt format files.**

Please note: I am able to access this file and retrieve metadata with the below request:
Method: GET
Headers: Authorization and Accept headers with right values (same as above)
URI: https://<site url>/_api/web/GetFileByServerRelativeUrl('/<path>/sample.aspx')

Any help would be much appreciated.

Thanks,
Kanthan

**Comment by koltyakov** [comment]
Hi @kanthan-r,

Probably the user who is running this request actually has no permissions to the page.
Also, it can be an error in the path. `GetFileByServerRelativeUrl` expects correct server relative url.
If the page url is `https://contoso.sharepoint.com/sites/site/web/web/doclib/page.aspx`, `/sites/site/web/web/doclib/page.aspx` should be passed to the method.

**Comment by patrick-rodgers** [comment]
@koltyakov is correct, if you get access denied the caller does not have access to that page/file. Otherwise what you are doing is correct. It also seems that you are using PostMan and not this library so I am going to close the issue.

**Comment by alexwinston** [comment]
I realize this thread is closed and not related specifically to this library but I also am currently experiencing this exact same issue and was wondering if @kanthan-r resolved this problem?  If I knew a way to contact him directly I would but thought I would start here.  I assume there is some weird Sharepoint misconfiguration or possibly GetFileByServerRelativeUrl doesn't work for all files.  In my case a link redirect to a PDF.

**Comment by koltyakov** [comment]
@alexwinston, could you please provide the link format (with any sensitive info replaced)?

**Comment by alexwinston** [comment]
Don't feel like you have to troubleshoot this for me because it is probably some obscure setting in Sharepoint but I am calling the service API with the link below using NTLM.  Funny thing is that the aspx link itself in Sharepoint for this user works fine, it redirects to the PDF in the browser.  It is only when I call the aspx though the service does it return UnauthorizedAccessException.  Even stranger is that if I use the link below to access the PDF directly it works as well.

GET https://sharepoint.*******.org/ea/healthit/cti/estar/train/_api/web/GetFileByServerRelativeUrl('/ea/healthit/cti/estar/Train/Shared%20Documents/Universal/Test%20Alex.aspx')/$value

**Comment by koltyakov** [comment]
That is what I was thinking of. It's not a link to the document
`/ea/healthit/cti/estar/Train/Shared%20Documents/Universal/Test%20Alex.aspx` which should be provided to the API.

The file relative URL is the path to the document itself, not a service page.

E.g. on the web with URL `/ea/healthit/cti/estar/Train` there is a document library and some folders inside. Let's assume standard Shared Document and folders structure inside `/projects/customer1`. Then a document name `MyFancy.pdf`.

Its URL should be `/ea/healthit/cti/estar/Train/Shared%20Documents/projects/customer1/MyFancy.pdf`.

In modern SP link can be retrieved in 2 clicks:

![image](https://user-images.githubusercontent.com/7816483/35879661-d4437938-0b8c-11e8-9b14-4dc8cb7aee43.png)

alternatively, from props disp form:

![image](https://user-images.githubusercontent.com/7816483/35879756-068ec06e-0b8d-11e8-882a-b406ce63c7c6.png)

Reading about `UnauthorizedAccessException` I'm not sure that your issue can be solved just replacing the url part, but it's a good starting point to provide something which API expects to receive.

Hope this will help.
