### ISSUE TITLE
People picker in SPFx _ Typescript _ KnockoutJs

### ISSUE THREAD

**Issue by Naveenrerd** [SharePoint/PnP-JS-Core#639]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [         ]

#### Expected / Desired Behavior / Question

I need to implement a people picker field in my SPFx webpart. Integrating [OfficeUIFabric - PeoplePicker](https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker) this failed as it is using Office fabric and It is a webpart rather than a simple module.

I tried [SP-Peoplepicker](https://www.npmjs.com/package/sp-peoplepicker), but was unsuccessful. Please suggest a plugin/installation steps for the people picker or if I have to implement a custom code, please let me know how to start the same.

Thanks!

**Comment by koltyakov** [comment]
Hi @Naveenrerd,
 
While dealing with SPFx solutions `spfxContext` should be passed to pnp setup, like described here in the wiki: https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework

@spjeff's control uses JSOM to request for users (`SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`).

This endpoint exists in REST too and can be requested with PnP JS Core in the following way:

```TypeScript
import { HttpClient } from 'sp-pnp-js';

let httpClient = new HttpClient();

let searchString = 'andrew';
let endpointUrl = `${_spPageContextInfo.webServerRelativeUrl}/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser`.replace(/\/\//g, '/');

httpClient
  .post(endpointUrl, {
    headers: {
      Accept: `application/json; odata=verbose`
    },
    body: JSON.stringify({
      queryParams: {
        __metadata: {
          type: 'SP.UI.ApplicationPages.ClientPeoplePickerQueryParameters'
        },
        AllowEmailAddresses: true,
        AllowMultipleEntities: false,
        AllUrlZones: false,
        MaximumEntitySuggestions: 50,
        PrincipalSource: 15,
        PrincipalType: 15,
        QueryString: searchString
      }
    })
  })
  .then(response => response.json())
  .then(data => {
    console.log(data);
  });
```

**Comment by patrick-rodgers** [comment]
Hi @Naveenrerd, this is a very broad question and @koltyakov has done his best to answer it. Questions like this are perhaps best asked in the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) as it does not deal specifically with this library. Thanks!
