### ISSUE TITLE
Configure throttling decorations

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#641]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [301]

#### Expected / Desired Behavior / Question
I'm trying to set the user agent request header to follow the [recommandation published a couple of weeks ago](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online).   
I tried to do it two ways (see steps to reproduce). Two questions: 
- Are we supposed to do that for code running in the browser? (not clear from the documentation)
- How or we suppose to implement it? Is my code wrong?

#### Observed Behavior
The user agent stays the browser's user agent.

#### Steps to Reproduce
I first tried via configuration
```TS
pnp.setup({
  sp: {
      headers: {
          'User-Agent': 'NONISV|2toLead|GSKMeetingWorkSPace/1.0',
      },
  },
});
```
Then I tried on the call
```TS
await pnp.sp.web.lists.getByTitle(MeetingAgendaConstants.AGENDA_LIST_NAME)
.items.getById(agendaitem.id)
        .configure({ headers: { 'user-agent': 'NONISV|2toLead|meetingapp/1.0'} }).update({
...
        });
```
Both methods are not raising issues in the browser.

**Comment by patrick-rodgers** [comment]
The library will in the next version include a User-agent string by default that should help here. Do you require a way to configure your own user-agent string?

**Comment by baywet** [comment]
Hey Patrick,
Thanks for answering. My understanding of these best practices is to allow teams operating SharePoint Online to identify what "app" is doing what call and adjust the throttling accordingly. I don't think it matters much which library we're using, it all becomes REST calls at the end of the day. So each app should provide it's own user agent string.
That being said, I think the majority of developers won't be aware of that so it's good that the library has a default we'll be able to override so at least the teams have the information it's a custom component leveraging sp-pnp-js.

**Comment by patrick-rodgers** [comment]
Actually, what browser are you using? I just did a little reading and some browsers don't allow you to set User-Agent. I am going to hit up the throttling team when I am back in the office to see what they advise.

**Comment by baywet** [comment]
Yeah having detailed guidance for front end components (Maybe using a X-User-Agent instead?) from the team would be good.
In my tests Chrome latest. However our customer have a wide eco-systems with IE11, Chrome, Edge, and Safari (Ipad/IPhone)

**Comment by patrick-rodgers** [comment]
Just heard back and apparently the current guidance is to append to the useragent header. I haven't tested this yet but they did give me some sample code...that works just in chrome. I will try this out, but I did push back a little and ask that they work on a way to just set a different header, such as the X-User-Agent or something. Will be much simpler and cross browser. Otherwise everyone will have to know to have this big block of code to append a header...seems less than ideal to me, but we'll see. Anyway let me try this out and see.

**Comment by baywet** [comment]
thanks for the follow up, let me know if I can help :)

**Comment by patrick-rodgers** [comment]
No updates, basically they are saying to update the user-agent - which has been shown to them not to work. So honestly not sure what the guidance here is. Folks are being impacted so perhaps some action will come. If you have customers being impacted I'd have them open a ticket on it to gain visibility. Wish I had something better to share.

**Comment by baywet** [comment]
thanks for the follow up on that. we don't see any impact so far but I can see situation like "we throttled you because the agent was not set" in the future. Or maybe they don't do any throttling for browser corresponding user agents but that would defeat the purpose and be a hack for people that want more power for their backend API's.
It's probably a feedback I can give to the product team at the summit in a couple of weeks if you can IM me the PM's contact information. I can also try the MVP DL for office API's to see if we get traction there. What do you think?

**Comment by patrick-rodgers** [comment]
Going to close this as I don't see any new guidance coming any time soon, and you can't set a User Agent in browser anyway.

**Comment by baywet** [comment]
thanks for the follow up, I opened a PR earlier today to add that mention on the official documentation, this way we avoid confusion!
