### ISSUE TITLE
Batch updating multiple list items

### ISSUE THREAD

**Issue by jawa-the-hutt** [SharePoint/PnP-JS-Core#642]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.0.1]

#### Expected / Desired Behavior / Question
I am trying to follow the wiki item here: https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#update-multiple-items, about how to batch update multiple items on a list, but am running into problems.

#### Observed Behavior
When following the code as given in the wiki article, i'm getting an error `list.items.inBatch(...).update is not a function`.  After digging through source and trying to figure out the exact correct call, I've come to a conclusion that the wiki article might be wrong?

I can't find that the `Items` class even has an `update` function.  The `Item` class does, so i'm not sure how the reference wiki article's code is even supposed to work.

The following does work: `list.items.getById(id).inBatch(batch).update`, so my guess is the wiki article is wrong, or I'm missing something about how to do it the way the wiki article is suggesting.

**Comment by patrick-rodgers** [comment]
The example looks like it might be wrong, thanks for pointing it out. Will get it fixed.

**Comment by ahsanranjha** [comment]
is this fixed already? what is the fix?

**Comment by koltyakov** [comment]
Items update works in batches just fine.

Example:

```typesctipt
(async () => {
	const batch = pnp.sp.web.createBatch();
	const list = pnp.sp.web.lists.getByTitle('ListA');
	const items = await list.items.select('Id,Title').get();
	const entityTypeFullName = await list.getListItemEntityTypeFullName();

	for (const item of items) {
		list.items.getById(item.Id).inBatch(batch)
			.update({ Title: `${item.Title} (${item.Id})` }, '*', entityTypeFullName);
	} 

	await batch.execute();
	console.log('Done');
})();
```

![image](https://user-images.githubusercontent.com/7816483/39519393-47ecbcfe-4e0f-11e8-80b3-85c8537e1731.png)

**Comment by ahsanranjha** [comment]
I am working in cross domain and sharepoint hosted app.  

I utilized promise function as code below 

        (async () => {
                            const web = $pnp.sp.crossDomainWeb(JobList.SPAppWebUrl, JobList.SPHostUrl);
                            const list = web.lists.getByTitle('MyList');
                            const itemEntityTypeFullName = await list.getListItemEntityTypeFullName();
                            return new Promise(function (resolve, reject) {
                                var array = [];
                                for (var i = 0; i < TasksSPItemCollection.length; i += 1) {
                                    array.push(list.items.getById(TasksSPItemCollection[i].Id).update({ VisaStatusId: 4}));
                                 }
                                Promise.all(array).then(function (CandidateItemCollection) {
                                    debugger;
                                    resolve(CandidateItemCollection);
                                });
                            });
                        })();

it works fine. I will check batch

**Comment by ahsanranjha** [comment]
I tried batch and end up with error 

 (async () => {
                            const batch = $pnp.sp.web.createBatch();
                            const list = $pnp.sp.web.lists.getByTitle('MyList');
                         
                            const entityTypeFullName = await list.getListItemEntityTypeFullName();
                          //  var 
                            //for (const item of items) {
                            list.items.getById(1).inBatch(batch).update({ Title: 'A 1' }, '*', entityTypeFullName);
                            list.items.getById(2).inBatch(batch).update({ Title: 'A 2' }, '*', entityTypeFullName);
                            list.items.getById(3).inBatch(batch).update({ Title: 'A 3' }, '*', entityTypeFullName);
                            list.items.getById(4).inBatch(batch).update({ Title: 'A 4' }, '*', entityTypeFullName);
                           

                            await batch.execute();
                            console.log('Done');
                        })();

![image](https://user-images.githubusercontent.com/9005752/39520178-b9c1e2f4-4e1a-11e8-80d1-b4ae32cdcc30.png)

**Comment by koltyakov** [comment]
I created a SPHostedApp and checked:

```typescript
(async () => {

	const web = pnp.sp.crossDomainWeb(
            GetUrlKeyValue('SPAppWebUrl'),
            GetUrlKeyValue('SPHostUrl')
        );

	const batch = pnp.sp.web.createBatch(); // worked
	// const batch = pnp.sp.createBatch(); // worked
        // const batch = web.createBatch(); // didn't work,
            // my assumption that a batch should be created from `crossDomainWeb` web object was faulty

	// code is omitted here ...

	await batch.execute();
	console.log('Done');

})().catch(console.log);
```
