### ISSUE TITLE
Issue when using typescript

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-JS-Core#643]
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [     3.0.1   ]

#### Expected / Desired Behavior / Question
Typescript compiles the typescript to javascript

#### Observed Behavior
Typescript is throwing all this errors:
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/configuration/spfxContextInterface.d.ts(3,71): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/fetchclient.d.ts(6,47): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(6,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(7,60): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(8,55): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(9,56): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(10,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(11,58): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/graphclient.d.ts(14,76): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(4,56): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(10,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(11,60): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(12,55): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(13,56): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(14,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/httpclient.d.ts(15,58): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/nodefetchclient.d.ts(21,47): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/sprequestexecutorclient.d.ts(9,47): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/net/utils.d.ts(14,46): error TS2304: Cannot find name 'Headers'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/caching.d.ts(20,21): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/core.d.ts(2,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/core.d.ts(5,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/core.d.ts(6,30): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/parsers.d.ts(6,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/parsers.d.ts(10,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/parsers.d.ts(13,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/odata/parsers.d.ts(16,14): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(3,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(4,60): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(5,55): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(6,56): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(7,57): error TS2304: Cannot find name 'Response'.
C:/Users/mjoye/Desktop/Interco Purchasing/node_modules/sp-pnp-js/lib/request/requestclient.d.ts(8,58): error TS2304: Cannot find name 'Response'.

#### Steps to Reproduce
Add the sp-pnp-js lib to the product and import into a class.

**Comment by patrick-rodgers** [comment]
What version of TypeScript are you using? This appears to be something in your tool chain missing the defs for Response. What are your tsconfig.json settings?

**Comment by patrick-rodgers** [comment]
Were you able to get past this issue or have any additional info you can share?

**Comment by ravenboilinux** [comment]
Yes I was able to. I had to modify my project package.json file
