### ISSUE TITLE
Adding a file, update the file, deleteing the file manually, adding + updateing again causes issues

### ISSUE THREAD

**Issue by masterl1983** [SharePoint/PnP-JS-Core#647]
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    sp-pnp-js v3.0.1     ]

#### Expected / Desired Behavior / Question
I am using sp-pnp-js in a plain JS File. I am trying to do the following:
1. Read a file as Blob from Library A
2. Add the file from Step1 to Library B
3. After the file got created in Library B I want to update its Metadata

`	var fieldsToUpdate = {};
			//fieldsToUpdate["INGA_Ersteller"] = _spPageContextInfo.userDisplayName;
			fieldsToUpdate["INGAId"] = parseInt(getParameterByName("currentIngaID"));
			//fieldsToUpdate["INGA_TXT"] = globalSelectedINGATitle;

		// Define the INGADocProperties
		var srcLibrary = "BeanweiFREI";
		var srcFileName = "";
		var destLibrary = "SelectedBALibrary";
		var destFileName = "BA"  + "_" + "@ItemID" + ".xlsm";

		var myProperties = new BADocProperties(srcLibrary, srcFileName, destLibrary, destFileName, fieldsToUpdate);

			$pnp.sp.web.lists.getByTitle(srcLibrary).items.getById(returnValue[0]).select("ErstellerPersonFieldId,GefahrstoffId,FieldValuesAsText").expand("FieldValuesAsText").get().then(function (srcItem) {
				//We need to get the "Abteilung" from INGAStammdaten as we want to pass it to the Document
				myProperties.fieldsToUpdate["GefahrstoffbezugId"] = srcItem.GefahrstoffId;
				console.log("Get: ", srcItem);
				//Set the SourceFileName
				myProperties.srcFileName = srcItem.FieldValuesAsText.FileLeafRef;
				//Read the sourceFile as a blob, create a new file based on the blob, update the newly created file with the properties passed in BADocProperties
				$pnp.sp.web.getFileByServerRelativeUrl(_spPageContextInfo.webServerRelativeUrl + "/" + myProperties.srcFileLib + "/" + myProperties.srcFileName).getBlob()
					.then(function (blob) {
						console.log("Document read successfully...");
						$pnp.sp.web.getFolderByServerRelativeUrl(_spPageContextInfo.webServerRelativeUrl + "/" + myProperties.destFileLib).files.add(myProperties.srcFileName, blob, true)
							.then(function (result) {
								console.log("Document added successfull...");
								console.log("Added file: ", result);
								result.file.getItem()
									.then(function (item) {
										console.log("Document Item received successfull...");
										
										// Only as of now we do know the ID of the file created. This ID is should be part of the fileName
										// So we update the passed fileName and add it as a property of the fields which needs to be updated
										myProperties.applyItemIdToFileName(item.Id);
										myProperties.addFileNameToFieldsToUpdate();
										console.log("Fields To update: ", myProperties.fieldsToUpdate);
										console.log("Item to Update: ", item);
										item.update(myProperties.fieldsToUpdate)
											.then(function (result) {
												//Everything went fine so we can refresh the page
												console.log("Document updated successfull...");
											})
											.catch(function (e) { console.error(e.data); console.log("update failed"); });
									});
							})
							.catch(function (e) { console.error(e.data) });
					});
			});

		} else if (result == SP.UI.DialogResult.cancel) {
			alert("alles cancel");
		}
	}

	function BADocProperties(srcFileLib, srcFileName, destFileLib, destFileName, fieldsToUpdate) {
		this.srcFileLib = srcFileLib;
		this.srcFileName = srcFileName;
		this.destFileLib = destFileLib;
		this.destFileName = destFileName;
		this.fieldsToUpdate = fieldsToUpdate; //object expected

		this.applyItemIdToFileName = function (itemID) {
			this.destFileName = this.destFileName.replace("@ItemID", itemID)
		}

		// Add the destFileName property to the fieldsToUpdate object
		this.addFileNameToFieldsToUpdate = function () {
			this.fieldsToUpdate.FileLeafRef = this.destFileName;
		}
	}`

#### Observed Behavior
The code above runs just fine. Lets assume my destLibrary (SelectedBALibrary) is brand new. So no single document got created in that library! When I run my Code the first time I get a file created in my destLibrary and metadata gets updates. I can run my code 100 times (always using the same srcFile) and everything goes well. BUT... Assume I created the first file in my destLibrary based on srcFile A. So the file which got created now has the ID=1. When I know delete this file with ID=1 and run my code again using the same srcFile something strange happens. The file gets created in my Library but result.file.getItem() will return an Item with ID=1! but should return an Item with ID=2.

So now the code tries to update an Item with ID=1 which does not exist! Am I doing something wrong?

#### Steps to Reproduce
See above

#### Submission Guidelines

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @masterl1983 - thanks for reporting this issue. We've had something like this reported before and I encourage you to [read through this thread](https://github.com/SharePoint/PnP-JS-Core/issues/538). Ultimately the solution was to add a no-cache header to the request where you are seeing issues.

```TypeScript
// something like:
    file.configure({
        headers: {
            "Cache-Control": "no-cache",
        },
    }).getItem()
```
This issue is due to the browser caching the result and we don't do anything to affect that automatically as it could have unintended side-effects. Give the header a try and let us know if that works. Thanks!

**Comment by masterl1983** [comment]
Hi Patrick. I have updated my code and it seems to be working as expected.
Thanks

**Comment by patrick-rodgers** [comment]
Great, glad to hear it. Cheers.
