### ISSUE TITLE
Feature request: Implement endpoint for Web/RegionalSettings/TimeZone

### ISSUE THREAD

**Issue by eirikb** [SharePoint/PnP-JS-Core#649]
#### Category
[ x ] Enhancement

[ ] Bug

[ ] Question

#### Version
latest 

#### Expected / Desired Behavior / Question
Some way to reach `Web/RegionalSettings/TimeZone`.
Perhaps `web.regionalSettings.timeZone.get()`.

Thanks!

**Comment by koltyakov** [comment]
Thanks, @eirikb for posting the issue.
It should not be hard to implement.
I'll take a look at this sooner.

**Comment by koltyakov** [comment]
Going to close the issue. Please stay tuned, the functionality should land in the new release.
Meanwhile, HttpClient can be used as a temporary solution or a custom build from the feature branch.
