### ISSUE TITLE
Sharepoint List Webbook callback includes Byte Order Marker (BOM)

### ISSUE THREAD

**Issue by wvanderdeijl** [SharePoint/PnP-JS-Core#653]
#### Category
[ ] Enhancement
[x] Bug
[ ] Question

Apologies for reporting this issue here. I suspect this is not a problem with PnP-JS-Core but rather with the sharepoint online backend. But hopefully you people have the contacts with the sharepoint team to bring this to their attention.

#### Expected / Desired Behavior / Question
After registering a webhook to a sharepoint list I expect my endpoint to be invoked with a JSON payload to notify it of a change in the monitored sharepoint list.

#### Observed Behavior
Registering the webhook works fine, but when my endpoint is invoked it fails to parse the JSON. After some investigation I found out that the http request includes a Byte Order Marker (BOM). You can see this in the screenshot below. After the last header there are two newlines (as expected) and then the BOM marker EF BB BF. AFAIK this is not valid json and expressjs body-parser fails to parse the message. Unfortunately we are using a cloud functions backend and the parsing happens before our cloud function is even invoked so we can't fix it in our own code by removing the BOM.

This is with sharepoint online on an office 365 domain that was just created (december 2 2017)

![image](https://user-images.githubusercontent.com/7952432/33528538-5b2082ba-d862-11e7-9c79-8cbfaa899864.png)

The error stack from our cloud function:
```
Error: invalid json
    at parse (/var/tmp/worker/node_modules/body-parser/lib/types/json.js:79:15)
    at /var/tmp/worker/node_modules/body-parser/lib/read.js:102:18
    at IncomingMessage.onEnd (/var/tmp/worker/node_modules/raw-body/index.js:149:7)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by patrick-rodgers** [comment]
Hi @wvanderdeijl - thanks for reporting this, but this should please be reported [here](https://github.com/SharePoint/sp-dev-docs) as that repo is monitored by the product team. Going to close the issue here but you can always link to this issue from the other issues list. Thanks!

**Comment by wvanderdeijl** [comment]
No problem. Thanks for pointing me in the right direction.
