### ISSUE TITLE
Search for items in a specific Search Resource

### ISSUE THREAD

**Issue by ashkan89** [SharePoint/PnP-JS-Core#658]
Hello guys.
I want to search for items choosing a specific search resource.How can I determine the search resource while querying?
I and developing a SearchResult SPFx webpart and I need to have a property for Administrator to select one or more search resources in whitch the result items should be return.
And please help me how to determine the search resources to be filled in a multiselect dropdown.
Thnx

**Comment by koltyakov** [comment]
Did you mean SourceId? You can request search results with:

```typescript
pnp.sp.search({
  Querytext: 'search for',
  SourceId: 'c0aefa61-af88-4dc0-b2ec-32e11212e932'
  // More options
})
  .then(res => {
    console.log(res.PrimarySearchResults);
  })
  .catch(console.log);
```

> I and developing a SearchResult SPFx webpart and I need to have a property for Administrator to select one or more search resources in whitch the result items should be return.

It's a bit out of the scope of library questions.
In SPFx you can define a property pane with a drop-down of search sources and options and use these properties as configuration options in further API requests.

Not sure though that there is a way if getting lists of search Sources in REST, if no, legacy `/_vti_bin/Search.asmx` can be used for this purposes.

**Comment by patrick-rodgers** [comment]
I am not aware of a way to get the result source list via REST or CSOM and didn't find one looking through the SP source. Going to close this as it isn't unfortunately something we can do with the library. You can ask this again in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) and/or [submit an issue](https://github.com/SharePoint/sp-dev-docs/issues) asking about a REST method to list result sources to the sp dev docs site.

**Comment by ashkan89** [comment]
I couldn't find a way to get the search source from rest or CSOM.I will submit an issue.
Thx for your reply
