### ISSUE TITLE
Determine time zone offset (with DST)

### ISSUE THREAD

**Issue by eirikb** [SharePoint/PnP-JS-Core#659]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

Please specify what version of the library you are using: [     3.0.3    ]

#### Expected / Desired Behavior / Question

Is it possible to determine the current time zone offset?
@koltyakov helped a lot by adding `RegionalSettings/TimeZone`, but this endpoint doesn't say if it is in DST or not, only what the DST value should be if it is in DST.

This is important in order to save date and time values the same way as SharePoint does without relying on client having same time zone as regional settings.  
SharePoint will save date and time in UTC, but +/- time zone.

**Comment by koltyakov** [comment]
Hi @eirikb,

Is this what you're searching for?

![image](https://user-images.githubusercontent.com/7816483/33756584-40e1b588-dc07-11e7-86e2-11cb798fffb6.png)

```typescript
pnp.sp.web.regionalSettings.timeZone.get().then(timeZone => {
  console.log(`DaylightBias: ${timeZone.Information.DaylightBias}`);
});
```

**Comment by eirikb** [comment]
Hi @koltyakov .  
That is the DST, which should be used when the time zone is in DST, yes.  
However, the tricky part is to know when one should be in DST, I live in Norway, and currently we don't use DST, not until March next year (the date is different from country to country, and perhaps year to year).

The logic for calculating the diff could be something like this:  
`Information.Bias + (isInDST() ? Information.DaylightBias : Information.StandardBias)`.

Here is one way to determine if current time zone is in DST:  
https://github.com/smallwins/spacetime/blob/master/data/zonefile.2017.json#L1862  
E.g., `spacetime(new Date(), 'Europe/Oslo').inDST()`, although I don't want to rely on client (browser), I want to know if the SharePoint is in DST or not.

**Comment by koltyakov** [comment]
There are such a things in REST API too which can be wraped into the lib:
```
/_api/web/RegionalSettings/TimeZone/utcToLocalTime(@date)?@date='2017-12-08T13:20:00'
/_api/web/RegionalSettings/TimeZone/localTimeToUTC(@date)?@date='2017-12-08T13:20:00'
```
Yet, not sure do the methods take care of DST.

**Comment by eirikb** [comment]
That method looks great, and a bit embarrassing since [I should have know about it](https://sharepoint.stackexchange.com/a/136309/627).  
Can't find anything online about if it includes DST or not. I would guess so, but won't know until next year :stuck_out_tongue:.  
This is probably how Microsoft intended developers to map to/from "SharePoint time", which makes me think it includes DST when it should. 

Perhaps one way to test it would be to run SharePoint on-premise, then set the server time to next year.

**Comment by koltyakov** [comment]
@eirikb, I've created a draft version of `utcToLocalTime` and `localTimeToUTC`. But got to discuss some implementation questions with Patrik before promising that it will be merged in 3.0.3.

**Comment by dcgit** [comment]
Is there a reference for which timezone setting gets used or does that not matter here? I thought there was something like if the user has their timezone set then regional setting doesnt take effect and users taes priority although times get converted automatically to users time.

**Comment by patrick-rodgers** [comment]
This is now merged and the method @koltyakov mentions are now available in the dev branch and will be part of the 3.0.3 release. @dcgit - a user's profile selection for timezone should take precedence but that is generally for UI display. In this case getting the current timezone for a web will be the timezone set for the web and not the user afaik. Let me know if this issue can now be closed or if there are further questions. Thanks!

**Comment by eirikb** [comment]
Thanks for the work @koltyakov.

I tested this today, but are you sure this line is correct?
https://github.com/SharePoint/PnP-JS-Core/blob/dev/src/sharepoint/regionalsettings.ts#L101
`toISOString()` converts the date to UTC, so the value sent into `localTimeToUTC` would not be local, but UTC.

**Comment by koltyakov** [comment]
@eirikb, do you mean it should be something like:

```javascript
if (typeof localTime === "string") {
  dateIsoString = localTime;
} else {
  let tzoffset = localTime.getTimezoneOffset() * 60000;
  dateIsoString = (new Date(localTime - tzoffset)).toISOString().slice(0, -1);
}
```

**Comment by eirikb** [comment]
@koltyakov yeah that ought to do it.

**Comment by patrick-rodgers** [comment]
Ug, I hate dates.

Yes you are correct about how the toISOString method works. So testing this really I think we don't need the method, right? Folks can just call toISOString and get the same result? I really really want to avoid adding a bunch of date math into the library as that is just internalizing complexity.

We could remove both methods as I think this can all be done with the date object? Thoughts?

**Comment by koltyakov** [comment]
The sweet thing about `localTimeToUTC` that is converts the local time for the timezone (which defined on SP web or a specific timezone which can be requested by its id) to UTC date.

**Comment by eirikb** [comment]
Sorry about that, was going to say @koltyakov is correct. Both methods work according to the SPWeb, not the browser (then I clicked wrong button).

**Comment by patrick-rodgers** [comment]
Ah, I see. Darn, removing things is always to much easier.

What if we replace that line with:

```TypeScript
dateIsoString = Util.dateAdd(localTime, "minute", localTime.getTimezoneOffset() * -1).toISOString();
```

That seems to be working the way I think it should, but again, I hate dates.

**Comment by patrick-rodgers** [comment]
With the above merge I think this can be closed?

**Comment by eirikb** [comment]
Agreed
