### ISSUE TITLE
Not able to do Paging in Discussion board List. It returns first page result for every next page request.

### ISSUE THREAD

**Issue by DattaBandgar** [SharePoint/PnP-JS-Core#661]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[ ] Question

#### Expected 
Paging is not working in "discussion board" list its returning first page result, even for next page info. Whereas it is working for custom list. 
 

#### Steps to Reproduce
 Use following code to get first 10 element from "DiscussionBoard" list
 
$pnp.sp.web.lists.getByTitle('DiscussionBoard').items.skip(0).top(10).get().then(function(d) {
   console.log(d);
}); 

Note the result,

Now run following code
$pnp.sp.web.lists.getByTitle('DiscussionBoard').items.skip(10).top(10).get().then(function(d) {
   console.log(d);
}); 
Here it should have returned next set of 10 element(i.e. 11-20) but its returning first 10 element(i.e. 0-10) only. 

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @DattaBandgar - what environment are you in? I just tested this against office365 and it appears to be working, at least for my test. Are you doing any other setup, i.e. verbose headers? Can you provide any additional details?

**Comment by DattaBandgar** [comment]
I am using Sharepoint online enviroment and  no aditional setup I have done.

Today I done some more research on this and find out the way to reproduce it. This issue is occuring for "Custom List" as well. Verified in sharepoint 2013 as well as sharepoint online.

Steps to reproduce the issue 

1. Create "Custom List" e.g. "SampleList"
2. Add Following 10 Items in "SampleList"
	item1
	item2
	item3
	item4
	item5
	item6
	item7
	item8
	item9
	item10
3. Now run following statement browser console where pnp file is referred 

    $pnp.sp.web.lists.getByTitle('SampleList').items.skip(0).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	
	**Actual Result : item1  Expected Result : item1(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(1).top(1).get().then(function(d) {
		console.log(d[0].Title);
	});
	
	**Actual Result : item2  Expected Result : item2(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(2).top(1).get().then(function(d) {
		console.log(d[0].Title);
	});
	
	**Actual Result : item3  Expected Result : item3(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(3).top(1).get().then(function(d) {
		console.log(d[0].Title);
	});
	
	**Actual Result : item4  Expected Result : item4(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(4).top(1).get().then(function(d) {
		console.log(d[0].Title);
	});
	
	**Actual Result : item5  Expected Result : item5(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(5).top(1).get().then(function(d) {
		console.log(d[0].Title);
	});
	
	**Actual Result : item6  Expected Result : item6(Correct)**
	
	 same works fine for remaining items and returns expected result.
	
4. **Now go to "SampleList"  list and delete first 3 items** 

	item1
	item2
	item3
	
   Now run  following statement in browser console
     	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(0).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	**Actual Result : item4  Expected Result : item4(Correct)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(1).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	**Actual Result : item4  Expected Result : item5(Incorrect)** 
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(2).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	**Actual Result : item4  Expected Result : item6(Incorrect)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(3).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	**Actual Result : item4  Expected Result : item7(Incorrect)**
	
	$pnp.sp.web.lists.getByTitle('SampleList').items.skip(4).top(1).get().then(function(d) {
	console.log(d[0].Title);
	});
	**Actual Result : item5  Expected Result : item8(Incorrect)**

**Comment by koltyakov** [comment]
Hi @DattaBandgar,

Everything looks fine to me. All the "Incorrect" cases are actually correct.

I have an assumption that you expect skipping a number of items. But it's not how it works in SharePoint. $skip modifier receives not a number of items to skip, but an Id of the item since which the request should return next chunk of paged the data.

So, for paginating in the app, the app should provide an Id of the last item on the page to get next page. 
There is nothing to do this it, just accept. ;) That's why you've never seen specific page buttons in SharePoint UI (like 1, 2, 3, ... and go to 10th page) because it doesn't allow this. 

When navigation in SharePoint (it's the same for the API) occurred, SharePoint deals with:
- Previous page - `Paged=TRUE&PagedPrev=TRUE&p_ID=7`, where 7 is first item Id on current page, PagedPrev=TRUE reverses the pagination mode - this case is not implemented in PnP JS Core yet
- Next page - `Paged=TRUE&p_ID=9`, where 9 is the last item Id on current page

Maybe this will help with list items pagination as it's a bit controversial.

**Comment by patrick-rodgers** [comment]
Hi folks, just catching up from getting over the flu - what @koltyakov says is correct, but only for list items. Everything else in SharePoint works the way you would expect. There are many long and complicated reasons why - but none of them matter as this is simply "how it is".

For list items you need to grab the ID of the last item in the previous page and pass that to skip. I know this is a bit lame if I am honest.

You can however use the getPaged method we added that should help with this, at least when moving forward in the collection.

```TypeScript
    pnp.sp.web.lists.getByTitle("BigList").items.select("Title").top(10).getPaged().then(p => {

        console.log(JSON.stringify(p.results, null, 4));

        if (p.hasNext) {
            p.getNext().then(p2 => {

                console.log(JSON.stringify(p2.results, null, 4));

            });
        }
    });
```

Going to close this one as answered, please _reopen_ if you need to continue the conversation. Thanks!
