### ISSUE TITLE
Upload and Update File POST instead of GET

### ISSUE THREAD

**Issue by wuliwux** [SharePoint/PnP-JS-Core#663]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.0.2]

i use this code to upload files and Update the entry.

let url = "url";
    pnp.sp.web.getFolderByServerRelativeUrl(url).files
      .add(file.name, file, true)
      .then(f => {
        f.file.getItem().then(item => {
          console.log(item);
          **item.update**({
            Title: file.name,
            Theme: this.theme.Id
          }).then((o: any) => {
            console.log(o);
            this.reloadDocument(o.Id);
            });
        });
      });
#### Question
the Upload is ok,
the **item.Update** send this regquest: 
/tools/VUM/_api/Web/Lists(guid'6f9605d3-431e-49f1-8661-b60c0543b803')/Items(457)
as POST, it sould be a GET.

What am I doing wrong?

Thanks!

**Comment by koltyakov** [comment]
Hi @wuliwux,

Update operations use `POST` method and `MERGE` X-HTTP-Method header, also they contain payload body object.
I'm wondering why it should be `GET`?

**Comment by wuliwux** [comment]
this as GET
/tools/VUM/_api/Web/Lists(guid'6f9605d3-431e-49f1-8661-b60c0543b803')/Items(457)
all fine
as POST i get Bad Request

i think the item.update load the item bevor it start the update...

![image](https://user-images.githubusercontent.com/1975703/33898415-9e6fdf4a-df68-11e7-8c4c-4e29b7bebbc4.png)

**Comment by koltyakov** [comment]
Could you click on this `500` and check the response message with the error.
Something might be wrong with the fields which you update. An update should 100% be a POST.
The structure of your code is also correct in general. So, my guess is this `Theme` property.

**Comment by wuliwux** [comment]
yes my bug... thanks

**Comment by patrick-rodgers** [comment]
Hi folks, just catching up from getting over the flu - looks like this can be closed as resolved. Please do _reopen_ the issue if this is not the case. Thanks!
