### ISSUE TITLE
renderListDataAsStream

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#665]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ x] Enhancement

[ ] Bug

[x ] Question

Would be good to get some docs on  renderListDataAsStream in here! (or elswhere)

**Comment by russgove** [comment]
Hi, 
I heard about this on last weeks community call. I'm did not know it even existed prior to that. I see support for it was added to pnp-js-core back in september:https://github.com/SharePoint/PnP-JS-Core/pull/588/commits. 

I'm hoping to try it out soon and will try to document it.

**Comment by russgove** [comment]
So I spent a lot of time exploring this function and its numerous options today.   Its obvious that it expsoses all the information you could ever need to build a custom list view.  I started trying to document my findings, but then began to think.... is this an undocumented feature for a reason? Is this function subject to change without notice?  I would LOVE  to use this in my solutions to save time, but being as it's an 'undocumented' feature I am hesitant.

**Comment by patrick-rodgers** [comment]
Hi @russgove - The method is not marked in the API as beta or anything to indicate it is fluid. As it is part of the public API if shouldn't change suddenly (famous last words). If you were to document it and put up a post I think that would be a very valuable thing for the community.

**Comment by AJIXuMuK** [comment]
The same method is actually called by SharePoint itself when rendering modern UI.
Parameters contain view id, filters, pagination information - all you can imagine to get the correct set of data.
And yes - it would be great to get the documentation :)

**Comment by russgove** [comment]
The method is really nice, you can pass it a caml query and it returns everything needed to render a view.  Working on a demo-- an extension to  the sp-dev-fx-controls-react/listview. You just pass in a list and some caml and it renders the view in your webpart.

**Comment by russgove** [comment]
so i traced this call on an out of the box modern list view.  It called the method with viewXML and      RenderOptions: 4103. SP returned the data in the view as well as a schema  that explains what the data is. Would be really easy to construct an OUIF Details list with this data.

But when I call the method from pnpJSCore, its not retruning the schema, not sure why. One  difference I noticed is that the out of the box modern list view had a parameter at the end of the query string ?view=

pnp js core does not append that parameter. I'm not sure if that's the issue? will have to test with spfx httpclient.

It would be really nice to have a control that I just pass in a viewxml and it renders the view in my webpart.

**Comment by russgove** [comment]
btw, the RenderOptions has a bunch of options that are not reflected in pnp-js-core: https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.renderlistdataoptions.aspx

**Comment by patrick-rodgers** [comment]
Going to close this as there hasn't been much movement lately. If you get a chance to update the wiki for this method please _reopen_ and let us know so we can include it in release notes. Thanks!

**Comment by patrick-rodgers** [comment]
Docs for this now available at: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#working-with-list-items-by-using-rest
