### ISSUE TITLE
Support for /_api/navigation/MenuState

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP-JS-Core#667]
#### Category
[ x] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [   3.0.3      ]

Does pnp have any support for this following navigation api?
/_api/navigation/MenuState?mapProviderName=%27CurrentNavigationSwitchableProvider%27

The api above basically returns managed metadata navigation structure. I would assume that this should be under pnp.sp.web.navigation? I am however not quite sure with the parameters values that are accepted for mapProviderName.

**Comment by koltyakov** [comment]
Hi Jonathan,

This endpoint is not implemented yet. There are `pnp.sp.web.navigation.quicklaunch` and `pnp.sp.web.navigation.topNavigationBar` methods for navigation right now.
But it's possible to request any custom endpoint with `HttpClient` helper within sp-pnp-js.

E.g.:
```javascript
import { HttpClient } from 'sp-pnp-js';

let client = new HttpClient();

client.get(
  `${_spPageContextInfo.webServerRelativeUrl}/_api/navigation/` +
  `MenuState?mapprovidername='GlobalNavigationSwitchableProvider'`
)
  .then(r => r.json())
  .then(console.log);
```

**Comment by jonathanhotono** [comment]
Thanks @koltyakov !
I will use the custom HttpClient helper for now, and also thanks for the link on the detailed parameters.

**Comment by koltyakov** [comment]
@jonathanhotono,
Yes, it does include request digest automatically for none-Get requests. Also, such feature as retry attempts is there, as well as auto-injecting of Accept/Content-Type headers (if not provided).

**Comment by koltyakov** [comment]
@patrick-rodgers,

How about the following shape for MenuState API? (if it worth implementing)

```typescript
pnp.sp.navigation
  .menuState({
    menuNodeKey: '1006', // root is by default
    depth: 5, // 10 is by default
    customProperties: '', // comma separated list of properties or an array of props
    mapProviderName: 'GlobalNavigationSwitchableProvider' // possible providers dict values 
  })
  .get()
  // .then(...)
```

Things that cause me thinking:

- MenuState is located under `/_api/navigation/MenuState`, not `/_api/web/navigation/MenuState`, which can lead to `pnp.sp.web.navigation` and `pnp.sp.navigation` chains that's not elegant (two different objects with the same name)
- or `pnp.sp.web.navigation` can be extended with `MenuState` method with endpoint constructor removing web part from the url - this leads to the misconception of the projecting fluent chains to API 

Also, I'm not sure in demand for `/_api/navigation/MenuState`, to tell the truth, me personally never needed it in projects, as far there is an alternative way of requesting for requesting any custom endpoint... some rarely used REST methods can be omitted in the lib. From the other hand side, a lot of folks learn about existing REST features and start using them after finding out their existence in IntelliSense, and greater coverage of the API is a good thing.

**Comment by patrick-rodgers** [comment]
This isn't an API I have ever used and not sure on demand to add support. We can leave this open and see if others want to comment, if folks can provide use cases that justify adding it we can take a look. Otherwise this as you say above can be done via the client. There is one other method on the navigation service "GetMenuNodeKey". Input welcome from others on need for implementing this.

**Comment by russgove** [comment]
this uses search to replace structural nav on classic pages. cut my response time in half.https://yetanothersharepointblog.wordpress.com/2016/11/14/search-based-global-navigation-in-sharepoint-on-line/

**Comment by tavikukko** [comment]
Thats one option @russgove, but you will be missing security trimming and some other options too.

**Comment by patrick-rodgers** [comment]
Ok, sounds like there is a good use for this, we'll add it for the next version. Thanks folks for the discussion.

**Comment by patrick-rodgers** [comment]
This is added and merged. I also just published a beta version so folks can try it out. Please see the new [doc page](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Navigation-Service) for details.
```
npm i sp-pnp-js@3.0.4-beta.0
```

**Comment by russgove** [comment]
I used the search based nav I noted above on some sites because the
structural nav was to slow. Can this new api be used to fetch the
structural nav for an entire site?

**Comment by jonathanhotono** [comment]
Thanks guys! Yes I am using this api to produce a mega menu for classic masterpage. I was just trying to tackle the performance issue on the server side rendering by loading the navigation using this managed navigation api. 

@russgove , I think based on the api you must utilize
`pnp.sp.navigation.getMenuNodeKey` to get the menu node key for a specified site collection then utilize `pnp.sp.navigation.getMenuState("**[NODE_KEY_HERE]**", 5)` to get the navigation of that site.

I did had a look with the search based api, it seems like a good solution but our intranet owner wants an "on demand" navigation for critical nav update. https://support.office.com/en-us/article/Navigation-options-for-SharePoint-Online-adb92b80-b342-4ecb-99a1-da2a2b4782eb
