### ISSUE TITLE
roleDefinitions add parameter was not correct

### ISSUE THREAD

**Issue by holysnake91** [SharePoint/PnP-JS-Core#670]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   3.0.3      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

Regarding this function pnp.sp.site.rootWeb.roleDefinitions.add(name:string,description:string,order:number,basePermissions:BasePermissions)
the basePermissions was using wrong format, i will get the error as picture below.
![image](https://user-images.githubusercontent.com/15364241/34239506-b618add0-e642-11e7-9e46-daa1b7cd0762.png)

After i test, the REST API required the high & low value of BasePermission to be pass in string.

**Comment by patrick-rodgers** [comment]
Thanks @holysnake91 for reporting this. Interesting as it used to work and now doesn't. I have fixed the interface to mark those properties as strings as well as added a test to ensure we catch it if it starts failing again. Thanks!
