### ISSUE TITLE
Different search results returned based on site executing the query

### ISSUE THREAD

**Issue by kmosti** [SharePoint/PnP-JS-Core#673]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

[3.0.3]

#### Expected / Desired Behavior / Question

The search query returns inconsistent results and I wonder if it is because I need to set some search property to allow returning consistent results.

The issue is that when I search from an Office 365 group (public or private), I only get 2 results from a query that returns 25 results when searching from tenant.sharepoint.com/search with the same code.

I do not understand why I get two results at all, but I suspect that it might have to do with the fact that the other 23 items are far newer (less than 24 hours old items, with one item per site collection so 23 new site collections as well)? However the search index should be the same across sites, right?

#### Observed Behavior

Console results when submitting query from within a group site collection:
![image](https://user-images.githubusercontent.com/20144749/34274495-20a06f3e-e699-11e7-91bc-8a23316d7e6f.png)

The same code executed from https://tenant.sharepoint.com/search:
![image](https://user-images.githubusercontent.com/20144749/34274520-39cab53c-e699-11e7-9bc3-ae9d682367b4.png)

#### Steps to Reproduce
I am using the Chrome SP editor to debug: [Chrome-SP-Editor](https://github.com/tavikukko/Chrome-SP-Editor)

```
import pnp, { SearchQueryBuilder, SearchResults, SearchQuery } from "pnp";

const _searchQuerySettings: SearchQuery = {
    TrimDuplicates: false,
    RowLimit: 500,
    SelectProperties: ["Title", "SPWebUrl"]
}

let q = SearchQueryBuilder.create("ContentType:ProsjektInformasjon", _searchQuerySettings).rowLimit(500);

pnp.sp.search(q).then(res => { 
	console.log(res.PrimarySearchResults.length);
	console.dir(res.PrimarySearchResults)
});
```
Thank you for a great library, it's the kind of "sugar on top" solution that makes developing new solutions for Office 365 a joy, so I hope you can help me overcome this minor annoyance :)

**Comment by kmosti** [comment]
I figured this one out.

Since the content is in private groups, I had to specify the search property to allow content from these:

```
const _searchQuerySettings: SearchQuery = {
    TrimDuplicates: false,
    RowLimit: 500,
    SelectProperties: ["Title", "SPWebUrl", "projectID"],
    Properties: [{
      Name: "EnableDynamicGroups",
      Value: {
        BoolVal: true,
        QueryPropertyValueTypeIndex: 3
      }
    }]
```

It would be nice if there was an easier way to set the searching of private groups, could this be added added as a feature request?

**Comment by patrick-rodgers** [comment]
Hi @kmosti - glad to see you figure it out. One of the issues with search is that there are so many ways to do things it is impossible to add shortcuts for all of them, and then we would miss some and each of the ones we would do would not meet someone's needs. For this reason we generally recommend folks 
create their queries as they need for their applications from the raw object. Or you can use the [query builder](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Search#searchquerybuilder), which can help create structured queries.

If you have a concrete proposal for what we could do to help out here we'll certainly have a look and can discuss.

**Comment by kmosti** [comment]
Thank you @patrick-rodgers, I can understand that you do not want to bloat this more than necessary, however I believe this is important because querying against content in office 365 groups is expected behaviour from a search service, without having to set some obtuse setting to true.

I suggest that a fix would be to change the SearchQuery interface to include a property for searching private groups, so that these two variables accomplish the same thing:

```
const _searchQuerySettings: SearchQuery = {
    TrimDuplicates: false,
    RowLimit: 500,
    SelectProperties: ["Title", "SPWebUrl", "projectID"],
    Properties: [{
      Name: "EnableDynamicGroups",
      Value: {
        BoolVal: true,
        QueryPropertyValueTypeIndex: 3
      }
    }]
}
```

```
const _searchQuerySettings: SearchQuery = {
    TrimDuplicates: false,
    RowLimit: 500,
    SelectProperties: ["Title", "SPWebUrl", "projectID"],
    queryPrivateGroups: true
}
```

I also believe that the default behaviour should be set to true (who want to search against an incomplete index?).

Failing that, I suggest that the wiki include a small mention of this issue.

**Comment by patrick-rodgers** [comment]
Hi @kmosti - had a think on this while I was out and I think the right approach is to [add this to the search wiki article](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Search#searching-for-office-365-groups). Please have a look at what I added and let us know if there are any details we should add.

My thinking here is that if we did the bool property and translate it at run time to the search property it opens the door to why don't we cover each special case with a property.

Thanks for using the library and keep the great feedback coming!

**Comment by kmosti** [comment]
Yes, I see your point and I agree having it mentioned in the wiki is a good solution.

Thank you for your help and for providing this great library 👍

**Comment by patrick-rodgers** [comment]
Going to close this as resolved, and thanks again for the feedback!
