### ISSUE TITLE
Paging with getItemsByCAMLQuery

### ISSUE THREAD

**Issue by khaderabdul** [SharePoint/PnP-JS-Core#674]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [  2.0.8  ]

Hello folks,

I am trying to fetch paged data from a list filtering by a Managed metadata column. I could only do that through a CAML query. But I am unable to get paged data by the getPaged() method. Below is my code 

![image](https://user-images.githubusercontent.com/18727287/34303872-03dea1e0-e6fd-11e7-9deb-f8930c62026e.png)

list.getItemsByCAMLQuery({ ViewXml: viewXML }, "Folder").getPaged().......this is not supported.

Is this functionality available or any work-arounds?

Thanks!

**Comment by patrick-rodgers** [comment]
The method getItemsByCAMLQuery executes the request and returns the items you have requested so the getPaged method is not available on the Promise<any> that you get back. We don't have any special helpers for CAML query as the odata methods are preferred. You can page using the ListItemCollectionPosition as shown in the sample code below:

```TypeScript
const xml = "<View><ViewFields><FieldRef Name='ID' /><FieldRef Name='Title' /></ViewFields><Query><OrderBy><FieldRef Name='Title' /></OrderBy></Query><RowLimit>2</RowLimit></View>";

const q: CamlQuery = {
    ViewXml: xml,
};

pnp.sp.web.lists.getByTitle("SPPnPJSExampleList").getItemsByCAMLQuery(q).then((r: any[]) => {

    console.log(JSON.stringify(r, null, 4));
    const last = r[r.length - 1];

    // build a query to get the next page
    const q2: CamlQuery = {
        ListItemCollectionPosition: { PagingInfo: `Paged=TRUE&p_ID=${last.ID}&p_Title=${last.Title}` },
        ViewXml: xml,
    };

    // run the next page query
    pnp.sp.web.lists.getByTitle("SPPnPJSExampleList").getItemsByCAMLQuery(q2).then((r2: any[]) => {

        console.log(JSON.stringify(r2, null, 4));
        process.exit(0);
    });

}).catch(console.error);
```

**Comment by patrick-rodgers** [comment]
Also updated [the wiki article](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#paging-with-getitemsbycamlquery) to include the above code.

**Comment by khaderabdul** [comment]
Thanks Patrick. I was able to build upon your idea and get through this.

**Comment by NasirSP** [comment]
i'm using the same code for pagination but it says "cannot find name 'CamlQuery'" 
```
const q: CamlQuery = {
            ViewXml: xml,
        };
```
i tried to install npm install camlquery --save but it seems there is no package for it
can you please let me know how to fix it?

**Comment by harshdamaniahd** [comment]
@patrick-rodgers  is it possible to filter list data using term id ? instead of value
