### ISSUE TITLE
Minimizing footprint in bundle

### ISSUE THREAD

**Issue by Leif-Frederiksen** [SharePoint/PnP-JS-Core#678]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [    3.0.2     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I am trying to optimize the size of my bundle, and I can see that sp-pnp-js is making quite a large footprint. Is there some way to optimize this? For example I am using only the Web object in some code, but I cannot find a way to import only that. I was thinking something like this:
import { Web } from sp-pnp-js/sharepoint/web;

I use import { Web } from sp-pnp-js; but this still includes "everything" in the bundle.

**Comment by patrick-rodgers** [comment]
Issue you will have there is that Web references pretty much everything else across the library. You could try and import more specific things, but then you'll lose the benefits of the fluent api. The best thing is to ref the library from a cdn and all clients will only need to grab it once (until you update the ref). So a one time hit vs packaging it in every bundle. That also will work across packages.

For the upcoming [@pnp scoped libraries](https://github.com/pnp/pnp) we have created the packages inline with what the rollup folks recommend so hopefully along with the split packages folks can realize some benefits from tree-shaking.

**Comment by patrick-rodgers** [comment]
Going to close this as it appears answered. If you would like to continue the discussion, please _reopen_ the issue. Thanks!
