### ISSUE TITLE
Fill UserField column in a list with ID User or Group

### ISSUE THREAD

**Issue by souuuf** [SharePoint/PnP-JS-Core#679]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Hello,

i have a need to fill a userField column in a list with an user or security group existing in AD.

so i have used this endpoint, to search a user/group. everything is ok, i can search for users and also for security groups, but unfortunatly i don't have the ID of user or group in the results.

/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser

as i understand, to use pnp for adding element in a list with a column UserField, i have to use the IDs of user/group.

My question is, how can i retrieve the ID of a user or security group using PNP.
i have tested this function, it works well with the loginName of a user. but retrieves nothins when i pass a loginName of a securityGroup

pnp.sp.profiles.getPropertiesFor("i:0#.f|membership|sou***@w****")
    .then(result =>{
        console.log(result);
    });

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by koltyakov** [comment]
> i have a need to fill a userField column in a list with an user or security group existing in AD.

Please check [this wiki article](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#user-fields) on what a payload format should be for people picker.

> to use pnp for adding element in a list with a column UserField, i have to use the IDs of user/group.

Yes, you should provide site collection's user id to populate user lookups. REST API works in such a way.

> My question is, how can i retrieve the ID of a user or security group using PNP.

It depends on scenario and amount of users and some other factors.
There is a special system list with uses which have been ensured on a site collection - UIL - User Information List. The same user on different site collections can have different IDs.

UIL list data (users and groups) can be requested with:

```typescript
pnp.sp.web.siteUsers.get().then(console.log);
```

The user which can be gotten with search or people picker's `clientPeoplePickerSearchUser` might be absent on a site collection. To get his/her ID, a user should be ensured. e.g.:

```typescript
pnp.sp.web.ensureUser('name or email here').then(console.log);
```

Ensure returns user object or creates UIL item and then returns user object.

If it's a question of a few users you can simply ensure then use id for lookup population.
In batch processes, I would suggest reading UIL data and ensure only in case is no such users are on site collection yet.

Hope this will help.

**Comment by souuuf** [comment]
Thank you,
it was really helpfull.
i'll use the pnp.sp.web.ensureUser('name or email here').then(console.log); Method

and pass the DisplayName of the search result that i get from the clientPeoplePickerSearchUser as parameter

Now, i'll have to use those IDs, to give permissions on a specific listitem. so i guess i have to find out how to break inheritance in a specific listitem, and then add those people

**Comment by koltyakov** [comment]
For permissions, [this](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Permissions) can be useful.

This script adds role assigment:
```typescript
(async () => {

	let listName = 'ID3Vnext';
	let itemId = 1;
	let principalId = 8; // User or group
        let permissionsRoleName = 'Contribute';

	const web = pnp.sp.web;
	const itemObject = web.lists.getByTitle(listName).items.getById(itemId);
	const hasUniqueRoleAssignments = await itemObject.select('HasUniqueRoleAssignments').get();
	if (!hasUniqueRoleAssignments) {
		await itemObject.breakRoleInheritance(); // break options
	}

	let roleDef = await web.roleDefinitions.filter(`Name eq '${permissionsRoleName}'`).get();
	await itemObject.roleAssignments.add(principalId, roleDef[0].Id);
	console.log('Permissions granted');

})();
```

**Comment by souuuf** [comment]
Thank you very mutch
