### ISSUE TITLE
Getting 404 with long CAML Query in renderlistdata function

### ISSUE THREAD

**Issue by SvenLauterbach** [SharePoint/PnP-JS-Core#680]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ sp-pnp-js v3.0.2 ]

#### Expected / Desired Behavior / Question
I would like to use the "renderlistdata" with any valid CAML Query i can build. 

#### Observed Behavior
When using the "renderlistdata" function with a long caml query, i get a 404 form SharePoint Online. When shortening the CAML, by removing fields from "<fieldref>", the query does run.

Example Query:

`<View>
    <ViewFields>
        <FieldRef Name="Title" />
        <FieldRef Name="Relation" />
        <FieldRef Name="Parent" />
        <FieldRef Name="Child" />
        <FieldRef Name="Parent_Title" />
        <FieldRef Name="Parent_Picture" />
        <FieldRef Name="Child_Title" />
        <FieldRef Name="Child_Picture" />
    </ViewFields>
    <Joins>
        <Join Type="LEFT" ListAlias="Parent">
            <Eq>
                <FieldRef Name="Parent" RefType="ID" />
                <FieldRef Name="ID" List="Parent" />
            </Eq>
        </Join>
        <Join Type="LEFT" ListAlias="Child">
            <Eq>
                <FieldRef Name="Child" RefType="ID" />
                <FieldRef Name="ID" List="Child" />
            </Eq>
        </Join>
    </Joins>
    <ProjectedFields>
        <Field ShowField="Title" Type="Lookup" Name="Parent_Title" List="Parent" />
        <Field ShowField="Picture" Type="Lookup" Name="Parent_Picture" List="Parent" />
        <Field ShowField="Title" Type="Lookup" Name="Child_Title" List="Child" />
        <Field ShowField="Picture" Type="Lookup" Name="Child_Picture" List="Child" />
    </ProjectedFields>
    <Query>
        <Where>
            <Or>
                <Eq>
                    <FieldRef Name="Parent" />
                    <Value Type="Number">1</Value>
                </Eq>
                <Eq>
                    <FieldRef Name="Child" />
                    <Value Type="Number">1</Value>
                </Eq>
            </Or>
        </Where>
    </Query>
</View>`

#### Steps to Reproduce
Create a List with some fields, lookup for example, and create a somewhat long caml query.

#### Context
Why Caml anyway? I couldn't find a way to retrieve managed metadata columns, lookup columns and user fields in one REST query. Especially Managed Metadata Fields do only return a Id from the HiddenTaxonomyList. 

### Possible Cause
Maybee the HTTP 404 is caused by a to long URL, some googling brought up some [SO post](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184) about URI max length. If so, it would be great to use the request body for the ViewXml. If there is no problem by using the request body i could create a pull request for it.

Thanks!

**Comment by koltyakov** [comment]
How about trying [RenderListDataAsStream](https://github.com/SharePoint/PnP-JS-Core/pull/588/files)?
`viewXml` is not a part of the URI, but a part of the payload and these URI length limitations should not affect. (But I haven't try RenderListDataAsStream personally, yet have a feeling it should suit the task).

**Comment by SvenLauterbach** [comment]
`renderListDataAsStream({ ViewXml: query })` does work! Thanks
