### ISSUE TITLE
How to update a listitem column of hyperlink type?

### ISSUE THREAD

**Issue by trillian74** [SharePoint/PnP-JS-Core#682]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [   1.3.4      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

I want to update a listitem column of hyperlink type, but i cannot see how to put that into a typedHash 
where off course the Thumnail has Url and Description
` SharePointDataProvider.UpdateItem("Insulation Items", this.state.item.Id, {
                    Thumbnail: config.images + file.name
              })`

Do you have en example on how to update such a column?

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @trillian74 - just wanted to confirm you are using the sp-pnp-js library? The code you posted appears to be from something else? Or perhaps a wrapper? Can you share the code you are using showing the call to sp-pnp-js methods so we can better assist? Thanks!

**Comment by trillian74** [comment]
Hi @patrick-rodgers 
Thanx for picking this up. i'm using  "sp-pnp-js": "^3.0.1"

it's just a wrapper
` public static UpdateItem(listName: string, itemId: number, item: TypedHash<string>): Promise<any> {
        return pnp.sp.web.lists.getByTitle(listName).items.getById(itemId).update(item);
    }`

**Comment by patrick-rodgers** [comment]
Ah, I see. One thing that will help you is that the item update now takes an TypedHash<any> so you can pass a more complex object.

I think this should work for you:

```TypeScript
 pnp.sp.web.lists.getByTitle("SPPnPJSExampleList").items.getById(1).update({
        UrlField: {
            "__metadata": { type: "SP.FieldUrlValue" },
            Description: "Description",
            Url: "https://318studios.sharepoint.com/sites/dev/Style%20Library/DSC_0024.JPG?csf=1&e=3729ff5a8af5402f8158192f61964747"
        },
    })
```

**Comment by trillian74** [comment]
thanx, actually i saw that i didn't hav any in the wrapper this morning 👍 Works as i wanted.
