### ISSUE TITLE
Shared Top Navigation

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#683]
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

Hi, I created a  a new web with pnp-js-core. I want to set it so that it shares the top nav  of the parent site.  I see the rest url is at /_api/Web/Navigation/TopNavigationBar/UseShared. Is that 'mapped' somewhere in the library? How do I do that wit pnp-js-core?

**Comment by patrick-rodgers** [comment]
No, I don't believe we have that anywhere. I can have a look.

**Comment by russgove** [comment]
yeah, i found it's a read only rest property. embedded up using jsom.
