### ISSUE TITLE
sendEmail From address is always the web title

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#684]
#### Expected / Desired Behavior / Question
Emails sent using  pnp.sp.utility.sendEmail(emailprops) should use the emailProps.from  as the from address

#### Observed Behavior
Emails sent using  pnp.sp.utility.sendEmail(emailprops) use  the web title as the From address

#### Steps to Reproduce
  let emailprops: EmailProperties = {
      To: toAddresses,
      CC: ccAddresses,
      Subject: "Task " + task.Title + " has been marked complete by " + this.context.pageContext.user.email,
      Body: this.context.pageContext.user.email + " has confirmed that " + task.EFRInformationRequested + " has been uploaded to the library " + task.EFRLibrary,
      From: " External Financial Reporting"
    }
    
    console.log("Sending email:");
    console.log(emailprops);
    await pnp.sp.utility.sendEmail(emailprops)
      .then((x) => {
        debugger;
      }).catch((err) => {
        debugger;
        console.error(err);
        (err);
        alert('Error sending email');
      })
  }

In the above snippet I expect the email 'from address to be ExternalFinancial Reporting, but in the email I receive the from address is the title of the web

**Comment by patrick-rodgers** [comment]
Looking at how the method works on the server side for REST calls the from value of the properties goes through a validation by calling the SPUtility.ResolvePrincipal method. If the supplied value does not resolve it uses the default configured from address for the site collection. This is done as a security precaution and there is no override to the behavior. So if you want to specify the from address it needs to resolve via ResolvePrincipal.

Going to close this as answered, HTH helps.

**Comment by russgove** [comment]
Ah, thanks patrick
