### ISSUE TITLE
Git question

### ISSUE THREAD

**Issue by nickvanhooydonk** [SharePoint/PnP-JS-Core#685]
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

Please specify what version of the library you are using: [    does not apply     ]

#### Expected / Desired Behavior / Question
I'm relatively new to Git and have a question about contributing:
I want to create a pull request on the dev branch, but I can't seem to push my local new branch to this Git repository. Is it not the intention to create a new branch to compare to basebranch DEV? (Or am I performing the wrong steps?)
Sorry in advance for my simple Git question.

#### Observed Behavior
Log:
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git config --get commit.template
git show :settings.js
git show :debug/debug-search.ts
git push -u origin fix_interface
remote: Permission to SharePoint/PnP-JS-Core.git denied to ***.
fatal: unable to access 'https://github.com/SharePoint/PnP-JS-Core.git/': The requested URL returned error: 403

Thanks!

**Comment by koltyakov** [comment]
Hey @nickvanhooydonk,

[This article](https://www.linkedin.com/pulse/contribution-pnp-js-core-debugging-source-code-andrew-koltyakov/) together with [contributing wiki page](https://github.com/SharePoint/PnP-JS-Core/wiki/Getting-Started:-Contribute) might be helpful.
The first article contains basic git commands for working with upstreams.

Long story short:

1\. Create a fork (your copy of a project where you have full permissions)
2\. Add remote upstream origin:

```bash
git remote add upstream https://github.com/SharePoint/PnP-JS-Core  
```
 
3\. Make sure dev branch is in sync with remote upstream:

```bash
git fetch upstream dev 
```

4\. Create a feature branch:

```bash
git checkout dev  
git fetch upstream dev  
git checkout -b [name_of_your_new_branch] 
```

5\. Apply changes in the branch
6\. Test locally (manual and mocha tests)
7\. Commit and push changes to the feature branch
8\. Create Pull Request with GitHub web UI, provide PR's info for maintainers
9\. Make sure CI tests have been passed successfully
10\. Thanks for commitment and stay tuned with PR collaboration

**Comment by nickvanhooydonk** [comment]
Thnx @koltyakov ,

I was missing the part to create a fork first.
Going to give that a try!

**Comment by nickvanhooydonk** [comment]
First of all: 
Your article was giving me great guidance @koltyakov !

I've managed to create a pull request, however it seems that CI (also new to me :) ) can't connect to pnp js core repo for cloning... Is this probably a problem I created or does someone authorised need to take a look at the CI connection? (I cannot change the config for that I guess?)

**Comment by patrick-rodgers** [comment]
Hmmm, I'll have a look. No, that isn't something you can fix. Thanks for the PR we'll get it reviewed and included in the next release!

**Comment by patrick-rodgers** [comment]
All fixed, no idea, just a transient issue I guess. Will review the PR soon. Thanks again!

**Comment by nickvanhooydonk** [comment]
No problem. And thankyou @patrick-rodgers for all your hard work on this awesome project!
