### ISSUE TITLE
How to hide menu Item from Top Nav

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#687]
#### Category
[ ] Enhancement

[ x] Bug

[ x] Question

#### Version

Please specify what version of the library you are using:  3.0.3    ]

Hi, I'm trying to use the library to  hide menu items from the top nav in a classic site,

I use this to get all the items in the top nav 
await pnp.sp.site.rootWeb.navigation.topNavigationBar.get().then((topNavigationBarResults) => {
      debugger;
      this.topNav = topNavigationBarResults;
    })

and then later, when a user selects the site he wants to hide, I run this
return pnp.sp.site.rootWeb.navigation.topNavigationBar.getById(navItem.Id).update({IsVisible:false}).then((results) => {
        debugger;
    }).catch(err => {
      debugger;
    });

The code runs fine, but it does not set the IsVisible  property of the navigation node to false. 

Is this doable using the library?

**Comment by patrick-rodgers** [comment]
Hi @russgove - no, this isn't possible. I've just had a look and the update method doesn't actually do anything on the server side via REST. It is one of those cases where it is designed to work with CSOM where you are calling the various things in the context. Not sure how this was missed for so long, but I am going to remove the update method from navigation node as it doesn't affect anything.

**Comment by russgove** [comment]
Thanks Patrick. Do we have any plans to start using CSOM where rest wont do?

**Comment by patrick-rodgers** [comment]
I assume you mean calling client.svc directly? I have very mixed feelings on that but it is something we are considering. I know it is possible and folks are doing it, but it is not supported so I am not certain we should be encouraging that pattern.

If we do, that update will likely not be in sp-pnp-js but perhaps in a separate library within the @pnp scope where it can be isolated and optional.

Going to close this issue as the original question is answered, thanks!
