### ISSUE TITLE
New Method to get all items in a list , no matter the list size

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#689]
We sometimes have the need to get all items from a large list. The library should have a method to do so.  The method could take in a caml query string representing any filters you may want to apply, and a batchsize (how many rows to get at once). 

The method could get the top(batchsize) where id > lastrowidfetched

or some other algorithm

#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by koltyakov** [comment]
Something like this?

```typescript
import { sp, List } from 'pnp';

const getAllItems = (
	list: List,
	select: string = '',
	tickCallback?: (chunk?: any[], allData?: any[]) => void,
	skip: number = 0,
	results: any[] = []
): Promise<any[]> => {
	return new Promise(resolve => {
		let items = list.items;
		if (select) {
			if (select.indexOf('Id') === -1) {
				select = `Id,${select}`;
			}
			items = items.select(select);
		}
		if (skip) {
			items = items.skip(skip);
		}
		items.top(5000).get()
			.then((res: any[]) => {
				if (res.length > 0) {
					results = results.concat(res);
					if (tickCallback && typeof tickCallback === 'function') {
						tickCallback(res, results);
					}
					skip = res[res.length - 1].Id;
					return resolve(getAllItems(list, select, tickCallback, skip, results));
				} else {
					return resolve(results);
				}
			});
	});
};

const list = sp.web.getList('/sites/dev-a/Lists/MyList');
let tickCallback = (chunk: any[], data: any[]) => {
	// Can tick progress in the UI
	console.log(`Id: ${chunk[chunk.length - 1].Id}, retrived: ${data.length}`);
};
getAllItems(list, 'Id,Title', tickCallback).then(console.log).catch(console.log);
```

**Comment by russgove** [comment]
yes, exactly

**Comment by patrick-rodgers** [comment]
I am leaning towards this being better as a sample or in the documentation. There are not many cases where getting all the items in a list regardless of list size is needed. I also worry that this would just become the default method for folks loading items from a list and we would have essentially baked in a bad pattern.

Welcome other's thoughts on this.

**Comment by jcrocke9** [comment]
One business case in favor of this enhancement would be to check for duplicates (esp. against one field, to keep the call shorter) prior to creating an item.

**Comment by russgove** [comment]
another case would be if i wanted to store everything in localstorage and
then only fetch the delta on suseqeunt loads.

Also, for any king of graphing  we need the fulll dataset.

Also ,  sharepoint rest does not support eggregate functions if i want to
calculate the sum of all items in a list, i need all the data.

Patrick, I understand your concens about an inexperienced developer jsut
using this all the time... We could name the method
DANGEROUSLYFecthAllItems, and better yet, have an CamlQuery as a required
parameter to do any filtering you need. That will scare off any beginner!
(I think we need the cam filter anyway)

**Comment by patrick-rodgers** [comment]
@russgove - that's a good point. You can crash a car if you are not responsible, but we still let folks drive them. I don't think there are a ton of use cases but this is a case where we can make folks lives easier.

@jcrocke9 - in that case why not filter by that field and value and check it count > 0?

**Comment by russgove** [comment]
@patrick-rodgers  at least yo need to pass a test and get a license to drive a car.  Unfortunately any puts with a text editor can crash your farm😩

**Comment by patrick-rodgers** [comment]
I have added this in #702. Sample usage is shown below. Only the odata operations top, select, and filter are supported. usingCaching and inBatch are ignored - you will need to handle caching the results on your own. This method will write a warning to the Logger and should not frequently be used. Instead the [standard paging operations](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#paged-get) should be used.

```TypeScript
// basic usage
pnp.sp.web.lists.getByTitle("BigList").items.getAll().then((allItems: any[]) => {

    // how many did we get
    console.log(allItems.length);
});

// set page size
pnp.sp.web.lists.getByTitle("BigList").items.getAll(4000).then((allItems: any[]) => {

    // how many did we get
    console.log(allItems.length);
});

// use select and top. top will set page size and override the any value passed to getAll
pnp.sp.web.lists.getByTitle("BigList").items.select("Title").top(4000).getAll().then((allItems: any[]) => {

    // how many did we get
    console.log(allItems.length);
});

// we can also use filter as a supported odata operation, but this will likely fail on large lists
pnp.sp.web.lists.getByTitle("BigList").items.select("Title").filter("TItle eq 'Test'").getAll().then((allItems: any[]) => {

    // how many did we get
    console.log(allItems.length);
});
```

**Comment by russgove** [comment]
+1

**Comment by vpsrihari** [comment]
@koltyakov  getAll method is failing when used with sp-rest-proxy. Getting a 401 Unauthorized and below error message.

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1234' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by koltyakov** [comment]
@vpsrihari, `getAll` and `getNext` didn't work as the following request was based on the `odata.nextLink`, which ended up with a request to SharePoint URL and corresponding CORS and auth blocker.

Published a new version of the proxy (ver. 2.5.9), which takes care of `odata.nextLink`. Methods with paged collections should work now.
