### ISSUE TITLE
List.defaultView returns SharePointQueryableInstance type

### ISSUE THREAD

**Issue by bLasTamos** [SharePoint/PnP-JS-Core#692]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [3.0.4]

#### Expected / Desired Behavior / Question
I'm currently trying to add fields to the default view of a list. However, the type returned by `pnp.sp.web.lists.getByTitle('something').defaultView` is a `SharePointQueryableInstance` instead of a `pnp.View` therefore I cannot access the `fields` property.

Any reason for this return type?

Thanks!

**Comment by koltyakov** [comment]
How about this as a workaround?

```typescript
let list = pnp.sp.web.lists.getByTitle('...');
list.defaultView.get()
  .then(view => list.getView(view.Id).fields.get())
  .then(console.log);
```

**Comment by patrick-rodgers** [comment]
Thanks, we'll have a look. For now @koltyakov 's workaround should get you going.

**Comment by koltyakov** [comment]
I actually applied a fix too. Just testing it before PR.

**Comment by patrick-rodgers** [comment]
Haha, you are too fast :)

**Comment by bLasTamos** [comment]
Cool. Thank you for the fast fix!

**Comment by patrick-rodgers** [comment]
Closing this as the fix is checked into dev, will be part of next release.
