### ISSUE TITLE
SPFx and PnP core js with Vue JS 2.3.4 computed properties not working as expected

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#695]
I'm rendering SP List items using Vue Js, to get the data from SPList i'm using PnP core js.
here is the render and readItems method
   
![render](https://user-images.githubusercontent.com/35560455/35317884-519023a0-00f2-11e8-90f6-b2a45c54e5e1.PNG)

here is the read items method
<pre><code>
private readItems(): void {   
    pnp.sp.web.lists.getByTitle("SportsDetail").items
    .select("Title","StartDate","EndDate","TypeOfSport/Title")
    .expand('TypeOfSport').get().then(result => {       
    new Vue({
        el: `#app-${this.context.instanceId}`,
        data: {
          searchString:"",
          SportsData: result
        },
        computed: {
            FilteredSportsData:function() {
                var filteredItemsArray = JSON.parse(JSON.stringify(this.$data)).SportsData;//this.SportsData                
                var searchString = JSON.parse(JSON.stringify(this.$data)).searchString;//this.searchString;
                if (searchString == "")
                    return filteredItemsArray;               
             //Get the data from db again based on filter
                pnp.sp.web.lists.getByTitle("SportsDetail").items.filter("Title eq '" + searchString + "'").get().then(newResult => {                
                filteredItemsArray = newResult; //SHOULD CALL FIRST
               });
               return filteredItemsArray; //CONTAINS THE OLD DATA
            }
          }
      });//end of vue js binding      
    });
}</code></pre>
**My Requirement is**
1) i need to filter the data by title mentioned in the v-model
**Problem i'm facing**
I'm able to get the filtered data by title by using the inner call but the DOM is not updating because returned variable still contains the old data.
Also i'm unable to access properties in computed method defined in the data(e.g searchString, SportsData), normally we can access them using this.PropertyName but in this case it not working so i'm using var searchString = JSON.parse(JSON.stringify(this.$data)).searchString; instead of var searchString = this.searchString;

I Notice that filteredItemsArray contains the old data and called first before the inner call.
Work around i DID
I've used the vue js plugin for async call but it seems to be not working with Vue 2.3.4 as mentioned [here](https://github.com/foxbenjaminfox/vue-async-computed/issues/26)

**Comment by patrick-rodgers** [comment]
Hi @NasirSP - this appears to be an issue specific to Vue.js so we can't really offer support. Would recommend you open a ticket there or reach out in the [tech community](community.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) to see if anyone has any experience related to this issue. If you can determine that this is an issue with the library, please do _reopen_ the issue so we can assist. Thanks!

**Comment by koltyakov** [comment]
@NasirSP,

I've taken a look at your code, this part, which is framework agnostic:

```typescript
  //Get the data from db again based on filter
  pnp.sp.web.lists.getByTitle("SportsDetail")
    .items.filter("Title eq '" + searchString + "'")
    .get()
    .then(newResult => {
      filteredItemsArray = newResult; //SHOULD CALL FIRST
    });
  return filteredItemsArray; //CONTAINS THE OLD DATA
```

And `//SHOULD CALL FIRST` and `//CONTAINS THE OLD DATA` are wrong assumptions.
Code inside `.then(newResult => {` is obviously executes after the line with `return filteredItemsArray;`, cause PnP JS Core's requests are promises.

I do not know Vue unfortunately. But there should be some `asyncComputed` concept in Vue framework with which you might be able to work with the asynchronous flow.

```typescript
  return pnp.sp.web.lists.getByTitle("SportsDetail")
    .items.filter("Title eq '" + searchString + "'")
    .get();
```

Also, I would recommend taking a look at how Promises works in ES6, it can answer a lot of questions.

Hope this will help.

**Comment by NasirSP** [comment]
Hi @koltyakov 
the following i've already tried but not working, still return filteredItemsArray fires first.
`  return pnp.sp.web.lists.getByTitle("SportsDetail")
    .items.filter("Title eq '" + searchString + "'")
    .get();`

**Comment by koltyakov** [comment]
Hi @NasirSP,
 
Please check how to work with async data in Vue.js computed properties, [e.g.](https://alligator.io/vuejs/async-computed-properties/).
As I understood, `computed` just support synchronous functions. You cant use [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for computed props. For such a purposes libraries like `vue-async-computed` were created.
Then with understanding that PnP JS Core deals with promises you can target the question to anyone in Vue.js community.

**Comment by NasirSP** [comment]
Hi @koltyakov ,

well said "computed just support synchronous functions", thank you  very much.
will have to explore vue-async-computed for promises.
