### ISSUE TITLE
Unable to add lookup field

### ISSUE THREAD

**Issue by bLasTamos** [SharePoint/PnP-JS-Core#697]
#### Category
[x] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [3.0.4]

#### Expected / Desired Behavior / Question
I'm trying to add a lookup field using the `pnp.sp.web.lists.getByTitle('...').fields.add()` which simply posts to the field collection endpoint. Apparently, however, this cannot be used to create lookup fields as I'm getting this error:

`Please use addfield to add a lookup field instead.`

Since the `addfield` REST API method is not available from the pnp js core API, all I have left is `createFieldAsXml` which is less than ideal to use (prone to malformed XML errors and lack of any sort of intellisense). As a workaround for now I'll be using this though.

Would it be possible to add a method to the pnp js core API for accessing the `addfield` REST API method?

Thanks!

**Comment by patrick-rodgers** [comment]
Thanks, yes, we can have a look at this.

**Comment by patrick-rodgers** [comment]
Added support in #703 for addUser and addLookup method on fields, usage:

```TypeScript
const list = pnp.sp.web.lists.getByTitle("Issue697");

list.fields.addUser("TestUser", FieldUserSelectionMode.PeopleAndGroups);

pnp.sp.web.lists.getByTitle("Issue694").select("Id").get().then(r => {

    list.fields.addLookup("TestLookup", r.Id, "Title");
});
```

**Comment by agamayaservers** [comment]
and what about it using REST API ?
