### ISSUE TITLE
Accessing a SP Hosted Addin list

### ISSUE THREAD

**Issue by floodycarlow** [SharePoint/PnP-JS-Core#699]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 2.0.5  ]

Dear all, 

I am trying to access a SP hosted add in list from outside its context.

Using the Content Editor WebPart I have placed some script on a sub site of my site collection e.g. 
https://work.sharepoint.com/teams/d/sandbox/

My SP app addin is hosted in the same site collection e.g. 
https://work-9850ba148f9a52.sharepoint.com/teams/d/MyApp/

When I try to access the list item via the following code I get a 403 error.

```
var pageweb = new $pnp.Web("https://work-9850ba148f9a52.sharepoint.com/teams/d/MyApp/");

pageweb.lists.getByTitle('ListTitle').items.get().then((r) => {
                console.log(r);
                    })
                .catch(function (error) {
                    console.log('Fetch Error:', error);
                });
```

Do I need to do something else to access the list within the add in? e.g. SPRequestExecutor as stated here https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-1.0.*-to-2.0.*#setup-sprequestexecutorclient

Advice appreciated.

Cheers

**Comment by koltyakov** [comment]
Hey @floodycarlow,

As Add-Ins have different hostnames. They can't be accessed this way due to the cross-origin requests limitations.

Luckily, there is `SP.AppContextSite` API, which allows sending requests via the proxy.

Please check `crossDomainSite` and `crossDomainWeb` options.
They operate with `_api/SP.AppContextSite(@target)` endpoint.

**Comment by patrick-rodgers** [comment]
Hi @floodycarlow - Closing this as it appears answered, please _reopen_ if you have further questions on the topic. Thanks!
