### ISSUE TITLE
Field and Fields are not accessible from the top-level import

### ISSUE THREAD

**Issue by bLasTamos** [SharePoint/PnP-JS-Core#700]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.4]

#### Expected / Desired Behavior / Question
I'm using TypeScript heavily so relying a lot on type safety. I'm trying to use the `Field` type as it's being exported in `sharepoint/fields.ts` but it's not being exported in `sharepoint/index.ts`

From what I see, only `FieldAddResult` and `FieldUpdateResult` are being exported, `Field` and `Fields` are not.

I need this type to enforce type safety in one of my interfaces which isn't possible from the top-level import right now, I have to use `import { Fields, Field } from 'sp-pnp-js/lib/sharepoint/fields'`.

Perhaps exposing these types in the top-level import would make this a bit more consistent (like `Lists`, `Web`, ...)

Thanks!

**Comment by patrick-rodgers** [comment]
Thanks, will update.

**Comment by patrick-rodgers** [comment]
Added exports in #702
