### ISSUE TITLE
Cant Add Items in bacth

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#701]
#### Category
[ ] Enhancement

[X ] Bug

[X ] Question

See also https://github.com/SharePoint/PnP-JS-Core/issues/202

I copied the example given in the solution in the above issue, and ith throws and exeption  and does not  add items,  Response from SP is Invalid request. I am using 3.0.4.

>   debugger;
    var batch = pnp.sp.createBatch();
    var promises = [];

    for (var i = 0, len = 25; i < len; i += 1) {
      promises.push(pnp.sp.web.lists.getByTitle('CustomList').items.inBatch(batch).add({ "Title": "Title " + i }));
    }

    Promise.all(promises).then(function () {
      console.log("Batch items creation is completed");
    });

    batch.execute().then((x) => {
      debugger;
    }).catch((err) => {
      debugger;
    });

I tried removing the promises and that did not work either:
`var batch2 = pnp.sp.createBatch();
    

    for (var i = 0, len = 25; i < len; i += 1) {
      pnp.sp.web.lists.getByTitle('CustomList').items.inBatch(batch2).add({ "Title": "Title " + i });
    }

    batch2.execute().then((x) => {
      debugger;
    }).catch((err) => {
      debugger;
    });`

**Comment by koltyakov** [comment]
Hey Russell,

Batches work just fine for me in v 3.0.4.

```typescript
(async () => {

  const batch = pnp.sp.web.createBatch(); // Scoping to web, pnp.sp.createBatch() works as well
  const list = pnp.sp.web.getList(`${_spPageContextInfo.webServerRelativeUrl}/Lists/List%20B`);
  const entityType = await list.getListItemEntityTypeFullName(); // It's better get entity type separetly
  // and pass it into item add method, so no additional requests will be sent to get entity type for each item

  for (let i = 0, len = 25; i < len; i += 1) {
    list.items.inBatch(batch).add({
      Title: `Item ${i}`
    }, entityType);
  }
  // Promise.all should not be used together with requests in batches

  await batch.execute(); // Batch execute response doesn't contains responses
  // responces can be received in a specific requests promises resolutions
  // even if no phisical request were sent

  console.log('Done');

})()
  .catch(console.log);
```

**Comment by russgove** [comment]
I tried to run this
`  const batch = pnp.sp.web.createBatch();
    const list = pnp.sp.web.lists.getByTitle("CustomList");
    // It's better get entity type separetly and pass it into item add method, 
    // so no additional requests will be sent to get entity type for each item
    const entityType = await list.getListItemEntityTypeFullName();

    for (let i = 0, len = 25; i < len; i += 1) {
      list.items.inBatch(batch).add({
        Title: `Item ${i}`
      }, entityType);
    }
    // Promise.all should not be used together with requests in batches

    await batch.execute(); // Batch execute response doesn't contain responses
    // responces can be received in a specific requests promises resolutions
    // even if no phisical requests were not send

    console.log('Done');`

![image](https://user-images.githubusercontent.com/2412956/35405594-a3191208-01d4-11e8-9c70-a210d825566e.png)

The request never even gets sent.

**Comment by russgove** [comment]
The request does get sent, this is the response I see in fiddler
![image](https://user-images.githubusercontent.com/2412956/35405932-8d52227e-01d5-11e8-8f03-8f4b1d26da4e.png)

**Comment by koltyakov** [comment]
Strange, everything looks fine in the request. Just wondering did you keep `async` function modification?

That's what I have with the example I provided before:

![image](https://user-images.githubusercontent.com/7816483/35406073-009acb58-0219-11e8-8651-32bc56d59426.png)

Also checked all OData modes. It just works.

Just to be sure, what the environment? SharePoint version?
Does the same add requests work without batches?

Running out of the ideas.

**Comment by russgove** [comment]
I'm on O365 , first release tenant . If I remove the batching it just works fine. 

The request going out looks valid:
![image](https://user-images.githubusercontent.com/2412956/35406812-ebff96ce-01d7-11e8-8634-066153d9091b.png)

But every item in the batch is marked as a Bad request:
![image](https://user-images.githubusercontent.com/2412956/35406951-500f4d44-01d8-11e8-8b0b-c8a1fc5f864a.png)

**Comment by russgove** [comment]
I changed it so i got the  list the way you did 
    const list2= await pnp.sp.web.getList('/sites/GRCTest/test/Lists/CustomList')

made no difference, still broken

**Comment by russgove** [comment]
Ah, I found it. I was missing 
  pnp.setup({
        spfxContext: this.context,
      });

I don't know how the non batched version was working with out that, but I'm glad my issue is resolved (was not going to fly uploadiing 200k items one at a a time  :+1:

**Comment by russgove** [comment]
My webpart is running on the rootweb of the site. It creates a subsite with some custom lists and then is trying to add items in the subsite,.  i'm thinking the issue is something with the context.

**Comment by koltyakov** [comment]
@russgove, 

Got an idea after your last comment.
Could you try to create batch from the web object you are using for managing data on a subweb.

E.g.:

```typesctipt
const web = new Web('absolute_web_url');
const batch = web.createBatch(); // not from pnp.sp.web.createBatch
```

**Comment by russgove** [comment]
yep, doing that now.

**Comment by russgove** [comment]
Sure enough, that was this issue!  
Closing the ticket. 

But I noticed that ny upload time is hast about the same with batching as it was without . Thats unfortunate. I was hoping it would have sped thing up.  I guess its sharepoint taking time to add the items, not mey connection speed.

Any Ideas as to how to 'quickly' upload 200K items to O365?

**Comment by koltyakov** [comment]
Glad it works now. =) 

I usually use chunking batched depending on item payload size.

Similar like it was discussed in this [issue](https://github.com/SharePoint/PnP-JS-Core/issues/668#issuecomment-352986262).

I found myself always providing itemEntityType reducing requests number.

Not sure that there is a way to create 200K items "quickly".

In some scenarios, I would try uploading data source as a file, I guess it is a CSV. And then hit server-side procedure for the actual process of items creation, so a user can close the page after almost immediate response with "import file was uploaded, it will be processed in a while".

**Comment by russgove** [comment]
Yeah, its a csv. 
I guess its time I started learning all that azure stuff! upload a csv and have a webjob process it. Webjob would be the right tool for that, right?
