### ISSUE TITLE
web.lists.getByTitle().items.get() fails when deployed in SPFx webpart

### ISSUE THREAD

**Issue by yogsodoth** [SharePoint/PnP-JS-Core#705]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.4]
 
Not sure if this should be reported here or in the SPFx dev area, but sicne the functionality is specific to this library, here it is. 

#### Expected / Desired Behavior / Question
web.lists.getByTItle('listname').items.get() should call the URL https://tenantname.sharepoint.com/sites/sitename/_api/web/lists/getByTitle('listname')/items when deployed in a React SPFx webpart and placed on a modern page. (I am using a Communications Site template).

#### Observed Behavior
web.lists.getByTItle('listname').items.get() calls the URL https://tenantname.sharepoint.com/sites/sitename/SitePages/_api/web/lists/getByTitle('listname')/items when deployed. However, it calls a different, correct URL when in the remote workbench.

#### Steps to Reproduce
1. Generate new SPFx webpart solution using latest template. Choose SP Online Only/React for options.
2. Add sp-pnp-js to solution via npm i sp-pnp-js
3. Add something in componentDidMount to call pnp.web.lists.getByTitle().items.get() on a list in the site template ('Site Pages' or 'Site Assets' generally are there by default in modern sites). In my sample this just dumps the data to the console.
4. Test using gulp serve --nobrowser in the remote workbench at https://tenant.sharepoint.com/sites/sitename/_layouts/15/workbench.aspx - This will work, the app will call the correct URL and the list data will be loaded. 
5. Run gulp bundle --ship
6. Run gulp package-solution --ship
7. Deploy app package to an AppCatalog on your tenant.
8. Add app to site from classic Site Contents page.
9. Go to or create a Modern page in the site.
10. Start your browser's console.
11. Place the app on the page.
12. The app will call the incorrect URL and the attempt to load the list data will fail.

**Comment by koltyakov** [comment]
It's not a bug really. With SPFx, the context should be configured:

```typescript
pnp.setup({
  spfxContext: this.context
}); 
```

[Details here](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework).

**Comment by yogsodoth** [comment]
Thanks, @koltyakov,

The context setting code is present in my original web part that fails, but I forgot to place it in the test case. I'll update the test case and run it again, will keep you posted.

**Comment by yogsodoth** [comment]
Confirmed, this fixes my test case, I will have to find what other issue is affecting my original web part. Thanks for the help!
