### ISSUE TITLE
implement paging with getItemsByCAMLQuery and VUE JS

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#706]
I got the paging data using the [code](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#paging-with-getitemsbycamlquery) and binded that data to VUE JS successfully but can anyone let me know how to implement pagination html like i need to add next, prev and other paging controls and then that paging should work accordingly.

here is my full code 
![page](https://user-images.githubusercontent.com/35560455/35480069-58b0c21c-0420-11e8-8421-20f3257d7eee.PNG)

**Comment by koltyakov** [comment]
Hi @NasirSP,

`getItemsByCAMLQuery` is a "fallback" functionality to support backwards compatibility.

It's better to use OData working with REST until something can be done without CAML.

getItemsByCAMLQuery has some downsides, everything connected with the fact that this endpoint doesn't deal with OData standards, so no REST modifiers are supported.

Paging works with OData nicely, I would recommend starting with REST+OData approach. You can use [getPaged](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#paged-get) helper method. Or control pagination by yourself using `.skip(itemId)`.

With previous page button is a bit more difficult, the code should "remember" a correct item's ids to skip. There is no `getPrev` and `hasPrev` in the API.

When navigation in SharePoint (it's the same for the API) occurs, SharePoint deals with $skiptoken:

- Next page - `Paged=TRUE&p_ID=9`, where 9 is the last item Id on current page - automated with .skip function
- Previous page - `Paged=TRUE&PagedPrev=TRUE&p_ID=7`, where 7 is first item Id on a current page, `PagedPrev=TRUE` reverses the pagination mode - not implemented yet (am I right with it @patrick-rodgers?)

@patrick-rodgers, I have some thoughts on reverse order and skip, will reach you with a comment about it or a PR for discussion in upcoming days. Just returned from SPS Helsinki and dead tired. :)

**Comment by patrick-rodgers** [comment]
Hi @NasirSP - this appears to be general development question that would be more appropriate for the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) or a forum specific to working with vuejs. Would recommend you review the docs and comments @koltyakov shared on paging as well to help you get going. Going to close this as it doesn't relate directly to this library. Thanks!

**Comment by patrick-rodgers** [comment]
@koltyakov - we can follow-up on your ideas offline.

**Comment by NasirSP** [comment]
Thanks guys ;)
