### ISSUE TITLE
Create SP List Item using PnP Core JS ANONYMOUS

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#707]
I've created a sample Contact Us form, I've successfully added the form data to SharePoint list using PnP but when i try to submit form using anonymously it gives error. I've already enabled the followings
1) Anonymous access to my web application From CA
2) Unchecked the remote client desktop from CA to enable client API
3) enabled the anonymous access from Site Collection

**Note: I'm creating a Public website so need to submit form with anonymous user(s)**

ERROR is as follows

**"Failed to load resource: the server responded with a status of 401 (Unauthorized)"
"Error: Error making HttpClient request in queryable: [401] Unauthorized
    at new ProcessHttpClientResponseException (exceptions.js:24)
    at core.js:33
    at <anonymous>"**

**Comment by koltyakov** [comment]
Hi @NasirSP,

The front-facing public website should use backend for submitting such a data.

There is a variety of architectural solutions how to achieve such a communication. But it's definitely not recommended trying to access SharePoint data from within client-side script located on a third-party public site.

It's really the topic outside the library scope. Anyway, I would recommend:

## Scenario 1

1. Saving data to the site's database
2. Moving records to SharePoint list (let's assume this data is processed then in SP workflow) with a job 

## Scenario 2

1. Form post goes to site's backend method
2. Sites backend method talks to SharePoint (authenticated as an app)

I can also spotlight Microsoft Flow as one of the possible drivers which can simplify your task.

**Comment by NasirSP** [comment]
Hi @koltyakov thanks for the reply, I'm trying to store data into my SharePoint list.

**Comment by koltyakov** [comment]
And you are trying write/read SahrePoint list data from a public site page (some front facing site for public, e.g. PHP hosted site), aren’t you?

**Comment by NasirSP** [comment]
I've a SharePoint 2016 public facing site and trying to submit a contact us form anonymously....

**Comment by koltyakov** [comment]
Oh... got this. I thought you were going to achieve accessing from outside SharePoint site.
Have no anonymous environment by hand to check, but I more than a sure that this is a configuration issue. And anonymous users can't write to your list.

**Comment by NasirSP** [comment]
@koltyakov  appreciate.
actually yesterday i've done it by going into list settings -> permissions -> break inheritense -> select anonymous access -> allow anonymous user to add and view items.....
so after doing these configuration it starts working but i'm worried IS IT SAFE TO DO THAT?

because in my previous project, it was working without doing anonymous settings at list level.

**Comment by koltyakov** [comment]
If I'm not wrong there are a couple of modes in global settings scope with access to all by default and without access without configuring individual lists. Probably you dealt with access allowed, so no list level permissions settings required.

Anonymous access is always not safe and depends on how it is being used.

I'm going to close this here, as the question indirectly relates to the library itself. And more a generic topic about SharePoint configuration and use cases.

It's a nice topic for [Tech Community](https://techcommunity.microsoft.com) though.
