### ISSUE TITLE
PnP Core JS Filter title field value contains the string

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#710]
I'm trying to filter the data based on Title field of SharePoint list and i need to apply string contains the specific value. it should return all the records that contains the specific title, here is my code
```
 pnp.sp.web.lists.getByTitle("SportsDetail").items.select("Id","Title").filter("substringof Title" + $("#txtSearch").val() + "").get().then((responseAfterFilterChanges)=>  { 
console.log(responseAfterFilterChanges)
});
```
normal REST API query is working fine but i don't know how to apply substring in PnP
here is normal Rest Api query for contains
`/_api/lists/getByTitle('SportsDetail')/items?$select=Title,Id&$filter=substringof(searchString,Title)`

**Comment by koltyakov** [comment]
Hey @NasirSP,

What is placed to `filter` function is a string which goes to `$filter=`.
So it should have the identical format and structure.

**Comment by NasirSP** [comment]
it would be string as /_api/lists/getByTitle('SportsDetail')/items?`$select=Title,Id&$filter=substringof(**'searchString'**,Title) `
how can i write this query using pnp? i have a textbox for filter so I'm taking the value from there to pas as param

**Comment by koltyakov** [comment]
Didn't actually get the question. Anyway, might be helpful:

```typescript
interface ISportsDetail {
  Id: number;
  Title: string;
}

const getListResults = (search: string): Promise<ISportsDetail[]> => {
  pnp.sp.web.lists
    .getByTitle('SportsDetail')
    .items.select('Id,Title')
    .filter(`substringof('${encodeURIComponent(search)}',Title)`) // Filter param goes to $filter=[...]
    .getAs<ISportsDetail[]>();
};

// Using

getListResults($('#txtSearch').val())
  .then(processYourStuffCallback)
  .catch(handleErrorCallback);
```

**Comment by NasirSP** [comment]
you solved my problem, here is the final code....issue fixed thanks
`pnp.sp.web.lists.getByTitle("SportsDetail").items.select("Id","Title").filter("substringof('" + $("#txtSearch").val() + "',Title)").get().then((responseAfterFilterChanges)=>  {
     //do something
    });`

**Comment by koltyakov** [comment]
Glad you figured it out. Closing it now.
