### ISSUE TITLE
Get List of Pages by Content Type PnP JS

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#711]
does the library has any method to get all items associated with a specific content type e.g I've a Pages library that has following content types
1) Article Page
2) NewsPageConentType
3) EventsPageConentType

I need to retrieve all the pages from Pages library that are created with the "NewsPageConentType"
normally i use CAML Query for this purpose as follows
```
<Where>
  <Eq>
    <FieldRef Name='ContentType'/>
    <Value Type='Computed'>NewsPageContentType</Value>
  </Eq>
</Where>
```
it would be great if there is any method in PnP JS some thing like
` pnp.sp.web.lists.getByTitle("Pages").contentType("NewsPageContentType").items......`

**Comment by patrick-rodgers** [comment]
@NasirSP - appreciate your interest in the library and finding new ways to use it. You've been posting a lot of questions lately that seem to ask folks to write code for you to solve what appear to be requirements on projects. Can you share what code you've tried to use on the above? I see you had a question just an hour ago on filtering by Title - perhaps you can take that example and work on filtering by content type? In this case a specific method as you suggest is not required as filter should handle this case.

I don't want to discourage you, but the issues list is intended for reporting bugs, suggesting new features, or asking questions around existing code that might not be working. General questions such as this might be more appropriate in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev).

If you can share the code you are trying to use on the above we can see how we can help.

**Comment by NasirSP** [comment]
@patrick-rodgers Thanks for your feedback. Actually i'm posting questions related to PnP core js library as there is not too much information over the internet related to specific PnP lib. I think it would also be helpful for the other new members who want to use this library......there would be more material and help available by posting new questions/suggestions.

**Comment by NasirSP** [comment]
@patrick-rodgers  I want to get all the Pages from a pages library that are created with article page.
So here are the old ways i used normally.

1. using JSOM and CAML Query
`<Where>
  <Eq>
    <FieldRef Name='ContentType'/>
    <Value Type='Computed'>Article Page</Value>
  </Eq>
</Where>`
System would get only the items that are related to Article Page

2. Using the simple Rest Query
`/_api/web/lists/getByTitle('Pages')/items?filter=contenttype eq 'Article Page'&$top=1`

3. Using PnP
I'm trying the following query
`  private GetData(): void{

    pnp.sp.web.lists.getByTitle("Pages").items.filter("ContentType eq 'Article Page'").top(1).getPaged().then(p1 => {
             
            pagedItemCollection = p1;//storing the 1st page result      
            new Vue({
              el: `#app-${this.context.instanceId}`,
              data: {
                ArticlePages: p1.results
              }
            });
        });
  }`
and it shows error "500 internal server error". 
when i compared the final generated query with REST query so i noticed dollar sign ($) is being appended with query while using PnP so finally filter using PnP NOT working

here is the simple rest query
`/_api/web/lists/getByTitle('Pages')/items?filter=contenttype eq 'Article Page'&$top=1`
here is the rest query generated by PnP
`/_api/web/lists/getByTitle('Pages')/items?**$**filter=ContentType eq 'Article Page'&$top=1`

If i manually remove the $ from the query then it is working fine but as you know query is being generated from PnP so i cannot remove it.

Please suggest how can i achieve this functionality using PnP.

**Comment by koltyakov** [comment]
Hey @NasirSP,

PnP JS generates the correct parameter for OData filter. It should definitely be `$filter=`. `filter=` is incorrect and it just ignored you can change its value to whatever and it will return the same item.

![image](https://user-images.githubusercontent.com/7816483/35775166-ee45a030-0994-11e8-9494-bc4a21746d4e.png)

![image](https://user-images.githubusercontent.com/7816483/35775162-caf6b6d2-0994-11e8-9173-118479e28379.png)

![image](https://user-images.githubusercontent.com/7816483/35775165-e17b2942-0994-11e8-858c-a40a9c8c7979.png)

**Comment by NasirSP** [comment]
Agreed.
does this work on SharePoint Server as well? as per the [thread](https://techcommunity.microsoft.com/t5/SharePoint-Developer/SharePoint-2016-REST-API-query-filtered-by-ContentType/td-p/51946) Content type is not working

I'm using the same code for SharePoint Server (Not deployed yet as I'm using workbench for testing) and getting the following error on console
![a](https://user-images.githubusercontent.com/35560455/35775321-2491285c-09a0-11e8-8178-d2414a63f7d2.PNG)

and here is the response
![b](https://user-images.githubusercontent.com/35560455/35775326-3429ecfe-09a0-11e8-9155-9840ffc97668.PNG)

**Comment by NasirSP** [comment]
I've tried with Title field and its working but filtering with CONTENT TYPE is NOT working in **SharePoint Server 2016**

**Comment by koltyakov** [comment]
With On-Prem, you should filter ContentTypeId field, by id.

E.g.:
```
.filter(`startswith(ContentTypeId,'0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF3900242457EFB8B24247815D688C526CD44D')`)
```

Content type's Id can be requested first by its Name.

```typescript
const list = pnp.sp.web.getList('/Pages');

list.contentTypes
  .select('Id')
  .filter(`Name eq 'Article Page'`)
  .get()
  .then(cts => cts[0].Id.StringValue)
  .then(ctId => {
    return list
      .items
      .filter(`ContentTypeId eq '${ctId}'`)
      .get();
  })
  .then(console.log);
```

And it actually an example of generic question, not related to the library but general REST questions/issues. Really! =)

**Comment by NasirSP** [comment]
Hi @koltyakov  Thank you very much....Appreciate your help and usual support.

It is working with Content type Id, it retrieves the data except for Publishing Rollup image field value...for that i need to follow the Partrick's [answer](https://github.com/SharePoint/PnP-JS-Core/issues/694)

**Comment by koltyakov** [comment]
Going to close the issue.

My usual recommendation with PnP JS:

> In the end of the day, it's a wrapper for REST API, to make working with REST API easier and in fluent way. It's not an alternative API in SharePoint and completety relies on REST (and Graph API too), abstracts some low level parts. But regards responses issues when HTTP errors showing up, REST trubleshooting comes first.
