### ISSUE TITLE
Problem in upload a file to many (eg. 4) site collections 

### ISSUE THREAD

**Issue by aemadhavan** [SharePoint/PnP-JS-Core#714]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [  @pnp/sp@1.0.1       ]

#### Expected / Desired Behavior / Question

Copy a file from a document library and using file add method create in 4 different site collections.

#### Observed Behavior
File created in one site collection not in other 3 site collections..

#### Steps to Reproduce

```typescript
event.selectedRows.forEach((row: RowAccessor, index: number) => {
  //alert(Id: ${row.getValueByName('ID')});
  var id = row.getValueByName('ID');
  var fileName = row.getValueByName("FileLeafRef");
  var fileRef = row.getValueByName("FileRef");
  var fileSize = row.getValueByName("SMTotalSize");
  var banners = row.getValueByName("Audience_x003A_");
  var bannerTiles = row.getValueByName("Banner_x0020_Tile_x003A_");
  var destinationSiteURL = "";
  var destinationDocLib = "";
  let isPromotionalPricing: boolean = false;
  let isOwnerOperater: boolean = false;
  let ruleId: Number = -1;

  for (let i = 0; i < bannerTiles.length; i++) {
    if (bannerTiles[i].Label.indexOf('Promotional Pricing') > 0) {
      isPromotionalPricing = true;
      break;
    }
    if (bannerTiles[i].Label.indexOf('Owner Operator') > 0) {
      isPromotionalPricing = true;
      break;
    }
  }

  for (var i = 0; i < banners.length; i++) {
    switch (banners[i].Label) {
      case "All Banners":
        ruleId = 16;
        break;
      case "New World":
        ruleId = 10;
        if (isOwnerOperater) ruleId = 8;
        if (isPromotionalPricing) ruleId = 9;
        break;
      case "PAK'nSAVE":
        ruleId = 14;
        if (isOwnerOperater) ruleId = 12;
        if (isPromotionalPricing) ruleId = 13;
        break;
      case "Four Square":
        ruleId = 6;
        if (isOwnerOperater) ruleId = 4;
        if (isPromotionalPricing) ruleId = 5;
        break;
      case "Gilmours":
        ruleId = 2;
        if (isOwnerOperater) ruleId = 0;
        if (isPromotionalPricing) ruleId = 1;
        break;
    }
    let filter = "RuleExecutionOrder eq " + ruleId;

    sp.web.lists.getByTitle("Content Migration Rules").items
      .filter(filter).get().then(r => {
        destinationSiteURL = r[0].DestinationSiteURL;
        destinationDocLib = destinationSiteURL.substring(destinationSiteURL.indexOf("/sites")) +
          r[0].DestinationLibPath;
        let destinationWeb = new Web(destinationSiteURL);
        if (fileSize <= 10485760) {
          // small upload
          try {
            sp.web.getFileByServerRelativeUrl(fileRef).getBuffer().then((buffer: ArrayBuffer) => {
              destinationWeb.getFolderByServerRelativeUrl(destinationDocLib).files.
                add(fileName, buffer, true).then();
              //this.WaitCreation(destinationWeb,destinationDocLib,fileName,buffer,true)
            });
            //alert("Small File Uploaded");  
          }
          catch (e) {
            alert(e);
          }
        } else {
          // large upload 
          sp.web.getFileByServerRelativeUrl(fileRef).getBlob().then((blob: Blob) => {
            destinationWeb.getFolderByServerRelativeUrl("/sites/sandpit/em/BannersDocument/").files.
              addChunked(fileName, blob, data => { }, true).then();
          });
          // alert("Large File Uploaded");
        }
      });
  };

});
```

**Comment by koltyakov** [comment]
Hi @aemadhavan, 

Thanks for posting the issue!

**What are the actual messages in the error responses?**

Are you sure, that `destinationSiteURL` and `destinationDocLib` always stand for correct values?

This line, bwt,

```
destinationWeb.getFolderByServerRelativeUrl("/sites/sandpit/em/BannersDocument/")
```

is definitely incorrect. It will fail when `destinationWeb`'s URI is not `/sites/sandpit/em`.

### Offside comments:

I wouldn't recommend sending all the requests simultaneously and use sequential queue requests instead, especially in case of manipulating with files. By initiating promises inside forEach loop code ends up with executing them all at the same time.

It's better using `asyns/await` and `for of` loops. That's how one can be sure easily that the execution flow is sequential.

Also, `try/catch` makes no sense being around promises, `catch` should be used instead.

**Comment by aemadhavan** [comment]
Hi @koltyakov ,

Thank you for your quick response. you write destinationDocLib is wrong. 

POST https://<<tenant>>.sharepoint.com/sites/<<site1>>/_api/web/getFolderByServerRelativeUrl('/sites/<<site2>>/Published%20Documents')/files/add(overwrite=true,url='Test%20Docs.doc') 400 ()
FetchClient.fetch @ netutil.ts:62
retry @ sphttpclient.ts:95
(anonymous) @ sphttpclient.ts:127
SPHttpClient.fetchRaw @ sphttpclient.ts:119
(anonymous) @ sphttpclient.ts:74
Promise resolved (async)
SPHttpClient.fetch @ sphttpclient.ts:74
(anonymous) @ pipeline.ts:222
ListViewCmdSetExtCommandSet.ts:130 Error: Error making HttpClient request in queryable: [400] 
    at new ProcessHttpClientResponseException (core.ts:14)
    at core.ts:66
    at <anonymous>

Changed to **foreach to for**, though the still issue exist.

for(var sr=0;sr<event.selectedRows.length;sr++)
        {
          var row:RowAccessor = event.selectedRows[sr];
          var id = row.getValueByName('ID');
          var fileName = row.getValueByName("FileLeafRef");
          var fileRef = row.getValueByName("FileRef");
          var fileSize = row.getValueByName("SMTotalSize");
          var banners = row.getValueByName("Audience_x003A_");
          var bannerTiles = row.getValueByName("Banner_x0020_Tile_x003A_");
          var destinationSiteURL = "";
          var destinationDocLib = "";
          let isPromotionalPricing:boolean = false;
          let isOwnerOperater:boolean = false;
          let ruleId:Number =-1;
          //let batch = pnp.sp.createBatch();          

          for(let i=0;i<bannerTiles.length;i++)
          {
            if(bannerTiles[i].Label.indexOf('Promotional Pricing')>0)
            {
              isPromotionalPricing=true;  
              break;                     
            }
            if(bannerTiles[i].Label.indexOf('Owner Operator')>0)
            {
              isPromotionalPricing=true;  
              break;              
            }
          }
         
           for(var i=0;i<banners.length;i++){   
             
              switch(banners[i].Label)
              {
                  case "All Banners":
                      ruleId=16;                      
                      break;
                  case "New World":
                      ruleId=10;
                      if(isOwnerOperater)ruleId=8;
                      if(isPromotionalPricing)ruleId=9;
                      break;
                  case "PAK'nSAVE":
                      ruleId=14;
                      if(isOwnerOperater)ruleId=12;
                      if(isPromotionalPricing)ruleId=13;
                      break;
                  case "Four Square":
                      ruleId=6;
                      if(isOwnerOperater)ruleId=4;
                      if(isPromotionalPricing)ruleId=5;
                      break;
                  case "Gilmours":
                      ruleId=2;
                      if(isOwnerOperater)ruleId=0;
                      if(isPromotionalPricing)ruleId=1;
                      break;
              }
              let filter = "RuleExecutionOrder eq "+ruleId;  
              
              sp.web.lists.getByTitle("Content Migration Rules").items
                    .filter(filter).get().then(r => {                          
                      destinationSiteURL = r[0].DestinationSiteURL;                      
                      destinationDocLib  = destinationSiteURL.substring(destinationSiteURL.indexOf("/sites"))+
                                            r[0].DestinationLibPath; 
              alert(destinationSiteURL+" - "+destinationDocLib);
              sp.web.configure({});
              let destinationWeb = new Web(destinationSiteURL);              
              
              alert(this.context.pageContext.web.absoluteUrl);
              if (fileSize <= 10485760) {
                // small upload              
                      sp.web.getFileByServerRelativeUrl(fileRef).getBuffer().then((buffer: ArrayBuffer) => {
                        destinationWeb.getFolderByServerRelativeUrl(destinationDocLib).files.
                        add(fileName, buffer,true).then(r=>{alert("Migrated!!!");}).catch(er=>{console.log(er)});                        
                      });
                    //alert("Small File Uploaded");                    
              } else {
                // large upload 
                sp.web.getFileByServerRelativeUrl(fileRef).getBlob().then((blob: Blob) => {
                  destinationWeb.getFolderByServerRelativeUrl(destinationDocLib).files.
                  addChunked(fileName, blob, data => {}, true).then();
                });            
              // alert("Large File Uploaded");
              }    
              
              });             
                                      
          }
        }

**Comment by koltyakov** [comment]
Hey @aemadhavan, 

> you write destinationDocLib is wrong

I didn't. Just pointed that it might be wrong, depending on incoming data.

> POST  https://<>.sharepoint.com/sites/<>/_api/web/getFolderByServerRelativeUrl('/sites/<>/Published%20Documents')/files/add(overwrite=true,url='Test%20Docs.doc') 400 ()

In Chrome browser, please click a link, it navigates to Network tab and in there in Response, there is an actual meaningful message, e.g.:

![image](https://user-images.githubusercontent.com/7816483/35775833-ae2da12a-09a1-11e8-84cb-395c0f52d880.png)

> Changed to foreach to for, though the still issue exist.

Sequential requests might not fix the issue as we still know nothing about your issue. =( Without error message it's hard to assume anything and with OData response error it probably be obvious.

And... It's not `for of` loop. =) `For of` loops is an ES6 feature which allows awaiting inside. E.g.:

```typescript
interface MyData {
  Id: number;
  // ...
}
const processData = async (dataArr: MyData[]): Promise<void> => {
  for (const data of dataArr) {
    await asyncFunctions(data.i)
      .then(res => {
        return chainedAsyncFunc(res.someData);
      });
  }
  return 'Done';
};
```

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks to @aemadhavan and @koltyakov for the great discussion. Please _reopen_ the issue should we need to continue the conversation. Thanks!
