### ISSUE TITLE
pnp.sp.search - example causes 404 error when deployed

### ISSUE THREAD

**Issue by mimuchan** [SharePoint/PnP-JS-Core#716]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version
[    sp-pnp-js@3.0.4 with   @microsoft/sp-core-library@1.4.0    ]
#### Observed Behavior
The example on pnp.sp.search works fine on the workbench environment, but encounters 404 error when deployed on a sharepoint online tenant and runs pnp.sp.search....

**Comment by koltyakov** [comment]
Hey @mimuchan,

Are you providing [SPFx context](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp-pnp-js-in-SharePoint-Framework)?

**Comment by patrick-rodgers** [comment]
@mimuchan - did @koltyakov 's suggestion help or are you still stuck?

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks @mimuchan and @koltyakov for the great discussion. Please _reopen_ the issue should we need to continue the conversation. Thanks!
