### ISSUE TITLE
sp-pnp-js not working in SPFx extension components

### ISSUE THREAD

**Issue by AsishP** [SharePoint/PnP-JS-Core#718]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Bug
#### Version
Please specify what version of the library you are using: [  2.0.6 ]

#### Expected / Desired Behavior / Question
sp-pnp-js should be working fine with existing SPFx components. 

#### Observed Behavior
Failed to load sp-pnp-js in SPFx component. We have used sp-pnp-js module in SPFx extension that is currently deployed to production. Started getting an error today in SPFx Extension with an issue below. Screenshot also attached.

Uncaught (in promise) Error: ***Failed to load component "477d3c2c-af7d-4fb2-8bef-96e5b6271f20" (XXXXXCommandSet).
Original error: ***Failed to load path dependency "sp-pnp-js" from component "477d3c2c-af7d-4fb2-8bef-96e5b6271f20" (XXXXXXCommandSet).
Original error: ***Failed to create global variable "sp-pnp-js" from script "{}"
    at t [as constructor] (listview-host-assembly_en-us_3d49d8367af105d9948165ebdab83af1.js:208)
    at new t (listview-host-assembly_en-us_3d49d8367af105d9948165ebdab83af1.js:413)
    at Function.e.buildErrorWithVerboseLog (listview-host-assembly_en-us_3d49d8367af105d9948165ebdab83af1.js:413)
    at Function.e.buildLoadComponentError (listview-host-assembly_en-us_3d49d8367af105d9948165ebdab83af1.js:413)
    at listview-host-assembly_en-us_3d49d8367af105d9948165ebdab83af1.js:413
    at <anonymous>

![image](https://user-images.githubusercontent.com/11584558/35900477-3dd1fade-0c26-11e8-84d6-bc3745abfaf3.png)

#### Steps to Reproduce
Create an SPFx extension and add the below to config.json 

"externals": {
    "sp-pnp-js": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.min.js",
      "globalName": "sp-pnp-js"
    }
  }

Thanks!

**Comment by patrick-rodgers** [comment]
Hi @AsishP - I just checked and the cloudflare link appears to be valid and working. Is this something that has been working and just stopped? It does look like in [the thread you posted here](https://github.com/SharePoint/sp-dev-docs/issues/1321) you got a suggestion, did that help? Let us know so we can help toubleshoot.

**Comment by AsishP** [comment]
Hi @patrick-rodgers, yeah I had referenced the CDN always and it was working earlier. And the CDN link is working but SPFx is not loading it. It broke yesterday. Below is the error from VS Code.

Error: ***Failed to load path dependency "sp-pnp-js" from component "e0cfe462-b593-43c1-92ff-7362f92989b1"
listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:208
Original error: ***Failed to create global variable "sp-pnp-js" from script "{}"
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:208:15366)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:413:36570)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:413:42273)
    at Function.e.buildLoadPathDependencyError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:413:40170)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:413:17577
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-19.010/listview-host-assembly_en-us_2720d6cf234638ace6848b63069bd7f8.js:413:18160
    at <anonymous>

**Comment by AsishP** [comment]
A quick update, so I found a workaround for it but not a suggested one I suppose. I had to remove the external ref ("externals": {}) to sp-pnp-js CDN in order for it to work. I think now it is pointing to the local bundled sp-pn-js and not to the CDN one?

**Comment by waldekmastykarz** [comment]
@AsishP that shouldn't be necessary. There are two ways in which you can reference an external resource in the SharePoint Framework and if the one you use, doesn't match the format of the script you want to load, you will get an error. Could you share the contents of your project.json file?

**Comment by AsishP** [comment]
@waldekmastykarz , sorry am not able to find the file you meant by project.json. There is no file with such name in the SPFx extension project. Please let me know. Is it the bundled <GUID>.js file in temp -> deploy folder?

**Comment by waldekmastykarz** [comment]
Sorry, my bad. I meant `config.json`. Apologies for the confusion.

**Comment by AsishP** [comment]
Sure, no probs. Please find the config.json content below. It was working earlier till yesterday, so don't know how could the references go wrong on their own.
`{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "page-actions-command-set": {
      "components": [
        {
          "entrypoint": "./lib/extensions/PageActions/PageActionsCommandSet.js",
          "manifest": "./src/extensions/PageActions/PageActionsCommandSet.manifest.json"
        }
      ]
    }
  },
  "externals": {
    "sp-pnp-js": {
          "path" : "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.min.js",
          "globalName": "sp-pnp-js"
        }
  },
  "localizedResources": {
    "PageActionsCommandSetStrings": "lib/extensions/PageActions/loc/{locale}.js"
  }
}
`

**Comment by waldekmastykarz** [comment]
Right, so following my comment in the other thread, your config.json should look like:

```
{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "page-actions-command-set": {
      "components": [
        {
          "entrypoint": "./lib/extensions/PageActions/PageActionsCommandSet.js",
          "manifest": "./src/extensions/PageActions/PageActionsCommandSet.manifest.json"
        }
      ]
    }
  },
  "externals": {
    "sp-pnp-js": "https://cdnjs.cloudflare.com/ajax/libs/sp-pnp-js/2.0.6/pnp.min.js"
  },
  "localizedResources": {
    "PageActionsCommandSetStrings": "lib/extensions/PageActions/loc/{locale}.js"
  }
}
```

The approach you used is meant for loading non-modules. The approach above, is for loading modules, such as sp-pnp-js.

**Comment by AsishP** [comment]
Thanks @waldekmastykarz for pointing out the difference. Yeah it is working now. 
Didn't know the syntax were different for modules and non-modules. Don't remember reading it in the documentation.
Also, I thought that modules were only ones having "@microsoft" because I remember installing sp-pnp-js module later using npm.

Thanks for the help guys.

**Comment by waldekmastykarz** [comment]
Glad to hear it's working. Here is the section in docs explaining it: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library#load-a-script-from-a-cdn

**Comment by patrick-rodgers** [comment]
Thanks @waldekmastykarz and @AsishP for working through that. Going to close this as resolved.
