### ISSUE TITLE
add support for azure storage (and other azure stuff)

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#721]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

Extend the library to support azure. 
I am just starting to learn azure, but it would be really nice to have pnp-js api to access some azure stuff.
For azure queues it would be great to have 
pnp.az.StorageAccount.GetbyName(xxx).queue.getByName('aaa').items.add() 
pnp.az.StorageAccount.GetbyName(xxx).queue.getByName('aaa').items.peek()

These would make it easier to add items to a queue to trigger some batch process and see how many items are in the queue from within an spfx webparrt. The underlying rest apis are documented at https://docs.microsoft.com/en-us/rest/api/storageservices/queue-service-rest-api

Would be nice to have methods to get and put Azure Table storage as well. We could (perhaps) offload some large lists to  azure Table storage.  I have a 200k access table that I cant get loaded into sharepoint.. Would be nice if I could just drop it in Azure table storage and fetch it using pnp-js.

Would also be nice to start and stop App services. I could start them when a user loaded some page and then stop them when he left. I'm thinking for once in a while admin-type actions

Would be great

**Comment by koltyakov** [comment]
Isn't is "slightly" out of the scope of O365/SharePoint related stuff? Azure is a huuuge and separate topic to cover. E.g. I can say I know SharePoint, but I can't say the same about Azure no matter I'm using/consuming it frequently.
Russel, have you seen [Azure SDK for Node.js](https://github.com/Azure/azure-sdk-for-node)? For instance, [queues service](http://azure.github.io/azure-sdk-for-node/azure-storage-legacy/latest/QueueService.html) part. Doesn't it cover the automation you're going to implement?

**Comment by russgove** [comment]
andrew, thanks for pointing me to that library. i will give it  a try.

**Comment by patrick-rodgers** [comment]
Going to close this as out of scope. I certainly don't have the time to dedicate to another full set of APIs and it appears there are existing libraries to cover this already. Good idea, just can't commit to doing anything here currently.
