### ISSUE TITLE
People Picker End Point with pnpjs

### ISSUE THREAD

**Issue by vamsi981** [SharePoint/PnP-JS-Core#722]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[X ] Enhancement

[ ] Bug

[ X] Question

**Comment by koltyakov** [comment]
Hi @vamsi981,

Thanks for the question.
PnPJS is based on Fetch client and [ES6 Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
 
`.catch` is used for error handling in the promises.

**Comment by koltyakov** [comment]
As for custom endpoint and [people picker](https://github.com/SharePoint/PnP-JS-Core/issues/639#issuecomment-344915530), in particular, PnP's HttpClient can be used for requesting eny REST endpoint not covered with the fluent API at the moment of time.

**Comment by vamsi981** [comment]
Thank You very much @koltyakov, is there any plans to integrate people picker with PnP
