### ISSUE TITLE
getItemsByCAMLQuery - Issue with lookup fields

### ISSUE THREAD

**Issue by kunalkankariya** [SharePoint/PnP-JS-Core#723]
Hello!

#### Category

[ * ] Question

I am using the getItemsByCAMLQuery method to get some items from a list in my SharePoint online site. The viewfields part of the query has only one lookup field's name in fieldref. I get only the lookupfields Id as the result in JSON object. 

For instance, if the field name is Competency, in the results, only "CompetencyId" is returned with the ID of the item in the master list. I need to access the value of the lookup field. I am unable to find a away to achieve this.

Code snippet
`const xml="<View><ViewFields><FieldRef Name='Competency'></ViewFields></View>"; 
return $pnp.sp.web.lists.getByTitle(listName).getItemsByCAMLQuery({'ViewXml':xml}).then(function(result){
return result; `

I could've used the rest OData operators like expand to get the value but then I will be unable to filter the data based on a managed metadata column using the '$filter' operator which is part of the query.

**Comment by koltyakov** [comment]
Hey @kunalkankariya,

I have some concerns that it's even possible to $expand with getItemsByCAMLQuery.
As an alternative, I would suggest trying `renderListData` or, in case of SPO, `renderListDataAsStream`.
These methods also deal with viewXml (side comment: double quotes should be used inside), but return data in a bit different way. E.g.

```typescript
pnp.sp.web.lists
  .getByTitle('MyList')
  .renderListData(`
	<View>
	  <ViewFields>
	    <FieldRef Name="Competency" />
	  </ViewFields>
	  <Query>
		<Where>
		  <Eq>
		   <FieldRef Name="ID"></FieldRef>
		   <Value Type="Number">19</Value>
          </Eq>
        </Where>
      </Query>
    </View>
  `.trim().split('\n').map(i => i.trim()).join(''))
  .then(console.log);
```

should return the following payload:

![image](https://user-images.githubusercontent.com/7816483/36259924-e0705f60-1270-11e8-8771-ec68ab666f1a.png)

**Comment by kunalkankariya** [comment]
Hey @koltyakov,

I wasn't implying to use $expand with getItemsByCAMLQuery. I was referring to the usual pnp syntax of querying items using rest API (using a GET ). 

Thanks for the alternative. I will give this a try, looks like this is the answer to my query. :)

**Comment by kfircs** [comment]
Hi @koltyakov, 

I am trying to do so with paging,
Can I use renderListData? => How?
Or there is another way to expand LookUp Field with getItemsByCAMLQuery?

Thanks in advance, Kfir Chen.

**Comment by koltyakov** [comment]
Hi @kfircs,

I would suggest `renderListDataAsStream`, an advanced version of `renderListData` available in SP2016 and SPO:

```typescript
const list = pnp.sp.web.getList(`${_spPageContextInfo.webServerRelativeUrl}/Lists/Suppliers`);
list.renderListDataAsStream({
  ViewXml: `
    <View>
      <RowLimit>10</RowLimit>
    </View>
  `,
  Paging: 'Paged=TRUE&p_ID=10'
}).then(r => r.Row)
  .then(console.log)
```

**Comment by kfircs** [comment]
Hi @koltyakov,

Thanks for the quick response,
It's working =].

Best Regards, Kfir Chen.
