### ISSUE TITLE
Uncaught (in promise) ReferenceError: PermissionKind is not defined

### ISSUE THREAD

**Issue by Cazeu64** [SharePoint/PnP-JS-Core#724]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version
 [    v3.0.4     ]

Hi !

I had an issue when trying to deal with permissions :

`$pnp.sp.web.currentUserHasPermissions(PermissionKind.AddListItems).then(perm => 
{
	console.log("Authorized : " + perm);
});`

I get the following error :

`Uncaught ReferenceError: PermissionKind is not defined`

I checked pnp.js, PermissionKind is defined in there.
Everything else is working fine.

Does anyone have an idea ? (I'm pretty new to that environment)

Thanks in advance ! :)

**Comment by patrick-rodgers** [comment]
I think you need $pnp.PermissionKind since it looks like you are working with the library in a global manner.

**Comment by Cazeu64** [comment]
Thanks for that fast reply.

Indeed, that worked, thanks a lot.

I could've found it by myself, sorry !
