### ISSUE TITLE
Error on import ClientSidePage

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/PnP-JS-Core#728]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[ yes] Question

#### Version
3.0.5
Please specify what version of the library you are using: [  node: 8.9.4, npm 5.6.0  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I am getting an error when i am adding 
import { ClientSidePage } from "sp-pnp-js" 

 it says " [ts] Module '"c:/Users/veeraman/Modernpage/node_modules/sp-pnp-js/lib/pnp"' has no exported member 'ClientSidePage'."

Thanks!

**Comment by patrick-rodgers** [comment]
This is a bug, and fixed in this #732. We will have a new release out in the beginning of March with this fix. If you need this functionality now you can also look to transition to the [@pnp libraries](https://pnp.github.io/pnp/) which do not have the same issue.

**Comment by veeramanx** [comment]
Hi Patrick, thanks you for your update. can you also let me know how to add custom web part into modern page. I have created textbox.io editor webpart and i am trying to add that into moder page page but cou;couldn't achieve this.

**Comment by veeramanx** [comment]
Hi, can you also let me know how to add custom client side webpart to modern page ?
