### ISSUE TITLE
How to get list of Choice fields and its values using PnP JS

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#731]
Hi,
I am working in SharePoint online with PnP. I have problem with to get list of selected fields and get the value of that fields. The fields are basically Choices field. I need to fetch the Choice field value and bind into different dropdown according to the field values. I tries the below approach but it is not working. Please help me for this.

`sp.web.lists.getByTitle(listTitle).fields`
       ` .filter('Hidden eq false')`
       ` .select('Type', 'Region', 'Frequency')`
       `.get()`
       `.map(field => { return {`
               `this.castAsList(field)`          
       `} })`

Method:-
`castAsList(field: any): MyList {`
    `return {`
      `Type: field.Type.Choices.results,`
      `Region: field.Region.Choices.results,`
      `Frequency: field.Frequency.Choices.results`
    `};`
  `}`

Thanks,
Philip

**Comment by koltyakov** [comment]
Hye @spvjebaraj,

With 

```typescript
list.fields.getByInternalNameOrTitle('ChoiceField').get().then(console.log);
``` 

you can get field schema with possible choices and a default one along with other metadata:

![image](https://user-images.githubusercontent.com/7816483/36468040-c7fd9674-16f2-11e8-878c-e38e0ec8417b.png)

Then use it in custom forms.

I really didn't get what kind of issue you're facing. But right in the code, there are 2 major errors:

- .map can't be chained with .get
- based on OData mode, choices options won't be always under .results prop

**Comment by spvjebaraj** [comment]
Hi Koltyakov,
If I use the above code, I can get only single field but I want to get multiple fields (in my list I'm having multiple Choice fields).
Please help me.

Thanks
Philip

**Comment by koltyakov** [comment]
There is no real difference, by filtering you're getting the same object's types but as array.

It can be done it with:

```typescript
list.fields
	.select('Choices,InternalName')
	.filter(`TypeDisplayName eq 'Choice'`)
	.get()
	.then(fields => {
		console.log(fields);
		return fields.reduce((res, field) => {
			res[field.InternalName] = field.Choices;
			return res;
		}, {});
	})
	.then(console.log)
```

![image](https://user-images.githubusercontent.com/7816483/36468903-4a4640ba-16f6-11e8-9e5c-cad51b277c47.png)

But does it relates to the library usage and not a general JS's dev? ;)

**Comment by spvjebaraj** [comment]
Hi Koltyakov,
Thanks a lot for your help. It works like a charm. Thanks again for your continuing support.
Actually I use Angular in my project and I return Observable, that's why I use map after get method.

Thanks,
Philip

**Comment by koltyakov** [comment]
> Angular in my project and I return Observable

Oh, yup, make sense.

Glad it works for you.

Closing the issue.
