### ISSUE TITLE
SharePointQueryable.clone and configure issue

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP-JS-Core#735]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

[latest]

#### Expected / Desired Behavior / Question
When using `configure` method with `SharePointQueryable's` `clone` method, configurable options (headers, etc) should be propagated to cloned object. 

#### Observed Behavior
Configurable options (headers, etc) are not propagated to cloned object. 

#### Steps to Reproduce
Call a method which uses `clone` inside, for example:
```TypeScript
pnp.sp.configure({
	headers: myHeaders,
}).utility.sendEmail(...)
```
`myHeaders` are not propagated to `sendMail`.

**Comment by patrick-rodgers** [comment]
Closing with merge of fix. Thanks @s-KaiNet !
