### ISSUE TITLE
copyTo should it create a new version in destination library?

### ISSUE THREAD

**Issue by trillian74** [SharePoint/PnP-JS-Core#737]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [     3.0.5    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
 pnp.sp.web.getFileByServerRelativeUrl(element.File.ServerRelativeUrl).copyTo(listInfo.RootFolder.ServerRelativeUrl + `/${element.File.Name}`, true)   shouldn't this update the version in destination library when the library has major fileversion versioning in place?

#### Observed Behavior
It doesn't - i just copies it

#### Steps to Reproduce
Copy from a library to a desitnation library with versionsupport for only major file versions

**Comment by patrick-rodgers** [comment]
Hi @trillian74 - the library just call the underlying REST method so will follow that behavior. Is the issue you expect the version to change from say 2 to 3 when it is copied and it stays 2?

**Comment by trillian74** [comment]
Yes, that is the situation. I work around it now with uploading new content
to destination, but it would be easier just to say copy to

Ole

man. 26. feb. 2018 kl. 16:05 skrev Patrick Rodgers <notifications@github.com

**Comment by patrick-rodgers** [comment]
Having had a look at this it is how the underlying API operates so nothing for us to change here. Unfortunate it doesn't work exactly as you'd like but so it goes. Thanks for your interest in the library and let us know if you have further feedback.

**Comment by trillian74** [comment]
No worries, and i love pnp

fre. 2. mar. 2018 kl. 16:39 skrev Patrick Rodgers <notifications@github.com
