### ISSUE TITLE
How to get SharePoint ListemItem Properties from the ListItem Unique ID using Search Engine (PNP JS)

### ISSUE THREAD

**Issue by Arioule** [SharePoint/PnP-JS-Core#739]
[ ] Question

#### Version

Version of the library I am using: [   3.0.4   ] : it is basically the last version compatible with SharePoint FrameWork (SharePoint 2016)

I would like to retrieve all the SharePoint ListItem Properties using the ListItem Unique ID.
How can I achieve it with PnP JS.

Regards,

Arioule

_

**Comment by patrick-rodgers** [comment]
Hi @Arioule please do see the guide for working with the [odata operators](https://github.com/SharePoint/PnP-JS-Core/wiki/Basic--Operations#odata-operators). I think you'll want to use filter on the items collection. Give it a try and if you are stuck please post your code so we can have a look at what might be wrong.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please do _reopen_ should you need to continue the conversation. Thanks!
