### ISSUE TITLE
Add custom client side webpart in modern page ?

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/PnP-JS-Core#740]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Hi, can you also let me know how to add custom client side web part to modern page ? i have done the following parts like getting webpart using ID and addcontrol but it is still not appearing in modern page. 

    const page = await ClientSidePage.fromFile(pnp.sp.web.getFileByServerRelativeUrl(`${siteurls}`));
    const partDefs = await pnp.sp.web.getClientSideWebParts();
    const part = ClientSideWebpart.fromComponentDef(partDefs.filter(c => c.Id === "{5A7081CE-4372-4F7C-A480-13B072326977}")[0]);
    const part1 = ClientSideWebpart.fromComponentDef(partDefs.filter(c => c.Id === "{863E3FB5-C9B8-46E2-9F40-6D19A59DE3B2}")[0]);
    const part2 = ClientSideWebpart.fromComponentDef(partDefs.filter(c => c.Id === "{D155B861-15C2-42FB-ADEA-B8663D0C8E4A}")[0]);
    const part3 = ClientSideWebpart.fromComponentDef(partDefs.filter(c => c.Id === "{6FEEF75A-6BD5-4728-86DD-EDCD75381C08}")[0]);
     
    part.setProperties<ClientSideWebpartData>({
      "id": "{5A7081CE-4372-4F7C-A480-13B072326977}",
      "instanceId": "dcb78f96-e670-47af-b65f-aebe589d5c9d",
      "title": "Helloworld2",
      "description": "Helloworld2 description",
      "dataVersion": "1.0",
      "properties": {
         "description": "Helloworld2"
        },
    });

    part1.setProperties<ClientSideWebpartData>({
      "id": "863e3fb5-c9b8-46e2-9f40-6d19a59de3b2",
      "instanceId": "ac83484b-d34a-4437-aa6c-eea0d88d80cb",
      "title": "Helloworld3",
      "description": "Helloworld3 description",
      "dataVersion": "1.0",
      "properties": {
      "description": "Helloworld3"
          }
      })
    page.addSection().addControl(part);
    page.addSection().addControl(part1);
    await page.save()

please let me know if i am making any mistake here
#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thanks!

**Comment by patrick-rodgers** [comment]
I think if you have a look at [this issue](https://github.com/pnp/pnp/issues/14) it is similar. There seems to be an inconsistency with the "{" and "}" chars. We are putting in a potential fix in the next version.

**Comment by veeramanx** [comment]
Hi Patrick, thanks for the update and fix. let me know when the next version is coming?

**Comment by patrick-rodgers** [comment]
New release just went out today.

**Comment by veeramanx** [comment]
Thanks patrick ...

**Comment by patrick-rodgers** [comment]
Are you missing the () on `await page.save`? Maybe should be `await page.save()`?

**Comment by veeramanx** [comment]
@patrick-rodgers  I am not missing () . i am using await page.save()

**Comment by veeramanx** [comment]
Hi patrick, any update on this please?

**Comment by bva999** [comment]
Hi. I have the same problem. Are there any updates?

**Comment by patrick-rodgers** [comment]
Can you share the errors you are getting? I also don't think you need to set the instance id or any of those other things, can you try something like this?

```
part.setProperties<ClientSideWebpartData>( {
     "description": "Helloworld2"
});
```

You haven't given us a lot to go on, so sharing the errors you are getting would really help us understand what is not working. Thanks!

**Comment by veeramanx** [comment]
@patrick-rodgers I am not getting any error. but, Webpart is not adding into the page instead I can see blank section added but no web part in it. Please let me know if further information needed.

**Comment by patrick-rodgers** [comment]
Going to close this as it appears you have gotten past this issue based on other issues you have submitted. Please _reopen_ should you need to continue the conversation. Thanks!
