### ISSUE TITLE
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'data.Id')

### ISSUE THREAD

**Issue by robpearmain** [SharePoint/PnP-JS-Core#743]
[ ] Enhancement

[X] Bug

[ ] Question

#### Version 3.0.5

Please specify what version of the library you are using: [lib/sharepoint/item.js line 137 ]

#### Expected / Desired Behavior / Question
Add Item cleanly finishes

#### Observed Behavior
My item is being added to the list, but it is not resolving the promise and return the IItemAddResult

Console Error
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'data.Id')
	(anonymous function) (input-web-part.js:3852)
	promiseReactionJob

#### Steps to Reproduce
pnp.sp.web.lists.getByTitle('_responses').items.add({
        Title: 'Ignore',
      }).then((iar: ItemAddResult) => {
        console.log(iar);
      });

**Comment by patrick-rodgers** [comment]
Hi @robpearmain - I am not able to duplicate this and this is a piece of functionality that hasn't changed in a long time. Are there any more details you can share around what you are doing or the surrounding code?

**Comment by robpearmain** [comment]
I deleted the list, and recreated it and then it worked.  The list had somehow become corrupted due to Compliancy Settings.

**Comment by patrick-rodgers** [comment]
Weirdness, but glad its working now. Thanks for letting us know.
