### ISSUE TITLE
Incorrect type definitions in 3.0.x

### ISSUE THREAD

**Issue by Oceanswave** [SharePoint/PnP-JS-Core#745]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.x]

#### Expected / Desired Behavior / Question

When attempting the use sp-pnp-js 3.0.x, the following error messages are output:

```
ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:306:5
    TS2411: Property 'DefaultFormula' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:307:5
    TS2411: Property 'Description' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:308:5
    TS2411: Property 'EnforceUniqueValues' of type 'boolean | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:309:5
    TS2411: Property 'FieldTypeKind' of type 'number | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:310:5
    TS2411: Property 'Group' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:311:5
    TS2411: Property 'Hidden' of type 'boolean | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:312:5
    TS2411: Property 'Indexed' of type 'boolean | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:313:5
    TS2411: Property 'Required' of type 'boolean | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:314:5
    TS2411: Property 'Title' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:315:5
    TS2411: Property 'ValidationFormula' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.

ERROR in [at-loader] ./node_modules/sp-pnp-js/lib/sharepoint/types.d.ts:316:5
    TS2411: Property 'ValidationMessage' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
```

This appears to come from the following:

https://github.com/SharePoint/PnP-JS-Core/blob/e87d3fe5f567e38e4a374254c098976185be75bf/src/sharepoint/types.ts#L361

the 2.x releases does not contain this error.

#### Steps to Reproduce

Create an application that uses sp-pnp-js and attempt to build it:

``` bash
create-react-app my-ts-app --scripts-version=@baristalabs/react-scripts-ts
cd my-ts-app
yarn add sp-pnp-js
```

Reference 'sp-pnp-js' for instance, adding ``` import { Web } from 'sp-pnp-js';``` to the top of App.tsx

then, 
``` bash
yarn build
```

Observe error in console.
```
/Users/Oceanswave/Projects/my-ts-app/node_modules/sp-pnp-js/lib/sharepoint/types.d.ts
(306,5): Property 'DefaultFormula' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
```

**Comment by patrick-rodgers** [comment]
What version of TypeScript are you using? As well what build rules do you have turned on in your tsconfig.json and this "at-loader" that is throwing the error? Something in your settings doesn't like the possibility that a property might not be on an interface which isn't explicitly allowing undefined. This shouldn't be a problem (if a property is optional and doesn't exist on an interface it would have undefined however so would literally every property name possible) but I would like to understand what is triggering it. IMO this isn't something that should throw an error.

**Comment by koltyakov** [comment]
@Oceanswave,

Another 2 cents:

I can't reproduce.

```bash
$ create-react-app --version
1.5.2
$ tsc --version
Version 2.7.1
```

Just installed a project on a clean machine with `create-react-app my-ts-app --scripts-version=@baristalabs/react-scripts-ts`:

![image](https://user-images.githubusercontent.com/7816483/36998024-9f861502-20cc-11e8-994a-e13deb49fb61.png)

This is with basic Web referencing in App.tsx with default CRA + @baristalabs/react-scripts-ts.

And default:

```json
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "config"
  ]
}
```

Default `tslint.json` which comes with `@baristalabs/react-scripts-ts` (extends `tslint-react` and a number of lint settings).

I do now think it's an issue of awesome-typescript-loader too.

We have a couple of projects with CRA, react-scripts-ts and sp-pnp-js or @pnp/sp recently and a huge number of such projects set ups with ts/webpack 3 (now with 4 too, not CRA)/react and I can't say that there were such issues with PnPjs.

But I saw similar weirdness with other libraries where I ended up with `"skipLibCheck": true` sometimes.

**Comment by Oceanswave** [comment]
@patrick-rodgers @koltyakov thanks for taking a look and sorry for the bother. Looks like I had an older version of tsc.

```
$ tsc --version
Version 2.4.1
$ create-react-app --version
1.5.2
```

After upgrading it no longer repos.

Thanks,

**Comment by NZainchkovskiy** [comment]
Hi! I have exactly the same issue with sp-pnp-js 3.0.7 with TypeScript 2.8.1 (latest create-react-app with typescript). With sp-pnp-js 3.0.4 there is no errors.

**Comment by koltyakov** [comment]
Hey Nick,

What build scripts are you using for CRA? (`react-scripts-ts`? Which version?)
How are CRA settings overwritten? (`react-app-rewired`?)

I'm wondering did you add `"skipLibCheck": true,` into your `tsconfig.json`?
Did you try migrating to new [PnPjs](https://github.com/pnp/pnpjs)? Highly recommend this.

We currently work hard on a project with CRA/react-scripts-ts/at-loader/PnPjs and experience no typing errors.

**Comment by NZainchkovskiy** [comment]
Hey Andrew,

I'm using react-scripts-ts version 2.14.0
Without settings overwrite.
skipLibChek did the trick, thanks for suggestion!
Is pnp-js-core obsolete? Should I use PnPjs instead?

**Comment by patrick-rodgers** [comment]
@NZainchkovskiy - there is a statement on the readme for sp-pnp-js describing things. July will be the last release of sp-pnp-js. The new libraries have all the same functionality and more, as well as allowing greater flexibility on what you import.

**Comment by koltyakov** [comment]
Yes, sir! :)

Please check [Special Message on the Future of sp-pnp-js](https://github.com/SharePoint/PnP-JS-Core#special-message-on-the-future-of-sp-pnp-js).

Our own experience showed that the migration from sp-pnp-js to PnPjs is pretty straightforward and painless. So I definitely recommend the switch!

**Comment by NZainchkovskiy** [comment]
@patrick-rodgers @koltyakov Thank you, guys, I will!
