### ISSUE TITLE
Not expected filter result with boolean

### ISSUE THREAD

**Issue by shinzhon** [SharePoint/PnP-JS-Core#747]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version
Please specify what version of the library you are using: [3.0.5]

#### Expected / Desired Behavior / Question
The filter seems not to return the results as i expected with a boolean value.
`.filter("BooleanValue eq true")` - this function returns as it seems 'false' values.
`.filter("BooleanValue gt false")` - this function returns the results i expected

The question is: why? Is there may an issue?

I know that booleans as numbers do working this way:
false = 0
true != 0 (negativ or positiv values)

#### Observed Behavior
`.filter("BooleanValue eq true")` 
-->`Object { BooleanValue: false, … }`

`.filter("BooleanValue gt false")` 
-->`Object { BooleanValue: false, … }`

`.filter("BooleanValue lt false")` 
-->No hit

Thank you for your help

**Comment by koltyakov** [comment]
Hi Diego,

In REST booleans in $filter conditions should be compared as 0/1:

```typescript
pnp.sp.web
  .getList(`${_spPageContextInfo.webServerRelativeUrl}/Lists/MyList`)
  .items.filter(`YesNoField eq 0`)
  .get().then(console.log)
```

![image](https://user-images.githubusercontent.com/7816483/36989094-c0645452-20b1-11e8-8bcf-a8a6f8726570.png)

**Comment by shinzhon** [comment]
Hello Andrew

Thank you for your response, it works fine.
May it would be a good idea to add/change this in the dev guide.
There are some examples with boolean filtering instead of 0/1.

Best regards

**Comment by koltyakov** [comment]
Could you please point me where in the docs is this?

**Comment by shinzhon** [comment]
Sure
[Resolving field names](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items#resolving-field-names)

**Comment by koltyakov** [comment]
But this one is actually correct, it's not for filtering YesNo/Choice fields. ;)
I know, somewhere one rules, somewhere another, but it's what the REST provides.

**Comment by shinzhon** [comment]
Oh, thats a SharePoint implementation -.-
[Programmatically setting the default value of a SPFieldBoolean field](https://blog.henryong.com/2008/12/05/programmatically-setting-the-default-value-of-a-spfieldboolean-field/)
Ok, now its clear to me. Thanks for your hint :-D
