### ISSUE TITLE
Audience tragetting functionlaity

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/PnP-JS-Core#748]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Question

Hi,

I am not sure if audience targeting functionality available in SPFx? could you please let me know if this available 

Thanks!

**Comment by patrick-rodgers** [comment]
I am also not aware of a way to audience target the web parts if that is what you mean.

**Comment by koltyakov** [comment]
For simple scenarios (selected user or a member of a group in the people picker, audience targeting without corresponding feature) I would suggest one well-known CAML trick and renderListData* and getItemsByCaml options.

**Comment by veeramanx** [comment]
@koltyakov thanks for your reply. i will try CAML trick . thanks :)
@patrick-rodgers  I am trying to control permission for web parts based on user's group.

**Comment by koltyakov** [comment]
In this case something like:

```xml
<Or>
  <Membership Type="CurrentUserGroups">
    <FieldRef Name="AssignedTo"/>
  </Membership>
  <Eq>
    <FieldRef Name="AssignedTo"></FieldRef>
    <Value Type="Integer">
      <UserID/>
    </Value>
  </Eq>
</Or>
```

in REST methods with CAML should help.

**Comment by veeramanx** [comment]
@koltyakov  thanks you. much appreciated. 
@patrick-rodgers I have installed the new pnp js package and i am still having issue in adding custom webpart. I am not sure if i am making any mistake. I really appreciate if you could please have a look at the code https://github.com/SharePoint/PnP-JS-Core/issues/740 . thanks in advance
