### ISSUE TITLE
Expose client people picker search endpoints

### ISSUE THREAD

**Issue by pedro-pedrosa** [SharePoint/PnP-JS-Core#749]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.6]

#### Expected / Desired Behavior / Question
Add the endpoints under `/_api/SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface` to the API.
This allows building custom people picker functionality in client-side components.

If this feature has a place in the API but the priority is not high enough to see it in the near future, I can implement this myself and create a PR.

Related to #633

Thanks!

**Comment by phawrylak** [comment]
Good idea, I can implement this shortly if you don't have time. We just need to decide where it belongs. I believe that we should place it in new query class and allow to access it using property of `pnp.sp`.

@patrick-rodgers:
What do you think? How it should be called and named?

**Comment by koltyakov** [comment]
There is also a lot of methods in `/_api/SP.UI.ApplicationPages`, this stopped me last time from PR. Cause I was not sure which fluent API and naming would be better.

It can be definitely a separate method, one is requested often. Still not sure in the naming.

**Comment by patrick-rodgers** [comment]
If folks want to use it we definitely should look at adding support. I haven't had a chance to really look at how much stuff is there. For the other "services" that are always on the root as have hung them off pnp.sp.{something} such as search or social. IF this is really big would it make sense to create a new package in @pnp libs for it? That way it is optional if folks want to use it but doesn't grow the core package too much. Thoughts?

I will try and take a look at the scope, currently deep in the heart of making ADAL auth work :)

**Comment by koltyakov** [comment]
Maybe it can be a helper under the search namespace or profiles (IMO it's so relevant to both)? 😷 Maybe other stuff from `/_api/SP.UI.ApplicationPages` can be omitted for now? 🐌

**Comment by phawrylak** [comment]
It's not too big and in my opinion many of methods are not really useful in real life.

[SP.UI.ApplicationPages namespace](https://msdn.microsoft.com/EN-US/library/office/jj246932.aspx)

I would propose to just make it like this:
`pnp.sp.applicationPages.clientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser(requestParameters)`

Or even:
`pnp.sp.applicationPages.clientPeoplePickerSearchUser(requestParameters)`

But I believe that we should go with the first option.

**Comment by pedro-pedrosa** [comment]
I don't really think it should go under `search` or `profiles`, frist because it doesn't mirror the REST API and second because they don't really belong there (when I was looking for the people picker methods under `pnp.sp` using intellisense I didn't even look under either of those).

Possibly just a partial implementation of the `SP.UI.ApplicationPages` for now would be enough.

**Comment by koltyakov** [comment]
@pedro-pedrosa, yeah, I know that it is not mirroring the API. On the other hand, it's kind of hack to mirror this part of API in an elegant way. No matter how I tried I didn't really like the result.

Namespace with a single method inside... well... 😆 After looking one more time into API refference, agreed with @phawrylak that other is stuff is probably never needed and we'll ended up with a single method... any ideas? Does `pnp.sp.applicationPages.clientPeoplePickerSearchUser` looks the most logical? Let's sleep with this idea!

**Comment by patrick-rodgers** [comment]
Hmmm...is there nothing else we can put in there? Or maybe we can roll that into pnp.sp.search?

**Comment by phawrylak** [comment]
I have checked and we don't have any other useful things in this namespace, so I think it would be reasonable to not create new property if it's acceptable to not mirror REST API. Whether it should be `search` or `profiles` is another question. The problem with `pnp.sp.search()` is that it's not really property, but method that takes search options and use `Search `class internally, so I don't know how it could look like without breaking API compatibility. I believe that mixing standard search options with people picker's ones and then making some ifs in code is not a good option. So in this case `profiles` is probably the best option here.

**Comment by pedro-pedrosa** [comment]
I guess as long as it's well documented in a wiki page then it's fine to expose the endpoint in a different path.

**Comment by koltyakov** [comment]
My vote is for `pnp.sp.profiles.` and wiki article. ;)

**Comment by phawrylak** [comment]
Ok, so @pedro-pedrosa, do you want to implement it or I can do it?

**Comment by pedro-pedrosa** [comment]
If you can, I'm currently a bit busy and cannot get started right away.

**Comment by patrick-rodgers** [comment]
Done in #750, closing issues. Thanks everyone!
