### ISSUE TITLE
ListAddResult.list does not access the correct list if the list title changes

### ISSUE THREAD

**Issue by pedro-pedrosa** [SharePoint/PnP-JS-Core#754]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.0.6]

#### Expected / Desired Behavior / Question
Because we cannot specify the URL value of a list when it's created and sometimes we want to control this value (especially when the title of the list contains spaces), a common pattern is to create the list with a URL-safe value as the title and then change the title to the desired value.

Example:

```ts
const { list: myList, data: myListData } = await web.lists.add('MyList');
await myList.update({
    Title: 'My List',
});
```

I should be able to then use `myList` to continue the list provisioning logic, like adding a field.

```ts
await myList.fields.addText('Text');
```

#### Observed Behavior
I get an error saying `MyList` doesn't exist when trying to add the field.

#### Steps to Reproduce
```ts
import * as pnp from 'sp-pnp-js';

const { list: myList, data: myListData } = await pnp.sp.web.lists.add('MyList');
await myList.update({
    Title: 'My List',
});
await myList.fields.addText('Text');
```

A better approach for the `Lists.add` method would be to return a list queryable instance pointing at its ID instead of its title.

Thanks!

**Comment by patrick-rodgers** [comment]
The update method already handles this. So you want to get the result of the update operation and make your subsequent changes from that. The result of the add call is now "old" because you have updated the list since it was created. HTH.

**Comment by patrick-rodgers** [comment]
Closing this as answered, please _reopen_ should you have further questions. Thanks!
