### ISSUE TITLE
How to delete multiple items using PnP JS

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#755]
Hi Team,
How to delete multiple list items in SharePoint using PnP JS core just like batch update. Could you please share the solution.

Regards,
Philip

**Comment by koltyakov** [comment]
[Batch API](https://github.com/SharePoint/PnP-JS-Core/wiki/Batching) can be used in SPO/2016.
In SP2013, Promise.all or for/of loops can be used for mass deletion requests.
