### ISSUE TITLE
Resume upload with addChunked

### ISSUE THREAD

**Issue by DaveCalGH** [SharePoint/PnP-JS-Core#758]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [    3.0.6     ]

#### Expected / Desired Behavior / Question
When using addChunked to upload a file, if a network error causes the upload to fail, there is no way to recover. I know resume should be available if I have the upload ID and last block number so is there a way to retrieve the uploadId in order to resume the upload of the file or is there a function already in existence that I can use to resume the upload?

#### Observed Behavior
When upload cannot complete due to network error, the upload fails and I must start from the beginning. Sometimes successful, sometimes not.

#### Steps to Reproduce
Start large upload with addChunked, disconnect network. No way to recover. I assume by this message that my local network somewhere along the way is dropping packets.
"The request body did not contain the specified number of bytes. Got 10,092,544, expected 10,485,760"

**Comment by patrick-rodgers** [comment]
I haven't tried this, but I guess you could use [continueUpload](https://msdn.microsoft.com/en-us/library/office/dn450841.aspx#bk_FileContinueUpload). Currently that is hidden away as a private method inside file, but is used by addChunked. Looking at the code, I don't immediately have an easy way to handle this since things are wrapped up fairly tightly. But I see the need so going to leave this open while I think about it.

**Comment by DaveCalGH** [comment]
I can try that but I'm still looking to find how I can access the uploadId guid that i was just attempting so i can pass that to continueUpload

**Comment by patrick-rodgers** [comment]
You can't currently as it is all contained in the call to addChunked. What I tried to say above is that we would need to change the library to help here, I am just not immediately certain on the best way to accomplish the goal.

**Comment by koltyakov** [comment]
How can this be simulated? Turning on/off offline mode in browsers dev tools while uploading something large? Should it be short network failures or one long period without network and then a possibility to upload from saved fileOffset.
I guess we can try retrying `continueUpload` from a specific fileOffset for a specific `uploadId` dumped to a client script on `progress` event. But not sure will SharePoint allows continue upload after "some" time.
I had a feeling that `postAsCore` already had a feature for retries series, but reasonably for short period of time and tries.
Interesting topic to investigate though.

**Comment by patrick-rodgers** [comment]
We retry requests on 429 and 503 but nothing else. And then only for 10 times. The way I ususally test stuff like this is just add a `throw` in somewhere that fails say 2 times. I am not sure what the range is before SPO abandons the uploaded data. I was thinking we could either 1) wrap up some retry logic into the setContentChunked method or 2) expose some retry methods and information on error (unsure how that would look). I am leaning to 1 - but that keeps everything wrapped up the way it is now and for example to @DaveCalGH 's point the uploadId would still be hidden.

We COULD return an object from setContentChunked that had the upload id and a Promise<FileAddResult> property - but then we also need to expose that from addChunked somehow. But that is a breaking change to the API and I don't want to do that.

After typing all that I think we need to handle the retry inside the method - exposing the complexity will break our API as well as be much harder for folks.

**Comment by DaveCalGH** [comment]
I completely understand. I was hoping uploadId could be added as a property to ChunkedFileUploadProgressData

That way my progresss function could pull it from there.

**Comment by patrick-rodgers** [comment]
We could do that @DaveCalGH (and happy to add it) - but then we don't expose a way for you to do anything with it currently.

**Comment by DaveCalGH** [comment]
I was hoping to manually take over and finish with the /continueupload endpoint. I have a pretty urgent need to get something working so I was hoping to offer this functionality even if it means recreating the wheel for myself.

**Comment by patrick-rodgers** [comment]
Got it. To try and help you out I have made the changes in #762 and published a beta version of the library.

`npm install sp-pnp-js@beta`

I added uploadId to the interface and I made the startUpload, continueUpload, and finishUpload methods protected. You can subclass File and add what you need to your class and call those methods. Hope this helps get your project.

If you figure out a nice retry pattern would appreciate if you could share it back so we can maybe roll it into the library to help everyone.
