### ISSUE TITLE
Anonymous users getting FORBIDDEN(403) Error

### ISSUE THREAD

**Issue by JuniorPointer** [SharePoint/PnP-JS-Core#759]
#### Category
[ ] Enhancement

[] Bug

[x] Question

#### Version
pnp - 2.0.2
sharepoint server 2013

#### Expected / Desired Behavior / Question
Anonymous users should be able to view and add list items from host web via Sharepoint-hosted app.

#### Observed Behavior
Web application and site collection are configured for anonymous access. Require Use Remote Interfaces permission is disabled, and anonymous users can successfully make an REST API calls. 
In app scripts I am using simple calls like this

`$pnp.sp.crossDomainWeb(appGlobalsModule.appWebUrl, appGlobalsModule.hostWebUrl).lists.getByTitle(listTitle).items.get().then(items=> {});`

But when they open app pages with desired functionality - 403 error pops out. In inner sharepoint exception, i am getting "There is no app context to execute this request." error.

I assume that i am missing some configuration piece for pnp, but i can't figure this out on my own. 

Thanks in advance

**Comment by patrick-rodgers** [comment]
I am not sure anonymous users are supported through the cross domain client. Do these calls work not via this library, say with jsom? What are the REST call they can successfully make?

**Comment by JuniorPointer** [comment]
Thanks for answer, I'll try to dig further and comment here about my progress

**Comment by JuniorPointer** [comment]
Well, it seems the only way for anonymous users to work lists is to create them on _add-in web_.

**Cross domain anonymous requests don't work and there are no workaround except previously mentioned** 

Hope it'll save some time for others.
