### ISSUE TITLE
pnpjs with Spfx onPrem

### ISSUE THREAD

**Issue by GkoEvo** [SharePoint/PnP-JS-Core#763]
#### Category

Bug

#### Version

npm package 1.0.3
SharePoint 2016 Feature Pack 2
Sharepoint generator v1.4.1
Node 6.11.5
SPFx 1.1.0

#### Observed Behavior
I would like to use the module pnpsp in my project. 
To do so I imported pnpsp as described in the documentation in the root component of my project (It's an empty project)

`import { sp } from "@pnp/sp"`

and run `gulp serve`

when I do it, I have these errors : 

![image](https://user-images.githubusercontent.com/31537054/37899168-0a596d10-30eb-11e8-9af7-2b5df8d22b44.png)

#### Steps to Reproduce
- Install the Node js 6.11.5 (Lastest working version for the SPFx onPrem)
- Install the latest version of the SharePoint generator 
- Create a SPFx projet for onPrem environnement 
- Install pnp `npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp @pnp/graph --save`
- Execute `gulp serve`

Let me know, if you need more informations. 

Thanks !

**Comment by koltyakov** [comment]
Hi there!

SPFx's build tools for OnPrem use an old version of typescript. Which do not support some of the core features used in PnP JS Core.

There is a workaround: https://github.com/SharePoint/PnP-JS-Core/issues/741#issuecomment-371637622

Hope that in next version of SPFx's dependencies this will be fixed.

**Comment by GkoEvo** [comment]
Hi @koltyakov, 

Thanks a lot for the answer, I solved the build errors with the workaround !
