### ISSUE TITLE
NoComponentId Error

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/PnP-JS-Core#764]
#### Expected / Desired Behavior / Question

I am trying to create modern page and add web parts programmatically through extensions.  when i run the code for the first time page is getting created succesfully and webparts are added to it. however, when i delete that page and re-run the code i am getting NoComponentId error. 

![image](https://user-images.githubusercontent.com/36476607/37900517-5176efd8-30e6-11e8-87d0-1d62b3ee05b9.png)

I am not sure what went wrong. Please let me know if you have any idea.

Thanks!

**Comment by patrick-rodgers** [comment]
If it works then doesn't I am not sure. Do you have any errors from the code running that might help diagnose this? Currently don't have enough to go on. Thanks.

**Comment by patrick-rodgers** [comment]
That would indicate something you are calling doesn't exist. If the page was deleted - are you trying to make calls against the deleted page? What is the url you tried calling that resulted in the 404?

**Comment by veeramanx** [comment]
Hi @patrick-rodgers ,  what i am doing in the code is first i am check if user page is available under sitepages library (ex: veeramanx.aspx exist or not), if not then create page. if exist then redirecting to user page. 
therefore, whenever new user comes it will create page for them.
