### ISSUE TITLE
Error making HttpClient request in queryable: [0] when using no-cors mode

### ISSUE THREAD

**Issue by maximgeerinck** [SharePoint/PnP-JS-Core#765]
I'm trying to get the JSON result from a request with the pnp mode set to **no-cors**

#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.0.6]

#### Expected / Desired Behavior / Question
Getting the result without an error

#### Observed Behavior
```
exceptions.js:24 Uncaught (in promise) Error: Error making HttpClient request in queryable: [0] 
    at new ProcessHttpClientResponseException (exceptions.js:24)
    at core.js:47
```

#### Steps to Reproduce
```
const mySp = pnp.sp.configure({
    mode: 'no-cors'
  })
  mySp.web.currentUser.get().then((result) => {
    console.log(result)
  })
```

**Comment by koltyakov** [comment]
Hey @maximgeerinck,

Could you please explain your use case?
Why do you ever need changing mode?

**Comment by maximgeerinck** [comment]
Hi, thank you for the quick reply.

Our sharepoint is managed by an external source and is hosted on a different domain.
When we normally query the sharepoint we therefore get a Access-Control Error

**Comment by koltyakov** [comment]
Hm... and what is the environment where PnPjs scripts are executed?
I have a guess that you're trying a development in a local workbench/dev server.

**Comment by maximgeerinck** [comment]
I have a Development environment, staging and production. In all three, the error occurs.

**Comment by koltyakov** [comment]
No, I mean how it happened that the context of execution of the front-end application ended up with a different domain? Is it an Add-In model or something?

**Comment by maximgeerinck** [comment]
I just rechecked it, it only occurs in the development environment (as we're developing from localhost). The staging and production automatically redirect to internet explorer. We deploy the frontend on the sharepoint under siteassets

**Comment by koltyakov** [comment]
So you have a front-end project with local workbench which is started e.g. with Gulp or Webpack Dev Server and is running on a localhost (e.g. `http://localhost:3000`) and you expect that the requests will be targeted to a development SharePoint tenant provisioned somewhere like `http://dev.contoso.com/sites/site`? This is not gonna work because of cross-origin access limitations.
You should deploy script to SharePoint assets (require extra time between change upload and result on the page); link scripts on SharePoint pages to your local server (not very convenient); or use a proxy which will be routing requests to localhost/_api/... to the development server.

**Comment by maximgeerinck** [comment]
So it's not possible to access it even with the mode set to 'no-cors' ?

**Comment by koltyakov** [comment]
I do not think so as this is a security limitation. Please correct me guys if I'm wrong.

**Comment by patrick-rodgers** [comment]
See this on [no-cors](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode), I am not sure it does what you think. For the localhost workbench you can see [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint) on the need to mock data in the local workbench.

In short what you are doing won't work as-is, nothing to do with this library specifically. You can review Andrew's article on using a proxy: https://www.linkedin.com/pulse/local-spfx-workbench-against-real-sharepoint-api-andrew-koltyakov/ as a possible work-around.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ should you need to continue the conversation. Thanks!
