### ISSUE TITLE
readme.md: link to transition guide broken

### ISSUE THREAD

**Issue by alirobe** [SharePoint/PnP-JS-Core#768]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Problem

README.md hash bd587de links to 'transition guide' : https://pnp.github.io/pnp/transition-guide.html
which is a 404.

**Comment by koltyakov** [comment]
Thanks for letting us know!
New repo was renamed from `pnp/pnp` to `pnp/pnpjs` because it was a reason for some controversy which we decided to emend.
Please use the following link for now: https://pnp.github.io/pnpjs/transition-guide.html

**Comment by koltyakov** [comment]
Fixed with PR. The new link will be after the merge.
