### ISSUE TITLE
Client side authentication 

### ISSUE THREAD

**Issue by pridemusvaire** [SharePoint/PnP-JS-Core#772]
#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Please specify what version of the library you are using: [    3.0     ]

Is there a way to authenticate client-side with sp-pnp-js, I would like to test my apps on my local machine without deploying to a SharePoint env.

**Comment by patrick-rodgers** [comment]
Hi @pridemusvaire - there are several ways. How will you be running your app? In Nodejs or something else?

You can start by having a look at these two guides to help get you started:

* [Testing against sharepoint](https://github.com/SharePoint/PnP-JS-Core/wiki/Testing-Against-SharePoint) - setting up a client id and secret
* [Debugging](https://github.com/SharePoint/PnP-JS-Core/wiki/Debugging) - various ways to debug this library, which should help you on setting up your app.

Let us know how you are running things and we can provide a little more exact guidance. Thanks!

**Comment by pridemusvaire** [comment]
Hi, @patrick-rodgers I'm running it on my local machine it's a react app bootstrapped with create-react-app, will look at the examples you gave thanks.

**Comment by koltyakov** [comment]
Oh, @pridemusvaire, we use the same [setup](https://twitter.com/AndrewKoltyakov/status/954292169698893824) (CRA + TS Scripts, Webpack Dev server + Proxy + hot reload, PnPjs, Office UI Fabric, manually crafted local workbench to mimic webpart on SharePoint Page (for keeping native SP elements), React 16, Redux, Router with MPA configuration to correspond real pages (with the same instance of app webpart), publishing scripts, 2016/2013/SPO). Setup is not documented yet. Maybe it's time to write down all the steps for me now.

With PnPjs there are nuances in configuring web context in such a way that it should be aware is it a local or real environment, luckily there is an OOTB helper, which gets or creates web absolute URL which then is used in `new Web([ABS_URL])` constructor so PnPjs works in local workbench and deployed to SP.

**Comment by patrick-rodgers** [comment]
Great - let us know if you have questions. @koltyakov linked a great resource as well.
