### ISSUE TITLE
Retrieve HasUniqueRoleAssignments and RoleAssignments properties and expand it using RenderListDataAsStream method

### ISSUE THREAD

**Issue by shrutikamendhe** [SharePoint/PnP-JS-Core#775]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [   3.0.0      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

We wanted to submit our SPFx web part on Microsoft App Catalog. During an evaluation, we got the feedback to implement `RenderListDataAsStream` method wherever we are using `getItemsByCAMLQuery` to retrieve the list items. 

We wanted to retrieve and expand `HasUniqueRoleAssignments` and `RoleAssignments` for files and folder for a particular document library. 

Could you please share some sample examples?

Thanks!

**Comment by patrick-rodgers** [comment]
I don't have an example handy for that specific operation. You can review the [existing docs for RenderListDataAsStream](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream) for guidance.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please reopen should you need to continue the conversation. Thanks!
