### ISSUE TITLE
Selecting the person that will be listed in the "Contact" webpart using sp-pnp-js

### ISSUE THREAD

**Issue by PerLundstrom** [SharePoint/PnP-JS-Core#782]
Category
[ ] Enhancement

[ ] Bug

[X] Question

Version
Please specify what version of the library you are using: [ 3.0.7]

Expected / Desired Behavior / Question
I have added the webpart "Contact" to a page using sp-pnp-js.

Can I select which person that will be listed in that webpart using sp-pnp-js or do I have to edit the page and manually select that person?

I´m using this as an example: https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Client-side-Pages

Thanks!

**Comment by patrick-rodgers** [comment]
Same answer as the other issue, yes you can using the setProperties method - but I don't have the properties format readily available.

**Comment by PerLundstrom** [comment]
Thanks!

Same solution as my other issue.
