### ISSUE TITLE
Order By is not working properly in PnP JS Core

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#785]
Hi,
I am using the below PnP code to sort the items but it is not sorting. Please help me to resolve this.

`const sortField = 'Title';`
`const sortAsc = false;`
`let items = sp.web.lists.getByTitle(this.listTitle).items`
     ` .filter(filterQuery)`
      `.select('*', 'Author/ID', 'Author/Title', 'Editor/ID', 'Editor/Title')`
      `.expand('Author,Editor')`
      `.orderBy(sortField, sortAsc);`
`if (sortField !== 'ID') {
      items = items.orderBy('ID', false);
    }
    items = items.top(pageSize);
    return Observable.fromPromise(items.getPaged())
      .map(res => {
        res.results = res.results.map(r => this.castAsReportingValue(r));
        return res;
      });`

From the above code, if I set the "sortField" to "Created" column it is working fine. For Title field it is not working. Kindly share your inputs.

**Comment by patrick-rodgers** [comment]
Are you getting an error back? Some fields are not sortable and perhaps in the list you are accessing Title is not?

**Comment by spvjebaraj** [comment]
Hi Rodgers,
I am not getting any error but it is not sorting. The results are displayed their own sorts not by ID or not by Title also.
Regards,
Philip

**Comment by spvjebaraj** [comment]
Hi Andrew,
It is working fine now. Thanks for shared the solution with good explanations and screenshots.

**Comment by koltyakov** [comment]
Nice! Glad you figured out. Closing the issue.
