### ISSUE TITLE
Provide a facility to handle 429 errors

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#786]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category

[x ] Enhancement

[ ] Bug

[x ] Question

Would it be possible to have pnp-js-core do automatic retries if it gets a 429 error from sharepoint? It's done in the pnp c# library. Can the same logic be implemented here?

**Comment by patrick-rodgers** [comment]
[Implemented](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/net/httpclient.ts#L87) since the beginning. Are you seeing it not retry?

**Comment by russgove** [comment]
Oh, I did not know that.  I will test it out!

**Comment by patrick-rodgers** [comment]
Cool, let us know if you see problems.
