### ISSUE TITLE
Incorrect ID format describing of custom webparts: getClientSideWebParts()

### ISSUE THREAD

**Issue by gord89** [SharePoint/PnP-JS-Core#801]
Incorrect ID format describing of custom webparts: getClientSideWebParts()

![screenshot_353](https://user-images.githubusercontent.com/3709809/39711584-caaf6e9e-5228-11e8-81d6-005268a58f89.png)

####Which PnP repository should you use to report the issue?####
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
The id format of custom webpages should be the same as others.

#### Steps to Reproduce
JS:
~~~
import pnp, { ClientSidePage, ClientSideText,  ClientSideWebpart, ClientSideWebpartPropertyTypes } from "sp-pnp-js";
...
const partDefs = await pnp.sp.web.getClientSideWebParts();
~~~

Similar problems:
https://github.com/SharePoint/PnP-JS-Core/issues/740
https://github.com/pnp/pnpjs/issues/14

Maybe it's problems with spfx.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks!
