### ISSUE TITLE
return type for getAll

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#810]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category

[x ] Enhancement

[ ] Bug

[ ] Question

#### Version

Hi, I am using this code to return an array of typed objects
public getRoleToTransaction(role: string): Promise<RoleToTransaction> {
    return sp.web.lists.getByTitle(this.properties.roleToTransactionListName)
      .items.filter(`Composite_x0020_role eq '${role}'`).get<RoleToTransaction>();
  }

I  returned results list may be huge in some rare cases so I want to use GetAll():
  public getRoleToTransaction(role: string): Promise<RoleToTransaction> {
    return sp.web.lists.getByTitle(this.properties.roleToTransactionListName)
      .items.filter(`Composite_x0020_role eq '${role}'`).getAll<RoleToTransaction>();
  }

But getAll doesn't take a type parameter.

Can we make  getAll take a type parameter?

**Comment by patrick-rodgers** [comment]
You can type the return to anything you like. It is any so something like:

```TypeScript

const h = <something>sp...getAll();

// or

const y: something = sp...getAll();
```

Not sure what advantage adding a type parameter would have here?

**Comment by russgove** [comment]
Thanks Patrick! I did not know that.
