### ISSUE TITLE
Qustion: The field 'xxxx' is not supported in query. The lookup list is in another web.

### ISSUE THREAD

**Issue by bulbapeppe** [SharePoint/PnP-JS-Core#812]
Dear All,
I have a question: I am trying to retrieve data of a column that is a lookup to a list stored in another web.
The error I retrieve is:
"The field 'xxxx' is not supported in query. The lookup list is in another web."

I read it in internet and it seems it is "normal".
Do you have any suggestion on how to solve it (I am using pnp libraries to get items). I

Thank you.

**Comment by koltyakov** [comment]
Hi @bulbapeppe,

This is a current limitation of REST API, values of lookup fields' to the list in other webs can't be requested with OData. `renderListData` or `renderListDataAsStream` should be used instead as well as `getItemsByCAMLQuery`, if I'm not wrong, can get such lookups data.

P.S.
Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!
