### ISSUE TITLE
Sharing Site collection to an external user

### ISSUE THREAD

**Issue by AntyfrizZz** [SharePoint/PnP-JS-Core#815]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category

[] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [1.0.5]

Hello there,

I have to share a SharePoint site collection with an external guest user, that have never been logged before to it (user@gmail.com or something like that). Basically the user must receive an email for site collection sharing and when he login, he will be automatically added to a group.

Can i do this with pnpjs or i must use csom or something?

Thank you in advance,
Yavor

**Comment by patrick-rodgers** [comment]
We do have the sharing stuff implemented, but it is at the web level. Please have a look at [the docs for sharing](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Sharing). Thanks.

-----
_Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July, 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible, or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_
