### ISSUE TITLE
A call to contextInfo is being made by each spfx webpart.

### ISSUE THREAD

**Issue by cslecours** [SharePoint/PnP-JS-Core#818]
#### Category

- [ ] Enhancement

- [x] Bug

- [ ] Question

#### Version

Please specify what version of the library you are using: [3.0.8  ]

#### Observed Behavior

I have 3 SPFX Webparts in a Classic Page.

I see 3 calls to /_api/contextinfo in the network traces when the page load.

![image](https://user-images.githubusercontent.com/3374584/41320035-05b05c42-6e6c-11e8-95b4-172c2f1876de.png)

It seems familiar to this bug #345 .

#### Expected / Desired Behavior / Question

Only one call if it's possible?

**Comment by patrick-rodgers** [comment]
Each webpart in SPFX exists within its own closure, so they don't know each other exist, hence the multiple calls. The issue you reference was a previous issue where we were making the contextinfo call for every request - which isn't the behavior your are seeing.

----
_Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July, 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible, or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_
