### ISSUE TITLE
how to add field to view?

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/PnP-JS-Core#822]
Hi, how to add field to view?

**Comment by koltyakov** [comment]
Hi @peterremote1980, 

This adds a field to a view: ```view.fields.add('FieldInternalName')```

If you need a field somewhere in the middle of the others, this can be helpful:

```typescript
import { sp } from "@pnp/sp";

(async () => {

    const list = sp.web.lists.getById(_spPageContextInfo.pageListId); // get a list whatever used to
    const view = list.defaultView;

    const batch = sp.web.createBatch();

    const fields = ['ID', 'LinkTitle', 'Author', 'Created', 'Editor', 'Modified'];

    view.fields.inBatch(batch).removeAll();
    fields.forEach(fieldName => {
        view.fields.inBatch(batch).add(fieldName);
    });

    await batch.execute();

    console.log('Done')

})()
    .catch(console.log);
```

-----
_Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July, 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible, or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_

**Comment by peterremote1980** [comment]
thanks
