### ISSUE TITLE
IncludeGroupsSites doesnt work in the sp.social.my.followed(SocialActorTypes.IncludeGroupsSites)

### ISSUE THREAD

**Issue by SerAlalal** [SharePoint/PnP-JS-Core#824]
IncludeGroupsSites doesnt work in the sp.social.my.followed(SocialActorTypes.IncludeGroupsSites)

**Comment by patrick-rodgers** [comment]
Hi @SerAlalal - can you provide more details? Thanks.

------
_Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July, 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible, or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_
