### ISSUE TITLE
Using Angular@6 util.js error

### ISSUE THREAD

**Issue by kfircs** [SharePoint/PnP-JS-Core#825]
#### Category
[x] Bug
#### Version
Please specify what version of the library you are using: [  3.0.9       ]
#### Expected / Desired Behavior / Question
When using pnp inside Angular@6 application 
for example-
pnp.sp.web.lists.getByTitle(listname).items.getAll().then(
      (response: any[]) => {
      console.log(<any>response);
      });

getting an error:
 Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at util.js:257

in this function:
Util.toAbsoluteUrl = function (candidateUrl) {
        return new Promise(function (resolve) {
            if (Util.isUrlAbsolute(candidateUrl)) {
                // if we are already absolute, then just return the url
                return resolve(candidateUrl);
            }
            if (pnplibconfig_1.RuntimeConfig.spBaseUrl !== null) {
                // base url specified either with baseUrl of spfxContext config property
                return resolve(Util.combinePaths(pnplibconfig_1.RuntimeConfig.spBaseUrl, candidateUrl));
            }
            if (typeof **global**._spPageContextInfo !== "undefined") {
                // operating in classic pages
                if (global._spPageContextInfo.hasOwnProperty("webAbsoluteUrl")) {
                    return resolve(Util.combinePaths(global._spPageContextInfo.webAbsoluteUrl, candidateUrl));
                }
                else if (global._spPageContextInfo.hasOwnProperty("webServerRelativeUrl")) {
                    return resolve(Util.combinePaths(global._spPageContextInfo.webServerRelativeUrl, candidateUrl));
                }
            }
            // does window.location exist and have a certain path part in it?
            if (typeof global.location !== "undefined") {
                var baseUrl_1 = global.location.toString().toLowerCase();
                ["/_layouts/", "/siteassets/"].forEach(function (s) {
                    var index = baseUrl_1.indexOf(s);
                    if (index > 0) {
                        return resolve(Util.combinePaths(baseUrl_1.substr(0, index), candidateUrl));
                    }
                });
            }
            return resolve(candidateUrl);
        });
    };

I was trying to add 
var global = window;
inside my application pollyfills, but with now success.

Thanks!

**Comment by kfircs** [comment]
I want to add that I have changed the files inside the sp-np-js
where ever the _global_ variable is used to _window_ , and it work fine.

hope that you have any insight for me.

Thanks.

**Comment by patrick-rodgers** [comment]
Hi @kfircs - this isn't something we will investigate for this library as the final release is this Friday. Could you please try moving to the [new libraries](https://github.com/pnp/pnpjs) and see if the problem persists? Thanks!

**Comment by kenneth-jearim** [comment]
Add:

(window as any).global = window;

To polyfills.ts file
