### ISSUE TITLE
How to get specific version of item?

### ISSUE THREAD

**Issue by vincent-chan-hk** [SharePoint/PnP-JS-Core#827]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Developer Guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

#### Category

[ ] Enhancement

[X ] Bug

[X ] Question

#### Version 

Please specify what version of the library you are using: [    3.0.7     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I found that it should have method of getting specific version of item (added support for additional file version methods and added support f… #651). But I cannot find out how to use this method in existing documentation. Please teach me! Thanks!

_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior

_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce

_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines

_Delete this section after reading_
- All suggestions, questions, and issues are welcome, please let us know what's on your mind.
- If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by koltyakov** [comment]
Hi @vincent-chan-hk,

You can get item's version using `item.version` method, or `item.versions.getById` for a specific version.
Though, it'll work in SPO as versions API landed to REST not far ago.

```typescript
item.versions.get().then(console.log); // all versions info
item.versions.getById(512).get().then(console.log); // a specific version
``` 

![image](https://user-images.githubusercontent.com/7816483/42377125-9554ba66-812a-11e8-8712-f1548fb7cf4a.png)

**Comment by vincent-chan-hk** [comment]
Thank you for your quick response! You save my Happy Friday! I completed my coding and I can have a drink in Lan Kwai Fong. :)
Happy Friday!

**Comment by koltyakov** [comment]
Cheers buddy!
