### ISSUE TITLE
Ability to view/add/remove Site Collection Admins?

### ISSUE THREAD

**Issue by ken-harris** [SharePoint/PnP-JS-Core#828]
#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.0.9]

#### Expected / Desired Behavior / Question

Is there any possible way for my application to retrieve/add/remove the users from the Site Collection Admin group? I have tried `pnp.sp.site.getRootWeb().then(rootWeb => {});` but I can't seem to find out how to search for this group and get its members.

Thank you very much for your time!

**Comment by koltyakov** [comment]
Hey @ken-harris, 

This might help:

```typescript
// Ensure a user on site collection
sp.web.ensureUser('john.doe@contoso.onmicrosoft.com').then(console.log);

// Get site collection admins
sp.web.siteUsers.filter(`IsSiteAdmin eq true`)
    .get().then(console.log);

// Remove a user from site collection admins
sp.web.siteUsers.getByLoginName('i:0#.f|membership|john.doe@contoso.onmicrosoft.com')
    .update({ IsSiteAdmin: false }).then(console.log);

// Add a user to site collection admins
sp.web.siteUsers.getByLoginName('i:0#.f|membership|john.doe@contoso.onmicrosoft.com')
    .update({ IsSiteAdmin: true }).then(console.log);
```

-----
_Thank you for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!_

**Comment by ken-harris** [comment]
That worked perfectly, thank you so much @koltyakov!
